Repository zenml-io/zenml, pull requests merged in 2021-11, with the labels that each got.

#150 Update quickstart example notebook
  examples/quickstart/quickstart.ipynb
Labels: documentation, internal

#151 Add documentation images
  docs/book/assets/2021-11-02-architecture-overview.png
  docs/book/assets/localstack-with-airflow-orchestrator.png
  docs/book/assets/localstack.png
  docs/book/assets/quickstart-diagram.png
  docs/book/core-concepts.md
  docs/book/guides/low-level-api/chapter-1.md
  docs/book/guides/low-level-api/chapter-2.md
  docs/book/guides/low-level-api/chapter-3.md
  docs/book/guides/low-level-api/chapter-4.md
  docs/book/guides/low-level-api/chapter-5.md
  docs/book/guides/low-level-api/chapter-6.md
  docs/book/guides/low-level-api/chapter-7.md
  docs/book/quickstart-guide.md
Labels: documentation, internal

#154 Add prettierignore to gitignore
  .gitignore
Labels: internal

#153 Airflow orchestrator improvements
  docs/book/guides/low-level-api/chapter-7.md
  examples/airflow_local/README.md
  examples/airflow_local/trigger_dag.py
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/artifact.py
  src/zenml/cli/config.py
  src/zenml/cli/metadata.py
  src/zenml/cli/orchestrator.py
  src/zenml/core/component_factory.py
  src/zenml/enums.py
  src/zenml/orchestrators/airflow/airflow_dag_runner.py
  src/zenml/orchestrators/airflow/airflow_orchestrator.py
  src/zenml/orchestrators/airflow/zenml_standalone_command.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/utils/daemon.py
Labels: internal

#155 Google colab added
  src/zenml/utils/analytics_utils.py
Labels: internal

#156 Add Paperspace environment check
  src/zenml/utils/analytics_utils.py
Labels: enhancement, internal

#157 Step caching
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/pipelines/test_base_pipeline.py
  tests/steps/test_base_step.py
Labels: internal

#158 Add documentation for pipeline step parameter and run name configuration
  docs/book/guides/pipeline-configuration.md
  docs/book/toc.md
Labels: internal

#159 Automatically disable caching if the step function code has changed
  src/zenml/steps/base_step.py
Labels: internal

#160 Make tests run in a random order
  pyproject.toml
Labels: enhancement, internal

#162 Connect steps using *args
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
Labels: internal

#163 Move location of repobeats image
  README.md
Labels: documentation, internal

#165 Hamza/add sam
  README.md
  docs/readme/sam_frustrated.jpg
  docs/readme/sam_zen_mode.jpg
Labels: internal

#164 Pipeline initialization with *args
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  tests/conftest.py
  tests/pipelines/test_base_pipeline.py
Labels: internal

#167 Improve detection of third party modules during class resolving
  src/zenml/utils/source_utils.py
  tests/utils/test_source_utils.py
Labels: internal

#168 Merge path_utils into fileio & refactor what was left
  README.md
  RELEASE_NOTES.md
  docs/book/.gitbook/assets/localstack (1).png
  docs/book/.gitbook/assets/localstack-with-airflow-orchestrator.png
  docs/book/.gitbook/assets/localstack.png
  docs/book/.gitbook/assets/sam_frustrated.jpg
  docs/book/.gitbook/assets/sam_zen_mode (1).jpg
  docs/book/.gitbook/assets/sam_zen_mode (2).jpg
  docs/book/.gitbook/assets/sam_zen_mode (3).jpg
  docs/book/.gitbook/assets/sam_zen_mode.jpg
  docs/book/guides/low-level-api/chapter-7.md
  docs/book/guides/pipeline-configuration.md
  docs/book/guides/post-execution-workflow-test.md
  docs/book/index.md
  docs/book/toc.md
  docs/interrogate.svg
  docs/readme/sam_frustrated.jpg
  docs/readme/sam_zen_mode.jpg
  examples/quickstart/quickstart.ipynb
  pyproject.toml
  src/zenml/VERSION
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/cli/base.py
  src/zenml/cli/example.py
  src/zenml/cli/utils.py
  src/zenml/cli/version.py
  src/zenml/config/global_config.py
  src/zenml/core/base_component.py
  src/zenml/core/git_wrapper.py
  src/zenml/core/local_service.py
  src/zenml/core/mapping_utils.py
  src/zenml/core/repo.py
  src/zenml/core/utils.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
  src/zenml/integrations/gcp/io/gcs_plugin.py
  src/zenml/io/fileio.py
  src/zenml/metadata/base_metadata_store.py
  src/zenml/metadata/sqlite_metadata_wrapper.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/path_utils.py
  src/zenml/utils/source_utils.py
  src/zenml/utils/yaml_utils.py
  tests/artifact_stores/test_gcp_artifact_store.py
  tests/cli/test_example.py
  tests/config/test_global_config.py
  tests/conftest.py
  tests/core/test_git_wrapper.py
  tests/core/test_local_service.py
  tests/io/test_fileio.py
  tests/pipelines/test_base_pipeline.py
  tests/steps/test_base_step.py
  tests/utils/test_source_utils.py
Labels: internal

#171 Hamza/deploy api reference
  .github/workflows/main.yml
  .github/workflows/publish-api-docs.yml
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  .gitignore
  docker/base-dev.Dockerfile
  docker/cuda-dev.Dockerfile
  docker/dataflow-dev.Dockerfile
  scripts/deploy-docs.sh
  src/zenml/cli/config.py
Labels: internal

#172 API Reference
  .github/workflows/main.yml
  .github/workflows/publish-api-docs.yml
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  .gitignore
  docker/base-dev.Dockerfile
  docker/cuda-dev.Dockerfile
  docker/dataflow-dev.Dockerfile
  docs/sphinx_docs/Makefile
  docs/sphinx_docs/_static/logo.png
  docs/sphinx_docs/_templates/module.rst_t
  docs/sphinx_docs/_templates/package.rst_t
  docs/sphinx_docs/conf.py
  docs/sphinx_docs/index.rst
  docs/sphinx_docs/make.bat
  pyproject.toml
  scripts/deploy-docs.sh
  scripts/generate-docs.sh
  src/zenml/cli/config.py
  src/zenml/orchestrators/airflow/airflow_component.py
  src/zenml/orchestrators/airflow/airflow_dag_runner.py
  src/zenml/stacks/base_stack.py
  src/zenml/steps/base_step.py
  src/zenml/utils/source_utils.py
Labels: internal

#176 Add colour back into our github actions
  scripts/test-coverage-xml.sh
Labels: internal

#177 Refactor tests not raising
  tests/core/test_repo.py
  tests/utils/test_analytics_utils.py
Labels: internal

#175 Improve step and pipeline interface
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  src/zenml/materializers/spec_materializer_registry.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  tests/conftest.py
  tests/pipelines/test_base_pipeline.py
  tests/steps/test_base_step.py
Labels: internal

#178 Alex/eng 27 windows bug again
  .github/workflows/main.yml
Labels: internal

#173 Automated todo tracking
  .github/workflows/update_todos.yml
  scripts/update_todos.py
  src/zenml/artifacts/base_artifact.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/stack.py
  src/zenml/core/git_wrapper.py
  src/zenml/io/gcs_plugin.py
  src/zenml/logger.py
  src/zenml/orchestrators/airflow/airflow_component.py
  src/zenml/steps/utils.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/path_utils.py
  src/zenml/utils/source_utils.py
  tests/cli/test_config.py
  tests/cli/test_example.py
  tests/cli/test_metadata.py
  tests/conftest.py
  tests/core/test_local_service.py
  tests/core/test_repo.py
  tests/metadata/test_base_metadata_wrapper.py
  tests/scripts/__init__.py
  tests/scripts/test_update_todos.py
  tests/utils/test_path_utils.py
Labels: internal

#179 Fix mypy issues related to windows
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/daemon.py
Labels: internal

#181 Include Github URL to TODO comment in issue
  .github/workflows/update_todos.yml
  scripts/update_todos.py
  tests/scripts/test_update_todos.py
Labels: internal

#184 Add README for visualizers examples
  examples/visualizers/README.md
Labels: internal

#185 Allow None as default value for BaseStep configs
  src/zenml/steps/base_step.py
  tests/steps/test_base_step.py
Labels: internal

#187 Remove unused base enum cases
  src/zenml/enums.py
Labels: internal

#180 Testing mocks for CLI `examples` command
  .github/workflows/pull_request.yml
  pyproject.toml
  src/zenml/cli/example.py
  tests/cli/test_example.py
  tests/cli/test_utils.py
Labels: internal

#188 Set the correct module for steps created using our decorator
  src/zenml/metadata/base_metadata_store.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/steps/test_base_step.py
Labels: internal

#190 Tag jira issues for which the todo was deleted
  .github/workflows/update_todos.yml
  scripts/update_todos.py
  tests/scripts/test_update_todos.py
Labels: internal

#191 Remove deadlinks
  docs/README.md
  docs/book/core-concepts.md
  docs/book/guides/deploy_to_production.md
  docs/book/support/tutorials.md
Labels: documentation, internal

#192 Fix typos
  examples/visualizers/statistics/README.md
Labels: documentation, internal

#194 Fix Apache Beam bug
  pyproject.toml
  src/zenml/core/repo.py
Labels: bug, internal

#195 Fix apache beam logging bug
  pyproject.toml
  src/zenml/logger.py
Labels: bug, internal

#196 Add step context
  src/zenml/exceptions.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_context.py
  src/zenml/steps/utils.py
  tests/conftest.py
  tests/steps/test_base_step.py
  tests/steps/test_step_context.py
Labels: internal

#197 Init docstrings
  docs/README.md
  docs/book/core-concepts.md
  docs/book/reference/cli-command-reference.md
  docs/book/why/framework-design.md
  src/zenml/artifact_stores/__init__.py
  src/zenml/artifacts/__init__.py
  src/zenml/cli/__init__.py
  src/zenml/config/__init__.py
  src/zenml/core/__init__.py
  src/zenml/core/base_component.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/beam/__init__.py
  src/zenml/integrations/facets/__init__.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/io/__init__.py
  src/zenml/materializers/__init__.py
  src/zenml/metadata/__init__.py
  src/zenml/orchestrators/__init__.py
  src/zenml/pipelines/__init__.py
  src/zenml/post_execution/__init__.py
  src/zenml/stacks/__init__.py
  src/zenml/steps/__init__.py
  src/zenml/utils/__init__.py
  src/zenml/visualizers/__init__.py
Labels: documentation, internal

#199 Hamza/small fixes
  src/zenml/core/repo.py
  src/zenml/types/__init__.py
  src/zenml/utils/analytics_utils.py
Labels: internal

#198 Fix writing to metadata store with airflow orchestrator
  src/zenml/integrations/airflow/orchestrators/airflow_component.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
Labels: internal

#200 Use pipeline parameter name as step name in post execution
  docs/book/guides/low-level-api/chapter-1.md
  docs/book/guides/low-level-api/chapter-2.md
  docs/book/guides/low-level-api/chapter-3.md
  docs/book/guides/low-level-api/chapter-4.md
  docs/book/guides/low-level-api/chapter-5.md
  docs/book/guides/low-level-api/chapter-6.md
  examples/low_level_guide/chapter_1.py
  examples/low_level_guide/chapter_2.py
  examples/low_level_guide/chapter_3.py
  examples/low_level_guide/chapter_4.py
  examples/low_level_guide/chapter_5.py
  examples/low_level_guide/chapter_6.py
  examples/not_so_quickstart/run.py
  src/zenml/metadata/base_metadata_store.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  tests/conftest.py
  tests/pipelines/test_base_pipeline.py
  tests/steps/test_base_step.py
Labels: internal

#201 Add error message when step name is not in metadata store
  src/zenml/metadata/base_metadata_store.py
Labels: internal
