Repository zenml-io/zenml, pull requests merged in 2021-12, with the labels that each got.

#202 Add option to set repo location using an environment variable
  src/zenml/constants.py
  src/zenml/core/repo.py
  src/zenml/io/fileio.py
Labels: internal

#203 Run cloudbuild after pypi publish
  .github/workflows/publish.yml
  cloudbuild.yaml
Labels: internal

#204 Refactor component generation
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
Labels: internal

#206 Removed unnecessary panel dependency
  pyproject.toml
Labels: internal

#205 Updated README to successively install requirements
  examples/airflow_local/README.md
Labels: internal

#208 Store active stack in local config
  src/zenml/config/global_config.py
  src/zenml/core/base_component.py
  src/zenml/core/local_service.py
  src/zenml/core/repo.py
Labels: internal

#212 Add chapter names
  docs/book/guides/low-level-api/chapter-1.md
  docs/book/guides/low-level-api/chapter-2.md
  docs/book/guides/low-level-api/chapter-3.md
  docs/book/guides/low-level-api/chapter-4.md
  docs/book/guides/low-level-api/chapter-5.md
  docs/book/toc.md
Labels: documentation, internal

#213 Fix docstring error
  examples/lineage/run.py
Labels: internal

#214 Hamza/add caching example
  examples/README.md
  examples/caching/README.md
  examples/caching/__init__.py
  examples/caching/run.py
Labels: internal

#216 Update readme
  README.md
  docs/readme/airflow-small.png
  docs/readme/kubeflow-small.png
  docs/readme/sam-side-by-side-full-text.png
  docs/readme/zenml-is-the-glue.jpeg
Labels: documentation, internal

#219 Hamza/add small utils
  README.md
  docs/book/zenml-quickstart-guide.md
  examples/quickstart/quickstart_simple.py
  src/zenml/integrations/sklearn/helpers/__init__.py
  src/zenml/integrations/sklearn/helpers/digits.py
  src/zenml/utils/__init__.py
Labels: internal

#222 Docs fixes
  docs/book/caching.md
  docs/book/guides/high-level-api/README.md
  docs/book/guides/using-cache.md
  docs/book/integrations.md
  docs/book/quickstart-guide.md
  docs/book/toc.md
  docs/book/why-zenml.md
Labels: documentation, internal

#221 Fix naming error
  src/zenml/integrations/graphviz/__init__.py
Labels: documentation, internal

#224 Remove framework design
  docs/book/index.md
  docs/book/toc.md
  docs/book/toc_base.md
Labels: documentation, internal

#223 Alexej/eng 234 zenml integration install
  .github/workflows/generate_doc_string_docs.yml
  .github/workflows/main.yml
  .github/workflows/publish-api-docs.yml
  .github/workflows/publish.yml
  .github/workflows/pull_request.yml
  src/zenml/cli/__init__.py
  src/zenml/cli/integration.py
  src/zenml/cli/utils.py
  tests/cli/test_integration.py
Labels: internal

#225 Fix deployment section order
  docs/book/cloud-pipelines.md
  docs/book/toc.md
Labels: documentation, internal

#227 the readme of the example
  examples/standard_interfaces/README.md
Labels: internal

#228 Delete blog reference from release notes
  RELEASE_NOTES.md
Labels: documentation, internal

#229 Docs updates
  docs/book/core-concepts.md
  docs/book/guides/post-execution-workflow/naming-a-pipeline-run.md
Labels: documentation, internal

#230 Update kubeflow guide
  docs/book/.gitbook/assets/localstack-with-kubeflow-orchestrator.png
  docs/book/.gitbook/assets/localstack.png
  docs/book/guides/low-level-api/README.md
  docs/book/guides/low-level-api/chapter-7.md
  examples/kubeflow/README.md
  examples/low_level_guide/chapter_7.py
  examples/low_level_guide/chapter_7_requirements.txt
Labels: internal

#231 Updated quickstart to reflect newest zenml version
  examples/quickstart/quickstart.ipynb
Labels: internal

#232 Baris/update docs with class api
  docs/book/guides/class-based-api/README.md
  docs/book/guides/class-based-api/chapter-1.md
  docs/book/guides/class-based-api/chapter-2.md
  docs/book/guides/class-based-api/chapter-3.md
  docs/book/guides/class-based-api/chapter-4.md
  docs/book/guides/class-based-api/chapter-5.md
  docs/book/guides/functional-api/README.md
  docs/book/guides/functional-api/chapter-1.md
  docs/book/guides/functional-api/chapter-2.md
  docs/book/guides/functional-api/chapter-3.md
  docs/book/guides/functional-api/chapter-4.md
  docs/book/guides/functional-api/chapter-5.md
  docs/book/guides/functional-api/chapter-6.md
  docs/book/guides/functional-api/chapter-7.md
  docs/book/guides/high-level-api/README.md
  docs/book/guides/high-level-api/chapter-1.md
  docs/book/quickstart-guide.md
  docs/book/toc.md
  docs/book/toc_base.md
  examples/class_based_api/__init__.py
  examples/class_based_api/chapter_1.py
  examples/class_based_api/chapter_2.py
  examples/class_based_api/chapter_3.py
  src/zenml/integrations/sklearn/steps/sklearn_evaluator.py
Labels: internal

#236 fixing a small typo [ci skip]
  docs/book/guides/class-based-api/README.md
Labels: internal

#237 fix broken links
  CODE-OF-CONDUCT.md
  README.md
  docs/book/core-concepts.md
  docs/book/guides/functional-api/chapter-1.md
  docs/book/guides/functional-api/chapter-2.md
  docs/book/guides/functional-api/chapter-5.md
  docs/book/integrations.md
  docs/book/support/tutorials.md
Labels: documentation, internal

#240 Unified use of cli_utils.print_table for all table format cli printouts
  src/zenml/cli/artifact.py
  src/zenml/cli/container_registry.py
  src/zenml/cli/integration.py
  src/zenml/cli/metadata.py
  src/zenml/cli/orchestrator.py
  src/zenml/cli/stack.py
  src/zenml/cli/utils.py
Labels: internal

#239 Remove unused tfx kubeflow code
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_utils.py
Labels: internal

#241 Relaxed typing requirements for cli_utils.print_table
  src/zenml/cli/utils.py
Labels: internal

#242 Pass input artifact types to kubeflow container entrypoint
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
Labels: internal

#243 Catch duplicate run name error and throw custom exception
  src/zenml/cli/utils.py
  src/zenml/exceptions.py
  src/zenml/integrations/airflow/orchestrators/airflow_component.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/orchestrators/local/local_dag_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/utils/string_utils.py
  tests/cli/test_utils.py
  tests/utils/test_string_utils.py
Labels: internal

#244 Improved logs
  run.py
  src/zenml/pipelines/base_pipeline.py
Labels: internal

#245 CLI active component highlighting
  src/zenml/cli/artifact.py
  src/zenml/cli/container_registry.py
  src/zenml/cli/integration.py
  src/zenml/cli/metadata.py
  src/zenml/cli/orchestrator.py
  src/zenml/cli/stack.py
  src/zenml/cli/utils.py
Labels: enhancement, internal

#250 CLI argument and option flag consistency improvements
  src/zenml/cli/artifact_store.py
  src/zenml/cli/container_registry.py
  src/zenml/cli/integration.py
  src/zenml/cli/metadata_store.py
  src/zenml/cli/orchestrator.py
  src/zenml/cli/stack.py
  tests/cli/test_integration.py
Labels: enhancement, internal

#252 Invalidate caching when a step requires a step context
  src/zenml/steps/base_step.py
  src/zenml/steps/step_context.py
  src/zenml/steps/step_decorator.py
  tests/steps/test_base_step.py
Labels: internal

#254 Implement better error messages for custom step output artifact types
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  tests/steps/test_base_step.py
Labels: internal

#251 Small improvements
  src/zenml/cli/integration.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/registry.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_dag_runner.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
Labels: internal

#249 Kubeflow dockerignore
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/cli/artifact_store.py
  src/zenml/cli/base.py
  src/zenml/cli/container_registry.py
  src/zenml/cli/example.py
  src/zenml/cli/metadata_store.py
  src/zenml/cli/orchestrator.py
  src/zenml/config/global_config.py
  src/zenml/container_registry/base_container_registry.py
  src/zenml/core/base_component.py
  src/zenml/core/local_service.py
  src/zenml/core/mapping_utils.py
  src/zenml/core/repo.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/docker_utils.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/io/utils.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/stacks/base_stack.py
  src/zenml/utils/string_utils.py
  tests/artifact_stores/test_local_artifact_store.py
  tests/conftest.py
  tests/core/test_base_component.py
  tests/core/test_local_service.py
  tests/core/test_repo.py
  tests/integrations/gcp/artifact_stores/test_gcp_artifact_store.py
  tests/utils/test_string_utils.py
Labels: internal

#257 Rename container registry folder to be consistent with the other stack components
  src/zenml/cli/container_registry.py
  src/zenml/container_registries/__init__.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/core/local_service.py
  src/zenml/stacks/base_stack.py
Labels: internal

#256 Update todo script
  docs/README.md
  scripts/update_todos.py
  src/zenml/exceptions.py
Labels: internal

#255 Update docs following CLI change
  docs/book/features/cloud-pipelines.md
  docs/book/guides/functional-api/deploy-to-production.md
  src/zenml/cli/__init__.py
Labels: documentation, internal

#258 Bump mypy version
  pyproject.toml
  src/zenml/utils/daemon.py
Labels: internal

#259 Kubeflow Windows daemon alternative
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
Labels: internal

#260 Run pre commit in local environment
  .pre-commit-config.yaml
Labels: internal

#262 Hamza/eng 269 move beam out
  src/zenml/integrations/__init__.py
  src/zenml/integrations/beam/__init__.py
  src/zenml/integrations/beam/materializers/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
  src/zenml/materializers/beam_materializer.py
  src/zenml/orchestrators/local/local_dag_runner.py
Labels: internal

#261 Update docs
  examples/airflow_local/README.md
  examples/kubeflow/README.md
  examples/kubeflow/ZenML Walkthrough Kubeflow Pipelines.ipynb
  examples/kubeflow/setup.sh
  src/zenml/cli/__init__.py
Labels: documentation, internal

#271 Hamza/update readme with contribitions
  CONTRIBUTING.md
  README.md
Labels: internal

#270 Hamza/eng 256 backoff analytics
  examples/legacy/backends/graphics/architecture.png
  src/zenml/logger.py
  src/zenml/utils/analytics_utils.py
Labels: internal

#264 Add spellcheck
  .codespell-ignore-words
  .pre-commit-config.yaml
  CODE_GUIDLINES.md
  RELEASE_NOTES.md
  docs/book/features/artifacts.md
  docs/book/guides/functional-api/import-dynamic-data.md
  docs/book/guides/functional-api/train-and-evaluate.md
  docs/book/introduction/core-concepts.md
  examples/airflow_local/__init__.py
  examples/airflow_local/run.py
  examples/caching/README.md
  examples/caching/__init__.py
  examples/caching/run.py
  examples/class_based_api/__init__.py
  examples/class_based_api/chapter_1.py
  examples/class_based_api/chapter_2.py
  examples/class_based_api/chapter_3.py
  examples/dag_visualizer/__init__.py
  examples/dag_visualizer/run.py
  examples/functional_api/__init__.py
  examples/functional_api/chapter_1.py
  examples/functional_api/chapter_2.py
  examples/functional_api/chapter_3.py
  examples/functional_api/chapter_4.py
  examples/functional_api/chapter_5.py
  examples/functional_api/chapter_6.py
  examples/functional_api/chapter_7.py
  examples/kubeflow/ZenML Walkthrough Kubeflow Pipelines.ipynb
  examples/kubeflow/__init__.py
  examples/kubeflow/run.py
  examples/lineage/__init__.py
  examples/lineage/run.py
  examples/not_so_quickstart/__init__.py
  examples/not_so_quickstart/run.py
  examples/not_so_quickstart/steps/tf_steps.py
  examples/not_so_quickstart/steps/torch_steps.py
  examples/quickstart/__init__.py
  examples/quickstart/quickstart.ipynb
  examples/quickstart/quickstart.py
  examples/standard_interfaces/run.py
  examples/statistics/__init__.py
  examples/statistics/run.py
  pyproject.toml
  scripts/check-spelling.sh
  scripts/format.sh
  src/zenml/cli/example.py
  src/zenml/cli/integration.py
  src/zenml/core/git_wrapper.py
  src/zenml/integrations/facets/__init__.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/orchestrators/local/local_dag_runner.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/step_output.py
  src/zenml/steps/utils.py
  src/zenml/utils/yaml_utils.py
  tests/core/test_base_component.py
  tests/integration/generate_test_pipelines.py
  tests/test_constants.py
Labels: internal

#263 Using the pipeline run name to explicitly access when explaining the …
  examples/not_so_quickstart/run.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/post_execution/step.py
Labels: internal

#273 Import user main module in kubeflow entrypoint to make sure all components are registered
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: internal

#272 Fix cli version command
  src/zenml/cli/cli.py
  src/zenml/cli/version.py
Labels: internal

#274 User is informed of version mismatch and example pull defaults to cod…
  src/zenml/cli/example.py
Labels: internal

#275 Hamza/eng 274 telemetry
  src/zenml/cli/artifact_store.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/metadata_store.py
  src/zenml/cli/orchestrator.py
  src/zenml/core/component_factory.py
  src/zenml/core/local_service.py
  src/zenml/core/repo.py
  src/zenml/integrations/dash/visualizers/pipeline_run_lineage_visualizer.py
  src/zenml/utils/analytics_utils.py
  tests/utils/test_analytics_utils.py
Labels: internal

#276 Update docs with right commands and events
  docs/book/features/cloud-pipelines.md
  docs/book/guides/functional-api/deploy-to-production.md
  docs/book/support/usage-analytics.md
  examples/kubeflow/README.md
  examples/kubeflow/ZenML Walkthrough Kubeflow Pipelines.ipynb
  examples/kubeflow/setup.sh
Labels: internal

#277 Fixed type annotation for some python versions
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/pull_request.yml
  .github/workflows/team_labeler.yml
  .github/workflows/update_todos.yml
  src/zenml/cli/artifact_store.py
  src/zenml/cli/metadata_store.py
  src/zenml/cli/orchestrator.py
Labels: internal

#278 Force pull overwrites local examples without user confirmation
  src/zenml/cli/example.py
Labels: bug, internal

#280 Updated README with latest features
  examples/README.md
Labels: internal

#279 Examples are automatically pulled if not present before any example command is run
  src/zenml/cli/example.py
Labels: bug, internal
