Repository zenml-io/zenml, pull requests merged in 2022-06, with the labels that each got.

#677 Fix failing integration tests
  src/zenml/integrations/whylogs/__init__.py
Labels: bug, internal

#673 Update `zenml stack down` to use --force flag
  docs/book/advanced-guide/run-on-kubeflow.md
  examples/airflow_orchestration/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  src/zenml/cli/stack.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: enhancement, internal

#678 Fix class resolving on windows
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_source_utils.py
Labels: bug, internal

#680 Docstring checks for `cli` module
  .pyspelling-ignore-words
  scripts/docstring.sh
  scripts/lint.sh
  src/zenml/cli/example.py
  src/zenml/cli/feature.py
  src/zenml/cli/formatter.py
  src/zenml/cli/integration.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
Labels: documentation, internal

#672 Docstring fixes for `entrypoints` and `experiment_trackers` modules
  .pyspelling-ignore-words
  pyproject.toml
  scripts/docstring.sh
  scripts/lint.sh
  src/zenml/entrypoints/__init__.py
  src/zenml/entrypoints/step_entrypoint.py
  src/zenml/entrypoints/step_entrypoint_configuration.py
  src/zenml/experiment_trackers/__init__.py
  src/zenml/experiment_trackers/base_experiment_tracker.py
Labels: documentation, enhancement, internal

#683 Reviewer Reminder
  .github/workflows/pull-request-reviewer-reminder.yml
Labels: internal

#670 Fix some docs phrasings and headers
  docs/book/developer-guide/fetching-historic-runs.md
  docs/book/developer-guide/materializer.md
  docs/book/developer-guide/post-execution-workflow.md
  docs/book/developer-guide/runtime-configuration.md
  docs/book/developer-guide/steps-and-pipelines.md
  docs/book/introduction/core-concepts.md
  docs/book/toc.md
Labels: documentation, internal

#690 Extending Alerters Docs
  .pyspelling-ignore-words
  docs/book/advanced-guide/alerts.md
  docs/book/developer-guide/materializer.md
  docs/book/extending-zenml/alerter.md
  docs/book/extending-zenml/orchestrator.md
  docs/book/toc.md
  src/zenml/alerter/base_alerter.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/steps/step_interfaces/base_alerter_step.py
Labels: internal

#694 Add docstrings for `materializers` and `metadata_stores`
  .pyspelling-ignore-words
  scripts/docstring.sh
  scripts/lint.sh
  src/zenml/materializers/__init__.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/beam_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/materializers/pandas_materializer.py
  src/zenml/materializers/service_materializer.py
  src/zenml/metadata_stores/__init__.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/metadata_stores/mysql_secret_schema.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
Labels: documentation, internal

#701 Update ignored words
  .pyspelling-ignore-words
Labels: bug, internal

#702 Add model deployer to CLI docs
  src/zenml/cli/__init__.py
Labels: enhancement, internal

#703 GitHub actions orchestrator example
  .pyspelling-ignore-words
  docs/book/extending-zenml/orchestrators.md
  docs/book/extending-zenml/secrets-managers.md
  examples/github_actions_orchestration/README.md
  examples/github_actions_orchestration/assets/github_actions_ui.png
  examples/github_actions_orchestration/pipelines/__init__.py
  examples/github_actions_orchestration/pipelines/github_example_pipeline/github_example_pipeline.py
  examples/github_actions_orchestration/run.py
  examples/github_actions_orchestration/steps/__init__.py
  examples/github_actions_orchestration/steps/first_step/first_step.py
  examples/github_actions_orchestration/steps/second_step/second_step.py
  examples/github_actions_orchestration/steps/third_step/third_step.py
  src/zenml/integrations/github/orchestrators/github_actions_entrypoint_configuration.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
Labels: documentation, enhancement, internal

#707 Fix broken link
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  src/zenml/steps/base_step.py
Labels: bug, documentation, enhancement, internal

#705 Add stack component copy command
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/utils/analytics_utils.py
Labels: enhancement, internal

#708 Remove `force` flag from secrets managers' implementation
  docs/book/extending-zenml/secrets-managers.md
  src/zenml/cli/secret.py
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
  src/zenml/integrations/azure/secrets_managers/azure_secrets_manager.py
  src/zenml/integrations/gcp/secrets_manager/gcp_secrets_manager.py
  src/zenml/integrations/github/secrets_managers/github_secrets_manager.py
  src/zenml/secrets_managers/base_secrets_manager.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  tests/unit/integrations/gcp/secrets_manager/__init__.py
  tests/unit/integrations/gcp/secrets_manager/test_gcp_secrets_manager.py
  tests/unit/secrets_manager/test_local_secrets_manager.py
Labels: enhancement, internal

#712 Fixed wrong example README
  examples/vertex_ai_orchestration/README.md
Labels: bug, internal

#710 Fix dead links in integrations docs.
  docs/book/advanced-guide/integrations.md
Labels: internal

#717 Adding azure-keyvault-secrets to azure integration dependencies
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/azure/secrets_managers/__init__.py
  src/zenml/integrations/azure/secrets_managers/azure_secrets_manager.py
Labels: bug, internal

#714 Replace alerter standard steps by Slack-specific steps to fix config issue.
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/send-automated-chat-alerts.md
  examples/slack_alert/run_ask.py
  examples/slack_alert/run_post.py
  src/zenml/alerter/__init__.py
  src/zenml/alerter/alerter_utils.py
  src/zenml/cli/stack.py
  src/zenml/integrations/slack/steps/slack_alerter_ask_step.py
  src/zenml/integrations/slack/steps/slack_alerter_post_step.py
Labels: bug, internal

#724 Invalidate cache
  pyproject.toml
Labels: bug, enhancement, internal

#688 Kubernetes orchestrator
  .pyspelling-ignore-words
  docs/book/advanced-guide/integrations.md
  docs/book/extending-zenml/metadata-stores.md
  docs/book/extending-zenml/orchestrators.md
  examples/kubernetes_orchestration/README.md
  examples/kubernetes_orchestration/pipelines/kubernetes_example_pipeline.py
  examples/kubernetes_orchestration/run.py
  examples/kubernetes_orchestration/setup.sh
  examples/kubernetes_orchestration/steps/__init__.py
  examples/kubernetes_orchestration/steps/evaluator.py
  examples/kubernetes_orchestration/steps/importer.py
  examples/kubernetes_orchestration/steps/skew_comparisons.py
  examples/kubernetes_orchestration/steps/sklearn_trainer.py
  src/zenml/constants.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/kubernetes/__init__.py
  src/zenml/integrations/kubernetes/metadata_stores/__init__.py
  src/zenml/integrations/kubernetes/metadata_stores/kubernetes_metadata_store.py
  src/zenml/integrations/kubernetes/orchestrators/__init__.py
  src/zenml/integrations/kubernetes/orchestrators/dag_runner.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint_configuration.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_step_entrypoint_configuration.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/repository.py
  src/zenml/utils/daemon.py
  tests/unit/integrations/kubernetes/__init__.py
  tests/unit/integrations/kubernetes/orchestrators/__init__.py
  tests/unit/integrations/kubernetes/orchestrators/test_dag_runner.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
Labels: enhancement, internal

#689 Vault Secrets Manager integration - KV Secrets Engine
  .github/workflows/unit-test.yml
  .pyspelling-ignore-words
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/manage-your-secrets.md
  examples/cloud_secrets_manager/README.md
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/vault/__init__.py
  src/zenml/integrations/vault/secrets_manager/__init__.py
  src/zenml/integrations/vault/secrets_manager/vault_secrets_manager.py
  tests/unit/integrations/vault/__init__.py
  tests/unit/integrations/vault/secrets_manager/__init__.py
  tests/unit/integrations/vault/secrets_manager/test_vault_secrets_manager.py
Labels: enhancement

#723 Add missing help text for CLI commands
  src/zenml/cli/base.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/stack.py
  src/zenml/cli/user_management.py
Labels: bug, internal

#713 Misc bugfixes
  examples/github_actions_orchestration/README.md
  src/zenml/cli/secret.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/utils/docker_utils.py
Labels: bug, internal

#555 Great Expectations integration for data validation
  .pyspelling-ignore-words
  examples/great_expectations_data_validation/README.md
  examples/great_expectations_data_validation/__init__.py
  examples/great_expectations_data_validation/assets/expectation_suite.png
  examples/great_expectations_data_validation/assets/validation_result.png
  examples/great_expectations_data_validation/great_expectations/great_expectations.yml
  examples/great_expectations_data_validation/pipelines/__init__.py
  examples/great_expectations_data_validation/pipelines/validation.py
  examples/great_expectations_data_validation/run.py
  examples/great_expectations_data_validation/setup.sh
  examples/great_expectations_data_validation/steps/__init__.py
  examples/great_expectations_data_validation/steps/importer.py
  examples/great_expectations_data_validation/steps/prevalidator.py
  examples/great_expectations_data_validation/steps/profiler.py
  examples/great_expectations_data_validation/steps/splitter.py
  examples/great_expectations_data_validation/steps/validator.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/data_validators/__init__.py
  src/zenml/data_validators/base_data_validator.py
  src/zenml/enums.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/integrations/great_expectations/data_validators/__init__.py
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/great_expectations/ge_store_backend.py
  src/zenml/integrations/great_expectations/materializers/__init__.py
  src/zenml/integrations/great_expectations/materializers/ge_materializer.py
  src/zenml/integrations/great_expectations/steps/__init__.py
  src/zenml/integrations/great_expectations/steps/ge_profiler.py
  src/zenml/integrations/great_expectations/steps/ge_validator.py
  src/zenml/integrations/great_expectations/steps/utils.py
  src/zenml/integrations/great_expectations/visualizers/__init__.py
  src/zenml/integrations/great_expectations/visualizers/ge_visualizer.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/stack/stack.py
  src/zenml/steps/utils.py
  tests/integration/example_validations.py
Labels: enhancement, internal

#730 Fix GCP artifact store
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
Labels: bug, internal

#732 Changed PR template to reflect integrations flow
  .github/pull_request_template.md
Labels: internal

#737 Fix broken Feast integration
  src/zenml/integrations/feast/__init__.py
Labels: bug, internal

#740 Describe args run.py application actually supports
  examples/mlflow_deployment/README.md
Labels: bug, documentation

#743 Update kubernetes_orchestration example
  .pyspelling-ignore-words
  examples/kubernetes_orchestration/README.md
  examples/kubernetes_orchestration/assets/facets_analysis_output.png
  examples/kubernetes_orchestration/assets/kubectl_get_pods_output.png
  examples/kubernetes_orchestration/assets/python_run_output.png
  examples/kubernetes_orchestration/assets/zenml_kubernetes_aws_stack_overview.png
  examples/kubernetes_orchestration/assets/zenml_stack_up_output.png
Labels: enhancement, internal

#744 Fix some example links
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/feast_feature_store/README.md
  examples/github_actions_orchestration/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/step_operator_remote_training/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
Labels: bug, internal
