Repository zenml-io/zenml, pull requests merged in 2022-10, with the labels that each got.

#911 Scenarios overview over the ZenML deployment
  docs/book/assets/getting_started/Scenario1.png
  docs/book/assets/getting_started/Scenario2.png
  docs/book/assets/getting_started/Scenario3.1.png
  docs/book/assets/getting_started/Scenario3.2.png
  docs/book/getting-started/deploying-zenml/how-it-works.md
Labels: documentation, internal

#912 Update `kserve` README
  examples/kserve_deployment/README.md
Labels: documentation, internal

#917 Confirmation prompts were not working
  src/zenml/cli/pipeline.py
  src/zenml/cli/stack.py
  src/zenml/cli/user_management.py
Labels: bug, internal

#920 Stacks can be registered in `Click<8.0.0` now
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
Labels: bug, internal

#919 Made Pipeline and Stack optional on the HydratedPipelineRunModel
  src/zenml/zen_server/models/pipeline_models.py
Labels: bug, internal

#915 Renamed all references from ZenServer to ZenML Server in logs and comments
  src/zenml/pipelines/base_pipeline.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/deploy/docker/__init__.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/__init__.py
  src/zenml/zen_server/deploy/local/local_provider.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/deploy/terraform/__init__.py
  src/zenml/zen_server/deploy/terraform/providers/__init__.py
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/openapi3_0.yaml
  src/zenml/zen_server/utils.py
Labels: internal

#921 Prettify pipeline runs list CLI output.
  .gitignore
  src/zenml/cli/pipeline.py
  src/zenml/cli/utils.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/zen_server/models/pipeline_models.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#904 Warn when registering non-local component with local ZenServer
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/client.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/azure/flavors/azureml_step_operator_flavor.py
  src/zenml/integrations/feast/flavors/feast_feature_store_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/github/flavors/github_actions_orchestrator_flavor.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
  src/zenml/integrations/great_expectations/flavors/great_expectations_data_validator_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/mlflow/flavors/mlflow_experiment_tracker_flavor.py
  src/zenml/integrations/mlflow/flavors/mlflow_model_deployer_flavor.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/stack/stack_component.py
  tests/unit/container_registries/test_base_container_registry.py
Labels: enhancement, internal

#922 Fix duplicate results in pipeline run lists and unlisted flag.
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#916 Fix error log
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/zen_server/deploy/local/local_provider.py
Labels: internal

#914 Advanced guide: Practical MLOps section
  docs/book/advanced-guide/practical/containerization.md
  docs/book/advanced-guide/practical/deploying-models.md
  docs/book/advanced-guide/practical/practical-mlops.md
  docs/book/advanced-guide/practical/secrets-management.md
  docs/book/advanced-guide/practical/stack-recipes.md
  docs/book/advanced-guide/practical/switching-orchestration.md
  docs/book/advanced-guide/practical/tracking-experiments.md
  docs/book/advanced-guide/practical/validating-data.md
  docs/book/assets/deployment/seldon-model-deployer.gif
  docs/book/assets/deployment/served-models-cli.png
Labels: documentation, internal

#913 Update cli docs
  src/zenml/cli/__init__.py
  src/zenml/cli/server.py
  src/zenml/services/service_endpoint.py
  src/zenml/zen_server/deploy/deployer.py
  src/zenml/zen_server/deploy/docker/docker_provider.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
Labels: enhancement, internal

#923 Fix Pipeline Run Status
  pyproject.toml
  src/zenml/constants.py
  src/zenml/models/pipeline_models.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/utils/proto_utils.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/metadata_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/unit/post_execution/test_pipeline_run.py
Labels: bug, internal

#926 Change the CLI emoji for whether a stack is shared or not.
  src/zenml/cli/utils.py
Labels: enhancement, internal

#925 Fix running pipelines from different locations.
  src/zenml/config/step_configurations.py
Labels: bug, internal

#929 Fix zenml stack-component describe CLI command.
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
Labels: bug, internal

#928 Update custom deployment to use ArtifactModel
  src/zenml/integrations/seldon/__init__.py
  src/zenml/utils/materializer_utils.py
Labels: bug, internal

#924 Fix the CI unit test and integration test failures
  examples/mlflow_deployment/setup.sh
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/setup.sh
  src/zenml/__init__.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/user_management.py
  src/zenml/services/container/container_service.py
  src/zenml/services/container/entrypoint.py
  src/zenml/services/local/local_daemon_entrypoint.py
  src/zenml/services/terraform/terraform_service.py
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
  tests/integration/example_validations.py
  tests/integration/secrets_manager/test_secrets_manager_scope.py
  tests/integration/secrets_manager/utils.py
  tests/integration/test_examples.py
  tests/unit/zen_server/test_zen_server.py
Labels: bug, internal

#931 Extend Post Execution Class Properties
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
Labels: enhancement, internal

#918 Fixes for examples
  examples/README.md
  examples/add_your_own/template_README.md
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/cloud_secrets_manager/steps/secret_loader/secret_loader_step.py
  examples/custom_code_deployment/README.md
  examples/deepchecks_data_validation/README.md
  examples/evidently_drift_detection/README.md
  examples/facets_visualize_statistics/README.md
  examples/feast_feature_store/README.md
  examples/feast_feature_store/run.py
  examples/github_actions_orchestration/README.md
  examples/great_expectations_data_validation/README.md
  examples/huggingface/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/label_studio_annotation/README.md
  examples/lightgbm/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/neural_prophet/README.md
  examples/pytorch/README.md
  examples/quickstart/README.md
  examples/scipy/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/slack_alert/run_post.py
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/README.md
  examples/xgboost/README.md
  src/zenml/integrations/feast/feature_stores/feast_feature_store.py
Labels: bug, documentation, internal

#932 Update cheat sheet
  docs/book/assets/zenml_cheat_sheet.pdf
  docs/book/assets/zenml_cheat_sheet.png
Labels: documentation, internal

#934 Update remaining example of managing stacks.
  docs/book/starter-guide/stacks/managing-stacks.md
Labels: internal

#937 Capitalize all docs page titles.
  docs/book/toc.md
Labels: internal

#940 Increase field sizes for docstrings and step parameters.
  src/zenml/zen_stores/schemas/pipeline_schemas.py
Labels: bug, internal

#938 Fixing the bug in the registration of custom flavors
  src/zenml/cli/stack_components.py
  src/zenml/client.py
  src/zenml/utils/source_utils.py
Labels: bug, internal

#936 Implemented `docstring` Attribute of StepModel
  src/zenml/config/compiler.py
  src/zenml/config/step_configurations.py
  src/zenml/zen_stores/metadata_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/config/test_compiler.py
Labels: enhancement, internal

#941 Fix shared stack emoji
  src/zenml/cli/utils.py
Labels: bug, internal

#944 Typo fix
  .pyspelling-ignore-words
Labels: bug, internal

#942 Update Kubernetes Orchestrator Example
  examples/kubernetes_orchestration/README.md
Labels: documentation, internal

#939 Add code and instructions to run quickstart on Colab.
  examples/quickstart/notebooks/quickstart.ipynb
Labels: enhancement, internal

#945 Fixing the interaction in getting stacks/components
  src/zenml/cli/utils.py
  src/zenml/client.py
Labels: bug, internal

#946 Fix Kubeflow run name
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#947 Fixed GitHub/Colab JSON formatting error on quickstart.
  examples/quickstart/notebooks/quickstart.ipynb
Labels: bug, internal

#948 Fixed GitHub/Colab JSON formatting error on quickstart. (#947)
  examples/quickstart/notebooks/quickstart.ipynb
Labels: internal, backport

#949 Fix 0.20.2 release notes.
  RELEASE_NOTES.md
Labels: internal, backport

#950 correct code from merge and fix import
  src/zenml/cli/stack_recipes.py
Labels: internal

#956 Check for active component using id instead of name
  src/zenml/cli/utils.py
Labels: bug, internal

#955 Tekton fix
  src/zenml/integrations/tekton/orchestrators/tekton_entrypoint_configuration.py
Labels: bug, internal

#957 Improve zenml up/down UX and other fixes
  .github/actions/setup_environment/action.yml
  .pyspelling-ignore-words
  docs/book/getting-started/deploying-zenml/docker.md
  src/zenml/cli/base.py
  src/zenml/cli/secret.py
  src/zenml/cli/server.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/enums.py
  src/zenml/integrations/feast/feature_stores/feast_feature_store.py
  src/zenml/models/user_management_models.py
  src/zenml/services/local/local_service.py
  src/zenml/utils/daemon.py
  src/zenml/zen_server/deploy/docker/docker_provider.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_provider.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/unit/cli/test_utils.py
  tests/unit/zen_server/test_zen_server.py
Labels: bug, internal

#958 Update kubeflow docs for multi-tenant deployments
  docs/book/component-gallery/orchestrators/kubeflow.md
  examples/kubeflow_pipelines_orchestration/README.md
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
Labels: internal

#959 Update kubeflow.md
  .github/workflows/release.yml
  docs/book/component-gallery/orchestrators/kubeflow.md
Labels: documentation

#954 Add additional stack validation for step operators
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/spark/step_operators/kubernetes_step_operator.py
Labels: enhancement, internal

#951 Fix pipeline run dashboard URL for unlisted runs
  src/zenml/pipelines/base_pipeline.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal

#964 Detect failed executions
  src/zenml/orchestrators/base_orchestrator.py
Labels: bug, internal

#960 Only build docker images for custom deployments
  src/zenml/integrations/kserve/constants.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/seldon/constants.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
Labels: bug, internal

#966 M1 Mac Installation Tutorial
  docs/book/assets/getting_started/installation/rosetta_terminal_1.png
  docs/book/assets/getting_started/installation/rosetta_terminal_2.png
  docs/book/assets/getting_started/installation/rosetta_terminal_3.png
  docs/book/assets/getting_started/installation/rosetta_terminal_4.png
  docs/book/assets/getting_started/installation/rosetta_terminal_5.png
  docs/book/assets/getting_started/installation/rosetta_terminal_6.png
  docs/book/getting-started/installation/installation.md
  docs/book/getting-started/installation/m1-mac-installation.md
  docs/book/toc.md
Labels: internal

#968 Update ZenBytes links in docs
  docs/book/advanced-guide/practical/practical-mlops.md
Labels: internal

#967 Fix the API docs builder
  .github/workflows/publish_api_docs.yml
  .pyspelling-ignore-words
  src/zenml/cli/server.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/integrations/feast/__init__.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/kubeflow/__init__.py
  src/zenml/integrations/tekton/__init__.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/metadata_config_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/roles_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/routers/teams_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  tests/conftest.py
Labels: bug, internal

#973 Add simple node affinitiy configurations
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: enhancement, internal

#962 First iteration of the CLI optimization
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/annotator.py
  src/zenml/cli/base.py
  src/zenml/cli/cli.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/feature.py
  src/zenml/cli/formatter.py
  src/zenml/cli/model.py
  src/zenml/cli/profile.py
  src/zenml/cli/secret.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/stack_recipes.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/constants.py
  src/zenml/environment.py
  src/zenml/exceptions.py
  src/zenml/io/fileio.py
  src/zenml/logger.py
  src/zenml/recipes/__init__.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/secret/__init__.py
  src/zenml/secret/arbitrary_secret_schema.py
  src/zenml/services/terraform/terraform_service.py
  src/zenml/utils/io_utils.py
  tests/unit/cli/test_utils.py
Labels: enhancement, internal

#976 Fix accessing local zen store and artifact store in containers
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/cli/server.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/config/store_config.py
  src/zenml/constants.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_server/deploy/deployer.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: bug, internal

#972 K3d local registry pod spec updated
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#986 Remove beam dependency
  pyproject.toml
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: enhancement, internal

#981 Fix error message when registering secret without secrets manager
  src/zenml/cli/annotator.py
  src/zenml/cli/model.py
  src/zenml/cli/secret.py
Labels: bug, internal

#987 Update cheat sheet up to `zenml==0.20.4`
  docs/book/assets/zenml_cheat_sheet.pdf
  docs/book/assets/zenml_cheat_sheet.png
Labels: hacktoberfest-accepted

#971 Example fixes (part 2)
  .gitignore
  .pyspelling-ignore-words
  docs/book/guidelines/global-config.md
  docs/book/guidelines/migration-zero-twenty.md
  examples/feast_feature_store/feast_feature_repo/__init__.py
  examples/feast_feature_store/feast_feature_repo/data/driver_stats.parquet
  examples/feast_feature_store/feast_feature_repo/data/registry.db
  examples/feast_feature_store/feast_feature_repo/example.py
  examples/feast_feature_store/feast_feature_repo/example_repo.py
  examples/feast_feature_store/feast_feature_repo/feature_store.yaml
  examples/feast_feature_store/steps/getter/get_features_step.py
  src/zenml/cli/secret.py
  src/zenml/cli/utils.py
  src/zenml/integrations/feast/feature_stores/feast_feature_store.py
  src/zenml/integrations/label_studio/__init__.py
  src/zenml/zen_stores/base_zen_store.py
Labels: bug, documentation, internal

#989 Allow duplicate step classes inside a pipeline
  docs/book/legacy/developer-guide/steps-pipelines/steps-and-pipelines.md
  docs/book/starter-guide/pipelines/pipelines.md
  examples/great_expectations_data_validation/steps/validator.py
  src/zenml/config/compiler.py
  src/zenml/config/step_configurations.py
  src/zenml/integrations/deepchecks/steps/deepchecks_data_drift.py
  src/zenml/integrations/deepchecks/steps/deepchecks_data_integrity.py
  src/zenml/integrations/deepchecks/steps/deepchecks_model_drift.py
  src/zenml/integrations/deepchecks/steps/deepchecks_model_validation.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  src/zenml/integrations/great_expectations/steps/ge_profiler.py
  src/zenml/integrations/great_expectations/steps/ge_validator.py
  src/zenml/integrations/whylogs/steps/whylogs_profiler.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#984 Include deployment in azureml docker build
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
Labels: bug, internal

#978 Automatically open browser upon `zenml up` command
  src/zenml/cli/server.py
  src/zenml/constants.py
Labels: enhancement, internal, hacktoberfest-accepted

#979 Add a `just_mine` flag for `zenml stack list`
  src/zenml/cli/stack.py
Labels: enhancement, internal

#988 Replace old flavor references, fix the windows local ZenML server and other fixes
  .pyspelling-ignore-words
  src/zenml/cli/server.py
  src/zenml/constants.py
  src/zenml/data_validators/__init__.py
  src/zenml/data_validators/base_data_validator.py
  src/zenml/integrations/deepchecks/data_validators/deepchecks_data_validator.py
  src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/model_deployers/__init__.py
  src/zenml/model_deployers/base_model_deployer.py
  src/zenml/utils/docker_utils.py
  src/zenml/utils/networking_utils.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/helm/templates/deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
Labels: bug, internal

#993 Update GH actions example
  examples/github_actions_orchestration/README.md
  examples/github_actions_orchestration/pipelines/github_example_pipeline/github_example_pipeline.py
  src/zenml/cli/server.py
Labels: bug, internal

#983 Seprated code docs into `core` and `integration` docs
  .github/workflows/publish_api_docs.yml
  .gitignore
  docs/mkdocstrings_helper.py
  scripts/generate-docs.sh
Labels: enhancement, internal

#997 Add docs/mkdocstrings_helper.py to format script sources
  docs/mkdocstrings_helper.py
  scripts/format.sh
Labels: internal

#992 Further CLI optimization
  .pyspelling-ignore-words
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#998 Fix GCP Artifact Store listdir empty path
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
Labels: bug, internal

#999 Add flavors mini-video to docs
  docs/book/advanced-guide/stacks/custom-flavors.md
Labels: documentation, internal

#1000 Remove the Client() warning when used inside a step
  src/zenml/client.py
  src/zenml/data_validators/base_data_validator.py
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/great_expectations/ge_store_backend.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/model_deployers/base_model_deployer.py
  src/zenml/stack/authentication_mixin.py
Labels: bug, internal

#1002 Fix broken links caused by updated
  docs/book/advanced-guide/pipelines/containerization.md
  docs/book/advanced-guide/pipelines/materializers.md
  docs/book/advanced-guide/pipelines/step-metadata.md
  docs/book/component-gallery/alerters/slack.md
  docs/book/component-gallery/artifact-stores/amazon-s3.md
  docs/book/component-gallery/artifact-stores/artifact-stores.md
  docs/book/component-gallery/artifact-stores/azure-blob-storage.md
  docs/book/component-gallery/artifact-stores/custom.md
  docs/book/component-gallery/artifact-stores/gcloud-gcs.md
  docs/book/component-gallery/artifact-stores/local.md
  docs/book/component-gallery/container-registries/amazon-ecr.md
  docs/book/component-gallery/container-registries/azure.md
  docs/book/component-gallery/container-registries/custom.md
  docs/book/component-gallery/container-registries/default.md
  docs/book/component-gallery/container-registries/dockerhub.md
  docs/book/component-gallery/container-registries/gcloud.md
  docs/book/component-gallery/container-registries/github.md
  docs/book/component-gallery/data-validators/custom.md
  docs/book/component-gallery/data-validators/deepchecks.md
  docs/book/component-gallery/data-validators/evidently.md
  docs/book/component-gallery/data-validators/great-expectations.md
  docs/book/component-gallery/data-validators/whylogs.md
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/experiment-trackers/wandb.md
  docs/book/component-gallery/feature-stores/feast.md
  docs/book/component-gallery/model-deployers/custom.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/mlflow.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/github-actions.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/local-docker.md
  docs/book/component-gallery/orchestrators/local.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/secrets-managers/aws.md
  docs/book/component-gallery/secrets-managers/azure.md
  docs/book/component-gallery/secrets-managers/custom.md
  docs/book/component-gallery/secrets-managers/gcp.md
  docs/book/component-gallery/secrets-managers/github.md
  docs/book/component-gallery/secrets-managers/hashicorp-vault.md
  docs/book/component-gallery/secrets-managers/local.md
  docs/book/component-gallery/step-operators/amazon-sagemaker.md
  docs/book/component-gallery/step-operators/azureml.md
  docs/book/component-gallery/step-operators/custom.md
  docs/book/component-gallery/step-operators/gcloud-vertexai.md
  docs/book/guidelines/global-config.md
  docs/book/legacy/developer-guide/advanced-usage/docker.md
  docs/book/legacy/developer-guide/advanced-usage/environment.md
  docs/book/legacy/developer-guide/advanced-usage/materializer.md
  docs/book/legacy/developer-guide/advanced-usage/step-fixtures.md
  docs/book/legacy/developer-guide/stacks-repositories/repository.md
  docs/book/reference/glossary.md
  src/zenml/logger.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
Labels: bug, internal

#1006 Doc updates
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/getting-started/deploying-zenml/cli.md
  docs/book/getting-started/deploying-zenml/helm.md
Labels: internal

#1018 Fixing broken links in docs
  docs/book/advanced-guide/pipelines/containerization.md
  docs/book/advanced-guide/pipelines/materializers.md
  docs/book/advanced-guide/practical/deploying-models.md
  docs/book/advanced-guide/practical/practical-mlops.md
  docs/book/advanced-guide/practical/secrets-management.md
  docs/book/advanced-guide/practical/tracking-experiments.md
  docs/book/advanced-guide/practical/validating-data.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/installation/installation.md
  docs/book/reference/cheat-sheet.md
  docs/book/reference/community-and-content.md
  docs/book/starter-guide/pipelines/iterating.md
  docs/book/starter-guide/pipelines/pipelines.md
  docs/book/starter-guide/stacks/stacks.md
Labels: documentation, internal

#1021 Label Studio example fix
  .pyspelling-ignore-words
  docs/book/component-gallery/artifact-stores/azure-blob-storage.md
  examples/label_studio_annotation/README.md
  examples/label_studio_annotation/steps/deployment_triggers.py
  examples/label_studio_annotation/steps/get_labeled_data.py
  examples/label_studio_annotation/steps/get_or_create_dataset.py
  examples/label_studio_annotation/steps/load_image_data_step.py
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/label_studio_annotation/steps/pytorch_trainer.py
  examples/label_studio_annotation/steps/sync_new_data_to_label_studio.py
Labels: bug, internal

#1010 Docs for using CUDA-enabled docker images
  docs/book/advanced-guide/pipelines/containerization.md
  docs/book/advanced-guide/pipelines/gpu-hardware.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/custom.md
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/local-docker.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/step-operators/amazon-sagemaker.md
  docs/book/component-gallery/step-operators/azureml.md
  docs/book/component-gallery/step-operators/custom.md
  docs/book/component-gallery/step-operators/gcloud-vertexai.md
  docs/book/component-gallery/step-operators/step-operators.md
  docs/book/toc.md
  examples/airflow_orchestration/README.md
Labels: documentation, internal

#1020 Add social media heading on docs page
  .github/teams.yml
  docs/book/reference/community-and-content.md
Labels: documentation, internal, hacktoberfest-accepted

#1012 Add executing custom command for getting requirements
  docs/book/advanced-guide/pipelines/containerization.md
  docs/book/legacy/developer-guide/advanced-usage/docker.md
  src/zenml/config/docker_settings.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: hacktoberfest-accepted

#1022 Update link checker configs for faster, more accurate checks
  .github/workflows/markdown-link-check.yml
  .github/workflows/markdown_check_config.json
Labels: enhancement, internal, hacktoberfest-accepted

#1027 Add `pip install zenml[server]` to relevant examples
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/custom_code_deployment/README.md
  examples/deepchecks_data_validation/README.md
  examples/evidently_drift_detection/README.md
  examples/facets_visualize_statistics/README.md
  examples/feast_feature_store/README.md
  examples/great_expectations_data_validation/README.md
  examples/huggingface/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/label_studio_annotation/README.md
  examples/lightgbm/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/neural_prophet/README.md
  examples/pytorch/README.md
  examples/scipy/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/README.md
  examples/xgboost/README.md
Labels: bug, internal

#994 Add Tolerations and NodeAffinity to Kubernetes executor
  .pyspelling-ignore-words
  CONTRIBUTING.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/flavors/__init__.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
Labels: hacktoberfest-accepted
