Repository zenml-io/zenml, pull requests merged in 2022-08, with the labels that each got.

#806 Support subscripted generic step output types
  .pyspelling-ignore-words
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  tests/unit/steps/test_base_step.py
Labels: bug, internal

#809 Allow empty kubeconfig when using local kubeflow orchestrator
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#815 fix the secret register command in kserve docs page
  docs/book/mlops-stacks/model-deployers/kserve.md
Labels: documentation, internal

#813 Annotation example (+ stack component update)
  .pyspelling-ignore-words
  docs/book/mlops-stacks/annotators/annotators.md
  docs/book/mlops-stacks/annotators/label-studio.md
  examples/label_studio_annotation/README.md
  examples/label_studio_annotation/__init__.py
  examples/label_studio_annotation/cloud_config/aws/cors.json
  examples/label_studio_annotation/data/batch_1/2dc5fe08-152d-47d0-bdd4-f70ddbfb6486.jpeg
  examples/label_studio_annotation/data/batch_1/7f5d8d61-c507-434f-9d4b-de28f93dad1e.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_95ffaa51-3894-4773-a8c6-a4e7d09de050.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0584.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0688.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0728.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_1481.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_1892.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_2262.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_2640.jpeg
  examples/label_studio_annotation/data/batch_2/11f096cb-4749-4a8b-ace0-f534bc7ed07d.jpeg
  examples/label_studio_annotation/data/batch_2/24cbc5d8-ca52-4974-841c-f91a2dfb46a7.jpeg
  examples/label_studio_annotation/data/batch_2/94f69181-2a52-43d3-9982-2cdbd018ff28.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_1507.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5514.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5515.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5530.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5587.jpeg
  examples/label_studio_annotation/data/batch_2/IMG_3154.jpeg
  examples/label_studio_annotation/data/batch_2/IMG_4813.jpeg
  examples/label_studio_annotation/materializers/__init__.py
  examples/label_studio_annotation/materializers/pillow_image_materializer.py
  examples/label_studio_annotation/pipelines/__init__.py
  examples/label_studio_annotation/pipelines/inference_pipeline.py
  examples/label_studio_annotation/pipelines/training_pipeline.py
  examples/label_studio_annotation/run.py
  examples/label_studio_annotation/steps/__init__.py
  examples/label_studio_annotation/steps/convert_annotations_step.py
  examples/label_studio_annotation/steps/deployment_triggers.py
  examples/label_studio_annotation/steps/get_labeled_data.py
  examples/label_studio_annotation/steps/get_or_create_dataset.py
  examples/label_studio_annotation/steps/load_image_data_step.py
  examples/label_studio_annotation/steps/model_deployers.py
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/label_studio_annotation/steps/pytorch_trainer.py
  examples/label_studio_annotation/steps/sync_new_data_to_label_studio.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py
  src/zenml/integrations/label_studio/label_studio_utils.py
  src/zenml/integrations/label_studio/steps/label_studio_standard_steps.py
  tests/unit/integrations/label_studio/__init__.py
  tests/unit/integrations/label_studio/label_config_generators/__init__.py
  tests/unit/integrations/label_studio/label_config_generators/test_label_config_generators.py
  tests/unit/integrations/label_studio/test_label_studio_utils.py
Labels: enhancement, internal, breaking-change

#794 Per-step resource configuration
  .pyspelling-ignore-words
  docs/book/developer-guide/advanced-usage/specify-step-resources.md
  docs/book/mlops-stacks/orchestrators/custom.md
  docs/book/mlops-stacks/orchestrators/orchestrators.md
  docs/book/mlops-stacks/step-operators/custom.md
  docs/book/mlops-stacks/step-operators/step-operators.md
  docs/book/toc.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  src/zenml/config/resource_configuration.py
  src/zenml/constants.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/step_operators/base_step_operator.py
  src/zenml/step_operators/step_executor_operator.py
  src/zenml/steps/__init__.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/unit/config/test_resource_configuration.py
  tests/unit/orchestrators/test_utils.py
Labels: enhancement, internal

#803 Scoped secrets
  .pyspelling-ignore-words
  docs/book/assets/secrets-manager/secret-scoping.png
  docs/book/mlops-stacks/data-validators/data-validators.md
  docs/book/mlops-stacks/secrets-managers/aws.md
  docs/book/mlops-stacks/secrets-managers/gcp.md
  docs/book/mlops-stacks/secrets-managers/hashicorp-vault.md
  docs/book/mlops-stacks/secrets-managers/secrets-managers.md
  src/zenml/cli/secret.py
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
  src/zenml/integrations/gcp/secrets_manager/gcp_secrets_manager.py
  src/zenml/integrations/vault/secrets_manager/vault_secrets_manager.py
  src/zenml/secrets_managers/base_secrets_manager.py
  src/zenml/secrets_managers/utils.py
  src/zenml/utils/string_utils.py
  tests/conftest.py
  tests/integration/secrets_manager/README.md
  tests/integration/secrets_manager/__init__.py
  tests/integration/secrets_manager/conftest.py
  tests/integration/secrets_manager/test_secrets_manager_scope.py
  tests/integration/secrets_manager/utils.py
  tests/unit/integrations/gcp/secrets_manager/test_gcp_secrets_manager.py
  tests/unit/integrations/vault/secrets_manager/__init__.py
  tests/unit/integrations/vault/secrets_manager/test_vault_secrets_manager.py
  tests/unit/utils/test_string_utils.py
Labels: enhancement, internal, breaking-change

#822 Backport/update readme
  README.md
  docs/book/assets/features.png
  docs/book/assets/meet_the_team.jpeg
  docs/book/assets/zenml_logo.png
Labels: backport

#823 update kserve installation to 0.9 on kserve deployment example
  examples/kserve_deployment/README.md
Labels: documentation, internal

#824 update kserve installation to 0.9 on kserve deployment example (#823)
  examples/kserve_deployment/README.md
Labels: internal, backport

#827 Allow setting caching via the `config.yaml`
  docs/book/developer-guide/steps-pipelines/caching.md
  examples/pytorch/config.yaml
  examples/pytorch/steps/trainers.py
  src/zenml/pipelines/base_pipeline.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#829 Fix the SQL zenstore to work with MySQL
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#832 Improve label studio error messages if secrets are missing or of wrong schema
  src/zenml/integrations/label_studio/steps/label_studio_standard_steps.py
Labels: bug, internal

#830 Azure secret scoping
  docs/book/mlops-stacks/secrets-managers/azure.md
  docs/book/mlops-stacks/secrets-managers/secrets-managers.md
  src/zenml/integrations/azure/secrets_managers/azure_secrets_manager.py
  src/zenml/integrations/gcp/secrets_manager/gcp_secrets_manager.py
  tests/integration/secrets_manager/README.md
  tests/integration/secrets_manager/conftest.py
  tests/integration/secrets_manager/test_secrets_manager_scope.py
  tests/integration/secrets_manager/utils.py
Labels: enhancement, internal

#833 Unify CLI concepts (removing `secret`, `feature` and `served-models`)
  docs/book/cloud-guide/aws/aws-guide.md
  docs/book/cloud-guide/azure/azure-guide.md
  docs/book/cloud-guide/execute-pipelines-in-cloud.md
  docs/book/cloud-guide/gcp/gcp-guide.md
  docs/book/mlops-stacks/annotators/label-studio.md
  docs/book/mlops-stacks/artifact-stores/amazon-s3.md
  docs/book/mlops-stacks/artifact-stores/azure-blob-storage.md
  docs/book/mlops-stacks/artifact-stores/gcloud-gcs.md
  docs/book/mlops-stacks/data-validators/whylogs.md
  docs/book/mlops-stacks/metadata-stores/mysql.md
  docs/book/mlops-stacks/model-deployers/kserve.md
  docs/book/mlops-stacks/model-deployers/model-deployers.md
  docs/book/mlops-stacks/model-deployers/seldon.md
  docs/book/mlops-stacks/secrets-managers/secrets-managers.md
  examples/cloud_secrets_manager/README.md
  examples/github_actions_orchestration/README.md
  examples/kserve_deployment/README.md
  examples/kserve_deployment/run_pytorch.py
  examples/kserve_deployment/run_tensorflow.py
  examples/label_studio_annotation/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_deployment/run.py
  examples/quickstart/notebooks/quickstart.ipynb
  examples/seldon_deployment/README.md
  examples/seldon_deployment/run.py
  examples/vertex_ai_orchestration/README.md
  examples/whylogs_data_profiling/README.md
  src/zenml/cli/__init__.py
  src/zenml/cli/annotator.py
  src/zenml/cli/feature.py
  src/zenml/cli/model.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/stack_components.py
  src/zenml/integrations/github/secrets_managers/github_secrets_manager.py
  src/zenml/stack/authentication_mixin.py
  tests/unit/cli/test_feature.py
Labels: enhancement, internal, breaking-change

#838 Put link checker as part of CI
  .github/workflows/ci.yml
  .github/workflows/markdown-link-check.yml
Labels: enhancement, internal

#834 Add missing requirement for step operators
  docs/book/mlops-stacks/step-operators/amazon-sagemaker.md
  docs/book/mlops-stacks/step-operators/azureml.md
  docs/book/mlops-stacks/step-operators/gcloud-vertexai.md
Labels: bug, internal

#836 Fix served models logs formatting error
  src/zenml/cli/model.py
Labels: bug, internal

#811 New Docker build configuration
  .pyspelling-ignore-words
  docs/book/developer-guide/advanced-usage/docker.md
  docs/book/mlops-stacks/orchestrators/gcloud-vertexai.md
  docs/book/mlops-stacks/orchestrators/github-actions.md
  docs/book/mlops-stacks/orchestrators/kubeflow.md
  docs/book/mlops-stacks/orchestrators/kubernetes.md
  docs/book/mlops-stacks/step-operators/amazon-sagemaker.md
  docs/book/mlops-stacks/step-operators/azureml.md
  docs/book/mlops-stacks/step-operators/gcloud-vertexai.md
  src/zenml/config/__init__.py
  src/zenml/config/docker_configuration.py
  src/zenml/constants.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/__init__.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/step_operators/base_step_operator.py
  src/zenml/step_operators/step_executor_operator.py
  src/zenml/steps/step_environment.py
  src/zenml/steps/utils.py
  src/zenml/utils/deprecation_utils.py
  src/zenml/utils/docker_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/unit/cli/test_stack.py
  tests/unit/container_registries/test_base_container_registry.py
  tests/unit/orchestrators/test_utils.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/test_environment.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#817 Secrets references on stack component attributes
  .pyspelling-ignore-words
  docs/book/developer-guide/advanced-usage/advanced-usage.md
  docs/book/developer-guide/advanced-usage/secret-references.md
  docs/book/mlops-stacks/secrets-managers/secrets-managers.md
  src/zenml/cli/__init__.py
  src/zenml/cli/secret.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/secrets_managers/base_secrets_manager.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/secret_utils.py
  tests/unit/secrets_manager/test_base_secrets_manager.py
  tests/unit/stack/conftest.py
  tests/unit/stack/test_stack_component.py
  tests/unit/utils/test_secret_utils.py
Labels: enhancement, internal

#842 Misc bugfixes
  src/zenml/config/resource_configuration.py
  src/zenml/constants.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/post_execution/step.py
  src/zenml/step_operators/entrypoint.py
  src/zenml/utils/source_utils.py
  tests/unit/config/test_resource_configuration.py
  tests/unit/orchestrators/test_utils.py
Labels: bug, internal

#820 Pillow Image materializer
  .github/workflows/unit-test.yml
  .pyspelling-ignore-words
  pyproject.toml
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/pillow/__init__.py
  src/zenml/integrations/pillow/materializers/__init__.py
  src/zenml/integrations/pillow/materializers/pillow_image_materializer.py
  src/zenml/materializers/__init__.py
  tests/unit/integrations/pillow/__init__.py
  tests/unit/integrations/pillow/test_pillow_image_materializer.py
Labels: enhancement, internal

#844 Add Tekton orchestrator
  .github/workflows/lint.yml
  .pyspelling-ignore-words
  docs/book/mlops-stacks/orchestrators/tekton.md
  docs/book/toc.md
  examples/tekton_pipeline_orchestration/README.md
  examples/tekton_pipeline_orchestration/__init__.py
  examples/tekton_pipeline_orchestration/assets/tekton_ui.png
  examples/tekton_pipeline_orchestration/assets/tekton_ui_2.png
  examples/tekton_pipeline_orchestration/assets/tekton_ui_3.png
  examples/tekton_pipeline_orchestration/assets/zenml.svg
  examples/tekton_pipeline_orchestration/config.yaml
  examples/tekton_pipeline_orchestration/pipelines/__init__.py
  examples/tekton_pipeline_orchestration/pipelines/mnist_pipeline.py
  examples/tekton_pipeline_orchestration/run.py
  examples/tekton_pipeline_orchestration/steps/__init__.py
  examples/tekton_pipeline_orchestration/steps/evaluators.py
  examples/tekton_pipeline_orchestration/steps/importers.py
  examples/tekton_pipeline_orchestration/steps/normalizers.py
  examples/tekton_pipeline_orchestration/steps/trainers.py
  pyproject.toml
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/tekton/__init__.py
  src/zenml/integrations/tekton/orchestrators/__init__.py
  src/zenml/integrations/tekton/orchestrators/tekton_entrypoint_configuration.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
Labels: enhancement, internal

#849 Add sleep before docker builds in release GH action
  .github/workflows/release.yml
Labels: enhancement, internal

#812 Implement Recursive Built-In Container Materializer
  .pyspelling-ignore-words
  src/zenml/materializers/__init__.py
  src/zenml/materializers/beam_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  tests/unit/materializers/test_built_in_materializer.py
Labels: enhancement, internal

#826 Decouple metadata store from stack
  .pyspelling-ignore-words
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/label_studio_annotation/steps/pytorch_trainer.py
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/config/profile_config.py
  src/zenml/enums.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/github/secrets_managers/github_secrets_manager.py
  src/zenml/integrations/kubeflow/__init__.py
  src/zenml/integrations/kubeflow/metadata_stores/__init__.py
  src/zenml/integrations/kubeflow/metadata_stores/kubeflow_metadata_store.py
  src/zenml/integrations/kubernetes/__init__.py
  src/zenml/integrations/kubernetes/metadata_stores/__init__.py
  src/zenml/integrations/kubernetes/metadata_stores/kubernetes_metadata_store.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/__init__.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/repository.py
  src/zenml/services/utils.py
  src/zenml/stack/__init__.py
  src/zenml/stack/flavor_registry.py
  src/zenml/stack/stack.py
  src/zenml/steps/step_context.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/unit/cli/test_stack.py
  tests/unit/integrations/gcp/orchestrators/test_vertex_orchestrator.py
  tests/unit/integrations/github/orchestrators/test_github_actions_orchestrator.py
  tests/unit/integrations/kubeflow/metadata_stores/__init__.py
  tests/unit/integrations/kubeflow/metadata_stores/test_kubeflow_metadata_store.py
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
  tests/unit/metadata_stores/test_mysql_metadata_store.py
  tests/unit/metadata_stores/test_sqlite_metadata_store.py
  tests/unit/orchestrators/test_utils.py
  tests/unit/post_execution/test_artifact.py
  tests/unit/post_execution/test_pipeline_run.py
  tests/unit/stack/conftest.py
  tests/unit/stack/test_stack.py
  tests/unit/stack/test_stack_validator.py
  tests/unit/steps/test_step_context.py
  tests/unit/test_repository.py
  tests/unit/zen_server/test_zen_server.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#837 Spark Integration
  .pyspelling-ignore-words
  docs/book/mlops-stacks/step-operators/spark.md
  docs/book/mlops-stacks/step-operators/step-operators.md
  docs/book/toc.md
  examples/spark_distributed_programming/README.md
  examples/spark_distributed_programming/__init__.py
  examples/spark_distributed_programming/pipelines/__init__.py
  examples/spark_distributed_programming/pipelines/spark_pipeline/__init__.py
  examples/spark_distributed_programming/pipelines/spark_pipeline/spark_pipeline.py
  examples/spark_distributed_programming/run.py
  examples/spark_distributed_programming/steps/__init__.py
  examples/spark_distributed_programming/steps/importer_step/__init__.py
  examples/spark_distributed_programming/steps/importer_step/importer_step.py
  examples/spark_distributed_programming/steps/split_step/__init__.py
  examples/spark_distributed_programming/steps/split_step/split_step.py
  examples/spark_distributed_programming/steps/statistics_step/__init__.py
  examples/spark_distributed_programming/steps/statistics_step/statistics_step.py
  examples/spark_distributed_programming/steps/trainer_step/__init__.py
  examples/spark_distributed_programming/steps/trainer_step/trainer_step.py
  examples/spark_distributed_programming/steps/transformer_step/__init__.py
  examples/spark_distributed_programming/steps/transformer_step/transformer_step.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/spark/__init__.py
  src/zenml/integrations/spark/materializers/__init__.py
  src/zenml/integrations/spark/materializers/spark_dataframe_materializer.py
  src/zenml/integrations/spark/materializers/spark_model_materializer.py
  src/zenml/integrations/spark/step_operators/__init__.py
  src/zenml/integrations/spark/step_operators/kubernetes_step_operator.py
  src/zenml/integrations/spark/step_operators/spark_entrypoint.py
  src/zenml/integrations/spark/step_operators/spark_step_operator.py
  src/zenml/step_operators/step_executor_operator.py
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal

#807 Add zenml stack recipe CLI commands
  .pyspelling-ignore-words
  README.md
  docs/book/cloud-guide/stack-recipes.md
  docs/book/toc.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/quickstart/README.md
  examples/seldon_deployment/README.md
  examples/vertex_ai_orchestration/README.md
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_recipes.py
  src/zenml/utils/analytics_utils.py
Labels: internal

#854 [BACKPORT] fix flag info on recipes in docs
  docs/book/cloud-guide/stack-recipes.md
  src/zenml/cli/stack_recipes.py
Labels: documentation, internal

#855 [BACKPORT] fix flag info on recipes in docs (#854)
  docs/book/cloud-guide/stack-recipes.md
  src/zenml/cli/stack_recipes.py
Labels: internal, backport

#852 Fix some materializer issues
  src/zenml/integrations/azure/artifact_stores/azure_artifact_store.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
  src/zenml/materializers/built_in_materializer.py
Labels: bug, internal

#851 Add ignore columns for evidently drift detection
  .github/workflows/unit-test.yml
  src/zenml/integrations/evidently/steps/evidently_profile.py
  tests/unit/integrations/evidently/__init__.py
  tests/unit/integrations/evidently/steps/__init__.py
  tests/unit/integrations/evidently/steps/test_ignore_columns.py
Labels: enhancement, good-second-issue

#857 Remove failing tests (from external PR)
  .github/workflows/unit-test.yml
  tests/unit/integrations/evidently/steps/test_ignore_columns.py
Labels: bug, internal

#856 Update ZenStore SQL Models
  src/zenml/zen_stores/schemas/schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#858 Add option to specify task dependencies
  docs/book/developer-guide/advanced-usage/advanced-usage.md
  docs/book/developer-guide/advanced-usage/step-execution-order.md
  docs/book/toc.md
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#853 Custom code readme and docs
  .pyspelling-ignore-words
  docs/book/mlops-stacks/model-deployers/kserve.md
  docs/book/mlops-stacks/model-deployers/model-deployers.md
  docs/book/mlops-stacks/model-deployers/seldon.md
  examples/custom_code_deployment/README.md
  examples/custom_code_deployment/requirements.txt
Labels: documentation, internal

#866 Raise zenml exception when cyclic graph is detected
  src/zenml/orchestrators/utils.py
Labels: enhancement, internal

#868 Add source to segment identify call
  src/zenml/cli/base.py
  src/zenml/enums.py
Labels: internal
