Repository zenml-io/zenml, pull requests merged in 2022-01, with the labels that each got.

#287 Hamza/eng 127 test scenarios
  src/zenml/config/global_config.py
  src/zenml/core/local_service.py
  tests/conftest.py
  tests/integration/test_examples.py
  tests/unit/cli/test_config.py
  tests/unit/config/test_global_config.py
Labels: internal

#288 Updated pull_request.yaml
  .github/workflows/pull_request.yml
Labels: internal

#289 Changing workdir before removing tmp_dir
  tests/conftest.py
Labels: bug, internal

#291 Don't raise an exception during integration installation check
  src/zenml/integrations/integration.py
Labels: internal

#294 update starting page for the API docs
  docs/book/toc.md
Labels: documentation, internal

#290 Add `stack up` failure prompts
  src/zenml/cli/stack.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: internal

#295 Spelling fixes
  RELEASE_NOTES.md
  docs/book/guides/class-based-api/split-and-preprocess.md
  docs/book/guides/class-based-api/train-and-evaluate.md
  examples/class_based_api/chapter_2.py
  examples/class_based_api/chapter_3.py
  examples/standard_interfaces/README.md
  examples/standard_interfaces/run.py
  src/zenml/artifacts/type_registry.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/sklearn/steps/sklearn_standard_scaler.py
  src/zenml/materializers/base_materializer.py
  src/zenml/pipelines/builtin_pipelines/training_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_interfaces/__init__.py
  src/zenml/steps/step_interfaces/base_preprocessor_step.py
Labels: internal

#297 Fix the `stack up` and `orchestrator up` failure prompts
  src/zenml/cli/orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: internal

#299 Prevent KFP install timeouts during `stack up`
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
Labels: internal

#303 Add stefannica to list of internal github users
  .github/teams.yml
Labels: internal

#292 Improve KFP UI daemon error messages
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/utils/networking_utils.py
Labels: internal

#306 Replaced old diagrams with new ones
  docs/book/assets/localstack-with-kubeflow-orchestrator.png
  docs/book/assets/localstack.png
  docs/book/assets/quickstart-diagram.png
Labels: internal

#304 Run KFP container as local user/group if local
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
Labels: internal

#308 Add james to github team
  .github/teams.yml
Labels: internal

#296 Alexej/eng 300 bugfix windows integration tests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  examples/run_example.sh
  src/zenml/cli/example.py
  src/zenml/integrations/mlflow/mlflow_utils.py
  tests/integration/test_examples.py
Labels: internal

#309 Add 'super quickstart' instructions for all examples
  examples/airflow_local/README.md
  examples/caching/README.md
  examples/class_based_api/README.md
  examples/dag_visualizer/README.md
  examples/functional_api/README.md
  examples/kubeflow/README.md
  examples/lineage/README.md
  examples/mlflow/README.md
  examples/not_so_quickstart/README.md
  examples/quickstart/README.md
  examples/standard_interfaces/README.md
  examples/statistics/README.md
  src/zenml/cli/example.py
Labels: documentation, internal

#300 Baris/eng 303 artifact param naming bug
  src/zenml/steps/base_step.py
Labels: internal

#298 Add tests for `fileio`
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/io/fileio.py
  tests/unit/cli/test_integration.py
  tests/unit/io/test_fileio.py
Labels: internal

#310 Stefan/eng 264 evidently integration
  examples/drift_detection/evidently.ipynb
  examples/drift_detection/run.py
  scripts/test-coverage-xml.sh
  src/zenml/artifacts/__init__.py
  src/zenml/artifacts/data_analysis_artifact.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  src/zenml/integrations/evidently/visualizers/__init__.py
  src/zenml/integrations/evidently/visualizers/evidently_visualizer.py
  src/zenml/integrations/facets/visualizers/facet_statistics_visualizer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/steps/step_interfaces/base_drift_detection_step.py
  src/zenml/visualizers/base_step_visualizer.py
  tests/integration/test_examples.py
  tests/unit/cli/test_integration.py
Labels: internal

#312 Bugfix/make mlflow example faster
  examples/mlflow/run.py
Labels: internal

#314 Add Docker Image Note on README
  README.md
Labels: internal

#315 Add markdown parser for `zenml example info` CLI command
  src/zenml/cli/example.py
Labels: internal

#313 Fix `drift_detection` and `mlflow` examples
  examples/drift_detection/README.md
  examples/drift_detection/drift_visualization.png
  examples/mlflow/README.md
Labels: documentation, internal

#320 Update integrations list
  docs/book/features/integrations.md
Labels: documentation, internal

#319 Amend `mlflow` example name
  examples/README.md
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/__init__.py
  examples/mlflow_tracking/run.py
  examples/mlflow_tracking/setup.sh
  tests/integration/test_examples.py
Labels: internal

#324 add jayesh to team
  .github/teams.yml
Labels: internal

#326 Update cloudbuild config to tag and push 'latest' images
  README.md
  cloudbuild.yaml
  docs/book/introduction/installation.md
  src/zenml/integrations/evidently/__init__.py
Labels: internal

#322 Add error message if the return type of a step function doesn't match the expected type
  src/zenml/steps/utils.py
  tests/conftest.py
  tests/unit/steps/test_base_step.py
Labels: internal

#321 Replaced the name with the pipeline_step_name within the repr of a St…
  docs/book/guides/functional-api/caching.md
  docs/book/guides/post-execution-workflow/post-execution-workflow.md
  examples/functional_api/chapter_4.py
  examples/not_so_quickstart/run.py
  examples/quickstart/quickstart.py
  src/zenml/integrations/dash/visualizers/pipeline_run_lineage_visualizer.py
  src/zenml/integrations/graphviz/visualizers/pipeline_run_dag_visualizer.py
  src/zenml/integrations/plotly/visualizers/pipeline_lineage_visualizer.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/post_execution/step.py
Labels: bug, internal

#325 [Bugfix] Make TODO parser run on develop branch and test source
  .github/workflows/update_todos.yml
  scripts/update_todos.py
  tests/integration/test_examples.py
  tests/unit/cli/test_artifact.py
  tests/unit/cli/test_config.py
  tests/unit/cli/test_container_registry.py
  tests/unit/cli/test_metadata.py
  tests/unit/cli/test_orchestrator.py
  tests/unit/cli/test_stack.py
  tests/unit/core/test_local_service.py
  tests/unit/core/test_repo.py
  tests/unit/scripts/test_update_todos.py
Labels: internal

#327 Fix broken links in quickstart and core concepts
  docs/book/introduction/core-concepts.md
  docs/book/introduction/quickstart-guide.md
Labels: documentation, internal

#330 Fix bug with running unpulled examples
  src/zenml/cli/example.py
Labels: internal

#332 Fixed evidently to <=0.1.40.dev0
  examples/drift_detection/README.md
  examples/drift_detection/setup.sh
Labels: internal

#334 [BACKPORT] Fixed evidently to <=0.1.40.dev0 (#332)
  examples/drift_detection/README.md
  examples/drift_detection/setup.sh
Labels: internal

#335 Fix typo in pipeline configuration page
  docs/book/features/pipeline-configuration.md
Labels: internal

#337 Add imports for visualizer `drift_detection` example
  examples/drift_detection/README.md
Labels: documentation, internal

#339 Disable telemetry for Evidently
  scripts/test-coverage-xml.sh
Labels: internal

#340 Fixed/changed links regarding api and cli docs
  docs/book/reference/cli-command-reference.md
  docs/book/toc.md
Labels: internal

#341 Fixed/changed links regarding api and cli docs (#340)
  docs/book/reference/cli-command-reference.md
  docs/book/toc.md
Labels: internal

#342 Backport/adjusted api doc links 0.5.7
  docs/book/reference/cli-command-reference.md
  docs/book/toc.md
Labels: internal

#343 Hotfix/fix api and cli links in docs
  docs/book/reference/cli-command-reference.md
  docs/book/toc.md
Labels: internal

#331 Additional telemetry tracking
  docs/book/support/usage-analytics.md
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/integration.py
  src/zenml/integrations/registry.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/repository.py
  src/zenml/utils/analytics_utils.py
  tests/unit/cli/test_integration.py
  tests/unit/utils/test_analytics_utils.py
Labels: internal

#348 Fixed formatting errors in docstrings
  src/zenml/artifacts/__init__.py
  src/zenml/cli/__init__.py
  src/zenml/cli/cli.py
  src/zenml/cli/utils.py
  src/zenml/integrations/airflow/orchestrators/__init__.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/evidently/visualizers/evidently_visualizer.py
  src/zenml/io/fileio.py
  src/zenml/materializers/base_materializer.py
  src/zenml/steps/step_context.py
  src/zenml/utils/yaml_utils.py
Labels: internal

#349 Update ZenML to use Evidently v0.1.41.dev0
  examples/drift_detection/README.md
  examples/drift_detection/setup.sh
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
Labels: bug, internal

#345 Fix some docs
  docs/book/guides/functional-api/train-and-evaluate.md
  docs/book/guides/post-execution-workflow/post-execution-workflow.md
Labels: internal

#350 Doc/add type flag to container registry documentation
  docs/book/guides/functional-api/deploy-to-production.md
  examples/kubeflow/README.md
  examples/kubeflow/setup.sh
Labels: internal

#351 Add cloudbuild configuration for building development images
  .gitignore
  cloudbuild-develop.yaml
Labels: internal

#336 Transition to Mkdocs for versioned api-docs
  .github/workflows/publish_api_docs.yml
  .gitignore
  docs/mkdocs.yml
  docs/mkdocs/.pages
  docs/mkdocs/_assets/favicon.png
  docs/mkdocs/cli.md
  docs/mkdocstrings_helper.py
  pyproject.toml
  scripts/deploy-docs.sh
  scripts/generate-docs.sh
Labels: internal

#347 Improvements for the local kubeflow orchestrator deployment
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
Labels: internal

#353 Add error message if step is called twice
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  tests/conftest.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/steps/test_base_step.py
Labels: internal

#357 Update integrations list
  docs/book/features/integrations.md
Labels: documentation, internal

#358 Fix typos in `whylogs` example README
  examples/whylogs/README.md
Labels: documentation, internal

#356 Remove legacy folder
  examples/legacy/backends/graphics/architecture.png
Labels: documentation, internal

#362 Update 0.6.0 release notes
  RELEASE_NOTES.md
Labels: documentation, internal

#364 Update 0.6.0 release notes (#362)
  RELEASE_NOTES.md
Labels: documentation, internal

#361 Fix cuda-dev base container image
  docker/cuda-dev.Dockerfile
Labels: internal

#367 [0.6.0] Fix cuda-dev base container image
  docker/cuda-dev.Dockerfile
Labels: internal, backport

#360 Mark ZenML as typed package
  pyproject.toml
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/py.typed
  src/zenml/steps/utils.py
  src/zenml/utils/source_utils.py
Labels: internal

#363 Improve error message if ZenML repo is missing inside kubeflow container entrypoint
  src/zenml/integrations/kubeflow/container_entrypoint.py
Labels: internal

#369 Spell whylogs and WhyLabs correctly in our docs
  docs/book/features/integrations.md
  docs/book/guides/common-usecases/visualizers.md
  examples/whylogs/README.md
Labels: documentation, internal

#372 Feature/add readme for mkdocs
  .gitignore
  docs/README.md
  docs/mkdocstrings_helper.py
  scripts/generate-docs.sh
  scripts/serve_api_docs.sh
  src/zenml/exceptions.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  src/zenml/integrations/facets/visualizers/facet_statistics_visualizer.py
  src/zenml/integrations/whylogs/whylogs_context.py
Labels: documentation, internal

#371 Cleaning up the assets pushed by gitbook automatically
  docs/book/.gitbook/assets/architecture.png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (1).png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (2) (3) (1).png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (2) (3) (2).png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (2) (3) (3).png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (2) (3) (4).png
  docs/book/.gitbook/assets/architecture_diagram (1) (2) (2) (3).png
  docs/book/.gitbook/assets/compare.png
  docs/book/.gitbook/assets/core_concepts_zenml.png
  docs/book/.gitbook/assets/cover_image.png
  docs/book/.gitbook/assets/localstack (1).png
  docs/book/.gitbook/assets/localstack-with-airflow-orchestrator.png
  docs/book/.gitbook/assets/localstack-with-kubeflow-orchestrator.png
  docs/book/.gitbook/assets/localstack.png
  docs/book/.gitbook/assets/monet.png
  docs/book/.gitbook/assets/sam_frustrated.jpg
  docs/book/.gitbook/assets/sam_zen_mode (1).jpg
  docs/book/.gitbook/assets/sam_zen_mode (2).jpg
  docs/book/.gitbook/assets/sam_zen_mode (3).jpg
  docs/book/.gitbook/assets/sam_zen_mode.jpg
  docs/book/.gitbook/assets/statistics_boston_housing.png
  docs/book/.gitbook/assets/tensorboard_inline.png
  docs/book/.gitbook/assets/zenml-deck-q2-21-3-.png
  docs/book/guides/common-usecases/post-execution-workflow.md
Labels: internal

#376 Turn codecov off for patch updates
  .github/codecov.yml
Labels: internal

#365 Minor changes and fixes
  docs/book/features/integrations.md
  docs/sphinx_docs/Makefile
  docs/sphinx_docs/_static/logo.png
  docs/sphinx_docs/_templates/module.rst_t
  docs/sphinx_docs/_templates/package.rst_t
  docs/sphinx_docs/conf.py
  docs/sphinx_docs/index.rst
  docs/sphinx_docs/make.bat
  src/zenml/cli/stack_components.py
  src/zenml/integrations/mlflow/mlflow_utils.py
  src/zenml/integrations/whylogs/whylogs_step_decorator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_interfaces/base_analyzer_step.py
  src/zenml/steps/step_interfaces/base_datasource_step.py
  src/zenml/steps/step_interfaces/base_drift_detection_step.py
  src/zenml/steps/step_interfaces/base_evaluator_step.py
  src/zenml/steps/step_interfaces/base_preprocessor_step.py
  src/zenml/steps/step_interfaces/base_split_step.py
  src/zenml/steps/step_interfaces/base_trainer_step.py
Labels: internal

#377 Only include python files when building local docs
  docs/mkdocstrings_helper.py
Labels: internal

#370 Prevent access to repo during step execution
  src/zenml/environment.py
  src/zenml/exceptions.py
  src/zenml/integrations/evidently/visualizers/evidently_visualizer.py
  src/zenml/integrations/facets/visualizers/facet_statistics_visualizer.py
  src/zenml/integrations/whylogs/visualizers/whylogs_visualizer.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/repository.py
  src/zenml/steps/utils.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/singleton.py
  src/zenml/utils/source_utils.py
  src/zenml/visualizers/base_step_visualizer.py
  tests/unit/steps/test_base_step.py
  tests/unit/test_environment.py
  tests/unit/test_repository.py
  tests/unit/utils/test_analytics_utils.py
  tests/unit/utils/test_singleton.py
Labels: internal

#379 Removed duplicated Section within docs
  docs/book/features/step-fixtures.md
Labels: bug, documentation, internal

#368 Fixing the materializer registry to spot sub-classes of defined types
  docs/book/guides/common-usecases/custom-materializer.md
  docs/book/guides/functional-api/materialize-artifacts.md
  examples/custom_materializer/run.py
  examples/functional_api/chapter_5.py
  src/zenml/artifacts/type_registry.py
  src/zenml/integrations/pytorch/materializers/pytorch_materializer.py
  src/zenml/integrations/pytorch_lightning/materializers/pytorch_lightning_materializer.py
  src/zenml/integrations/sklearn/materializers/sklearn_materializer.py
  src/zenml/integrations/tensorflow/materializers/keras_materializer.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/beam_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/materializers/pandas_materializer.py
  tests/unit/materializers/test_base_materializer.py
  tests/unit/materializers/test_default_materializer_registry.py
  tests/unit/steps/test_base_step.py
Labels: internal

#375 Computing hash of step and materializer works in notebooks
  src/zenml/steps/base_step.py
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_source_utils.py
Labels: internal
