Repository zenml-io/zenml, pull requests merged in 2022-05, with the labels that each got.

#552 Improve missing brackets error message
  src/zenml/pipelines/base_pipeline.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#546 Beautify CLI by grouping commands list into tags
  pyproject.toml
  src/zenml/cli/cli.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/feature.py
  src/zenml/cli/formatter.py
  src/zenml/cli/integration.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/service.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/enums.py
  tests/unit/cli/test_cli.py
  tests/unit/cli/test_formatter.py
Labels: internal

#557 Stream model deployer logs through CLI
  pyproject.toml
  src/zenml/cli/served_models.py
  src/zenml/integrations/seldon/seldon_client.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/model_deployers/base_model_deployer.py
  src/zenml/services/local/local_service.py
  src/zenml/services/service.py
Labels: enhancement, internal

#561 Fix various usability bugs
  pyproject.toml
  src/zenml/cli/config.py
  src/zenml/cli/service.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/console.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/logger.py
  src/zenml/services/local/local_service.py
  src/zenml/services/service.py
  src/zenml/utils/daemon.py
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
Labels: bug, internal

#564 Adjusted handling of duplicated configuration
  src/zenml/exceptions.py
  src/zenml/pipelines/base_pipeline.py
Labels: bug, internal

#560 Add `zenml stack export` and `zenml stack import` commands
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  tests/unit/cli/test_stack.py
Labels: enhancement, internal

#562 Only build non-dev docker images on release
  cloudbuild.yaml
Labels: bug, internal

#551 Add container registry types
  docs/book/advanced_guide/guide-aws-gcp-azure.md
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/container_registries/__init__.py
  src/zenml/container_registries/azure_container_registry.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/container_registries/dockerhub_container_registry.py
  src/zenml/container_registries/gcp_container_registry.py
  src/zenml/container_registries/github_container_registry.py
  src/zenml/container_registries/gitlab_container_registry.py
  src/zenml/enums.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/container_registries/__init__.py
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/sagemaker/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/vertex/step_operators/vertex_step_operator.py
  src/zenml/repository.py
  src/zenml/stack/flavor_registry.py
  src/zenml/stack/stack_component.py
Labels: enhancement, internal

#559 Add PyTorch example
  docs/book/advanced_guide/integrations.md
  examples/pytorch/README.md
  examples/pytorch/__init__.py
  examples/pytorch/requirements.txt
  examples/pytorch/run.py
  examples/pytorch/setup.sh
  pyproject.toml
  src/zenml/integrations/pytorch/materializers/__init__.py
  src/zenml/integrations/pytorch/materializers/pytorch_dataloader_materializer.py
  src/zenml/integrations/pytorch/materializers/pytorch_module_materializer.py
  tests/integration/test_examples.py
Labels: enhancement, internal

#566 Replace `-f` and `--force` with `-y` and `--yes`
  .github/workflows/kubeflow.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/unit-test.yml
  docs/README.md
  docs/book/advanced_guide/run_on_kubeflow.md
  docs/book/introduction/quickstart-guide.md
  examples/add_your_own/template_setup.sh
  examples/airflow_orchestration/README.md
  examples/airflow_orchestration/setup.sh
  examples/evidently_drift_detection/evidently.ipynb
  examples/evidently_drift_detection/setup.sh
  examples/facets_visualize_statistics/setup.sh
  examples/huggingface/README.md
  examples/huggingface/setup.sh
  examples/kubeflow_pipelines_orchestration/setup.sh
  examples/lightgbm/README.md
  examples/lightgbm/setup.sh
  examples/mlflow_deployment/setup.sh
  examples/mlflow_tracking/setup.sh
  examples/neural_prophet/README.md
  examples/neural_prophet/setup.sh
  examples/quickstart/setup.sh
  examples/run_example.sh
  examples/scipy/setup.sh
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/setup.sh
  examples/xgboost/README.md
  examples/xgboost/setup.sh
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/example.py
  src/zenml/cli/integration.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/service.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  tests/integration/example_validations.py
  tests/unit/cli/test_integration.py
Labels: enhancement, internal

#568 Fix airflow orchestrator
  src/zenml/integrations/airflow/orchestrators/airflow_component.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
Labels: bug, internal

#540 Add hidden `zenml clean` command for use in development / debugging
  src/zenml/cli/base.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/constants.py
  tests/unit/cli/test_base.py
Labels: enhancement, internal

#570 Suppress info log messages for integrations
  src/zenml/logger.py
Labels: enhancement, internal

#571 Make it easier to submit issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general.yml
  src/zenml/environment.py
  src/zenml/integrations/registry.py
  src/zenml/utils/analytics_utils.py
Labels: internal

#576 Consolidate landing page with what is zenml
  docs/book/index.md
  docs/book/toc.md
Labels: internal

#572 Removed tf reference in sklearn step
  src/zenml/integrations/sklearn/steps/sklearn_evaluator.py
Labels: bug, internal

#569 Fix Keras materializer to work with remote artifact stores
  src/zenml/integrations/lightgbm/materializers/lightgbm_booster_materializer.py
  src/zenml/integrations/tensorflow/materializers/keras_materializer.py
  src/zenml/integrations/xgboost/materializers/xgboost_booster_materializer.py
  src/zenml/integrations/xgboost/materializers/xgboost_dmatrix_materializer.py
Labels: bug, internal

#578 Optional log suppression with environment variable
  docs/book/reference/system-env.md
  src/zenml/constants.py
  src/zenml/logger.py
Labels: enhancement, internal

#545 Extend `zenml pipeline run` to allow multifile code
  .github/workflows/unit-test.yml
Labels: enhancement, internal

#567 CLI speed improvement
  src/zenml/cli/base.py
  src/zenml/cli/feature.py
  src/zenml/cli/integration.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/service.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/io/fileio.py
  src/zenml/repository.py
  src/zenml/utils/source_utils.py
  src/zenml/zen_stores/models/flavor_wrapper.py
  tests/unit/zen_service/test_zen_service.py
Labels: enhancement, internal

#579 Document global configuration and repository
  docs/book/developer-guide/repo-and-config.md
Labels: documentation, internal

#584 Improve error message for missing return type annotations of `@step` functions
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  tests/conftest.py
  tests/unit/orchestrators/test_utils.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#577 Ensure `rich` CLI displays full text and wraps table text
  src/zenml/cli/utils.py
Labels: enhancement, internal

#588 Sync the repository and local store with the disk configuration files and other fixes
  scripts/test-coverage-xml.sh
  src/zenml/cli/stack.py
  src/zenml/integrations/azureml/step_operators/azureml_step_operator.py
  src/zenml/repository.py
  src/zenml/services/local/local_daemon_entrypoint.py
  src/zenml/utils/filesync_model.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/models/zen_store_model.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#580 New MySQL metadata stores
  docs/book/advanced_guide/secrets.md
  examples/seldon_deployment/README.md
  src/zenml/cli/__init__.py
  src/zenml/cli/secret.py
  src/zenml/cli/stack.py
  src/zenml/cli/utils.py
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/metadata_stores/mysql_secret_schema.py
  src/zenml/secret/base_secret.py
  src/zenml/secret/secret_schema_class_registry.py
Labels: internal

#582 Updated Release Workflow
  .github/workflows/publish.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/release.yml
  scripts/publish.sh
Labels: enhancement, internal

#591 Fix GH action cache
  .github/actions/setup_environment/action.yml
Labels: bug, internal

#585 Change zen service to zen server
  src/zenml/__init__.py
  src/zenml/cli/__init__.py
  src/zenml/cli/config.py
  src/zenml/cli/server.py
  src/zenml/constants.py
  src/zenml/services/local/local_daemon_entrypoint.py
  src/zenml/zen_server/__init__.py
  src/zenml/zen_server/zen_server.py
  src/zenml/zen_server/zen_server_api.py
  tests/unit/zen_server/__init__.py
  tests/unit/zen_server/test_zen_server.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#592 Fix evidently visualizer on Colab
  src/zenml/environment.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/evidently/visualizers/evidently_visualizer.py
Labels: bug, internal

#596 Fix CLI formatting issues
  src/zenml/cli/utils.py
Labels: bug, internal

#594 Small CLI fixes regarding stack components
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/cli/example.py
  src/zenml/cli/stack_components.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/stack/stack_component.py
Labels: bug, internal

#597 ZenML Collaboration docs
  docs/book/advanced-guide/advanced-zenml/README.md
  docs/book/advanced-guide/cloud/README.md
  docs/book/advanced-guide/integrations/README.md
  docs/book/advanced-guide/integrations/visualize-your-data.md
  docs/book/collaborate/collaborate.md
  docs/book/collaborate/profiles.md
  docs/book/collaborate/stack-export.md
  docs/book/collaborate/zenml-server.md
  docs/book/developer-guide/getting-started/README.md
  docs/book/developer-guide/profiles.md
  docs/book/developer-guide/repo-and-config.md
  docs/book/developer-guide/stacks.md
  docs/book/stack-components/feature-store.md
  docs/book/toc.md
Labels: documentation, internal

#598 S3 Compatible Artifact Store and materializers file handling
  src/zenml/materializers/pandas_materializer.py
Labels: bug, internal

#603 Added success message
  src/zenml/cli/stack_components.py
Labels: enhancement, internal

#609 Fixed gitbook commit and replace underscore with - for future robustn…
  docs/book/advanced-guide/advanced-zenml/skip-materialization.md
  docs/book/advanced-guide/advanced-zenml/zenml-example-cli.md
  docs/book/advanced-guide/cloud/continuous-training-and-deployment.md
  docs/book/advanced-guide/cloud/guide-aws-gcp-azure.md
  docs/book/advanced-guide/cloud/services.md
  docs/book/advanced-guide/cloud/step-operators.md
  docs/book/advanced-guide/integrations/drift-detection.md
  docs/book/advanced-guide/integrations/experiment-tracking.md
  docs/book/advanced-guide/integrations/feature-store.md
  docs/book/advanced-guide/integrations/integrations.md
  docs/book/advanced-guide/integrations/run-on-kubeflow.md
  docs/book/advanced-guide/integrations/secrets.md
  docs/book/advanced-guide/integrations/visualizer.md
  docs/book/index.md
  docs/book/introduction/core-concepts.md
  docs/book/introduction/quickstart-guide.md
  docs/book/reference/glossary.md
  docs/book/stack-components/artifact-store.md
  docs/book/stack-components/container-registry.md
  docs/book/stack-components/experiment-tracker.md
  docs/book/stack-components/feature-store.md
  docs/book/stack-components/metadata-store.md
  docs/book/stack-components/model-deployer.md
  docs/book/stack-components/orchestrator.md
  docs/book/stack-components/secrets-manager.md
  docs/book/stack-components/step-operator.md
  docs/book/stack_components/feature_store.md
  docs/book/toc.md
Labels: internal

#601 Pipeline run tracking
  scripts/check-spelling.sh
  src/zenml/cli/config.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/config/profile_config.py
  src/zenml/constants.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/repository.py
  src/zenml/stack/stack.py
  src/zenml/steps/step_decorator.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/models/__init__.py
  src/zenml/zen_stores/models/component_wrapper.py
  src/zenml/zen_stores/models/pipeline_models.py
  src/zenml/zen_stores/models/zen_store_model.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/stack/test_stack.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#608 Docs + README updates
  README.md
  docs/book/assets/core_concepts/concepts-1.png
  docs/book/assets/core_concepts/concepts-2.png
  docs/book/assets/core_concepts/concepts-3.png
  docs/book/assets/dag-visualizer.png
  docs/book/assets/extensibility.gif
  docs/book/assets/mlflow-screenshot.png
  docs/book/assets/stack-list.png
  docs/book/introduction/core-concepts.md
Labels: enhancement, internal

#611 Hotfix/fix failing release
  .github/workflows/release.yml
Labels: internal

#612 Remove autocomplete + alerter from documentation
  docs/book/developer-guide/installation.md
  docs/book/toc.md
Labels: bug, documentation, internal

#605 Support Python 3.9
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/poetry-install.yml
  .github/workflows/unit-test.yml
  docs/book/developer-guide/installation.md
  pyproject.toml
  src/zenml/steps/utils.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#623 Don't build cuda image on release
  cloudbuild.yaml
Labels: enhancement, internal

#622 Improve kubeflow manual setup logs
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: enhancement, internal

#613 Added --set flag to register stack command
  docs/book/advanced-guide/cloud/continuous-training-and-deployment.md
  docs/book/advanced-guide/integrations/secrets.md
  examples/airflow_orchestration/README.md
  examples/aws_secret_manager/README.md
  examples/cloud_secrets_manager/README.md
  examples/feast_feature_store/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/seldon_deployment/README.md
  examples/step_operator_remote_training/README.md
  examples/wandb_tracking/README.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
Labels: enhancement, internal

#629 Bring back the `served_model` format to the keras materializer
  src/zenml/integrations/tensorflow/materializers/keras_materializer.py
Labels: bug, internal

#630 Fix broken example links
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/feast_feature_store/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/lightgbm/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/requirements.txt
  examples/mlflow_tracking/setup.sh
  examples/seldon_deployment/README.md
  examples/wandb_tracking/README.md
Labels: bug, internal

#633 Fix version parsing
  src/zenml/config/global_config.py
Labels: bug, internal

#586 Alerter Component for Slack Integration
  examples/slack_alert/README.md
  examples/slack_alert/__init__.py
  examples/slack_alert/assets/slack-message.png
  examples/slack_alert/run.py
  examples/slack_alert/setup.sh
  src/zenml/alerter/__init__.py
  src/zenml/alerter/alerter_step.py
  src/zenml/alerter/base_alerter.py
  src/zenml/cli/stack.py
  src/zenml/enums.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/slack/__init__.py
  src/zenml/integrations/slack/alerters/__init__.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/stack/stack.py
  src/zenml/steps/step_interfaces/__init__.py
  src/zenml/steps/step_interfaces/base_alerter_step.py
Labels: enhancement, internal

#631 Update `zenml go` to open quickstart/notebooks.
  examples/quickstart/notebooks/_assets/data_drift.png
  examples/quickstart/notebooks/_assets/inference_pipeline.png
  examples/quickstart/notebooks/_assets/mlflow_ui.png
  examples/quickstart/notebooks/_assets/quickstart_pipelines.png
  examples/quickstart/notebooks/_assets/stack_overview.png
  examples/quickstart/notebooks/_assets/train_pipeline.png
  examples/quickstart/notebooks/_assets/train_test_skew.png
  examples/quickstart/notebooks/_assets/training_serving_skew.png
  examples/quickstart/notebooks/quickstart.ipynb
  src/zenml/cli/base.py
Labels: enhancement, internal

#638 Update examples
  examples/facets_visualize_statistics/setup.sh
  examples/huggingface/README.md
  examples/huggingface/setup.sh
  examples/lightgbm/README.md
  examples/mlflow_deployment/setup.sh
  examples/mlflow_tracking/README.md
  examples/neural_prophet/README.md
  examples/pytorch/README.md
  examples/pytorch/setup.sh
  examples/quickstart/README.md
  examples/quickstart/setup.sh
  examples/scipy/README.md
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/README.md
  examples/whylogs_data_profiling/setup.sh
  examples/xgboost/README.md
Labels: enhancement, internal

#639 More detailed instructions on creating an integration
  CONTRIBUTING.md
Labels: internal

#641 Added publish api docs to release workflow
  .github/workflows/publish_api_docs.yml
Labels: enhancement, internal

#637 Added *.md to ignore paths
  .github/workflows/ci.yml
Labels: internal

#632 Update README and Docs with new messaging and fix broken links
  README.md
  docs/book/advanced-guide/advanced-zenml/README.md
  docs/book/advanced-guide/advanced-zenml/skip-materialization.md
  docs/book/advanced-guide/cloud/README.md
  docs/book/advanced-guide/continuous-training-and-deployment.md
  docs/book/advanced-guide/drift-detection.md
  docs/book/advanced-guide/experiment-tracking.md
  docs/book/advanced-guide/feature-store.md
  docs/book/advanced-guide/guide-aws-gcp-azure.md
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/integrations/README.md
  docs/book/advanced-guide/integrations/experiment-tracking.md
  docs/book/advanced-guide/run-on-kubeflow.md
  docs/book/advanced-guide/secrets.md
  docs/book/advanced-guide/services.md
  docs/book/advanced-guide/stacks-components-flavors.md
  docs/book/advanced-guide/step-operators.md
  docs/book/advanced-guide/visualize-your-data.md
  docs/book/advanced-guide/visualizer.md
  docs/book/developer-guide/caching.md
  docs/book/developer-guide/class-based-api.md
  docs/book/developer-guide/fetching-historic-runs.md
  docs/book/developer-guide/getting-started/README.md
  docs/book/developer-guide/installation.md
  docs/book/developer-guide/materializer.md
  docs/book/extending-zenml/getting-started.md
  docs/book/index.md
  docs/book/introduction/zenml-example-cli.md
  docs/book/resources/best-practices.md
  docs/book/resources/contributing.md
  docs/book/resources/faq.md
  docs/book/resources/system-env.md
  docs/book/resources/usage-analytics.md
  docs/book/toc.md
Labels: internal

#642 Pass secret to release linting workflow
  .github/workflows/release.yml
Labels: bug, internal

#649 Fix broken GCP Secrets example CLI command
  examples/cloud_secrets_manager/README.md
Labels: bug, documentation, internal

#651 Upgrade to `ml-pipelines-sdk` v1.8.0
  pyproject.toml
Labels: internal, dependencies

#647 Fix example list CLI command name
  src/zenml/cli/example.py
Labels: bug, internal

#657 Fix README
  README.md
  docs/book/assets/oss-header.svg
Labels: bug, internal

#652 Fix broken links in docs
  docs/book/advanced-guide/continuous-training-and-deployment.md
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/run-on-kubeflow.md
  docs/book/advanced-guide/stacks-components-flavors.md
  docs/book/advanced-guide/visualizer.md
  docs/book/developer-guide/materializer.md
  docs/book/developer-guide/repo-and-config.md
  docs/book/extending-zenml/artifact-store.md
  docs/book/extending-zenml/container-registry.md
  docs/book/extending-zenml/model-deployer.md
  docs/book/extending-zenml/orchestrator.md
  docs/book/extending-zenml/secrets-manager.md
  docs/book/extending-zenml/step-operator.md
  docs/book/introduction/quickstart-guide.md
  docs/book/introduction/whats_zenml.md
  docs/book/reference/glossary.md
  docs/book/resources/best-practices.md
  docs/book/resources/faq.md
  docs/book/resources/usage-analytics.md
Labels: documentation, internal

#659 Docs fixes
  README.md
  docs/book/advanced-guide/continuous-training-and-deployment.md
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/run-on-kubeflow.md
  docs/book/advanced-guide/stacks-components-flavors.md
  docs/book/advanced-guide/visualizer.md
  docs/book/assets/oss-header.svg
  docs/book/developer-guide/materializer.md
  docs/book/developer-guide/repo-and-config.md
  docs/book/extending-zenml/artifact-store.md
  docs/book/extending-zenml/container-registry.md
  docs/book/extending-zenml/model-deployer.md
  docs/book/extending-zenml/orchestrator.md
  docs/book/extending-zenml/secrets-manager.md
  docs/book/extending-zenml/step-operator.md
  docs/book/introduction/quickstart-guide.md
  docs/book/introduction/whats_zenml.md
  docs/book/reference/glossary.md
  docs/book/resources/best-practices.md
  docs/book/resources/faq.md
  docs/book/resources/usage-analytics.md
Labels: internal, backport

#661 Fix index page links and Heading links.
  docs/book/developer-guide/class-based-api.md
  docs/book/developer-guide/fetching-historic-runs.md
  docs/book/developer-guide/runtime-configuration.md
  docs/book/developer-guide/step-fixtures.md
  docs/book/developer-guide/steps-and-pipelines.md
  docs/book/index.md
  docs/book/resources/faq.md
Labels: internal

#481 Add docstring checks to `pre-commit` script
  .darglint
  .flake8
  pyproject.toml
  scripts/docstring.sh
  scripts/lint.sh
  src/zenml/alerter/__init__.py
  src/zenml/alerter/alerter_step.py
  src/zenml/alerter/base_alerter.py
  src/zenml/artifact_stores/__init__.py
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/artifacts/__init__.py
  src/zenml/artifacts/base_artifact.py
  src/zenml/artifacts/constants.py
  src/zenml/artifacts/data_analysis_artifact.py
  src/zenml/artifacts/data_artifact.py
  src/zenml/artifacts/model_artifact.py
  src/zenml/artifacts/schema_artifact.py
  src/zenml/artifacts/service_artifact.py
  src/zenml/artifacts/statistics_artifact.py
  src/zenml/artifacts/type_registry.py
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/cli.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/feature.py
  src/zenml/cli/formatter.py
  src/zenml/cli/integration.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/secret.py
  src/zenml/cli/served_models.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/text_utils.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/cli/version.py
  src/zenml/feature_stores/__init__.py
  src/zenml/feature_stores/base_feature_store.py
  src/zenml/io/__init__.py
  src/zenml/io/fileio.py
  src/zenml/io/utils.py
  src/zenml/model_deployers/__init__.py
  src/zenml/model_deployers/base_model_deployer.py
  src/zenml/step_operators/__init__.py
  src/zenml/step_operators/base_step_operator.py
  src/zenml/step_operators/entrypoint.py
  src/zenml/step_operators/step_executor_operator.py
Labels: documentation, internal

#666 Pin MLflow to <1.26.0 to prevent issues when matplotlib is not installed
  src/zenml/integrations/mlflow/__init__.py
Labels: bug, internal

#658 Making `utils` more consistent
  docs/book/developer-guide/repo-and-config.md
  src/zenml/cli/base.py
  src/zenml/cli/example.py
  src/zenml/cli/server.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/azure/artifact_stores/azure_artifact_store.py
  src/zenml/integrations/facets/visualizers/facet_statistics_visualizer.py
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/integrations/tensorflow/materializers/keras_materializer.py
  src/zenml/integrations/vertex/orchestrators/vertex_orchestrator.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/repository.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/secrets_managers/utils.py
  src/zenml/services/local/local_service.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/docker_utils.py
  src/zenml/utils/io_utils.py
  src/zenml/utils/yaml_utils.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
  tests/unit/cli/test_base.py
  tests/unit/io/test_fileio.py
  tests/unit/secrets_manager/test_local_secrets_manager.py
  tests/unit/test_repository.py
Labels: enhancement, internal

#669 Fix linting failures on `develop`
  src/zenml/cli/utils.py
Labels: bug, internal

#668 Add docstrings for `config` module
  scripts/docstring.sh
  scripts/lint.sh
  src/zenml/config/__init__.py
  src/zenml/config/base_config.py
  src/zenml/config/config_keys.py
  src/zenml/config/global_config.py
  src/zenml/config/profile_config.py
Labels: documentation, enhancement, internal

#665 Make ZenServer dependencies optional
  .github/actions/setup_environment/action.yml
  README.md
  docs/book/collaborate/zenml-server.md
  pyproject.toml
  src/zenml/__init__.py
  src/zenml/cli/server.py
Labels: enhancement, internal
