Repository zenml-io/zenml, pull requests merged in 2022-07, with the labels that each got.

#747 Fix broken links for docs and examples
  CONTRIBUTING.md
  docs/book/advanced-guide/manage-external-services.md
  docs/book/advanced-guide/manage-your-secrets.md
  docs/book/advanced-guide/perform-drift-detection.md
  docs/book/advanced-guide/run-on-kubeflow.md
  docs/book/advanced-guide/run-steps-on-specialized-hardware.md
  docs/book/advanced-guide/send-automated-chat-alerts.md
  docs/book/drafts/organization.md
  docs/book/reference/glossary.md
  examples/evidently_drift_detection/README.md
  examples/feast_feature_store/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/seldon_deployment/README.md
Labels: documentation, internal

#748 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation, internal

#738 Fix references to types when registering secrets managers
  docs/book/advanced-guide/manage-your-secrets.md
Labels: bug, documentation, internal

#761 Use correct region when trying to fetch ECR repositories
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
Labels: bug, internal

#760 Encode azure secrets manager secret names
  src/zenml/integrations/azure/secrets_managers/azure_secrets_manager.py
Labels: bug, internal, breaking-change

#742 Add nested mlflow option to enable_mlflow decorator
  examples/mlflow_tracking/README.md
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/mlflow_step_decorator.py
Labels: enhancement

#759 Combine all MLMD contexts
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/context_utils.py
  src/zenml/orchestrators/utils.py
  src/zenml/step_operators/step_executor_operator.py
  tests/unit/orchestrators/test_context_utils.py
  tests/unit/orchestrators/test_utils.py
Labels: enhancement, internal

#763 Prevent extra attributes when initializing StackComponents
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
  src/zenml/stack/stack_component.py
  tests/unit/stack/test_stack_component.py
Labels: enhancement, internal

#750 Vertex AI entrypoint
  docs/book/assets/VertexAiRun.png
  docs/book/cloud-guide/gcp/gcp_guide.md
Labels: documentation, internal

#749 Add AWS cloud guide
  docs/book/cloud-guide/aws/aws_guide.md
Labels: documentation, internal

#765 Fix facets magic display in Google Colab
  src/zenml/integrations/facets/visualizers/facet_statistics_visualizer.py
Labels: bug, internal

#766 Allow fetching secrets from within a step
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/stack/authentication_mixin.py
Labels: bug, internal

#768 Add notebook to great expectation example
  examples/great_expectations_data_validation/great_expectations.ipynb
  examples/great_expectations_data_validation/great_expectations_stack.png
Labels: enhancement, internal

#735 Module resolving and path fixes
  .pyspelling-ignore-words
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/config/global_config.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/utils/docker_utils.py
  src/zenml/utils/io_utils.py
  src/zenml/utils/source_utils.py
Labels: bug, internal

#771 Fix step operator entrypoint
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/step_operators/entrypoint.py
Labels: bug, internal

#775 Added changes from 1062 and 1061 into the updated docs
  docs/book/developer-guide/stacks-profiles-repositories/stack.md
  docs/book/developer-guide/steps-pipelines/inspecting-pipeline-runs.md
  docs/book/developer-guide/steps-pipelines/pipeline-visualization.md
  docs/book/mlops-stacks/model-deployers/mlflow.md
  docs/book/mlops-stacks/model-deployers/seldon.md
  docs/book/resources/best-practices.md
Labels: internal

#776 Refresh Examples on `zenml examples pull`
  examples/kubeflow_pipelines_orchestration/README.md
  src/zenml/cli/example.py
Labels: bug, internal

#764 Annotation stack component and Label Studio integration
  .github/workflows/lint.yml
  .github/workflows/publish_api_docs.yml
  .pyspelling-ignore-words
  docs/book/assets/annotation/annotation-when-where.png
  docs/book/mlops-stacks/annotators/annotators.md
  docs/book/mlops-stacks/annotators/custom.md
  docs/book/mlops-stacks/annotators/label-studio.md
  docs/book/mlops-stacks/categories.md
  docs/book/reference/glossary.md
  docs/book/toc.md
  src/zenml/annotators/__init__.py
  src/zenml/annotators/base_annotator.py
  src/zenml/cli/secret.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/enums.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/label_studio/__init__.py
  src/zenml/integrations/label_studio/annotators/__init__.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/label_studio/label_config_generators/__init__.py
  src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py
  src/zenml/integrations/label_studio/label_studio_utils.py
  src/zenml/integrations/label_studio/steps/__init__.py
  src/zenml/integrations/label_studio/steps/label_studio_standard_steps.py
  src/zenml/stack/stack.py
Labels: enhancement, internal

#779 Fix integration tests
  examples/deepchecks_data_validation/setup.sh
  examples/evidently_drift_detection/setup.sh
  examples/great_expectations_data_validation/setup.sh
  examples/whylogs_data_profiling/setup.sh
  tests/integration/example_validations.py
  tests/integration/test_examples.py
Labels: bug, internal

#782 Fix Links on the examples
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/evidently_drift_detection/README.md
  examples/feast_feature_store/README.md
  examples/github_actions_orchestration/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/quickstart/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/step_operator_remote_training/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
Labels: bug, internal

#783 Fix links on the release 0.11.0
  examples/airflow_orchestration/README.md
  examples/cloud_secrets_manager/README.md
  examples/evidently_drift_detection/README.md
  examples/feast_feature_store/README.md
  examples/github_actions_orchestration/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/quickstart/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/step_operator_remote_training/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
Labels: internal, backport

#719 Invalidating artifact/metadata store if there is a change in one of them
  .pyspelling-ignore-words
  docs/book/developer-guide/stacks-profiles-repositories/stack.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/constants.py
  src/zenml/repository.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/models/__init__.py
  src/zenml/zen_stores/models/component_wrapper.py
  src/zenml/zen_stores/models/stack_wrapper.py
  src/zenml/zen_stores/models/zen_store_model.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/cli/test_stack.py
  tests/unit/stack/conftest.py
  tests/unit/test_repository.py
Labels: bug, internal

#785 Fixed broken link in README
  README.md
Labels: internal

#789 Add data validation documentation
  .pyspelling-ignore-words
  docs/book/assets/deepchecks/data-integrity-results.png
  docs/book/assets/evidently/drift-visualization-01.png
  docs/book/assets/evidently/drift-visualization-02.png
  docs/book/assets/evidently/drift-visualization.png
  docs/book/assets/great_expectations/expectation_suite.png
  docs/book/assets/great_expectations/validation_result.png
  docs/book/assets/whylogs/whylogs-visualizer-01.png
  docs/book/assets/whylogs/whylogs-visualizer-02.png
  docs/book/mlops-stacks/artifact-stores/artifact-stores.md
  docs/book/mlops-stacks/artifact-stores/custom.md
  docs/book/mlops-stacks/categories.md
  docs/book/mlops-stacks/data-validators/custom.md
  docs/book/mlops-stacks/data-validators/data-validators.md
  docs/book/mlops-stacks/data-validators/deepchecks.md
  docs/book/mlops-stacks/data-validators/evidently.md
  docs/book/mlops-stacks/data-validators/great-expectations.md
  docs/book/mlops-stacks/data-validators/great_expectations.md
  docs/book/mlops-stacks/data-validators/whylogs.md
  docs/book/mlops-stacks/experiment-trackers/custom.md
  docs/book/mlops-stacks/experiment-trackers/experiment-trackers.md
  docs/book/mlops-stacks/metadata-stores/custom.md
  docs/book/toc.md
  examples/evidently_drift_detection/README.md
  examples/evidently_drift_detection/assets/drift_visualization.png
  src/zenml/integrations/deepchecks/data_validators/deepchecks_data_validator.py
  src/zenml/integrations/deepchecks/validation_checks.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
Labels: documentation

#786 Add local path for mlflow experiment tracker
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
Labels: enhancement, internal

#793 Improve Docker build logs.
  src/zenml/utils/docker_utils.py
Labels: enhancement, internal

#799 Allow standard library types in steps
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_source_utils.py
Labels: bug, internal

#801 Added small description
  docs/book/developer-guide/steps-pipelines/inspecting-pipeline-runs.md
Labels: documentation, internal

#792 Replace the restriction to use Repository inside step with a warning
  .pyspelling-ignore-words
  examples/quickstart/notebooks/quickstart.ipynb
  examples/quickstart/steps/prediction_steps.py
  src/zenml/entrypoints/step_entrypoint_configuration.py
  src/zenml/exceptions.py
  src/zenml/repository.py
  src/zenml/step_operators/entrypoint.py
  src/zenml/steps/base_step.py
  src/zenml/steps/restrict_step_access_decorator.py
  src/zenml/steps/step_environment.py
  src/zenml/steps/utils.py
  tests/unit/test_environment.py
  tests/unit/test_repository.py
Labels: bug, internal

#797 Adjust quickstart to data validators
  examples/README.md
  examples/evidently_drift_detection/assets/drift-visualization-01.png
  examples/evidently_drift_detection/assets/drift-visualization-02.png
  examples/quickstart/README.md
  examples/quickstart/notebooks/quickstart.ipynb
  examples/quickstart/run.py
  examples/quickstart/setup.sh
  examples/quickstart/steps/__init__.py
  examples/quickstart/steps/data_loaders.py
  examples/quickstart/steps/skew_comparisons.py
Labels: bug, internal

#778 Add utility function to deprecate pydantic attributes
  .pyspelling-ignore-words
  src/zenml/utils/deprecation_utils.py
  tests/unit/utils/test_deprecation_utils.py
Labels: enhancement, internal

#796 Fix the mismatch KFP version between Kubeflow and GCP integration
  .github/workflows/kubeflow.yml
  src/zenml/integrations/gcp/__init__.py
Labels: bug, internal

#802 Made mlflow more verbose
  docs/book/mlops-stacks/experiment-trackers/mlflow.md
Labels: internal

#655 KServe model deployer integration
  .github/workflows/lint.yml
  .pyspelling-ignore-words
  README.md
  docs/book/developer-guide/advanced-usage/manage-external-services.md
  docs/book/developer-guide/stacks-profiles-repositories/stack.md
  docs/book/mlops-stacks/integrations.md
  docs/book/mlops-stacks/model-deployers/kserve.md
  docs/book/toc.md
  examples/README.md
  examples/kserve_deployment/README.md
  examples/kserve_deployment/assets/pytorch_inference_remote.png
  examples/kserve_deployment/assets/pytorch_train_deploy_remote.png
  examples/kserve_deployment/assets/tensorflow_inference_remote.png
  examples/kserve_deployment/assets/tensorflow_train_deploy_remote.png
  examples/kserve_deployment/pipelines/__init__.py
  examples/kserve_deployment/pipelines/pytorch_pipeline.py
  examples/kserve_deployment/pipelines/tensorflow_pipeline.py
  examples/kserve_deployment/run_pytorch.py
  examples/kserve_deployment/run_tensorflow.py
  examples/kserve_deployment/steps/__init__.py
  examples/kserve_deployment/steps/deployment_trigger/__init__.py
  examples/kserve_deployment/steps/deployment_trigger/deployment_trigger.py
  examples/kserve_deployment/steps/prediction_service_loader/__init__.py
  examples/kserve_deployment/steps/prediction_service_loader/prediction_service_loader.py
  examples/kserve_deployment/steps/pytorch_steps/__init__.py
  examples/kserve_deployment/steps/pytorch_steps/mnist.py
  examples/kserve_deployment/steps/pytorch_steps/mnist_handler.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_data_loader.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_evaluator.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_inference_processor.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_model_deployer.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_predictor.py
  examples/kserve_deployment/steps/pytorch_steps/pytorch_trainer.py
  examples/kserve_deployment/steps/tensorflow_steps/__init__.py
  examples/kserve_deployment/steps/tensorflow_steps/dynamic_importer.py
  examples/kserve_deployment/steps/tensorflow_steps/mnist_importer.py
  examples/kserve_deployment/steps/tensorflow_steps/normalizer.py
  examples/kserve_deployment/steps/tensorflow_steps/tensorflow_model_deployer.py
  examples/kserve_deployment/steps/tensorflow_steps/tf_evaluator.py
  examples/kserve_deployment/steps/tensorflow_steps/tf_predict_preprocessor.py
  examples/kserve_deployment/steps/tensorflow_steps/tf_predictor.py
  examples/kserve_deployment/steps/tensorflow_steps/tf_trainer.py
  examples/seldon_deployment/README.md
  pyproject.toml
  src/zenml/cli/served_models.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/kserve/__init__.py
  src/zenml/integrations/kserve/model_deployers/__init__.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/kserve/secret_schemas/__init__.py
  src/zenml/integrations/kserve/secret_schemas/secret_schemas.py
  src/zenml/integrations/kserve/services/__init__.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/kserve/steps/__init__.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/kserve/steps/kserve_step_utils.py
  src/zenml/integrations/kubeflow/__init__.py
Labels: enhancement, internal

#805 retrieve pipeline requirement within running step
  src/zenml/step_operators/step_executor_operator.py
  src/zenml/steps/step_environment.py
  src/zenml/steps/utils.py
  tests/unit/test_environment.py
Labels: enhancement, internal

#814 Fix `--decouple_stores` error message
  src/zenml/stack/stack.py
Labels: bug, internal
