Repository zenml-io/zenml, pull requests merged in 2022-09, with the labels that each got.

#873 Use default local paths/URIs for the local artifact and metadata stores
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
  src/zenml/stack/stack.py
  tests/unit/stack/test_stack.py
Labels: bug, internal

#862 Implement local docker orchestrator
  .pyspelling-ignore-words
  docs/book/mlops-stacks/orchestrators/local-docker.md
  docs/book/mlops-stacks/orchestrators/orchestrators.md
  docs/book/toc.md
  src/zenml/orchestrators/__init__.py
  src/zenml/orchestrators/local_docker/__init__.py
  src/zenml/orchestrators/local_docker/local_docker_entrypoint_configuration.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/stack/flavor_registry.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal

#867 Update cheat sheet with latest CLI commands from 0.13.0
  docs/book/assets/zenml_cheat_sheet.pdf
  docs/book/assets/zenml_cheat_sheet.png
Labels: bug, documentation, enhancement, internal

#878 Bugfix/misc
  docs/book/mlops-stacks/experiment-trackers/wandb.md
  docs/book/toc.md
  pyproject.toml
  src/zenml/materializers/built_in_materializer.py
  src/zenml/utils/docker_utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/materializers/test_built_in_materializer.py
Labels: bug, internal

#871 Add cookie consent
  docs/mkdocs.yml
Labels: bug, enhancement, internal

#872 Stack recipe CLI improvements
  .gitignore
  .pyspelling-ignore-words
  docs/book/mlops-stacks/model-deployers/model-deployers.md
  docs/book/stack-deployment-guide/manual-deployments/aws/aws.md
  docs/book/stack-deployment-guide/manual-deployments/azure/azure.md
  docs/book/stack-deployment-guide/manual-deployments/gcp/gcp-guide.md
  docs/book/stack-deployment-guide/manual-deployments/gcp/gcp.md
  docs/book/stack-deployment-guide/stack-recipes.md
  examples/custom_code_deployment/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/tekton_pipelines_orchestration/__init__.py
  examples/tekton_pipelines_orchestration/assets/tekton_ui.png
  examples/tekton_pipelines_orchestration/assets/tekton_ui_2.png
  examples/tekton_pipelines_orchestration/assets/tekton_ui_3.png
  examples/tekton_pipelines_orchestration/assets/zenml.svg
  examples/tekton_pipelines_orchestration/config.yaml
  examples/tekton_pipelines_orchestration/pipelines/__init__.py
  examples/tekton_pipelines_orchestration/pipelines/mnist_pipeline.py
  examples/tekton_pipelines_orchestration/run.py
  examples/tekton_pipelines_orchestration/steps/__init__.py
  examples/tekton_pipelines_orchestration/steps/evaluators.py
  examples/tekton_pipelines_orchestration/steps/importers.py
  examples/tekton_pipelines_orchestration/steps/normalizers.py
  examples/tekton_pipelines_orchestration/steps/trainers.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_recipes.py
  tests/unit/cli/test_stack.py
  tests/unit/zen_server/test_zen_server.py
Labels: enhancement, internal

#886 Kubeflow workaround added
  docs/book/mlops-stacks/orchestrators/kubeflow.md
Labels: internal

#894 Minor doc updates for backporting
  docs/book/mlops-stacks/data-validators/deepchecks.md
  docs/book/mlops-stacks/orchestrators/kubeflow.md
  examples/wandb_tracking/README.md
Labels: internal

#891 Runtime Lineage Graph
  examples/great_expectations_data_validation/steps/importer.py
  examples/label_studio_annotation/steps/prediction_steps.py
  src/zenml/post_execution/__init__.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/lineage/__init__.py
  src/zenml/post_execution/lineage/edge.py
  src/zenml/post_execution/lineage/lineage_graph.py
  src/zenml/post_execution/lineage/node/__init__.py
  src/zenml/post_execution/lineage/node/artifact_node.py
  src/zenml/post_execution/lineage/node/base_node.py
  src/zenml/post_execution/lineage/node/step_node.py
Labels: enhancement, internal

#897 Removed feature request and replaced with hellonext board
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: internal

#880 Unit tests for (some) integrations
  .github/workflows/unit-test.yml
  .pyspelling-ignore-words
  tests/unit/integrations/deepchecks/__init__.py
  tests/unit/integrations/deepchecks/data_validators/__init__.py
  tests/unit/integrations/deepchecks/data_validators/test_deepchecks_data_validator.py
  tests/unit/integrations/deepchecks/test_validation_checks.py
  tests/unit/integrations/evidently/data_validators/__init__.py
  tests/unit/integrations/evidently/data_validators/test_evidently_data_validator.py
  tests/unit/integrations/evidently/materializers/__init__.py
  tests/unit/integrations/evidently/materializers/test_evidently_profile_materializer.py
  tests/unit/integrations/great_expectations/__init__.py
  tests/unit/integrations/great_expectations/materializers/__init__.py
  tests/unit/integrations/great_expectations/materializers/test_ge_materializer.py
  tests/unit/integrations/huggingface/__init__.py
  tests/unit/integrations/huggingface/materializers/__init__.py
  tests/unit/integrations/huggingface/materializers/test_huggingface_datasets_materializer.py
  tests/unit/integrations/huggingface/materializers/test_huggingface_pt_model_materializer.py
  tests/unit/integrations/huggingface/materializers/test_huggingface_tf_model_materializer.py
  tests/unit/integrations/huggingface/materializers/test_huggingface_tokenizer_materializer.py
  tests/unit/integrations/lightgbm/__init__.py
  tests/unit/integrations/lightgbm/materializers/__init__.py
  tests/unit/integrations/lightgbm/materializers/test_lightgbm_booster_materializer.py
  tests/unit/integrations/lightgbm/materializers/test_lightgbm_dataset_materializer.py
  tests/unit/integrations/neural_prophet/__init__.py
  tests/unit/integrations/neural_prophet/materializers/__init__.py
  tests/unit/integrations/neural_prophet/materializers/test_neural_prophet_materializer.py
  tests/unit/integrations/pillow/materializers/__init__.py
  tests/unit/integrations/pillow/materializers/test_pillow_image_materializer.py
  tests/unit/integrations/pytorch/__init__.py
  tests/unit/integrations/pytorch/materializers/__init__.py
  tests/unit/integrations/pytorch/materializers/test_pytorch_dataloader_materializer.py
  tests/unit/integrations/pytorch/materializers/test_pytorch_module_materializer.py
  tests/unit/integrations/scipy/__init__.py
  tests/unit/integrations/scipy/materializers/__init__.py
  tests/unit/integrations/scipy/materializers/test_sparse_materializer.py
  tests/unit/integrations/sklearn/__init__.py
  tests/unit/integrations/sklearn/materializers/__init__.py
  tests/unit/integrations/sklearn/materializers/test_sklearn_materializer.py
  tests/unit/integrations/tensorflow/__init__.py
  tests/unit/integrations/tensorflow/materializers/__init__.py
  tests/unit/integrations/tensorflow/materializers/test_keras_materializer.py
  tests/unit/integrations/tensorflow/materializers/test_tf_dataset_materializer.py
  tests/unit/integrations/whylogs/__init__.py
  tests/unit/integrations/whylogs/materializers/__init__.py
  tests/unit/integrations/whylogs/materializers/test_whylogs_materializer.py
  tests/unit/integrations/xgboost/__init__.py
  tests/unit/integrations/xgboost/materializers/__init__.py
  tests/unit/integrations/xgboost/materializers/test_xgboost_dmatrix_materializer.py
  tests/unit/test_general.py
Labels: internal, tests

#900 Fixed integration installation command
  docs/book/mlops-stacks/model-deployers/seldon.md
Labels: bug, documentation

#901 [Bugfix] Fix bug in auto-import of stack after recipe deploy
  README.md
  docs/book/collaborate/stack-export-import.md
  docs/book/stack-deployment-guide/stack-recipes.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/quickstart/README.md
  examples/seldon_deployment/README.md
  examples/vertex_ai_orchestration/README.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack_recipes.py
Labels: bug, internal

#902 Some docs updates
  docs/book/advanced-guide/pipelines/step-resources.md
  docs/book/advanced-guide/practical/containerization.md
  docs/book/legacy/developer-guide/stack-deployment-guide/execute-pipelines-in-cloud.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/gcp/gcp-guide.md
  docs/book/mlops-stacks/data-validators/deepchecks.md
  docs/book/mlops-stacks/data-validators/whylogs.md
  docs/book/mlops-stacks/experiment-trackers/mlflow.md
  docs/book/mlops-stacks/experiment-trackers/wandb.md
  docs/book/mlops-stacks/orchestrators/custom.md
  docs/book/mlops-stacks/secrets-managers/azure.md
  docs/book/mlops-stacks/secrets-managers/gcp.md
  docs/book/mlops-stacks/secrets-managers/secrets-managers.md
  docs/book/mlops-stacks/step-operators/amazon-sagemaker.md
  docs/book/mlops-stacks/step-operators/azureml.md
  docs/book/mlops-stacks/step-operators/custom.md
  docs/book/mlops-stacks/step-operators/gcloud-vertexai.md
  docs/book/mlops-stacks/step-operators/spark.md
  docs/book/mlops-stacks/step-operators/step-operators.md
  docs/book/popular-stack-guides/gcp/basic-stack.md
Labels: internal

#905 Pretty flavor describe command for the CLI
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/integrations/s3/flavors/s3_artifact_store_flavor.py
Labels: enhancement, internal

#907 Update TOC on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, internal

#906 Backend changes to enable the new Telemetry flow
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/user_management_models.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/source_utils.py
  src/zenml/zen_server/deploy/helm/templates/deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  src/zenml/zen_server/models/user_management_models.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/user_management_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal
