Repository zenml-io/zenml, pull requests merged in 2022-11, with the labels that each got.

#1023 Support pydantic subclasses in BaseParameter attributes
  src/zenml/steps/base_step.py
  tests/unit/steps/test_base_step.py
Labels: bug, internal

#1025 Unify run names across orchestrators
  .pyspelling-ignore-words
  docker/local-dev.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  src/zenml/config/compiler.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/entrypoints/step_entrypoint_configuration.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_entrypoint_configuration.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/github/orchestrators/github_actions_entrypoint_configuration.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_entrypoint_configuration.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint_configuration.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_step_entrypoint_configuration.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/tekton/orchestrators/tekton_entrypoint_configuration.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/models/pipeline_models.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/stack/stack.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/utils/uuid_utils.py
  src/zenml/zen_server/models/pipeline_models.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_stores/migrations/versions/d02b3d3464cf_add_orchestrator_run_id_column.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/unit/stack/test_stack_component.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1026 Add gRPC metadata service to the ZenML helm chart
  .pyspelling-ignore-words
  docker/zenml-server-devel.Dockerfile
  src/zenml/zen_server/deploy/helm/templates/NOTES.txt
  src/zenml/zen_server/deploy/helm/templates/_helpers.tpl
  src/zenml/zen_server/deploy/helm/templates/cert-secret.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-ingress.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-secret.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-service.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/server-ingress.yaml
  src/zenml/zen_server/deploy/helm/templates/server-service.yaml
  src/zenml/zen_server/deploy/helm/templates/tests/test-connection.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#1032 Make the MLMD pipeline run information transfer synchronous
  src/zenml/constants.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/alembic.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: bug, internal

#1034 Add console spinner back
  src/zenml/cli/stack.py
Labels: bug, internal

#1035 Fix Azure CLI auth problem
  src/zenml/integrations/azure/__init__.py
Labels: bug, internal

#1033 Allow non-local Label Studio instances for annotation
  docs/book/component-gallery/annotators/label-studio.md
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/label_studio/flavors/label_studio_annotator_flavor.py
Labels: bug, internal

#1029 Before deleting the global zen_server files, spin it down
  src/zenml/cli/base.py
Labels: enhancement, internal

#1017 Adding zenserver integration to stack recipe CLI
  docs/book/getting-started/deploying-zenml/cli.md
  src/zenml/cli/server.py
  src/zenml/cli/stack_recipes.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/zen_server/deploy/terraform/providers/aws_provider.py
  src/zenml/zen_server/deploy/terraform/providers/gcp_provider.py
  src/zenml/zen_server/deploy/terraform/recipes/aws/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/vpc.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
Labels: enhancement, internal

#1008 Kubernetes Pod settings
  .pyspelling-ignore-words
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/tekton.md
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/utils.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
  src/zenml/integrations/kubernetes/serialization_utils.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  tests/unit/integrations/kubernetes/test_serialization_utils.py
Labels: enhancement, internal

#1039 Include latest (not oldest) three runs in HydratedPipelineModel
  src/zenml/zen_server/models/pipeline_models.py
  tests/unit/zen_server/models/__init__.py
  tests/unit/zen_server/models/test_pipeline_models.py
Labels: bug, internal

#1037 Update docs to use `pip install [server]`
  docs/book/getting-started/installation/m1-mac-installation.md
  examples/README.md
  examples/add_your_own/template_README.md
Labels: documentation, internal

#1040 Docs fix for Deepchecks
  docs/book/component-gallery/data-validators/deepchecks.md
Labels: bug, documentation, internal

#1041 Fix the pipeline run sync on sqlite and the --blocking zenml server deployment
  .pyspelling-ignore-words
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#1007 Introduce Permissions, Link Permissions to Roles, Restrict Access to endpoints based on Permission
  .gitignore
  src/zenml/cli/__init__.py
  src/zenml/cli/user_management.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/user_management_models.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/models/user_management_models.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/metadata_config_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/roles_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/routers/teams_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/5994f9ad0489_introduce_role_permissions.py
  src/zenml/zen_stores/schemas/user_management_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1049 Fix copy-pasted log message for annotator
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
Labels: documentation, internal

#1047 Add warning message for client server version mismatch
  src/zenml/constants.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#1053 Fix path to ingress values in ZenServer recipes
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
Labels: bug, internal

#1046 Prevent deletion/update of default entities
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/client.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/cli/test_stack.py
  tests/unit/cli/test_stack_components.py
  tests/unit/stack/test_stack_component.py
  tests/unit/test_client.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1054 Fix Publish API docs workflow
  .github/workflows/publish_api_docs.yml
Labels: bug, internal

#1051 Fix multiple alembic heads warning
  src/zenml/zen_stores/migrations/versions/5994f9ad0489_introduce_role_permissions.py
Labels: bug, internal

#1050 Fix Null Step Configuration/Parameters Error
  src/zenml/zen_stores/metadata_store.py
  src/zenml/zen_stores/migrations/versions/7280c14811d6_use_text_type.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
Labels: bug, internal

#1056 Fix role permission migration
  src/zenml/zen_stores/migrations/versions/5994f9ad0489_introduce_role_permissions.py
  src/zenml/zen_stores/migrations/versions/__init__.py
Labels: bug, internal

#1059 Made role assignment/revokation possible through zen_server
  src/zenml/cli/user_management.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: bug, internal

#1064 Manually set scoped for each endpoint
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/metadata_config_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/roles_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/routers/teams_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#1060 Add run args to local docker orchestrator settings
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
Labels: enhancement, internal

#1061 Docker ZenML deployment improvements and docs
  .pyspelling-ignore-words
  docs/book/getting-started/deploying-zenml/docker.md
  src/zenml/cli/server.py
  src/zenml/config/global_config.py
  src/zenml/config/store_config.py
  src/zenml/environment.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/services/container/container_service.py
  src/zenml/services/container/container_service_endpoint.py
  src/zenml/utils/networking_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_server/deploy/docker/docker_provider.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: documentation, internal

#1067 Bugfix Mlflow service cleanup configuration
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
Labels: bug, internal

#1058 Rename DB Tables and Fix Foreign Keys
  .pyspelling-ignore-words
  src/zenml/zen_stores/migrations/alembic.py
  src/zenml/zen_stores/migrations/versions/5330ba58bf20_rename_tables_and_foreign_keys.py
  src/zenml/zen_stores/migrations/versions/5994f9ad0489_introduce_role_permissions.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/project_schemas.py
  src/zenml/zen_stores/schemas/schema_utils.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/schemas/user_management_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#1057 Paginate secrets in `AWSSecretsManager`
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
Labels: bug

#1052 Add explicit dashboard docs
  docs/book/assets/dashboard/zenml-dag-artifact-inspection.png
  docs/book/starter-guide/pipelines/dashboard.md
  docs/book/starter-guide/pipelines/pipelines.md
  docs/book/toc.md
Labels: documentation, internal

#1048 Add Inference Server Predictor to KServe and Seldon Docs
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
  examples/kserve_deployment/README.md
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
Labels: documentation, internal

#1073 Rename project table to workspace
  src/zenml/zen_stores/migrations/versions/5330ba58bf20_rename_tables_and_foreign_keys.py
  src/zenml/zen_stores/schemas/project_schemas.py
Labels: enhancement, internal

#1042 Airflow orchestrator v2
  .github/workflows/lint.yml
  .pyspelling-ignore-words
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/github-actions.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/local-docker.md
  docs/book/component-gallery/orchestrators/local.md
  docs/book/component-gallery/orchestrators/tekton.md
  examples/airflow_orchestration/README.md
  examples/airflow_orchestration/assets/DAG.png
  examples/airflow_orchestration/pipelines/__init__.py
  examples/airflow_orchestration/pipelines/fashion_mnist_pipeline.py
  examples/airflow_orchestration/run.py
  examples/airflow_orchestration/setup.sh
  examples/airflow_orchestration/steps/__init__.py
  examples/airflow_orchestration/steps/evaluators.py
  examples/airflow_orchestration/steps/importers.py
  examples/airflow_orchestration/steps/trainers.py
  examples/kubeflow_pipelines_orchestration/README.md
  pyproject.toml
  src/zenml/cli/stack.py
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/airflow/flavors/airflow_orchestrator_flavor.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/airflow/orchestrators/dag_generator.py
  src/zenml/pipelines/base_pipeline.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_examples.py
  tests/unit/integrations/airflow/orchestrators/test_airflow_orchestrator.py
  tests/unit/integrations/airflow/orchestrators/test_dag_generator.py
  tests/unit/orchestrators/test_utils.py
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal

#1070 Add get_or_create_run() ZenStore method
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#1044 BentoML Deployer Integration
  .github/workflows/lint.yml
  .pyspelling-ignore-words
  docs/book/component-gallery/model-deployers/bentoml.md
  docs/book/component-gallery/model-deployers/model-deployers.md
  examples/bentoml_deployment/README.md
  examples/bentoml_deployment/__init__.py
  examples/bentoml_deployment/config.yaml
  examples/bentoml_deployment/constants.py
  examples/bentoml_deployment/inference_samples/ankle_boot.jpg
  examples/bentoml_deployment/inference_samples/bag.jpeg
  examples/bentoml_deployment/inference_samples/dress.jpeg
  examples/bentoml_deployment/inference_samples/pullover.jpeg
  examples/bentoml_deployment/inference_samples/shirt.jpeg
  examples/bentoml_deployment/inference_samples/sneaker.jpeg
  examples/bentoml_deployment/inference_samples/trouser.jpeg
  examples/bentoml_deployment/pipelines/__init__.py
  examples/bentoml_deployment/pipelines/inference_fashion_mnist.py
  examples/bentoml_deployment/pipelines/training_fashion_mnist.py
  examples/bentoml_deployment/requirements.txt
  examples/bentoml_deployment/run.py
  examples/bentoml_deployment/service.py
  examples/bentoml_deployment/setup.sh
  examples/bentoml_deployment/steps/__init__.py
  examples/bentoml_deployment/steps/bento_builder.py
  examples/bentoml_deployment/steps/deployer.py
  examples/bentoml_deployment/steps/deployment_trigger_step.py
  examples/bentoml_deployment/steps/evaluators.py
  examples/bentoml_deployment/steps/importers.py
  examples/bentoml_deployment/steps/inference_loader.py
  examples/bentoml_deployment/steps/prediction_service_loader.py
  examples/bentoml_deployment/steps/predictor.py
  examples/bentoml_deployment/steps/trainers.py
  pyproject.toml
  src/zenml/integrations/__init__.py
  src/zenml/integrations/bentoml/__init__.py
  src/zenml/integrations/bentoml/constants.py
  src/zenml/integrations/bentoml/flavors/__init__.py
  src/zenml/integrations/bentoml/flavors/bentoml_model_deployer_flavor.py
  src/zenml/integrations/bentoml/materializers/__init__.py
  src/zenml/integrations/bentoml/materializers/bentoml_bento_materializer.py
  src/zenml/integrations/bentoml/model_deployers/__init__.py
  src/zenml/integrations/bentoml/model_deployers/bentoml_model_deployer.py
  src/zenml/integrations/bentoml/services/__init__.py
  src/zenml/integrations/bentoml/services/bentoml_deployment.py
  src/zenml/integrations/bentoml/steps/__init__.py
  src/zenml/integrations/bentoml/steps/bento_builder.py
  src/zenml/integrations/bentoml/steps/bentoml_deployer.py
  src/zenml/integrations/constants.py
  src/zenml/utils/materializer_utils.py
Labels: enhancement, internal

#1055 Sync Speedup
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/pipeline_models.py
  src/zenml/utils/proto_utils.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/models/pipeline_models.py
  src/zenml/zen_server/routers/metadata_sync_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/metadata_store.py
  src/zenml/zen_stores/migrations/versions/8a64fbfecda0_add_num_outputs_to_run_step.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#1076 Fixed broken links in docs and examples.
  docs/book/advanced-guide/practical/secrets-management.md
  docs/book/component-gallery/alerters/slack.md
  docs/book/component-gallery/artifact-stores/amazon-s3.md
  docs/book/component-gallery/artifact-stores/azure-blob-storage.md
  docs/book/component-gallery/artifact-stores/gcloud-gcs.md
  docs/book/component-gallery/container-registries/amazon-ecr.md
  docs/book/component-gallery/container-registries/default.md
  docs/book/component-gallery/data-validators/deepchecks.md
  docs/book/component-gallery/data-validators/evidently.md
  docs/book/component-gallery/data-validators/great-expectations.md
  docs/book/component-gallery/data-validators/whylogs.md
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/experiment-trackers/wandb.md
  docs/book/component-gallery/feature-stores/feast.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/mlflow.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/github-actions.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/secrets-managers/aws.md
  docs/book/component-gallery/secrets-managers/azure.md
  docs/book/component-gallery/secrets-managers/gcp.md
  docs/book/component-gallery/secrets-managers/github.md
  docs/book/component-gallery/secrets-managers/hashicorp-vault.md
  docs/book/component-gallery/step-operators/amazon-sagemaker.md
  docs/book/component-gallery/step-operators/azureml.md
  docs/book/component-gallery/step-operators/gcloud-vertexai.md
  docs/book/starter-guide/pipelines/pipelines.md
  docs/book/starter-guide/stacks/managing-stacks.md
  docs/book/starter-guide/stacks/registering-stacks.md
  docs/book/starter-guide/stacks/stacks.md
  examples/README.md
  examples/custom_code_deployment/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/neural_prophet/README.md
  examples/seldon_deployment/README.md
  examples/vertex_ai_orchestration/README.md
Labels: internal

#1069 Make additional stack component config options available as a setting
  .pyspelling-ignore-words
  docs/book/advanced-guide/pipelines/settings.md
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/experiment-trackers/wandb.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/local-docker.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/step-operators/amazon-sagemaker.md
  docs/book/component-gallery/step-operators/azureml.md
  docs/book/component-gallery/step-operators/gcloud-vertexai.md
  docs/book/component-gallery/step-operators/spark.md
  src/zenml/config/compiler.py
  src/zenml/integrations/airflow/flavors/airflow_orchestrator_flavor.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/flavors/azureml_step_operator_flavor.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/kserve/flavors/kserve_model_deployer_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/flavors/mlflow_experiment_tracker_flavor.py
  src/zenml/integrations/seldon/flavors/seldon_model_deployer_flavor.py
  src/zenml/integrations/slack/flavors/slack_alerter_flavor.py
  src/zenml/integrations/spark/flavors/spark_step_operator_flavor.py
  src/zenml/integrations/spark/step_operators/spark_step_operator.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/integrations/vault/flavors/vault_secrets_manager_flavor.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/integrations/whylogs/flavors/whylogs_data_validator_flavor.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/settings_utils.py
  tests/unit/integrations/gcp/orchestrators/test_vertex_orchestrator.py
  tests/unit/stack/conftest.py
Labels: enhancement, internal

#1075 Rename `step_run_artifact` table to `step_run_input_artifact`
  src/zenml/zen_stores/migrations/versions/5330ba58bf20_rename_tables_and_foreign_keys.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#1071 Update Spark Example to ZenML post 0.20.0
  examples/spark_distributed_programming/README.md
  examples/spark_distributed_programming/pipelines/spark_pipeline/spark_pipeline.py
  examples/spark_distributed_programming/run.py
Labels: bug, internal

#1078 RMTFX: Redesign Artifact Tables
  src/zenml/models/pipeline_models.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_stores/migrations/versions/26b776ad583e_redesign_artifacts.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1084 Add global config dir to `zenml status`
  src/zenml/cli/server.py
Labels: enhancement, internal

#1083 Remove source pins and ignore source pins during step spec comparisons
  src/zenml/config/step_configurations.py
  src/zenml/utils/source_utils.py
  tests/unit/config/test_step_configurations.py
  tests/unit/utils/test_source_utils.py
Labels: bug, internal

#1085 RMTFX: Add caching info and start/end times of runs to DB
  src/zenml/client.py
  src/zenml/models/pipeline_models.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/zen_stores/migrations/versions/6a28c4fd0ef2_add_caching_info.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
Labels: enhancement, internal

#1090 RMTFX: Redesign Artifact Models
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/models/pipeline_models.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/lineage/lineage_graph.py
  src/zenml/post_execution/step.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_stores/migrations/versions/26b776ad583e_redesign_artifacts.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/conftest.py
  tests/unit/cli/test_pipeline.py
  tests/unit/post_execution/test_artifact.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1091 Docs/links for roles permissions
  docs/book/starter-guide/collaborate/roles-and-permissions.md
Labels: documentation, internal

#1087 Backport role and permission docs to release 0.22.0
  docs/book/starter-guide/collaborate/roles-and-permissions.md
  docs/book/toc.md
Labels: internal, backport

#1092 Add get_artifact() endpoint
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#1089 Bugfix/eng 1485 fix api docs build
  .github/workflows/publish_api_docs.yml
  .pyspelling-ignore-words
Labels: bug, internal

#1094 Add bentoctl to BentoML docs and example
  .pyspelling-ignore-words
  docs/book/component-gallery/model-deployers/bentoml.md
  examples/bentoml_deployment/README.md
  examples/bentoml_deployment/requirements.txt
Labels: bug, internal

#1095 RMTFX: `io/`
  src/zenml/io/__init__.py
  src/zenml/io/fileio.py
  src/zenml/io/filesystem.py
  src/zenml/io/filesystem_registry.py
  src/zenml/io/local_filesystem.py
Labels: enhancement, internal

#1093 RMTFX: `artifacts/`, `artifact_stores/`, `materializers/`
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifacts/base_artifact.py
  src/zenml/artifacts/constants.py
  src/zenml/integrations/kubeflow/orchestrators/utils.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/launcher.py
  src/zenml/steps/step_context.py
  src/zenml/steps/utils.py
  src/zenml/utils/materializer_utils.py
Labels: enhancement, internal

#1102 Add bentoctl to BentoML docs and example (#1094)
  .pyspelling-ignore-words
  docs/book/component-gallery/model-deployers/bentoml.md
  examples/bentoml_deployment/README.md
  examples/bentoml_deployment/requirements.txt
Labels: internal, backport

#1105 ENG 1357 active stack env
  src/zenml/client.py
Labels: bug, internal

#1104 Khalas [Bug fix]
  src/zenml/cli/utils.py
Labels: bug, internal

#1106 Revert gRPC metadata service
  src/zenml/zen_server/deploy/helm/templates/_helpers.tpl
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-ingress.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-secret.yaml
  src/zenml/zen_server/deploy/helm/templates/grpc-metadata-service.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal

#1108 Remove deprecated warnings
  src/zenml/client.py
Labels: bug, internal

#1111 Fixed evidently docs
  docs/book/component-gallery/data-validators/evidently.md
Labels: internal

#1112 Update sagemaker default instance type
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: bug, internal

#1114 Update stack exporting and importing
  src/zenml/cli/stack.py
  src/zenml/client.py
  src/zenml/models/stack_models.py
  tests/unit/cli/test_stack.py
Labels: bug, internal

#1116 Fix readme
  README.md
Labels: bug, internal

#1109 Remove Pyarrow dependency
  .pyspelling-ignore-words
  pyproject.toml
  src/zenml/integrations/neural_prophet/materializers/neural_prophet_materializer.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/materializers/pandas_materializer.py
Labels: enhancement, internal

#1120 Add YouTube video explaining Stack Components Settings vs Config
  docs/book/advanced-guide/pipelines/settings.md
Labels: documentation, internal

#1115 Add failed Status to component when step fails
  docs/book/component-gallery/experiment-trackers/experiment-trackers.md
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/mlflow_utils.py
  src/zenml/integrations/neptune/experiment_trackers/neptune_experiment_tracker.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
Labels: bug, internal, breaking-change

#1119 Add architecture diagrams to docs
  docs/book/assets/diagrams/RemoteServer.png
  docs/book/assets/diagrams/Remote_with_deployer.png
  docs/book/assets/diagrams/Remote_with_exp_tracker.png
  docs/book/assets/diagrams/Remote_with_git_ops.png
  docs/book/assets/diagrams/Remote_with_secrets_manager.png
  docs/book/component-gallery/experiment-trackers/experiment-trackers.md
  docs/book/component-gallery/model-deployers/model-deployers.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/getting-started/architecture-diagrams.md
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
  docs/book/toc.md
Labels: documentation, internal

#1121 Backport architecture diagrams to docs for 0.22.0
  docs/book/assets/diagrams/RemoteServer.png
  docs/book/assets/diagrams/Remote_with_deployer.png
  docs/book/assets/diagrams/Remote_with_exp_tracker.png
  docs/book/assets/diagrams/Remote_with_git_ops.png
  docs/book/assets/diagrams/Remote_with_secrets_manager.png
  docs/book/component-gallery/experiment-trackers/experiment-trackers.md
  docs/book/component-gallery/model-deployers/model-deployers.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/getting-started/architecture-diagrams.md
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
  docs/book/toc.md
Labels: internal, backport

#1122 Remove local orchestrator restriction from step operator docs
  docs/book/component-gallery/step-operators/amazon-sagemaker.md
  docs/book/component-gallery/step-operators/gcloud-vertexai.md
Labels: bug, internal

#1110 Validate Stack Before Provision
  .pyspelling-ignore-words
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
  src/zenml/stack/stack.py
  tests/unit/stack/test_stack.py
Labels: bug, internal
