Repository zenml-io/zenml, pull requests merged in 2022-03, with the labels that each got.

#437 Remove support for python 3.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/testing.yml
  README.md
  docs/book/introduction/installation.md
  examples/mlflow_deployment/pipeline.py
  examples/mlflow_deployment/requirements.txt
  examples/mlflow_tracking/requirements.txt
  pyproject.toml
  src/zenml/README.md
  src/zenml/cli/base.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/sklearn/helpers/digits.py
  src/zenml/integrations/tensorflow/__init__.py
  src/zenml/materializers/numpy_materializer.py
Labels: enhancement, internal

#430 Create clean test repos in separate folders
  tests/conftest.py
Labels: bug, internal

#434 Copy explicit materializers before modifying, log correct class
  src/zenml/steps/base_step.py
  src/zenml/utils/source_utils.py
Labels: bug, internal

#443 Training resource step component and decorator option
  src/zenml/enums.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/azure/training_resources/__init__.py
  src/zenml/integrations/azure/training_resources/azureml_training_resource.py
  src/zenml/repository.py
  src/zenml/stack/stack.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  src/zenml/training_resources/__init__.py
  src/zenml/training_resources/base_training_resource.py
Labels: enhancement, internal

#438 Fix typo in mysql password parameter
  docs/book/features/cloud-pipelines/cloud-pipelines.md
Labels: documentation

#405 Pytest-fixture for separate virtual environments for each integration test
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/kubeflow.yml
  .github/workflows/lint.yml
  .github/workflows/poetry-install.yml
  .github/workflows/testing.yml
  .github/workflows/unit-test.yml
  README.md
  src/zenml/cli/example.py
  tests/conftest.py
  tests/integration/test_examples.py
  tests/venv_clone_utils.py
Labels: internal

#444 Bugfix/fix failing tests due to comments step
  .github/workflows/ci.yml
Labels: bug, internal

#445 Added --use-virtualenvs option to allow choosing envs to run
  .github/actions/setup_environment/action.yml
  .github/workflows/kubeflow.yml
  scripts/test-coverage-xml.sh
  tests/conftest.py
  tests/integration/test_examples.py
Labels: enhancement, internal

#448 Implement first version of azureml training resource
  src/zenml/cli/stack.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/training_resources/__init__.py
  src/zenml/integrations/aws/training_resources/sagemaker_training_resource.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/azure/training_resources/azureml_training_resource.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/utils.py
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  src/zenml/training_resources/base_training_resource.py
  src/zenml/training_resources/entrypoint.py
  src/zenml/training_resources/training_resource_executor_operator.py
Labels: internal

#442 Improve error message when provisioning local kubeflow resources with a non-local container registry.
  src/zenml/cli/stack.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#449 Implement first version of sagemaker training resource
  src/zenml/integrations/aws/io/__init__.py
  src/zenml/integrations/aws/training_resources/sagemaker_training_resource.py
  src/zenml/integrations/azure/training_resources/azureml_training_resource.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/training_resources/training_resource_executor_operator.py
  src/zenml/utils/docker_utils.py
Labels: internal

#440 Enable generic step inputs and outputs
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  tests/unit/steps/test_base_step.py
  tests/unit/steps/test_utils.py
Labels: bug, internal

#452 Removed old reference to a step that no longer exists
  .github/actions/setup_environment/action.yml
Labels: enhancement, internal

#451 Correctly use custom kubernetes context if specified
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#450 Fix CLI stack component describe/list commands
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
Labels: bug, internal

#453 Ignore type of any tfx proto file
  pyproject.toml
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/orchestrators/context_utils.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/utils.py
  src/zenml/steps/utils.py
Labels: enhancement, internal

#455 Another boyscout pr on the gh actions
  .github/workflows/ci.yml
Labels: bug, internal

#457 Added ZenFiles to README
  README.md
Labels: internal

#459 Feature/zen service daemon
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/service.py
  src/zenml/service.py
  src/zenml/services/local/local_daemon_entrypoint.py
  src/zenml/services/service.py
  src/zenml/zen_service/__init__.py
  src/zenml/zen_service/zen_service.py
  src/zenml/zen_service/zen_service_deployment.py
Labels: enhancement, internal

#461 Addding the AzureML example
  examples/azureml_step_operator/README.md
  examples/azureml_step_operator/__init__.py
  examples/azureml_step_operator/pipeline.py
  examples/azureml_step_operator/setup.sh
Labels: enhancement, internal

#464 Enable step operators on kubeflow
  examples/airflow_local/run.py
  examples/airflow_local/run_schedule.py
  src/zenml/constants.py
  src/zenml/integrations/airflow/orchestrators/airflow_component.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/step_operators/entrypoint.py
  src/zenml/step_operators/step_executor_operator.py
  src/zenml/steps/base_step.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#460 Implementing the `explain` subcommand
  src/zenml/artifact_stores/__init__.py
  src/zenml/cli/__init__.py
  src/zenml/cli/stack_components.py
  src/zenml/container_registries/__init__.py
  src/zenml/metadata_stores/__init__.py
  src/zenml/orchestrators/__init__.py
Labels: enhancement, internal

#463 add sagemaker example
  examples/sagemaker_step_operator/README.md
  examples/sagemaker_step_operator/__init__.py
  examples/sagemaker_step_operator/requirements.txt
  examples/sagemaker_step_operator/setup.sh
  examples/sagemaker_step_operator/train_on_sagemaker.py
Labels: enhancement, internal

#466 Add docs for step operators Feature/eng 640 training resource docs
  docs/book/features/cloud-pipelines/cloud-pipelines.md
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
  docs/book/features/integrations.md
Labels: enhancement, internal

#468 Added quick mention of how to use dockerignore
  docs/book/guides/functional-api/deploy-to-production.md
Labels: documentation, internal

#472 Made rich traceback optional with ENV variable
  src/zenml/constants.py
  src/zenml/logger.py
Labels: enhancement, internal

#476 Fix `zenml stack describe` bug
  src/zenml/cli/utils.py
  src/zenml/steps/base_step.py
  tests/unit/cli/test_utils.py
Labels: bug, internal

#478 Secrets manager interface tests
  src/zenml/cli/secret.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  tests/unit/secrets_manager/test_local_secrets_manager.py
Labels: internal

#482 Add `examples` folder to linting script
  examples/airflow_local/run.py
  examples/airflow_local/run_schedule.py
  scripts/lint.sh
Labels: internal

#483 Fix profile handing in the Azure ML step operator
  src/zenml/integrations/azureml/__init__.py
  src/zenml/integrations/azureml/step_operators/azureml_step_operator.py
Labels: bug, internal

#480 Copy the entire stack configuration into containers
  src/zenml/config/global_config.py
  src/zenml/repository.py
  src/zenml/stack_stores/base_stack_store.py
  src/zenml/utils/docker_utils.py
Labels: bug, internal

#490 Add linting of examples to `pre-commit`
  .pre-commit-config.yaml
Labels: bug, internal

#488 Remove dev-specific entries in `.gitignore`
  .gitignore
Labels: internal

#487 Produce periodic mocked data for Segment/Mixpanel
  .github/workflows/mixpanel-test-data.yml
  scripts/mixpanel_filters_test.py
Labels: enhancement, internal
