Repository zenml-io/zenml, pull requests merged in 2022-12, with the labels that each got.

#1126 Skip kubeflow UI daemon provisioning if a hostname is configured
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
Labels: bug, internal

#1124 Update Neptune Example
  examples/neptune_tracking/README.md
  examples/neptune_tracking/assets/neptune_charts.png
  examples/neptune_tracking/assets/neptune_monitoring.png
  examples/neptune_tracking/assets/neptune_runs.png
  examples/neptune_tracking/pipelines/training_pipeline/training_pipeline.py
  examples/neptune_tracking/setup.sh
Labels: bug, internal

#1097 Add debugging guide to docs
  docs/book/assets/misc/doc_search_bar.png
  docs/book/assets/misc/opendev_search_bar.png
  docs/book/assets/misc/slack_search_bar.png
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
  docs/book/misc/debugging.md
  docs/book/toc.md
Labels: documentation, internal

#1127 Fix stack component attribute removal CLI command
  src/zenml/cli/__init__.py
  tests/unit/cli/test_stack_components.py
Labels: bug, internal

#1117 Improving error messages when fetching entitites
  .pyspelling-ignore-words
  src/zenml/cli/stack.py
  src/zenml/client.py
  src/zenml/exceptions.py
Labels: bug, internal

#1123 Introduce username and password to kubeflow for more native multi-tenant support
  .pyspelling-ignore-words
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: enhancement, internal

#1062 Add support for Label Studio OCR config generation
  docs/book/component-gallery/annotators/label-studio.md
  src/zenml/enums.py
  src/zenml/integrations/label_studio/label_config_generators/__init__.py
  src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py
  tests/unit/integrations/label_studio/label_config_generators/test_label_config_generators.py
Labels: enhancement

#1131 Misc doc updates
  docs/book/advanced-guide/practical/secrets-management.md
  docs/book/component-gallery/orchestrators/orchestrators.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/toc.md
Labels: documentation, internal

#1130 Fix Neptune run cleanup
  .pyspelling-ignore-words
  src/zenml/integrations/neptune/experiment_trackers/neptune_experiment_tracker.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
Labels: bug, internal

#1133 Remove stack extra from installation, enable re-running the quickstart
  docs/book/getting-started/installation/installation.md
  examples/quickstart/setup.sh
Labels: bug, internal

#1137 Secrets manager support to experiment trackers docs
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/experiment-trackers/neptune.md
  docs/book/component-gallery/experiment-trackers/wandb.md
Labels: documentation, internal

#1138 Secrets manager support to experiment trackers docs - backport
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/experiment-trackers/neptune.md
  docs/book/component-gallery/experiment-trackers/wandb.md
Labels: internal, backport

#1128 Updating the README files of our examples
  docs/book/component-gallery/artifact-stores/amazon-s3.md
  docs/book/component-gallery/artifact-stores/azure-blob-storage.md
  docs/book/component-gallery/artifact-stores/gcloud-gcs.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/getting-started/introduction.md
  docs/book/toc.md
  examples/README.md
  examples/airflow_orchestration/README.md
  examples/bentoml_deployment/README.md
  examples/cloud_secrets_manager/README.md
  examples/custom_code_deployment/README.md
  examples/evidently_drift_detection/README.md
  examples/facets_visualize_statistics/README.md
  examples/github_actions_orchestration/README.md
  examples/huggingface/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/label_studio_annotation/README.md
  examples/lightgbm/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/neural_prophet/README.md
  examples/pytorch/README.md
  examples/quickstart/README.md
  examples/scipy/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/README.md
  examples/xgboost/README.md
Labels: documentation, internal

#1141 Updating the README files of our examples (#1128)
  docs/book/component-gallery/artifact-stores/amazon-s3.md
  docs/book/component-gallery/artifact-stores/azure-blob-storage.md
  docs/book/component-gallery/artifact-stores/gcloud-gcs.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/getting-started/introduction.md
  docs/book/toc.md
  examples/README.md
  examples/airflow_orchestration/README.md
  examples/bentoml_deployment/README.md
  examples/cloud_secrets_manager/README.md
  examples/custom_code_deployment/README.md
  examples/evidently_drift_detection/README.md
  examples/facets_visualize_statistics/README.md
  examples/github_actions_orchestration/README.md
  examples/huggingface/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/label_studio_annotation/README.md
  examples/lightgbm/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_tracking/README.md
  examples/neural_prophet/README.md
  examples/pytorch/README.md
  examples/quickstart/README.md
  examples/scipy/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
  examples/whylogs_data_profiling/README.md
  examples/xgboost/README.md
Labels: internal, backport

#1134 Prevent running with local ZenStore and remote code execution
  docs/book/component-gallery/orchestrators/airflow.md
  examples/airflow_orchestration/README.md
  src/zenml/stack/stack.py
  tests/unit/stack/conftest.py
  tests/unit/stack/test_stack.py
Labels: bug, internal

#1139 RMTFX: Cleanup step run and artifact models
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/artifact_models.py
  src/zenml/models/step_run_models.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/lineage/node/artifact_node.py
  src/zenml/post_execution/step.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
  src/zenml/utils/materializer_utils.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_stores/migrations/versions/7834208cc3f6_artifact_project_scoping.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/project_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/conftest.py
  tests/unit/post_execution/test_artifact.py
  tests/unit/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1142 Fix Huggingface dataset materializer
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
Labels: bug, internal

#1140 Disallow alembic downgrades for 0.30.0 release
  src/zenml/zen_stores/migrations/versions/26b776ad583e_redesign_artifacts.py
  src/zenml/zen_stores/migrations/versions/6a28c4fd0ef2_add_caching_info.py
  src/zenml/zen_stores/migrations/versions/7834208cc3f6_artifact_project_scoping.py
Labels: internal

#1153 Fix Client flavor-related methods
  src/zenml/client.py
Labels: bug, internal

#1147 Replace User Password with Token in docker images
  src/zenml/config/global_config.py
  src/zenml/constants.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#1150 Remove zenml pipeline runs export / import CLI commands
  src/zenml/cli/pipeline.py
  src/zenml/client.py
  tests/unit/cli/test_pipeline.py
Labels: internal, breaking-change

#1156 Add Neptune exp tracker into flavors table
  docs/book/component-gallery/experiment-trackers/experiment-trackers.md
Labels: internal

#1160 Display correct name when updating a stack component
  src/zenml/cli/stack_components.py
Labels: bug, internal

#1152 Update mysql database creation
  .pyspelling-ignore-words
  src/zenml/config/step_configurations.py
  src/zenml/integrations/neural_prophet/__init__.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#1162 Adding component conditions to experiment tracker examples and adding to the environmental variable docs
  docs/book/guidelines/system-environmental-variables.md
  examples/mlflow_deployment/steps/tf_evaluator/tf_evaluator_step.py
  examples/mlflow_deployment/steps/tf_trainer/tf_trainer_step.py
  examples/mlflow_tracking/steps/evaluator/evaluator_step.py
  examples/mlflow_tracking/steps/trainer/trainer_step.py
  examples/neptune_tracking/steps/evaluator/evaluator_step.py
  examples/neptune_tracking/steps/trainer/trainer_step.py
  examples/quickstart/steps/trainers.py
  examples/slack_alert/steps/trainer.py
  examples/wandb_tracking/steps/evaluator/evaluator_step.py
  examples/wandb_tracking/steps/trainer/trainer_step.py
Labels: documentation, internal

#1163 Increase dependency range for protobuf
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/mlflow/__init__.py
Labels: enhancement, internal

#1158 Scheduling documentation
  docs/book/advanced-guide/pipelines/scheduling-runs.md
  docs/book/toc.md
Labels: documentation, internal

#1148 Adding scheduling for Vertex Pipelines
  .pyspelling-ignore-words
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  pyproject.toml
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/google_cloud_function.py
  src/zenml/integrations/gcp/google_cloud_scheduler.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/__init__.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/main.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/requirements.txt
Labels: enhancement, internal

#1165 Fix alembic migration for sqlite<3.25
  src/zenml/zen_stores/migrations/versions/26b776ad583e_redesign_artifacts.py
  src/zenml/zen_stores/migrations/versions/7834208cc3f6_artifact_project_scoping.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, breaking-change

#1167 Fix installation instructions in readme and docs
  README.md
  docs/book/getting-started/installation/installation.md
Labels: bug, internal

#1168 Fix installation instructions in readme and docs (#1167)
  README.md
  docs/book/getting-started/installation/installation.md
Labels: internal, backport

#1169 Fix broken TOC for scheduling docs
  docs/book/toc.md
Labels: bug, documentation, internal

#1170 Fix docs TOC (#1169)
  docs/book/toc.md
Labels: bug, documentation, internal

#1144 Check if all ZenML server dependencies are installed for local zenml deployment using `zenml up`
  pyproject.toml
  src/zenml/models/user_models.py
  src/zenml/zen_server/deploy/local/local_provider.py
Labels: enhancement, internal

#1173 Persist the server ID in the database
  .pyspelling-ignore-words
  docs/book/getting-started/deploying-zenml/docker.md
  scripts/lint.sh
  src/zenml/cli/server.py
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/terraform/providers/terraform_provider.py
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  src/zenml/zen_stores/migrations/versions/7e4a481d17f7_add_identity_table.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/identity_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#1179 Tiny docs improvements
  docs/book/advanced-guide/pipelines/settings.md
  docs/book/guidelines/migration-zero-twenty.md
  docs/book/starter-guide/pipelines/parameters-and-caching.md
  docs/book/toc.md
Labels: documentation, internal

#1174 Changing some interactions with analytics fields
  src/zenml/models/base_models.py
  src/zenml/models/component_models.py
  src/zenml/models/constants.py
  src/zenml/models/flavor_models.py
  src/zenml/models/pipeline_models.py
  src/zenml/models/project_models.py
  src/zenml/models/role_models.py
  src/zenml/models/stack_models.py
  src/zenml/models/team_models.py
  src/zenml/models/user_models.py
  src/zenml/utils/analytics_utils.py
Labels: bug, internal

#1178 Fix `PyTorchDataLoaderMaterializer` for older torch versions
  src/zenml/integrations/pytorch/materializers/pytorch_dataloader_materializer.py
Labels: bug, internal

#1171 Fixing the error messages when fetching entities
  src/zenml/cli/project.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/client.py
Labels: bug, internal

#1161 Moved the active_user property onto the client, implemented get_myself as zenstore method
  .pyspelling-ignore-words
  pyproject.toml
  src/zenml/cli/user_management.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/role_schemas.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/conftest.py
  tests/integration/functional/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1183 Bugfix/bump evidently version
  src/zenml/integrations/evidently/__init__.py
Labels: bug, internal

#1181 Alembic migration to update size of flavor config schema
  src/zenml/zen_stores/migrations/versions/248dfd320b68_update_size_of_flavor_config_schema.py
Labels: bug, internal

#1164 Deleting pipeline runs and artifacts
  src/zenml/cli/__init__.py
  src/zenml/cli/artifact.py
  src/zenml/cli/pipeline.py
  src/zenml/client.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/cli/test_artifact.py
  tests/integration/functional/cli/test_pipeline.py
  tests/integration/functional/zen_stores/conftest.py
  tests/integration/functional/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1192 Adding exception tracking to `zeml init`
  src/zenml/client.py
Labels: bug, internal

#1186 Prevent crashes during Airflow server forking on MacOS
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
Labels: bug, internal

#1197 add alpha as server deployment type
  src/zenml/models/server_models.py
Labels: enhancement, internal

#1195 Bugfix for custom flavor registration
  src/zenml/client.py
Labels: bug, internal

#1200 Tests for `uuid_utils`
  src/zenml/utils/uuid_utils.py
  tests/unit/utils/test_uuid_utils.py
Labels: internal, tests

#1177 Sagemaker orchestrator integration
  .pyspelling-ignore-words
  docs/book/component-gallery/orchestrators/gcloud-vertexai.md
  docs/book/component-gallery/orchestrators/orchestrators.md
  docs/book/component-gallery/orchestrators/sagemaker.md
  docs/book/toc.md
  examples/sagemaker_orchestration/README.md
  examples/sagemaker_orchestration/__init__.py
  examples/sagemaker_orchestration/assets/sagemaker0.png
  examples/sagemaker_orchestration/assets/sagemaker1.png
  examples/sagemaker_orchestration/assets/sagemaker2.png
  examples/sagemaker_orchestration/assets/sagemaker3.png
  examples/sagemaker_orchestration/assets/sagemaker4.png
  examples/vertex_ai_orchestration/README.md
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/flavors/__init__.py
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/__init__.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/s3/__init__.py
  src/zenml/orchestrators/step_launcher.py
Labels: enhancement, internal, breaking-change

#1193 Fix Pandas Materializer Index
  src/zenml/materializers/pandas_materializer.py
  tests/unit/materializers/test_pandas_materializer.py
Labels: bug, internal

#1188 Add support for deploying custom stack recipes using the ZenML CLI
  src/zenml/cli/stack_recipes.py
Labels: enhancement, internal

#1176 Add cloud CI environments
  .dockerignore
  .github/workflows/integration-test.yml
  docs/book/getting-started/deploying-zenml/cli.md
  src/zenml/cli/example.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/kubeflow/__init__.py
  src/zenml/integrations/seldon/__init__.py
  src/zenml/integrations/tekton/__init__.py
  src/zenml/models/constants.py
  src/zenml/zen_stores/migrations/versions/248dfd320b68_update_size_of_flavor_config_schema.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  tests/harness/cfg/cloud/aws/deployments.yaml
  tests/harness/cfg/cloud/aws/environments.yaml
  tests/harness/cfg/cloud/aws/requirements.yaml
  tests/harness/cfg/cloud/gcp/deployments.yaml
  tests/harness/cfg/cloud/gcp/environments.yaml
  tests/harness/cfg/cloud/gcp/requirements.yaml
  tests/harness/cfg/cloud/requirements.yaml
  tests/harness/cfg/environments.yaml
  tests/harness/cfg/tests.yaml
  tests/harness/deployment/base.py
  tests/harness/model/environment.py
  tests/harness/model/requirements.py
  tests/harness/model/secret.py
  tests/integration/examples/test_step_operator_remote_training.py
  tests/integration/examples/utils.py
Labels: enhancement, internal

#1203 Fix project scoping for artifact list through ZenServer
  src/zenml/zen_server/routers/artifacts_endpoints.py
Labels: bug, internal
