Repository zenml-io/zenml, pull requests merged in 2022-02, with the labels that each got.

#383 Sort requirements to improve docker build caching
  src/zenml/integrations/kubeflow/docker_utils.py
Labels: internal

#382 Make sure the s3 artifact store is registered when the integration is activated
  src/zenml/integrations/aws/artifact_stores/__init__.py
Labels: internal

#385 Reset _has_been_called to False ahead of pipeline.connect
  src/zenml/pipelines/base_pipeline.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: bug, internal

#366 Fix local airflow example
  examples/airflow_local/README.md
  examples/airflow_local/setup.sh
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
Labels: internal

#380 Improve and extend base materializer error messages
  examples/drift_detection/run.py
  src/zenml/exceptions.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/default_materializer_registry.py
  src/zenml/steps/base_step.py
  tests/unit/materializers/test_base_materializer.py
Labels: internal

#389 Windows CI issue
  examples/mlflow_tracking/requirements.txt
  examples/not_so_quickstart/setup.sh
  src/zenml/integrations/tensorflow/__init__.py
Labels: internal

#355 Add the ability to attach custom properties to the Metadata Store
  examples/mlflow_tracking/pipeline.py
  examples/mlflow_tracking/run.py
  examples/mlflow_tracking/run_schedule.py
  src/zenml/enums.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/orchestrators/context_utils.py
  src/zenml/orchestrators/local/local_dag_runner.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/stack/stack.py
  tests/unit/orchestrators/test_context_utils.py
Labels: internal

#386 Handle case when return values do not match output
  src/zenml/steps/utils.py
  tests/unit/steps/test_base_step.py
Labels: bug, internal

#387 Quickstart code in docs fixed
  docs/book/introduction/quickstart-guide.md
Labels: internal

#394 Create todo issues with separate issue type
  .github/workflows/update_todos.yml
Labels: internal

#381 Log that steps are cached while running pipeline
  .gitignore
  src/zenml/orchestrators/utils.py
  tests/unit/orchestrators/test_utils.py
Labels: internal

#391 Schedule added to context for all orchestrators
  examples/airflow_local/run.py
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/orchestrators/context_utils.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/pipelines/base_pipeline.py
Labels: internal

#395 Fix lineage and statistics examples
  examples/lineage/run.py
  examples/statistics/run.py
Labels: internal

#398 Updated notebook for quickstart
  examples/quickstart/README.md
  examples/quickstart/quickstart.ipynb
Labels: internal

#396 Update tensorflow base image
  docker/cuda-dev.Dockerfile
  docker/cuda.Dockerfile
Labels: internal

#400 Add cloud specific deployment guide + refactoring
  docs/book/features/cloud-pipelines/cloud-pipelines.md
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
  docs/book/guides/functional-api/deploy-to-production.md
Labels: internal

#401 add cloud sub page to toc.md
  docs/book/toc.md
Labels: internal

#403 Backport/eng 486 cloud guide
  docs/book/features/cloud-pipelines/cloud-pipelines.md
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
  docs/book/guides/functional-api/deploy-to-production.md
  docs/book/toc.md
Labels: internal

#404 Updated notebook for quickstart (#398)
  examples/quickstart/README.md
  examples/quickstart/quickstart.ipynb
Labels: internal, backport

#390 Bugfix for workflows failing due to modules not being found
  src/zenml/post_execution/artifact.py
  src/zenml/utils/source_utils.py
  tests/unit/materializers/test_base_materializer.py
  tests/unit/post_execution/test_artifact.py
  tests/unit/utils/test_source_utils.py
Labels: internal

#406 Improve github workflows
  .github/branch-labels.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/pull_request.yml
  .github/workflows/team_labeler.yml
  .github/workflows/testing.yml
Labels: enhancement, internal

#414 Add plausible script to docs.zenml.io pages
  docs/_templates/layout.html
Labels: documentation, enhancement, internal

#413 add orchestrator and acr docs
  docs/book/assets/cloud/workflow-configmap.png
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
Labels: internal

#410 Update quickstart in docs to conform to examples
  docs/book/introduction/quickstart-guide.md
Labels: internal

#411 Updated PR template with some more details
  .github/pull_request_template.md
Labels: internal

#412 Bugfix on the CLI to work without a git installation
  src/zenml/cli/example.py
  src/zenml/exceptions.py
Labels: bug, internal

#419 Adding an info message on Windows if there is no application associated to .sh files
  src/zenml/cli/example.py
  src/zenml/orchestrators/local/local_orchestrator.py
Labels: bug, internal

#416 Catch `matplotlib` crash when running IPython in terminal
  src/zenml/environment.py
  tests/unit/test_environment.py
Labels: bug, internal

#420 Automatically activate integrations when unable to find stack component
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/stack/stack_component_class_registry.py
  tests/unit/stack/test_stack_component_class_registry.py
Labels: bug, internal

#423 Prepare integration tests on kubeflow
  .github/workflows/kubeflow.yml
  .github/workflows/testing.yml
  .gitignore
  examples/airflow_local/setup.sh
  examples/kubeflow/setup.sh
  examples/not_so_quickstart/run.py
  examples/run_example.sh
  src/zenml/cli/example.py
  src/zenml/cli/utils.py
  src/zenml/integrations/evidently/visualizers/evidently_visualizer.py
  src/zenml/integrations/kubeflow/docker_utils.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  tests/integration/conftest.py
  tests/integration/example_validations.py
  tests/integration/test_examples.py
Labels: enhancement, internal

#425 Add concepts back into glossary
  docs/book/reference/glossary.md
Labels: documentation, internal

#426 Fix httplib to 0.19 and pyparsing to 2.4
  pyproject.toml
Labels: bug, internal

#397 Wrap context serialization in try blocks
  src/zenml/integrations/airflow/orchestrators/airflow_dag_runner.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_dag_runner.py
  src/zenml/orchestrators/context_utils.py
  src/zenml/orchestrators/local/local_orchestrator.py
  tests/unit/materializers/test_base_materializer.py
  tests/unit/orchestrators/test_context_utils.py
Labels: internal

#429 Track stack configuration when registering and running a pipeline
  src/zenml/pipelines/base_pipeline.py
  src/zenml/repository.py
Labels: enhancement, internal

#415 MLflow deployment integration
  docs/book/assets/architecture.png
  docs/book/features/continous-training-and-deployment.md
  docs/book/features/integrations.md
  docs/book/introduction/core-concepts.md
  docs/book/reference/glossary.md
  docs/book/toc.md
  examples/mlflow_deployment/README.md
  examples/mlflow_deployment/__init__.py
  examples/mlflow_deployment/pipeline.py
  examples/mlflow_deployment/requirements.txt
  examples/mlflow_deployment/run.py
  examples/mlflow_deployment/setup.sh
  examples/run_example.sh
  src/zenml/artifacts/__init__.py
  src/zenml/artifacts/service_artifact.py
  src/zenml/environment.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/mlflow/mlflow_environment.py
  src/zenml/integrations/mlflow/mlflow_step_decorator.py
  src/zenml/integrations/mlflow/mlflow_utils.py
  src/zenml/integrations/mlflow/services/__init__.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/mlflow/steps/__init__.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/materializers/__init__.py
  src/zenml/materializers/service_materializer.py
  src/zenml/services/__init__.py
  src/zenml/services/local/__init__.py
  src/zenml/services/local/local_daemon_entrypoint.py
  src/zenml/services/local/local_service.py
  src/zenml/services/local/local_service_endpoint.py
  src/zenml/services/service.py
  src/zenml/services/service_endpoint.py
  src/zenml/services/service_monitor.py
  src/zenml/services/service_registry.py
  src/zenml/services/service_status.py
  src/zenml/services/service_type.py
  src/zenml/services/utils.py
  src/zenml/utils/daemon.py
  src/zenml/utils/networking_utils.py
  src/zenml/utils/source_utils.py
  src/zenml/utils/typed_model.py
  src/zenml/utils/yaml_utils.py
  tests/integration/example_validations.py
  tests/integration/test_examples.py
Labels: enhancement, internal

#432 fix typo
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
Labels: documentation, internal

#433 fix typo in cloud guide (#432)
  docs/book/features/cloud-pipelines/guide-aws-gcp-azure.md
Labels: internal, backport

#436 Remove tabulate dependency (replaced by rich)
  pyproject.toml
Labels: enhancement, internal

#428 Fix potential issue with local integration tests
  tests/integration/test_examples.py
Labels: bug, internal
