Repository zenml-io/zenml, pull requests merged in 2022-04, with the labels that each got.

#492 enable and disable cache from runtime config
  src/zenml/orchestrators/utils.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/step.py
  src/zenml/stack/stack.py
Labels: enhancement, internal

#378 Parallelise our test suite and make errors more readable
  pyproject.toml
  scripts/test-coverage-xml.sh
Labels: internal

#493 bugfix/optional-secrets-manager
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/utils/docker_utils.py
  tests/unit/secrets_manager/test_local_secrets_manager.py
Labels: bug, internal

#501 Quick fix for copying folders
  src/zenml/io/utils.py
Labels: bug, internal

#507 Fix datetime test / bug
  tests/unit/cli/test_utils.py
Labels: bug, internal

#515 Fix typos
  examples/huggingface/README.md
Labels: documentation, internal

#513 Bugfix/hypothesis given doesnt work with fixture
  pyproject.toml
  tests/unit/io/test_fileio.py
Labels: bug, internal

#514 Bug: fix long Kubernetes labels in Seldon deployments
  src/zenml/integrations/seldon/seldon_client.py
Labels: bug, internal

#516 Change prediction_uri to prediction_url in MLflow deployer
  examples/mlflow_deployment/run.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
Labels: enhancement, internal

#517 Simplify HuggingFace Integration
  docs/book/features/integrations.md
  examples/huggingface/README.md
  examples/huggingface/__init__.py
  examples/huggingface/run_pipeline.py
  examples/huggingface/sequence_classification.py
  examples/huggingface/token_classification.py
  pyproject.toml
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
  src/zenml/integrations/neural_prophet/materializers/neural_prophet_materializer.py
Labels: enhancement, internal

#518 Weights & Biases Basic Integration
  .gitignore
  docs/book/features/integrations.md
  examples/wandb_tracking/README.md
  examples/wandb_tracking/__init__.py
  examples/wandb_tracking/assets/wandb_charts_results.png
  examples/wandb_tracking/assets/wandb_table_results.png
  examples/wandb_tracking/pipeline.py
  examples/wandb_tracking/run.py
  examples/wandb_tracking/setup.sh
  pyproject.toml
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/wandb/__init__.py
  src/zenml/integrations/wandb/wandb_environment.py
  src/zenml/integrations/wandb/wandb_step_decorator.py
Labels: enhancement, internal

#524 Fix caching & `mypy` errors
  .github/actions/setup_environment/action.yml
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
  src/zenml/integrations/wandb/wandb_environment.py
Labels: bug, internal

#508 Switch unit test from local_daemon to multiprocessing
  src/zenml/constants.py
  src/zenml/zen_service/zen_service.py
  src/zenml/zen_service/zen_service_api.py
  tests/unit/stack_stores/test_stack_stores.py
Labels: bug, internal

#525 Change Pytorch materializer to support remote storage
  src/zenml/integrations/pytorch/materializers/pytorch_materializer.py
Labels: bug, internal

#527 Remove TODO from Feature Store `init` docstring
  src/zenml/feature_stores/__init__.py
Labels: documentation, internal

#531 Replaced old local_* logic
  docs/book/guides/functional-api/deploy-to-production.md
  examples/airflow_local/README.md
  examples/airflow_local/setup.sh
  examples/kubeflow/README.md
  examples/kubeflow/ZenML Walkthrough Kubeflow Pipelines.ipynb
  examples/kubeflow/setup.sh
  examples/step_operator_remote_training/README.md
Labels: internal

#533 capitalize aws username in ECR docs
  docs/book/features/guide-aws-gcp-azure.md
Labels: documentation, internal

#537 Build docker base images quicker after release
  cloudbuild.yaml
Labels: enhancement, internal

#532 Allow configuration of s3fs
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/integrations/azure/artifact_stores/azure_artifact_store.py
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
Labels: enhancement, internal

#536 Update contributing and fix ci badge to main
  CONTRIBUTING.md
  README.md
Labels: internal

#539 Added fa9r to .github/teams.yml.
  .github/teams.yml
Labels: internal

#529 Secret Manager improvements and Seldon Core secret passing
  examples/mlflow_deployment/run.py
  examples/seldon_deployment/README.md
  examples/seldon_deployment/run.py
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/cli/secret.py
  src/zenml/cli/utils.py
  src/zenml/enums.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/secret_schemas/aws_secret_schema.py
  src/zenml/integrations/aws/secrets_managers/aws_secrets_manager.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_component.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/seldon/__init__.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/integrations/seldon/secret_schemas/__init__.py
  src/zenml/integrations/seldon/secret_schemas/secret_schemas.py
  src/zenml/integrations/seldon/seldon_client.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
  src/zenml/secret/__init__.py
  src/zenml/secret/arbitrary_secret_schema.py
  src/zenml/secret/base_secret.py
  src/zenml/secret/secret_schema_class_registry.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/services/local/local_service.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/secrets_manager_utils.py
Labels: enhancement, internal

#500 User management
  docs/book/features/profiles.md
  src/zenml/cli/__init__.py
  src/zenml/cli/config.py
  src/zenml/cli/service.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/config/profile_config.py
  src/zenml/constants.py
  src/zenml/exceptions.py
  src/zenml/repository.py
  src/zenml/stack_stores/local_stack_store.py
  src/zenml/stack_stores/rest_stack_store.py
  src/zenml/stack_stores/sql_stack_store.py
  src/zenml/zen_service/zen_service.py
  src/zenml/zen_service/zen_service_api.py
  src/zenml/zen_stores/__init__.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/models/__init__.py
  src/zenml/zen_stores/models/stack_component_wrapper.py
  src/zenml/zen_stores/models/stack_wrapper.py
  src/zenml/zen_stores/models/user_management_models.py
  src/zenml/zen_stores/models/zen_store_model.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/stack_stores/test_stack_stores.py
  tests/unit/zen_service/test_zen_service.py
  tests/unit/zen_stores/__init__.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#497 Update stack and stack components via the CLI
  docs/book/support/usage-analytics.md
  scripts/test-coverage-xml.sh
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/constants.py
  src/zenml/repository.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_service/zen_service_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/local_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/cli/test_stack.py
  tests/unit/cli/test_stack_components.py
  tests/unit/test_repository.py
  tests/unit/zen_stores/test_zen_stores.py
Labels: enhancement, internal

#542 Fix the Kubeflow metadata store and other stack management improvements
  src/zenml/cli/stack_components.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/integrations/kubeflow/metadata_stores/kubeflow_metadata_store.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/local_deployment_utils.py
  src/zenml/integrations/mlflow/model_deployers/mlflow_model_deployer.py
  src/zenml/integrations/sagemaker/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/vertex/step_operators/vertex_step_operator.py
  src/zenml/metadata_stores/base_metadata_store.py
  src/zenml/metadata_stores/mysql_metadata_store.py
  src/zenml/metadata_stores/sqlite_metadata_store.py
  src/zenml/repository.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/stack/stack_validator.py
  src/zenml/utils/daemon.py
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
  tests/unit/stack/conftest.py
  tests/unit/stack/test_stack.py
  tests/unit/stack/test_stack_validator.py
Labels: bug, internal

#530 Experiment tracker stack components
  .gitignore
  examples/mlflow_deployment/README.md
  examples/mlflow_deployment/run.py
  examples/mlflow_deployment/setup.sh
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/run.py
  examples/mlflow_tracking/run_schedule.py
  examples/mlflow_tracking/setup.sh
  examples/wandb_tracking/README.md
  examples/wandb_tracking/assets/wandb_grouped.png
  examples/wandb_tracking/assets/wandb_runs_ungrouped.png
  examples/wandb_tracking/pipeline.py
  examples/wandb_tracking/setup.sh
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/enums.py
  src/zenml/experiment_trackers/__init__.py
  src/zenml/experiment_trackers/base_experiment_tracker.py
  src/zenml/integrations/airflow/orchestrators/airflow_component.py
  src/zenml/integrations/kubeflow/container_entrypoint.py
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/mlflow/experiment_trackers/__init__.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/mlflow_environment.py
  src/zenml/integrations/mlflow/mlflow_step_decorator.py
  src/zenml/integrations/mlflow/mlflow_utils.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/wandb/__init__.py
  src/zenml/integrations/wandb/experiment_trackers/__init__.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/wandb/wandb_environment.py
  src/zenml/integrations/wandb/wandb_step_decorator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/step_operators/entrypoint.py
  tests/integration/example_validations.py
  tests/integration/test_examples.py
Labels: enhancement, internal

#549 Fix some inconsistencies with CLI
  src/zenml/cli/config.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/served_models.py
  src/zenml/cli/service.py
  src/zenml/cli/version.py
Labels: enhancement, internal

#548 Add `stack delete` confirmation prompt
  src/zenml/cli/stack.py
  tests/unit/cli/test_stack.py
Labels: enhancement, internal

#550 Update 0.7.3 release notes in RELEASE_NOTES.md.
  RELEASE_NOTES.md
Labels: internal
