Repository zenml-io/zenml, pull requests merged in 2023-08, with the labels that each got.

#1726 Fix bug in service connector, Closes #1720
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug

#1722 Document the namespace and service account k8s orchestrator settings
  docs/book/user-guide/component-guide/orchestrators/kubernetes.md
Labels: documentation, internal

#1728 Update custom orchestrator guide
  docs/book/user-guide/component-guide/orchestrators/custom.md
Labels: documentation, internal

#1729 Improve error message when passing non-json serializable parameter
  docs/book/user-guide/component-guide/orchestrators/custom.md
  src/zenml/steps/entrypoint_function_utils.py
  tests/unit/steps/test_base_step_new.py
Labels: enhancement, internal

#1730 Bump `ruff` to 0.0.282
  pyproject.toml
Labels: internal, dependencies

#1708 bump `MLflow` to 2.5.0
  src/zenml/integrations/mlflow/__init__.py
Labels: enhancement, internal

#1734 Add Error Handling for Empty Pipelines
  src/zenml/config/compiler.py
Labels: bug, internal

#1736 Add Error Handling for Empty Pipelines
  src/zenml/config/compiler.py
  tests/unit/config/test_compiler.py
  tests/unit/conftest.py
  tests/unit/conftest_new.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/pipelines/test_build_utils.py
  tests/unit/stack/test_stack.py
Labels: bug, internal

#1731 Revisit `init --template` CLI for new templates
  .github/actions/setup_environment/action.yml
  docs/book/toc.md
  docs/book/user-guide/starter-guide/starter-guide.md
  docs/book/user-guide/starter-guide/using-project-templates.md
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  tests/integration/functional/cli/test_base.py
Labels: enhancement, internal, breaking-change

#1702 Add Python 3.11 Support
  .dockerignore
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint-unit-test.yml
  README.md
  docs/book/getting-started/installation.md
  pyproject.toml
  release-cloudbuild.yaml
  scripts/install-zenml-dev.sh
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/registry.py
  src/zenml/integrations/tensorboard/__init__.py
  src/zenml/integrations/tensorflow/__init__.py
  tests/integration/examples/test_tensorflow.py
  tests/unit/conftest.py
  tests/unit/integrations/gcp/artifact_stores/test_gcp_artifact_store.py
  tests/unit/integrations/gcp/image_builders/test_gcp_image_builder.py
  tests/unit/integrations/gcp/orchestrators/test_vertex_orchestrator.py
  tests/unit/integrations/kaniko/image_builders/test_kaniko_image_builder.py
  tests/unit/integrations/kserve/__init__.py
  tests/unit/integrations/kserve/test_kserve_step_utils.py
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
  tests/unit/integrations/kubeflow/test_utils.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
  tests/unit/integrations/mlflow/experiment_trackers/test_mlflow_experiment_tracker.py
Labels: enhancement, internal, dependencies

#1739 Bugfix for identify calls with empty email strings
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/routers/users_endpoints.py
Labels: bug, internal

#1751 Add cloud architecture docs
  docs/book/.gitbook/assets/cloud_architecture_diagram.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2a.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2b.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2c.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_3.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_4.png
  docs/book/deploying-zenml/zenml-cloud/cloud-system-architecture.md
  docs/book/deploying-zenml/zenml-cloud/zenml-cloud.md
  docs/book/toc.md
Labels: documentation, internal

#1754 Update docs/docstrings following `mlstacks` repo name change
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-zenml-cli.md
  docs/book/stacks-and-components/component-guide/model-deployers/seldon.md
  docs/book/stacks-and-components/component-guide/orchestrators/airflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/kubeflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/sagemaker.md
  docs/book/stacks-and-components/component-guide/orchestrators/vertex.md
  docs/book/stacks-and-components/stack-deployment/contribute-flavors-or-components.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-component.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-using-stack-recipes.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack_recipes.py
  src/zenml/recipes/stack_recipe_service.py
Labels: documentation, internal

#1757 Update Cloud deployment scenarios
  docs/book/.gitbook/assets/cloud_architecture_scenario_3.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_3a.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_3b.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_4.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_5.png
  docs/book/deploying-zenml/zenml-cloud/cloud-system-architecture.md
Labels: internal

#1748 Fixing the logging message regarding caching
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/step_launcher.py
Labels: bug, internal

#1733 Improvements to the step logs storage functionality
  docs/book/.gitbook/assets/zenml_step_logs.png
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  src/zenml/constants.py
  src/zenml/logging/__init__.py
  src/zenml/logging/step_logging.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#1760 Fix `qemu`/`colima` Github Actions bug
  .github/workflows/integration-test.yml
Labels: bug, internal

#1762 Bump `ruff` and `mypy`
  pyproject.toml
  src/zenml/cli/utils.py
  src/zenml/integrations/evidently/materializers/evidently_profile_materializer.py
  tests/unit/steps/test_base_step.py
  tests/unit/steps/test_base_step_new.py
Labels: internal, dependencies

#1745 Add Template Testing in Core
  .github/workflows/ci.yml
  .github/workflows/templates-test.yml
  pyproject.toml
  src/zenml/cli/base.py
Labels: enhancement, internal, tests

#1753 Removing analytics v1 and optimizing v2
  docs/book/user-guide/advanced-guide/environment-management/global-settings-of-zenml.md
  pyproject.toml
  src/zenml/analytics/__init__.py
  src/zenml/analytics/client.py
  src/zenml/analytics/consumer.py
  src/zenml/analytics/context.py
  src/zenml/analytics/enums.py
  src/zenml/analytics/models.py
  src/zenml/analytics/request.py
  src/zenml/analytics/utils.py
  src/zenml/cli/base.py
  src/zenml/cli/config.py
  src/zenml/cli/hub.py
  src/zenml/cli/integration.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/stack_recipes.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/models/base_models.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/post_execution/pipeline.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/stack/flavor_registry.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/base_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/rest_secrets_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/conftest.py
  tests/unit/utils/test_analytics_utils.py
Labels: enhancement, internal

#1758 Update publish script to take a token
  scripts/publish.sh
Labels: bug, internal, fix

#1764 Update variable name for release publication token
  scripts/publish.sh
Labels: internal, fix

#1763 Lock `MYSQL` Database during DB migrations
  src/zenml/zen_stores/migrations/alembic.py
Labels: bug, internal

#1721 `mlstacks` integration (and deprecation of old deployment logic)
  .github/actions/setup_environment/action.yml
  .gitignore
  docs/book/deploying-zenml/zenml-self-hosted/manage-the-deployed-services/troubleshoot-stack-components.md
  docs/book/introduction.md
  docs/book/stacks-and-components/component-guide/artifact-stores/gcp.md
  docs/book/stacks-and-components/component-guide/artifact-stores/s3.md
  docs/book/stacks-and-components/component-guide/container-registries/aws.md
  docs/book/stacks-and-components/component-guide/container-registries/gcp.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/mlflow.md
  docs/book/stacks-and-components/component-guide/model-deployers/seldon.md
  docs/book/stacks-and-components/component-guide/orchestrators/airflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/kubeflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/kubernetes.md
  docs/book/stacks-and-components/component-guide/orchestrators/sagemaker.md
  docs/book/stacks-and-components/component-guide/orchestrators/tekton.md
  docs/book/stacks-and-components/component-guide/step-operators/sagemaker.md
  docs/book/stacks-and-components/stack-deployment/contribute-flavors-or-components.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-component.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-using-stack-recipes.md
  docs/book/stacks-and-components/stack-deployment/stack-deployment.md
  docs/book/toc.md
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/analytics/enums.py
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/stack_recipes.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/models/component_models.py
  src/zenml/models/stack_models.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/utils/mlstacks_utils.py
  src/zenml/zen_stores/migrations/README.md
  src/zenml/zen_stores/migrations/versions/e1d66d91a099_add_stack_and_component_spec_paths_to_.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_example.py
  tests/integration/functional/cli/test_stack_recipes.py
  tests/unit/utils/test_mlstacks_utils.py
Labels: documentation, enhancement, internal, dependencies, tests, breaking-change

#1768 Fixing the publish workflow
  .github/workflows/publish_to_pypi.yml
Labels: bug, internal

#1741 Upgrade typing extensions within api docs build workflow
  scripts/generate-docs.sh
Labels: bug, internal

#1770 Remove pinned `zenml` version specified in TOC for SDK docs
  docs/book/toc.md
Labels: documentation, internal

#1774 Modified the track metadata for the opt-in event
  src/zenml/analytics/utils.py
Labels: bug, internal

#1773 Check alembic branch divergence in CI
  .github/workflows/lint-unit-test.yml
  scripts/check-alembic-branches.sh
Labels: enhancement, internal
