Repository zenml-io/zenml, pull requests merged in 2023-03, with the labels that each got.

#1365 Small clarifications for slack alerter
  docs/book/component-gallery/alerters/slack.md
  examples/slack_alert/README.md
  examples/slack_alert/assets/slack_token.jpg
Labels: documentation, internal

#1335 update Neptune integration for v1.0 compatibility
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
Labels: dependencies

#1255 Integrations conditional requirements
  src/zenml/cli/utils.py
  src/zenml/enums.py
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/integration.py
  src/zenml/integrations/pytorch/__init__.py
  src/zenml/integrations/registry.py
  src/zenml/integrations/tensorflow/__init__.py
  src/zenml/integrations/utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal

#1363 Fix fetching versioned pipelines in post execution
  src/zenml/pipelines/base_pipeline.py
  src/zenml/post_execution/pipeline.py
  tests/unit/post_execution/test_pipeline.py
Labels: bug, internal

#1367 Load artifact store before loading artifact to register filesystem
  src/zenml/utils/materializer_utils.py
  tests/unit/utils/test_materializer_utils.py
Labels: bug, internal

#1346 Remove poetry from CI
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/setup-python-environment.yml
  .github/workflows/unit-test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/README.md
  pyproject.toml
  src/zenml/README.md
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal, dependencies

#1366 GCP backend for Secrets Store
  .pyspelling-ignore-words
  docker/base.Dockerfile
  docker/zenml-server-dev.Dockerfile
  pyproject.toml
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  tests/integration/functional/cli/utils.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/test_secrets_store.py
Labels: enhancement, internal

#1370 Fix Sagemaker example readme
  examples/sagemaker_orchestration/README.md
Labels: documentation, internal

#1372 Fix neptune linting error on `develop` (and bump ruff)
  pyproject.toml
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
Labels: bug, internal, dependencies

#1371 Add pydantic materializer
  src/zenml/materializers/__init__.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/pydantic_materializer.py
  tests/unit/materializers/test_pydantic_materializer.py
Labels: enhancement, internal

#1368 Registering GIFs added
  docs/book/assets/starter_guide/stacks/03_register_stack_component.gif
  docs/book/assets/starter_guide/stacks/04_register_stack.gif
  docs/book/starter-guide/stacks/registering-stacks.md
Labels: documentation, internal

#1347 Refresh CLI cheat sheet
  docs/book/assets/zenml_cheat_sheet.pdf
  docs/book/assets/zenml_cheat_sheet.png
Labels: documentation, internal

#1337 Add dependency resolution docs
  docs/book/misc/handling-dependencies.md
  docs/book/toc.md
Labels: documentation, internal

#1353 [BUGFIX] Fix error while using an existing SQL server with GCP ZenServer
  src/zenml/zen_server/deploy/terraform/recipes/gcp/sql.tf
Labels: internal

#1310 Update step name assignment with the parameter name
  examples/mlflow_deployment/run.py
  src/zenml/config/step_run_info.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
  src/zenml/steps/step_environment.py
  tests/unit/orchestrators/test_step_runner.py
  tests/unit/test_environment.py
Labels: bug, internal, breaking-change

#1351 Copy huggingface data directory to local before loading in materializers
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
Labels: bug

#1369 Update huggingface token classification example
  examples/huggingface/README.md
  examples/huggingface/run.py
  examples/huggingface/steps/evaluation/sequence_evaluation_step.py
  examples/huggingface/steps/training/sequence_training_step.py
Labels: bug, documentation, internal

#1376 Use the most specialized materializer based on MRO
  .pyspelling-ignore-words
  src/zenml/materializers/default_materializer_registry.py
  tests/unit/materializers/test_default_materializer_registry.py
Labels: bug, internal

#1373 Update Kserve to support 0.10.0
  src/zenml/integrations/kserve/__init__.py
Labels: internal, dependencies

#1380 Fix order of runs and order of pipelines in post-execution
  docs/book/advanced-guide/pipelines/settings.md
  docs/book/component-gallery/data-validators/deepchecks.md
  docs/book/component-gallery/data-validators/evidently.md
  docs/book/component-gallery/data-validators/great-expectations.md
  docs/book/component-gallery/data-validators/whylogs.md
  docs/book/guidelines/best-practices.md
  docs/book/legacy/developer-guide/steps-pipelines/inspecting-pipeline-runs.md
  docs/book/legacy/developer-guide/steps-pipelines/pipeline-visualization.md
  docs/book/starter-guide/pipelines/fetching-pipelines.md
  examples/deepchecks_data_validation/deepchecks.ipynb
  examples/deepchecks_data_validation/run.py
  examples/evidently_data_validation/evidently.ipynb
  examples/evidently_data_validation/run.py
  examples/facets_visualize_statistics/README.md
  examples/facets_visualize_statistics/run.py
  examples/feast_feature_store/run.py
  examples/great_expectations_data_validation/great_expectations.ipynb
  examples/great_expectations_data_validation/run.py
  examples/huggingface/README.md
  examples/kubernetes_orchestration/run.py
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/neural_prophet/notebooks/post_execution.ipynb
  examples/quickstart/notebooks/quickstart.ipynb
  examples/quickstart/run.py
  examples/whylogs_data_profiling/README.md
  examples/whylogs_data_profiling/run.py
  examples/whylogs_data_profiling/whylogs.ipynb
  src/zenml/integrations/tensorboard/visualizers/tensorboard_visualizer.py
  src/zenml/post_execution/pipeline.py
  tests/integration/examples/test_quickstart.py
  tests/integration/functional/post_execution/lineage/test_lineage_graph.py
  tests/integration/functional/post_execution/test_pipeline_run.py
  tests/integration/functional/post_execution/test_step_run.py
Labels: bug, breaking-change

#1349 Fix broken docs URLs and add SDK docs url
  src/zenml/artifact_stores/local_artifact_store.py
  src/zenml/container_registries/azure_container_registry.py
  src/zenml/container_registries/default_container_registry.py
  src/zenml/container_registries/dockerhub_container_registry.py
  src/zenml/container_registries/gcp_container_registry.py
  src/zenml/container_registries/github_container_registry.py
  src/zenml/image_builders/local_image_builder.py
  src/zenml/integrations/airflow/flavors/airflow_orchestrator_flavor.py
  src/zenml/integrations/aws/flavors/aws_container_registry_flavor.py
  src/zenml/integrations/aws/flavors/aws_secrets_manager_flavor.py
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/azure/flavors/azure_artifact_store_flavor.py
  src/zenml/integrations/azure/flavors/azure_secrets_manager_flavor.py
  src/zenml/integrations/azure/flavors/azureml_step_operator_flavor.py
  src/zenml/integrations/bentoml/flavors/bentoml_model_deployer_flavor.py
  src/zenml/integrations/deepchecks/flavors/deepchecks_data_validator_flavor.py
  src/zenml/integrations/evidently/flavors/evidently_data_validator_flavor.py
  src/zenml/integrations/feast/flavors/feast_feature_store_flavor.py
  src/zenml/integrations/gcp/flavors/gcp_artifact_store_flavor.py
  src/zenml/integrations/gcp/flavors/gcp_image_builder_flavor.py
  src/zenml/integrations/gcp/flavors/gcp_secrets_manager_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/github/flavors/github_actions_orchestrator_flavor.py
  src/zenml/integrations/github/flavors/github_secrets_manager_flavor.py
  src/zenml/integrations/great_expectations/flavors/great_expectations_data_validator_flavor.py
  src/zenml/integrations/kaniko/flavors/kaniko_image_builder_flavor.py
  src/zenml/integrations/kserve/flavors/kserve_model_deployer_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/label_studio/flavors/label_studio_annotator_flavor.py
  src/zenml/integrations/mlflow/flavors/mlflow_experiment_tracker_flavor.py
  src/zenml/integrations/mlflow/flavors/mlflow_model_deployer_flavor.py
  src/zenml/integrations/neptune/flavors/neptune_experiment_tracker_flavor.py
  src/zenml/integrations/s3/flavors/s3_artifact_store_flavor.py
  src/zenml/integrations/seldon/flavors/seldon_model_deployer_flavor.py
  src/zenml/integrations/slack/flavors/slack_alerter_flavor.py
  src/zenml/integrations/spark/flavors/spark_on_kubernetes_step_operator_flavor.py
  src/zenml/integrations/spark/flavors/spark_step_operator_flavor.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/vault/flavors/vault_secrets_manager_flavor.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
  src/zenml/integrations/whylogs/flavors/whylogs_data_validator_flavor.py
  src/zenml/models/flavor_models.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
  src/zenml/stack/flavor.py
  src/zenml/zen_stores/migrations/versions/623a234c11f5_add_sdk_docs_url_to_flavors.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, documentation, internal

#1377 Fix label studio `dataset delete` command
  examples/label_studio_annotation/README.md
  src/zenml/cli/annotator.py
  src/zenml/integrations/label_studio/__init__.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
Labels: bug, documentation, internal

#1379 Add missing links to Quickstart
  examples/quickstart/README.md
  examples/quickstart/notebooks/quickstart.ipynb
Labels: documentation, internal

#1382 Fix PyPI readme logo display
  README.md
Labels: bug, internal

#1386 Fixed broken migration for flavors
  src/zenml/stack/flavor_registry.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#1374 Add debug mode flag for `zenml info`
  src/zenml/cli/base.py
  src/zenml/cli/utils.py
Labels: enhancement, internal

#1387 Update issue creation for bugs
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, internal

#1389 Integration sdk docs generated correctly now
  pyproject.toml
  scripts/verify_flavor_url_valid.py
  src/zenml/enums.py
  src/zenml/integrations/mlflow/flavors/mlflow_model_registry_flavor.py
  src/zenml/stack/flavor.py
  tests/unit/test_flavor.py
Labels: bug, internal

#1383 Add CLI utils tests
  src/zenml/cli/utils.py
  tests/integration/functional/cli/test_utils.py
Labels: internal, tests

#1394 Don't use docker client when building images remotely
  src/zenml/image_builders/base_image_builder.py
  src/zenml/image_builders/local_image_builder.py
  src/zenml/integrations/gcp/image_builders/gcp_image_builder.py
  src/zenml/integrations/kaniko/image_builders/kaniko_image_builder.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal

#1388 Ignore starting quotes from Artifact store path
  src/zenml/artifact_stores/base_artifact_store.py
  tests/unit/artifact_stores/test_base_artifact_store.py
Labels: bug, internal

#1384 CI speed improvements
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/docstring.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint-unit-test.yml
  .github/workflows/lint.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/release.yml
  .github/workflows/setup-python-environment.yml
  .github/workflows/spellcheck.yml
  .github/workflows/unit-test.yml
  pyproject.toml
  src/zenml/integrations/facets/__init__.py
Labels: enhancement, internal

#1393 Fix stack recipe link
  docs/book/getting-started/deploying-zenml/cli.md
Labels: documentation, internal

#1395 Switch FastAPI response class to orjson so `NaN` values don't break the server
  pyproject.toml
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal

#1392 Numpy materializer metadata for arrays with strings
  .pyspelling-ignore-words
  src/zenml/materializers/numpy_materializer.py
  tests/unit/materializers/test_numpy_materializer.py
  tests/unit/test_general.py
Labels: bug, internal

#1361 Add failure (and success hooks)
  .pyspelling-ignore-words
  docs/book/advanced-guide/pipelines/hooks.md
  docs/book/advanced-guide/pipelines/pipelines.md
  docs/book/advanced-guide/pipelines/step-metadata.md
  docs/book/toc.md
  examples/failure_and_success_hooks/README.md
  examples/failure_and_success_hooks/hooks/__init__.py
  examples/failure_and_success_hooks/hooks/success_hooks.py
  examples/failure_and_success_hooks/pipelines/__init__.py
  examples/failure_and_success_hooks/pipelines/hook_pipeline.py
  examples/failure_and_success_hooks/run.py
  examples/failure_and_success_hooks/steps/__init__.py
  examples/failure_and_success_hooks/steps/simple_steps.py
  src/zenml/alerter/base_alerter.py
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/hooks/__init__.py
  src/zenml/hooks/alerter_hooks.py
  src/zenml/hooks/hook_validators.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_context.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/unit/config/test_compiler.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#1400 Replace `pyspelling` with `typos`
  .github/workflows/lint-unit-test.yml
  .pyspelling-ignore-words
  .pyspelling.yml
  .typos.toml
  CONTRIBUTING.md
  RELEASE_NOTES.md
  docs/book/advanced-guide/pipelines/hooks.md
  docs/book/component-gallery/image-builders/kaniko.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/model-registries/mlflow.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/orchestrators/vertex.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/azure/azure-guide.md
  docs/book/legacy/developer-guide/stack-deployment-guide/stack-recipes.md
  docs/book/popular-stack-guides/azure/basic-stack.md
  docs/book/starter-guide/collaborate/roles-and-permissions.md
  docs/book/starter-guide/pipelines/fetching-pipelines.md
  docs/book/starter-guide/pipelines/parameters-and-caching.md
  docs/mkdocstrings_helper.py
  examples/bentoml_deployment/README.md
  examples/custom_code_deployment/kserve_pytorch/steps/prediction_service_loader.py
  examples/custom_code_deployment/kserve_tensorflow/steps/prediction_service_loader.py
  examples/custom_code_deployment/run_kserve_pytorch.py
  examples/custom_code_deployment/run_kserve_tensorflow.py
  examples/custom_code_deployment/run_seldon_pytorch.py
  examples/custom_code_deployment/run_seldon_tensorflow.py
  examples/custom_code_deployment/seldon_pytorch/steps/prediction_service_loader.py
  examples/custom_code_deployment/seldon_tensorflow/steps/prediction_service_loader.py
  examples/failure_and_success_hooks/README.md
  examples/kserve_deployment/run_pytorch.py
  examples/kserve_deployment/run_tensorflow.py
  examples/kserve_deployment/steps/prediction_service_loader/__init__.py
  examples/kserve_deployment/steps/prediction_service_loader/prediction_service_loader.py
  examples/kubeflow_pipelines_orchestration/README.md
  examples/mlflow_deployment/pipelines/__init__.py
  examples/mlflow_deployment/pipelines/continuous_deployment_pipeline/continuous_deployment_pipeline.py
  examples/mlflow_registry/README.md
  examples/spark_distributed_programming/pipelines/spark_pipeline/spark_pipeline.py
  examples/spark_distributed_programming/run.py
  pyproject.toml
  scripts/check-spelling.sh
  src/zenml/integrations/bentoml/model_deployers/bentoml_model_deployer.py
  src/zenml/post_execution/base_view.py
  tests/unit/utils/test_analytics_utils.py
Labels: enhancement, internal, dependencies

#1410 Fix the download nltk param for report step (#1409)
  examples/evidently_data_validation/evidently.ipynb
Labels: internal, backport

#1403 Bump `ruff` to v0.255
  pyproject.toml
Labels: internal, dependencies

#1412 Update title of deployment docs page
  docs/book/toc.md
Labels: documentation, internal

#1406 Changed to debug log
  src/zenml/client.py
  src/zenml/config/secret_reference_mixin.py
  src/zenml/stack/stack_component.py
Labels: internal

#1413 Fix incorrect `--sort_by` help text
  src/zenml/cli/utils.py
  src/zenml/models/filter_models.py
Labels: bug, internal

#1414 Document CLI filtering query language
  src/zenml/cli/__init__.py
  src/zenml/cli/integration.py
Labels: documentation, internal

#1375 Add orchestrator logs link for Sagemaker
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: enhancement, internal

#1421 Add MLflow UI messge to quickstart example and fix autolog spillage
  examples/quickstart/run.py
  examples/quickstart_py37/run.py
  src/zenml/integrations/dash/__init__.py
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
Labels: bug, internal

#1415 Add tests for the model registry
  tests/integration/functional/cli/test_model.py
  tests/unit/model_registries/__init__.py
  tests/unit/model_registries/test_base_model_registry.py
Labels: enhancement, internal, tests

#1419 Remove Aspell installation
  .github/workflows/lint-unit-test.yml
Labels: internal, dependencies

#1422 Increase `step_configurations` column size to 2^24
  src/zenml/models/constants.py
  src/zenml/zen_stores/migrations/versions/9d8020441014_increase_step_configuration_length.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  tests/unit/models/test_pipeline_deployment_models.py
Labels: bug, internal, tests

#1424 Add help text for `enable_service` option in recipe sub-command
  docs/book/component-gallery/orchestrators/kubeflow.md
  examples/kubeflow_pipelines_orchestration/README.md
  src/zenml/cli/stack_recipes.py
Labels: internal

#1429 Move token to the db
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/hub/client/client.py
  src/zenml/models/user_models.py
  src/zenml/zen_stores/migrations/versions/b4eccf34dfa3_add_hub_token_to_user_model.py
  src/zenml/zen_stores/schemas/user_schemas.py
Labels: enhancement, internal

#1428 Fix hook parser
  src/zenml/hooks/alerter_hooks.py
  src/zenml/hooks/hook_validators.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
Labels: bug, internal

#1426 Fix some pipeline bugs
  src/zenml/config/compiler.py
  src/zenml/zen_stores/migrations/versions/728c6369cfaa_add_name_column_to_input_artifact_pk.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: bug, internal

#1430 ZenML Failure Hook for OpenAI ChatGPT fixes
  docs/book/advanced-guide/pipelines/hooks.md
  docs/book/assets/openai/failure_alerter.png
  src/zenml/hooks/alerter_hooks.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/openai/__init__.py
  src/zenml/integrations/openai/hooks/__init__.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
Labels: enhancement, internal

#1306 Add basic tests for the server and recipes CLI
  scripts/run-ci-checks.sh
  scripts/serve_api_docs.sh
  src/zenml/cli/stack_recipes.py
  tests/integration/functional/cli/test_server.py
  tests/integration/functional/cli/test_stack_recipes.py
Labels: internal, tests

#1423 Add to our alembic migration guide
  src/zenml/zen_stores/migrations/README.md
Labels: documentation, internal

#1411 Analytics 2.0
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docs/book/misc/usage-analytics.md
  src/zenml/analytics/__init__.py
  src/zenml/analytics/client.py
  src/zenml/analytics/consumer.py
  src/zenml/analytics/context.py
  src/zenml/analytics/request.py
  src/zenml/cli/base.py
  src/zenml/cli/config.py
  src/zenml/cli/example.py
  src/zenml/cli/integration.py
  src/zenml/cli/server.py
  src/zenml/cli/stack_recipes.py
  src/zenml/config/global_config.py
  src/zenml/constants.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/base_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/utils/test_analytics_utils.py
Labels: enhancement, internal

#1402 Improve Slack Alerter by adding message blocks
  src/zenml/alerter/alerter_utils.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/integrations/slack/steps/slack_alerter_ask_step.py
  src/zenml/integrations/slack/steps/slack_alerter_post_step.py
Labels: enhancement

#1438 Add HF deployment type
  src/zenml/models/server_models.py
Labels: internal

#1285 Test integration for seldon example
  .github/workflows/publish_api_docs.yml
  examples/seldon_deployment/run.py
  src/zenml/integrations/seldon/__init__.py
  tests/README.md
  tests/harness/cfg/tests.yaml
  tests/integration/examples/test_seldon_deployment.py
Labels: internal

#1425 Update `pytorch-lightning` to support `2.0`
  pyproject.toml
  src/zenml/integrations/pytorch_lightning/__init__.py
  src/zenml/integrations/pytorch_lightning/materializers/pytorch_lightning_materializer.py
Labels: enhancement, internal, dependencies

#1439 Bump `ruff` to 0.259
  pyproject.toml
Labels: internal, dependencies

#1432 Update `mypy>=1.1.1` and fix new errors
  pyproject.toml
  src/zenml/client.py
  src/zenml/integrations/kserve/secret_schemas/secret_schemas.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/seldon/secret_schemas/secret_schemas.py
  src/zenml/integrations/seldon/seldon_client.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/model_registries/base_model_registry.py
  src/zenml/models/artifact_models.py
  src/zenml/models/component_models.py
  src/zenml/models/filter_models.py
  src/zenml/models/flavor_models.py
  src/zenml/models/pipeline_deployment_models.py
  src/zenml/models/pipeline_models.py
  src/zenml/models/pipeline_run_models.py
  src/zenml/models/role_models.py
  src/zenml/models/schedule_model.py
  src/zenml/models/secret_models.py
  src/zenml/models/stack_models.py
  src/zenml/models/step_run_models.py
  src/zenml/models/team_models.py
  src/zenml/models/team_role_assignment_models.py
  src/zenml/models/user_models.py
  src/zenml/models/user_role_assignment_models.py
  src/zenml/models/workspace_models.py
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/lineage/lineage_graph.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/services/terraform/terraform_service.py
  src/zenml/utils/filesync_model.py
  src/zenml/utils/secret_utils.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/harness/model/deployment.py
Labels: enhancement, internal, dependencies

#1435 Add `--upgrade` option to ZenML integration install
  docs/book/component-gallery/integrations.md
  src/zenml/cli/integration.py
  src/zenml/cli/utils.py
Labels: enhancement, internal

#1441 Bump `MLflow` to 2.2.2
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/model-registries/mlflow.md
  src/zenml/integrations/mlflow/__init__.py
  tests/integration/functional/cli/test_server.py
Labels: internal

#1427 HuggingFace Spaces server deployment option
  docker/zenml-server-hf-spaces.Dockerfile
  docs/book/assets/huggingface/hf-spaces-sdk.png
  docs/book/assets/huggingface/hf_spaces_chart.png
  docs/book/getting-started/deploying-zenml/huggingface.md
  docs/book/toc.md
Labels: documentation, enhancement, internal

#1442 Bugfix for server import
  src/zenml/analytics/context.py
Labels: bug, internal

#1444 Fix HF Spaces URL
  docs/book/getting-started/deploying-zenml/huggingface.md
Labels: bug, documentation, internal

#1445 Fix HF Spaces URL (#1444)
  docs/book/getting-started/deploying-zenml/huggingface.md
Labels: bug, documentation, internal

#1447 Remove all `zenml.cli` imports outside of `zenml.cli`
  src/zenml/integrations/dash/visualizers/pipeline_run_lineage_visualizer.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/secrets_managers/local/local_secrets_manager.py
Labels: bug, internal

#1437 Add recursive deletion of components for `zenml stack delete`
  src/zenml/cli/stack.py
  src/zenml/client.py
  tests/integration/functional/cli/test_stack.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement

#1450 Temporarily disable primary key requirement for newer mysql versions
  src/zenml/zen_stores/migrations/versions/728c6369cfaa_add_name_column_to_input_artifact_pk.py
  tests/harness/deployment/local_docker.py
  tests/harness/deployment/server_docker_compose.py
Labels: bug, internal

#1381 SageMaker step operator: expand input arguments and add support for S3 input data
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: enhancement
