Repository zenml-io/zenml, pull requests merged in 2023-10, with the labels that each got.

#1848 CI Fixes / Improvements
  .github/workflows/integration-test.yml
  .github/workflows/update-e2e-template.yml
  scripts/install-zenml-dev.sh
  src/zenml/integrations/evidently/__init__.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/integrations/skypilot/orchestrators/test_skypilot_orchestrator.py
Labels: internal

#1849 [Model WatchTower] Extend client
  src/zenml/client.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/pipeline.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1843 Fix MLflow registry methods with empty metadata
  examples/e2e/.copier-answers.yml
  examples/e2e/steps/inference/inference_get_current_version.py
  examples/e2e/steps/promotion/promote_get_versions.py
  examples/e2e/steps/promotion/promote_metric_compare_promoter.py
  src/zenml/cli/base.py
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
  src/zenml/model_registries/base_model_registry.py
  tests/integration/functional/cli/test_model.py
Labels: bug, internal

#1851 Use configured template REF in CI
  .github/workflows/update-e2e-template.yml
  src/zenml/cli/base.py
Labels: internal

#1850 Fix AWS service connector installation requirements
  pyproject.toml
Labels: bug, internal

#1747 [Docs] Improvements to custom flavor and custom orchestrator pages
  docs/book/deploying-zenml/zenml-cloud/cloud-system-architecture.md
  docs/book/reference/faq.md
  docs/book/reference/migration-guide/migration-zero-twenty.md
  docs/book/stacks-and-components/component-guide/alerters/custom.md
  docs/book/stacks-and-components/component-guide/annotators/custom.md
  docs/book/stacks-and-components/component-guide/artifact-stores/custom.md
  docs/book/stacks-and-components/component-guide/component-guide.md
  docs/book/stacks-and-components/component-guide/container-registries/custom.md
  docs/book/stacks-and-components/component-guide/data-validators/custom.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/custom.md
  docs/book/stacks-and-components/component-guide/feature-stores/custom.md
  docs/book/stacks-and-components/component-guide/image-builders/custom.md
  docs/book/stacks-and-components/component-guide/model-deployers/custom.md
  docs/book/stacks-and-components/component-guide/model-registries/custom.md
  docs/book/stacks-and-components/component-guide/orchestrators/custom.md
  docs/book/stacks-and-components/component-guide/step-operators/custom.md
  docs/book/stacks-and-components/custom-solutions/custom-stack-solutions.md
  docs/book/stacks-and-components/custom-solutions/implement-a-custom-integration.md
  docs/book/stacks-and-components/custom-solutions/implement-a-custom-stack-component.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/custom-stack-solutions/implement-a-custom-stack-component.md
Labels: documentation, internal

#1835 Optimizing the performance through database changes
  src/zenml/config/compiler.py
  src/zenml/models/__init__.py
  src/zenml/models/pipeline_deployment_models.py
  src/zenml/models/pipeline_run_models.py
  src/zenml/models/step_run_models.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/step_invocation.py
  src/zenml/zen_stores/migrations/README.md
  src/zenml/zen_stores/migrations/versions/37835ce041d2_optimizing_database.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/base_schemas.py
  src/zenml/zen_stores/schemas/logs_schemas.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/schedule_schema.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_utils.py
  tests/integration/functional/cli/utils.py
  tests/integration/functional/models/test_pipeline_run.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/conftest.py
  tests/unit/entrypoints/test_base_entrypoint_configuration.py
  tests/unit/models/test_step_run_models.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/orchestrators/test_containerized_orchestrator.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/pipelines/test_build_utils.py
Labels: enhancement, internal

#1860 Add `README` for `examples` folder
  examples/README.md
Labels: documentation, internal

#1855 Make Terraform Optional Again
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/cli/server.py
  src/zenml/constants.py
  src/zenml/environment.py
  src/zenml/recipes/__init__.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/services/__init__.py
  src/zenml/utils/terraform_utils.py
  src/zenml/zen_server/deploy/__init__.py
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
Labels: enhancement, internal, dependencies

#1868 Model watchtower becomes Model control plane
  docs/book/deploying-zenml/zenml-cloud/zenml-cloud.md
  docs/book/introduction.md
Labels: documentation, internal

#1866 Fix CI by freeing up space on runner
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/setup-python-environment.yml
Labels: bug, internal, tests

#1857 Allow for `user` param to be specified (successfully) in `DockerSettings`
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal

#1870 Add `get_pipeline_context`
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/pipelining-features/fetch-metadata-within-pipeline.md
  docs/book/user-guide/advanced-guide/pipelining-features/pipelining-features.md
  src/zenml/__init__.py
  src/zenml/new/pipelines/pipeline_context.py
  tests/integration/functional/pipelines/test_pipeline_context.py
Labels: enhancement, internal

#1874 [Helm] Use GCP creds directly instead of a file.
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
Labels: internal

#1858 Connect to Service-connector at component registration
  src/zenml/cli/stack_components.py
Labels: enhancement, internal

#1859 [Model Control Plane] parallel running versions support
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/model_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_stores/migrations/versions/3b68abe58f44_add_model_entity.py
  src/zenml/zen_stores/migrations/versions/3b68abe58f44_add_model_watchtower_entities.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/steps/parallel_pipeline.py
  tests/integration/functional/steps/test_external_artifact.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/models/test_model_models.py
  tests/unit/steps/test_external_artifact.py
Labels: enhancement, internal

#1877 Fixing the `upgrade` migration script after the database changes
  src/zenml/zen_stores/migrations/versions/37835ce041d2_optimizing_database.py
Labels: bug, internal

#1861 [Model Control Plane] Add CLI
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/cli/__init__.py
  src/zenml/cli/model.py
  src/zenml/cli/model_registry.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/model/__init__.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/model_utils.py
  src/zenml/zen_stores/migrations/versions/3b68abe58f44_add_model_watchtower_entities.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/cli/test_model.py
  tests/integration/functional/cli/test_model_registry.py
Labels: enhancement, internal

#1878 Update to templates
  .github/workflows/ci.yml
  .github/workflows/update-templates-to-examples.yml
  docs/book/user-guide/starter-guide/using-project-templates.md
  src/zenml/cli/base.py
Labels: enhancement, internal

#1875 Docs for orgs, rbac and sso
  docs/book/deploying-zenml/zenml-cloud/get-started.md
  docs/book/deploying-zenml/zenml-cloud/user-management.md
  docs/book/toc.md
Labels: enhancement, internal

#1856 Add missing Docker build options for GCP image builder
  src/zenml/integrations/gcp/image_builders/gcp_image_builder.py
Labels: bug, internal

#1879 Solve alembic branching issue
  src/zenml/zen_stores/migrations/versions/3b68abe58f44_add_model_watchtower_entities.py
  src/zenml/zen_stores/migrations/versions/f3b3964e3a0f_add_oauth_devices.py
Labels: bug, internal

#1881 Fix typo for 0.45 release
  docs/book/deploying-zenml/zenml-cloud/user-management.md
Labels: documentation, internal

#1889 Add warning header to docs for version 0.10.0
  docs/book/advanced-guide/continuous-training-and-deployment.md
  docs/book/advanced-guide/execute-pipelines-in-cloud.md
  docs/book/advanced-guide/integrations.md
  docs/book/advanced-guide/load-your-data-from-feature-stores.md
  docs/book/advanced-guide/manage-external-services.md
  docs/book/advanced-guide/manage-your-secrets.md
  docs/book/advanced-guide/perform-drift-detection.md
  docs/book/advanced-guide/run-on-kubeflow.md
  docs/book/advanced-guide/run-steps-on-specialized-hardware.md
  docs/book/advanced-guide/send-automated-chat-alerts.md
  docs/book/advanced-guide/stacks-components-flavors.md
  docs/book/advanced-guide/track-your-experiments.md
  docs/book/advanced-guide/track_metadata_in_the_cloud.md
  docs/book/collaborate/collaborate-with-zenml.md
  docs/book/collaborate/share-with-profiles.md
  docs/book/collaborate/stack-export-import.md
  docs/book/collaborate/zenml-server.md
  docs/book/core-concepts.md
  docs/book/developer-guide/caching.md
  docs/book/developer-guide/class-based-api.md
  docs/book/developer-guide/fetching-historic-runs.md
  docs/book/developer-guide/installation.md
  docs/book/developer-guide/materializer.md
  docs/book/developer-guide/post-execution-workflow.md
  docs/book/developer-guide/repo-and-config.md
  docs/book/developer-guide/runtime-configuration.md
  docs/book/developer-guide/step-fixtures.md
  docs/book/developer-guide/steps-and-pipelines.md
  docs/book/examples-and-use-cases.md
  docs/book/extending-zenml/alerters.md
  docs/book/extending-zenml/artifact-stores.md
  docs/book/extending-zenml/container-registries.md
  docs/book/extending-zenml/experiment-trackers.md
  docs/book/extending-zenml/feature-stores.md
  docs/book/extending-zenml/getting-started.md
  docs/book/extending-zenml/metadata-stores.md
  docs/book/extending-zenml/model-deployers.md
  docs/book/extending-zenml/orchestrators.md
  docs/book/extending-zenml/secrets-managers.md
  docs/book/extending-zenml/step-operators.md
  docs/book/introduction.md
  docs/book/reference/glossary.md
  docs/book/resources/best-practices.md
  docs/book/resources/contributing.md
  docs/book/resources/faq.md
  docs/book/resources/index.md
  docs/book/resources/system-environmental-variables.md
  docs/book/resources/usage-analytics.md
Labels: documentation, internal, backport

#1888 Only import ipinfo when necessary
  src/zenml/zen_server/utils.py
Labels: bug, internal

#1885 [Model Control Plane] Suppress excessive logging in model control plane
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_base_model.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/steps/base_step.py
Labels: bug, internal

#1929 Add warning generation scripts for Gitbook docs
  scripts/add-docs-warning.py
  scripts/add-docs-warning.sh
Labels: enhancement, internal

#1930 Lightweight template CI
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
Labels: bug, internal

#1931 Update `Skypilot` orchestrator setting docs section
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
Labels: documentation, internal

#1933 Moved docs to starter guide
  docs/book/deploying-zenml/zenml-cloud/user-management.md
  docs/book/user-guide/starter-guide/switch-to-production.md
Labels: documentation, internal

#1936 Fix Server API
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: bug, internal

#1938 Fix failing Docker CI
  .github/workflows/ci.yml
  scripts/test-coverage-xml.sh
  src/zenml/zen_stores/migrations/versions/37835ce041d2_optimizing_database.py
Labels: bug, internal

#1940 Revert debug changes
  .github/workflows/ci.yml
  scripts/test-coverage-xml.sh
Labels: bug, internal

#1934 Prepare release 0.45.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.0_release.py
Labels: internal

#1935 Add missing space when creating new model version
  src/zenml/models/model_base_model.py
Labels: bug, enhancement, internal

#1867 [Artifacts Tab] Globally Unique Default Artifact Names
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  src/zenml/models/artifact_models.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/utils.py
  src/zenml/utils/artifact_utils.py
  src/zenml/zen_stores/migrations/versions/389046140cad_data_versioning.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  tests/integration/functional/models/test_artifact.py
  tests/unit/steps/test_utils.py
Labels: enhancement, internal

#1869 [Artifacts Tab] Artifact Versioning
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/cli/artifact.py
  src/zenml/client.py
  src/zenml/models/artifact_models.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/utils/artifact_utils.py
  src/zenml/zen_stores/migrations/versions/389046140cad_data_versioning.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  tests/integration/functional/cli/test_artifact.py
  tests/integration/functional/models/test_artifact.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/conftest.py
  tests/unit/models/test_artifact_models.py
  tests/unit/utils/test_artifact_utils.py
Labels: enhancement, internal

#1944 Fix alembic inconsistencies
  src/zenml/zen_stores/migrations/versions/6f707b385dc1_fix_model_artifacts.py
Labels: bug, internal

#1945 Fixing the migration issues
  src/zenml/models/pipeline_deployment_models.py
  src/zenml/models/step_run_models.py
  src/zenml/zen_stores/migrations/versions/37835ce041d2_optimizing_database.py
  src/zenml/zen_stores/migrations/versions/6f707b385dc1_fix_model_artifacts.py
  src/zenml/zen_stores/migrations/versions/7f603e583dd7_fixed_migration.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
Labels: bug, internal

#1948 Release prepped
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.1_release_0_45_1.py
Labels: internal

#1950 set length for varchar in migration
  src/zenml/zen_stores/migrations/versions/7f603e583dd7_fixed_migration.py
Labels: bug, internal

#1952 Update FAQ to account for `examples` changes
  docs/book/reference/faq.md
Labels: documentation, internal

#1951 Prepare release 0.45.2
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.2_release.py
Labels: internal

#1876 Evaluate YAML based config early + OSS-2511
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/pipeline.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/parallel_pipeline.py
Labels: enhancement, internal

#1955 Fixing nullable parameter to avoid extra migrations
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
Labels: bug, internal

#1958 Pin Helm version to avoid 400 Bad Request error
  .github/workflows/publish_helm_chart.yml
Labels: bug, internal

#1957 `external_input_artifact` backward compatibility with alembic
  src/zenml/zen_stores/migrations/versions/729263e47b55_fix_external_input_artifacts.py
Labels: bug, internal

#1961 handle NULLs in migration
  src/zenml/zen_stores/migrations/versions/729263e47b55_fix_external_input_artifacts.py
Labels: bug, internal

#1959 Prepare release 0.45.3
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.3_release.py
Labels: internal

#1954 Increase reuse of `ModelConfig`
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/cli/model.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/model_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  src/zenml/zen_stores/migrations/versions/4f66af55fbb9_rename_model_config_model_to_model_.py
  src/zenml/zen_stores/schemas/model_schemas.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/integration/functional/steps/test_external_artifact.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/model/test_model_config_init.py
  tests/unit/models/test_model_models.py
Labels: enhancement, internal

#1964 resolve alembic branches
  src/zenml/zen_stores/migrations/versions/4f66af55fbb9_rename_model_config_model_to_model_.py
Labels: internal

#1966 Fix corrupted migration for old dbs
  src/zenml/zen_stores/migrations/versions/729263e47b55_fix_external_input_artifacts.py
Labels: bug, internal

#1967 Prepare release 0.45.4
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.4_release.py
Labels: internal

#1953 Add a 'how do I...' section into docs
  docs/book/reference/how-do-i.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/environment-management/handling-dependencies.md
Labels: documentation, internal

#1963 Bump `mypy`, `ruff` and `black`
  pyproject.toml
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/evidently/column_mapping.py
  src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
  src/zenml/integrations/evidently/metrics.py
  src/zenml/integrations/evidently/tests.py
  src/zenml/integrations/feast/feature_stores/feast_feature_store.py
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/great_expectations/ge_store_backend.py
  src/zenml/integrations/great_expectations/materializers/ge_materializer.py
  src/zenml/integrations/great_expectations/steps/ge_profiler.py
  src/zenml/integrations/great_expectations/steps/ge_validator.py
  src/zenml/integrations/great_expectations/utils.py
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
  src/zenml/integrations/tensorboard/services/tensorboard_service.py
  src/zenml/integrations/tensorboard/visualizers/tensorboard_visualizer.py
  src/zenml/integrations/tensorflow/__init__.py
  src/zenml/integrations/vault/secrets_manager/vault_secrets_manager.py
  src/zenml/utils/secret_utils.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  tests/harness/deployment/server_docker_compose.py
Labels: enhancement, internal, dependencies

#1975 SQLModel docs backport fixes
  README.md
  docs/book/getting-started/installation.md
  examples/label_studio_annotation/README.md
  examples/label_studio_text_annotation/README.md
  examples/quickstart/README.md
Labels: documentation, internal

#1976 SQLModel installation instructions update (#1975)
  README.md
  docs/book/getting-started/installation.md
  examples/label_studio_annotation/README.md
  examples/label_studio_text_annotation/README.md
  examples/quickstart/README.md
Labels: bug, documentation, internal, backport

#1977 Updated quickstart command in cloud quickstart
  examples/quickstart/notebooks/quickstart-zenml-cloud.ipynb
Labels: enhancement, internal

#1979 Updated quickstart command in cloud quickstart (#1977)
  examples/quickstart/notebooks/quickstart-zenml-cloud.ipynb
Labels: documentation, internal, backport

#1980 Updated quickstart command in cloud quickstart (#1977)
  examples/quickstart/notebooks/quickstart-zenml-cloud.ipynb
Labels: documentation, internal, backport

#1978 Make sure vertex job id is only lower case letter, number or dash
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
Labels: enhancement, internal

#1965 Fix DB initialization when using external authentication
  src/zenml/cli/base.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
Labels: enhancement, internal

#1982 Source code repository type not included in resolve source
  src/zenml/utils/source_utils.py
Labels: internal

#1981 Prepare release 0.45.5
  README.md
  RELEASE_NOTES.md
  docs/book/getting-started/installation.md
  examples/label_studio_annotation/README.md
  examples/label_studio_text_annotation/README.md
  examples/quickstart/README.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.5_release.py
Labels: internal

#1986 Updating `README.md` and update images
  README.md
  docs/book/.gitbook/assets/Scenario3.png
  docs/book/.gitbook/assets/header.png
  docs/book/.gitbook/assets/intro-zenml-overview.png
  docs/book/.gitbook/assets/overview.gif
Labels: documentation, internal

#1989 Always set the active workspace to be the default workspace server side
  src/zenml/client.py
Labels: bug, internal

#1991 Turn synchronous mode on by default for all orchestrators
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
Labels: enhancement, internal

#1983 Use docker credentials in the skypilot orchestrator
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
  src/zenml/container_registries/base_container_registry.py
  src/zenml/integrations/s3/__init__.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_aws_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
Labels: bug, internal

#1994 Add missing space to `@step` warning message
  src/zenml/steps/step_decorator.py
Labels: internal

#1993 Fix sagemaker orchestrator and step operator env vars and other minor bugs
  src/zenml/cli/utils.py
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator_entrypoint_config.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator_entrypoint_config.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/step_operators/base_step_operator.py
  src/zenml/utils/env_utils.py
  tests/unit/utils/test_env_utils.py
Labels: bug, internal

#1969 fix: `BasePyTorchMaterliazer` -> `Materializer`
  src/zenml/integrations/neural_prophet/materializers/neural_prophet_materializer.py
  src/zenml/integrations/pytorch/materializers/base_pytorch_materializer.py
  src/zenml/integrations/pytorch/materializers/pytorch_dataloader_materializer.py
  src/zenml/integrations/pytorch/materializers/pytorch_module_materializer.py
  src/zenml/integrations/pytorch_lightning/materializers/pytorch_lightning_materializer.py
Labels: bug

#1997 allow calling old base pytorch materilizzer
  src/zenml/integrations/pytorch/materializers/base_pytorch_materializer.py
Labels: internal

#1996 Add connector support to sagemaker step operator.
  docs/book/stacks-and-components/component-guide/step-operators/sagemaker.md
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: enhancement, internal

#1988 Server-Side Component Config Validation
  src/zenml/client.py
  src/zenml/exceptions.py
  src/zenml/stack/utils.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: bug, internal

#1864 Allow disconnecting service-connector from stack component
  src/zenml/cli/stack_components.py
  src/zenml/client.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2000 Prepare release 0.45.6
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.45.6_release.py
Labels: internal
