Repository zenml-io/zenml, pull requests merged in 2023-04, with the labels that each got.

#1454 Add Screenshots to Code Repo Token
  docs/book/assets/code_repo/copy-github-fine-grained-token.png
  docs/book/assets/code_repo/github-fine-grained-token-name.png
  docs/book/assets/code_repo/github-generate-fine-grained-token.png
  docs/book/assets/code_repo/github-token-permissions-overview.png
  docs/book/assets/code_repo/github-token-set-permissions.png
  docs/book/assets/code_repo/gitlab-copy-access-token.png
  docs/book/assets/code_repo/gitlab-generate-access-token.png
  docs/book/starter-guide/production-fundamentals/code-repositories.md
Labels: documentation, internal

#1458 Fix broken ENV variable
  docker/zenml-server-hf-spaces.Dockerfile
Labels: bug, internal

#1457 Update examples to mention stack component deploy CLI command
  examples/custom_code_deployment/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/sagemaker_orchestration/README.md
  examples/seldon_deployment/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
Labels: documentation, enhancement, internal

#1456 Documentation for `zenml <stack_component> deploy` subcommand
  docs/book/advanced-guide/practical/stack-recipes.md
  docs/book/component-gallery/artifact-stores/gcp.md
  docs/book/component-gallery/artifact-stores/s3.md
  docs/book/component-gallery/container-registries/aws.md
  docs/book/component-gallery/container-registries/gcp.md
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/sagemaker.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/step-operators/sagemaker.md
  docs/book/starter-guide/stacks/managing-stacks.md
  src/zenml/cli/__init__.py
Labels: documentation, internal

#1468 Backport - Fix screenshot size in code repo
  docs/book/starter-guide/production-fundamentals/code-repositories.md
Labels: internal, backport

#1470 Fix CI (Deepchecks integration tests)
  src/zenml/integrations/deepchecks/__init__.py
Labels: bug, internal

#1459 chore: update teams.yml
  .github/teams.yml
Labels: internal

#1464 Fix `BuiltInContainerMaterializer` for subtypes and non-built-in types
  src/zenml/materializers/built_in_materializer.py
  tests/unit/materializers/test_built_in_materializer.py
Labels: bug, internal

#1460 Kubernetes Orchestrator Improvements
  src/zenml/integrations/kubeflow/utils.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
  tests/unit/integrations/kubeflow/test_utils.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
  tests/unit/integrations/kubernetes/orchestrators/test_manifest_utils.py
Labels: enhancement, internal

#1465 Fix flaky CLI tests
  tests/integration/functional/cli/test_server.py
Labels: bug, internal

#1463 Fix circular import during type checking
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/utils/code_repository_utils.py
  src/zenml/utils/downloaded_repository_context.py
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_code_repository_utils.py
  tests/unit/utils/test_source_utils.py
Labels: bug, internal

#1471 Allow secret values replacement in REST API PUT
  src/zenml/models/base_models.py
  src/zenml/zen_server/routers/secrets_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/secrets_stores/rest_secrets_store.py
  tests/integration/functional/zen_stores/test_secrets_store.py
Labels: bug, enhancement, internal

#1473 Fix two steps race condition
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#1474 Downgrading ZenML Version in global config
  docs/book/guidelines/global-config.md
  src/zenml/cli/__init__.py
  src/zenml/cli/downgrade.py
  src/zenml/config/global_config.py
Labels: bug, internal

#1416 Add metadata to stack components
  src/zenml/cli/__init__.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/models/component_models.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_stores/migrations/versions/43a86093b60e_add_labels_for_stack_components.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_stack_components.py
Labels: enhancement, internal

#1480 remove modules from the list output for stack recipes
  src/zenml/cli/stack_recipes.py
Labels: bug, internal

#1461 Pin `openai` integration to `>0.27.0`
  src/zenml/integrations/openai/__init__.py
Labels: bug, internal, dependencies

#1462 Apply formatting fixes to `/scripts`
  scripts/format.sh
  scripts/verify_flavor_url_valid.py
Labels: internal

#1485 Remove top-level config from recommended repo structure
  docs/book/guidelines/best-practices.md
Labels: documentation, internal

#1477 ZenML Version Downgrade - Silence Warnning
  docs/book/guidelines/global-config.md
  src/zenml/cli/__init__.py
  src/zenml/cli/downgrade.py
  src/zenml/config/global_config.py
Labels: bug, internal

#1483 Update ZenServer recipes to include secret stores
  src/zenml/zen_server/deploy/terraform/recipes/aws/helm.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/ingress.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/vpc.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/helm.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/ingress.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/key_vault.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/rg.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/helm.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/ingress.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
Labels: enhancement, internal

#1489 fix: use pool_pre_ping to discard invalid SQL connections when borrow…
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug

#1490 Docs/zenml hub documentation
  docs/book/assets/zenml_hub/create_plugin_dashboard.png
  docs/book/assets/zenml_hub/login_dashboard.png
  docs/book/assets/zenml_hub/plugins_cli.png
  docs/book/assets/zenml_hub/plugins_dashboard.png
  docs/book/component-gallery/orchestrators/sagemaker.md
  docs/book/component-gallery/orchestrators/vertex.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/getting-started/core-concepts.md
  docs/book/starter-guide/collaborate/collaborate.md
  docs/book/starter-guide/collaborate/users.md
  docs/book/starter-guide/collaborate/zenml-deployment.md
  docs/book/starter-guide/collaborate/zenml-hub.md
  docs/book/starter-guide/production-fundamentals/production-fundamentals.md
  docs/book/starter-guide/stacks/managing-stacks.md
  docs/book/starter-guide/stacks/sharing-stacks.md
  docs/book/starter-guide/stacks/stacks.md
  docs/book/toc.md
Labels: documentation, internal

#1494 Sort integration list before display
  src/zenml/cli/integration.py
Labels: bug, internal

#1496 Update docs to surface CLI filtering syntax
  docs/book/starter-guide/pipelines/fetching-pipelines.md
  src/zenml/cli/__init__.py
Labels: documentation, enhancement, internal

#1497 Delete Legacy Docs
  docs/book/drafts/framework-design.md
  docs/book/legacy/developer-guide/advanced-usage/advanced-usage.md
  docs/book/legacy/developer-guide/advanced-usage/custom-flavors.md
  docs/book/legacy/developer-guide/advanced-usage/docker.md
  docs/book/legacy/developer-guide/advanced-usage/environment.md
  docs/book/legacy/developer-guide/advanced-usage/manage-external-services.md
  docs/book/legacy/developer-guide/advanced-usage/secret-references.md
  docs/book/legacy/developer-guide/advanced-usage/specify-step-resources.md
  docs/book/legacy/developer-guide/advanced-usage/stack-environment-variables.md
  docs/book/legacy/developer-guide/advanced-usage/stack-state-management.md
  docs/book/legacy/developer-guide/advanced-usage/step-execution-order.md
  docs/book/legacy/developer-guide/advanced-usage/step-fixtures.md
  docs/book/legacy/developer-guide/stack-deployment-guide/deploy-terraform.md
  docs/book/legacy/developer-guide/stack-deployment-guide/execute-pipelines-in-cloud.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/aws/aws-guide.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/aws/aws.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/azure/azure-guide.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/azure/azure.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/gcp/gcp-guide.md
  docs/book/legacy/developer-guide/stack-deployment-guide/manual-deployments/gcp/gcp.md
  docs/book/legacy/developer-guide/stack-deployment-guide/overview.md
  docs/book/legacy/developer-guide/stack-deployment-guide/stack-recipes.md
  docs/book/legacy/developer-guide/stacks-repositories/repository.md
  docs/book/legacy/developer-guide/stacks-repositories/stack.md
  docs/book/legacy/developer-guide/stacks-repositories/stacks-repositories.md
  docs/book/legacy/developer-guide/steps-pipelines/caching.md
  docs/book/legacy/developer-guide/steps-pipelines/functional-vs-class-based-api.md
  docs/book/legacy/developer-guide/steps-pipelines/inspecting-pipeline-runs.md
  docs/book/legacy/developer-guide/steps-pipelines/pipeline-visualization.md
  docs/book/legacy/developer-guide/steps-pipelines/runtime-configuration.md
  docs/book/legacy/developer-guide/steps-pipelines/steps-and-pipelines.md
Labels: documentation, internal

#1451 Improve the REST API error handling
  src/zenml/exceptions.py
  src/zenml/zen_server/exceptions.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/code_repositories_endpoints.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/pipeline_builds_endpoints.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/role_assignments_endpoints.py
  src/zenml/zen_server/routers/roles_endpoints.py
  src/zenml/zen_server/routers/run_metadata_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/schedule_endpoints.py
  src/zenml/zen_server/routers/secrets_endpoints.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/routers/team_role_assignments_endpoints.py
  src/zenml/zen_server/routers/teams_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  tests/unit/zen_server/test_exceptions.py
Labels: bug, internal

#1501 Fix circular import of PipelineRunConfiguration
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/pipelines/base_pipeline.py
  tests/integration/functional/cli/test_pipeline.py
  tests/unit/config/test_compiler.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/stack/test_stack.py
Labels: bug, internal

#1498 Delete Deprecated Artifacts and Materializer Code
  src/zenml/artifacts/__init__.py
  src/zenml/artifacts/base_artifact.py
  src/zenml/artifacts/data_analysis_artifact.py
  src/zenml/artifacts/data_artifact.py
  src/zenml/artifacts/model_artifact.py
  src/zenml/artifacts/schema_artifact.py
  src/zenml/artifacts/service_artifact.py
  src/zenml/artifacts/statistics_artifact.py
  src/zenml/materializers/base_materializer.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/post_execution/artifact.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  tests/unit/steps/test_base_step.py
Labels: internal

#1506 Add example to docs for passing stack component specific settings
  docs/book/advanced-guide/pipelines/settings.md
Labels: documentation

#1503 Increase step run field lengths
  src/zenml/zen_stores/migrations/versions/fbd7f18ced1e_increase_step_run_field_lengths.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
Labels: bug, internal

#1508 Fix Sagemaker orchestrator pipeline name bug
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal
