Repository zenml-io/zenml, pull requests merged in 2023-05, with the labels that each got.

#1505 Generate unique SageMaker training job name based on pipeline and ste…
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: bug

#1516 [CI Fix] Pin Llama Index Version
  src/zenml/integrations/llama_index/__init__.py
Labels: bug, internal

#1512 Basic PyCaret integration and materializer
  .github/actions/setup_environment/action.yml
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/pycaret/__init__.py
  src/zenml/integrations/pycaret/materializers/__init__.py
  src/zenml/integrations/pycaret/materializers/model_materializer.py
Labels: enhancement

#1513 Specify line endings for different operating systems
  .gitattributes
Labels: enhancement, internal

#1509 Extend SageMakerOrchestratorSettings with processor_args enabling step level configuration
  docs/book/component-gallery/orchestrators/sagemaker.md
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: enhancement

#1510 Fix post execution `get_pipeline()` and `pipeline.get_runs()`
  docs/book/guidelines/best-practices.md
  src/zenml/integrations/plotly/visualizers/pipeline_lineage_visualizer.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/post_execution/__init__.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  tests/integration/functional/conftest.py
  tests/integration/functional/post_execution/test_pipeline.py
  tests/unit/post_execution/test_pipeline.py
Labels: bug, internal

#1518 Add Kubernetes Orchestrator Settings
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
  tests/unit/integrations/kubernetes/orchestrators/test_manifest_utils.py
Labels: enhancement, internal

#1520 Bump `ruff` to 0.0.265
  pyproject.toml
Labels: internal, dependencies

#1523 Fix Kubernetes Orchestrator Config Loading
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
Labels: bug, internal

#1521 Resolve path during module resolving
  src/zenml/utils/source_utils.py
Labels: bug, internal

#1524 Fix `SO_REUSEPORT` issue
  src/zenml/utils/networking_utils.py
Labels: bug, internal

#1328 Add individual stack component deployment through recipes
  docs/book/advanced-guide/practical/stack-recipes.md
  docs/book/component-gallery/artifact-stores/gcp.md
  docs/book/component-gallery/artifact-stores/s3.md
  docs/book/component-gallery/container-registries/aws.md
  docs/book/component-gallery/container-registries/gcp.md
  docs/book/component-gallery/deploying components.md
  docs/book/component-gallery/experiment-trackers/mlflow.md
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/kubernetes.md
  docs/book/component-gallery/orchestrators/sagemaker.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/component-gallery/step-operators/sagemaker.md
  docs/book/starter-guide/stacks/managing-stacks.md
  examples/custom_code_deployment/README.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/sagemaker_orchestration/README.md
  examples/seldon_deployment/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/stack_recipes.py
  src/zenml/client.py
  src/zenml/exceptions.py
  src/zenml/recipes/__init__.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/services/terraform/terraform_service.py
  src/zenml/utils/analytics_utils.py
  tests/integration/functional/cli/test_stack_recipes.py
Labels: enhancement, internal

#1522 Raise 501 for Unauthenticated Artifact Stores
  src/zenml/integrations/bentoml/steps/bento_builder.py
  src/zenml/integrations/kserve/custom_deployer/zenml_custom_model.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/seldon/custom_deployer/zenml_custom_model.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/post_execution/artifact.py
  src/zenml/utils/artifact_utils.py
  src/zenml/zen_server/routers/artifacts_endpoints.py
  tests/integration/functional/post_execution/test_artifact.py
  tests/unit/utils/test_artifact_utils.py
Labels: bug, internal

#1528 Fix pulling of stack recipes on `zenml init`
  src/zenml/recipes/stack_recipe_service.py
Labels: bug, internal

#1525 Store dockerfile and requirments for builds
  pyproject.toml
  src/zenml/config/build_configuration.py
  src/zenml/models/pipeline_build_models.py
  src/zenml/pipelines/build_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/743ec82b1b3c_update_size_of_build_images.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  tests/integration/functional/cli/test_pipeline.py
  tests/unit/pipelines/test_build_utils.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal

#1530 Fix Source Resolving in Colab
  src/zenml/environment.py
  src/zenml/post_execution/artifact.py
Labels: bug, internal

#1534 Cleanup remaining references of `zenml.artifacts`
  docs/book/component-gallery/model-deployers/model-deployers.md
  docs/book/component-gallery/model-deployers/seldon.md
  examples/label_studio_annotation/steps/model_deployers.py
Labels: bug, internal

#1540 Remove dev breakpoints
  src/zenml/cli/stack_components.py
  src/zenml/client.py
Labels: bug, internal

#1545 Improve CLI help text for `zenml integration install -i ...`
  src/zenml/cli/__init__.py
  src/zenml/cli/integration.py
Labels: documentation, internal

#1538 New Introduction Docs Page
  docs/book/.gitbook/assets/intro_dashboard.png
  docs/book/.gitbook/assets/intro_dashboard_details.png
  docs/book/.gitbook/assets/intro_dashboard_stacks.png
  docs/book/.gitbook/assets/intro_zenml_overview.png
  docs/book/introduction.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/handle-custom-data-types.md
Labels: documentation, internal

#1539 Fix RestZenStore error handling for list responses
  src/zenml/integrations/neural_prophet/__init__.py
  src/zenml/zen_server/exceptions.py
  tests/unit/zen_server/test_exceptions.py
Labels: bug, internal

#1511 Simplify Dashboard UX via `zenml.show()`
  examples/quickstart/notebooks/quickstart.ipynb
  pyproject.toml
  src/zenml/__init__.py
  src/zenml/api.py
  src/zenml/cli/server.py
  src/zenml/enums.py
  src/zenml/environment.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/utils/networking_utils.py
  src/zenml/zen_server/utils.py
Labels: enhancement, internal

#1546 Revert Quickstart Changes
  examples/quickstart/notebooks/quickstart.ipynb
Labels: internal

#1541 Deprecate some long overdue functions
  src/zenml/cli/secret.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/cli/workspace.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  tests/integration/functional/cli/test_workspace.py
Labels: enhancement, internal

#1532 Define `@pipeline` and `@step` decorators as public API
  src/zenml/__init__.py
  src/zenml/new/pipelines/pipeline_decorator.py
  src/zenml/new/steps/decorated_step.py
  src/zenml/new/steps/step_decorator.py
Labels: enhancement, internal

#1551 Fix automatic dashboard opening after `zenml up`
  src/zenml/api.py
Labels: bug, internal

#1554 Update Neptune README
  examples/neptune_tracking/README.md
Labels: documentation, internal

#1558 Feature/hamza docs
  docs/book/platform-guide/set-up-your-mlops-platform/productionalize-with-ci-cd-ct.md
  docs/book/platform-guide/set-up-your-mlops-platform/user-management.md
  docs/book/user-guide/advanced-guide/connect-your-git-repository.md
  docs/book/user-guide/advanced-guide/containerize-your-pipeline.md
  docs/book/user-guide/advanced-guide/data-versioning-and-artifacts-lineage.md
  docs/book/user-guide/advanced-guide/manage-environments.md
Labels: enhancement, internal

#1553 New README
  README.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/visualize-artifacts.md
Labels: enhancement, internal

#1555 Update example READMEs following deployment PR
  docs/book/component-gallery/orchestrators/kubeflow.md
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/mlflow_registry/README.md
  examples/mlflow_tracking/README.md
  examples/seldon_deployment/README.md
  examples/tekton_pipelines_orchestration/README.md
Labels: documentation, internal

#1542 Fix and update Label Studio example
  examples/label_studio_annotation/README.md
  examples/label_studio_annotation/steps/load_image_data_step.py
  examples/label_studio_annotation/steps/prediction_steps.py
  src/zenml/integrations/label_studio/__init__.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/label_studio/label_studio_utils.py
  src/zenml/integrations/label_studio/steps/label_studio_standard_steps.py
  src/zenml/integrations/pillow/materializers/pillow_image_materializer.py
Labels: bug, internal, dependencies

#1557 Fix linter errors
  src/zenml/cli/stack_recipes.py
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/recipes/stack_recipe_service.py
  src/zenml/utils/pydantic_utils.py
Labels: bug, internal

#1559 Add Vertex as orchestrator and step operator to deploy CLI
  docs/book/advanced-guide/practical/stack-recipes.md
  src/zenml/cli/stack_components.py
Labels: internal

#1563 Fixed some places where the old api was used
  docs/book/.gitbook/assets/youtldr_summarizer_fef5163dc0 (1).webp
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/aws-service-connector.md
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/gcp-service-connector.md
  docs/book/platform-guide/set-up-your-mlops-platform/use-the-secret-store/interact-with-secrets.md
  docs/book/user-guide/advanced-guide/handle-custom-data-types.md
  docs/book/user-guide/component-guide/alerters/slack.md
  docs/book/user-guide/component-guide/data-validators/deepchecks.md
  docs/book/user-guide/component-guide/data-validators/evidently.md
  docs/book/user-guide/component-guide/data-validators/great-expectations.md
  docs/book/user-guide/component-guide/data-validators/whylogs.md
  docs/book/user-guide/component-guide/experiment-trackers/neptune.md
  docs/book/user-guide/component-guide/model-deployers/model-deployers.md
  docs/book/user-guide/component-guide/orchestrators/airflow.md
  docs/book/user-guide/component-guide/secrets-managers/secrets-managers.md
  docs/book/user-guide/component-guide/step-operators/azureml.md
  docs/book/user-guide/component-guide/step-operators/sagemaker.md
  docs/book/user-guide/component-guide/step-operators/spark-kubernetes.md
  docs/book/user-guide/component-guide/step-operators/step-operators.md
  docs/book/user-guide/component-guide/step-operators/vertex.md
  examples/add_your_own/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/neptune_tracking/README.md
  examples/quickstart/README.md
  examples/quickstart_py37/README.md
  examples/sagemaker_orchestration/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
Labels: enhancement, internal

#1556 Easy CSV Visualization
  src/zenml/materializers/__init__.py
  src/zenml/materializers/structured_string_materializer.py
  src/zenml/types.py
  tests/unit/materializers/test_structured_string_materializer.py
Labels: enhancement, internal

#1564 Bugfix/broken links on api docs
  docs/mkdocstrings_helper.py
Labels: bug, internal

#1566 Add `sandbox` to the `ServerDeploymentType`
  src/zenml/models/server_models.py
Labels: enhancement, internal

#1571 Convert dict to tuple in ArtifactConfiguration validator
  src/zenml/config/step_configurations.py
Labels: bug, internal

#1569 Docs cleanup
  README.md
  docs/book/user-guide/advanced-guide/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/containerize-your-pipeline.md
  docs/book/user-guide/advanced-guide/fetch-metadata-within-steps.md
  docs/book/user-guide/advanced-guide/global-settings-of-zenml.md
  docs/book/user-guide/advanced-guide/handle-custom-data-types.md
  docs/book/user-guide/starter-guide/cache-previous-executions.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  docs/book/user-guide/starter-guide/fetch-runs-after-execution.md
  docs/book/user-guide/starter-guide/starter-guide.md
  docs/book/user-guide/starter-guide/understand-stacks.md
  docs/book/user-guide/starter-guide/version-pipelines.md
  src/zenml/cli/__init__.py
  src/zenml/cli/server.py
  src/zenml/materializers/cloudpickle_materializer.py
Labels: documentation, internal

#1576 Update Example for sandbox
  examples/great_expectations_data_validation/README.md
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/run.py
Labels: documentation, enhancement, internal

#1570 Document `zenml show`
  docs/book/user-guide/starter-guide/connect-to-a-deployed-zenml.md
  docs/book/user-guide/starter-guide/starter-guide.md
  src/zenml/cli/__init__.py
Labels: documentation, internal
