Repository zenml-io/zenml, pull requests merged in 2023-09, with the labels that each got.

#1775 Add `bandit` to CI for security linting
  .github/workflows/lint-unit-test.yml
  examples/generative_chat/steps/utils.py
  pyproject.toml
  scripts/check-security.sh
  src/zenml/cli/stack_components.py
  src/zenml/config/build_configuration.py
  src/zenml/image_builders/base_image_builder.py
  src/zenml/integrations/github/code_repositories/github_code_repository.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/integrations/spark/step_operators/spark_step_operator.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/new/pipelines/build_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/cache_utils.py
  src/zenml/services/service_endpoint.py
  src/zenml/steps/base_step.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/utils/uuid_utils.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  tests/integration/examples/lightgbm/steps/data_loader/data_loader_step.py
  tests/integration/examples/mlflow/steps/dynamic_importer_step.py
  tests/integration/examples/seldon/steps/common/importer.py
  tests/integration/examples/xgboost/steps/loader/loader_step.py
  tests/integration/functional/cli/test_server.py
  tests/integration/functional/test_zen_server_api.py
  tests/unit/utils/test_analytics_utils.py
  tests/unit/zen_server/test_zen_server.py
Labels: enhancement, internal, dependencies, tests

#1767 Add `mlstacks` compatibility check to CI
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/release.yml
Labels: enhancement, internal, dependencies, tests

#1769 extend `StepContext` visibility to materializers
  src/zenml/orchestrators/step_runner.py
  tests/integration/functional/steps/test_step_context.py
Labels: enhancement, internal

#1777 Reduce CI runner count
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint-unit-test.yml
  .github/workflows/setup-python-environment.yml
Labels: enhancement, internal, tests

#1766 Add E2E teamplate as example
  .github/workflows/ci.yml
  .github/workflows/update-e2e-template.yml
  examples/e2e/.assets/00_pipelines_composition.png
  examples/e2e/.copier-answers.yml
  examples/e2e/.dockerignore
  examples/e2e/LICENSE
  examples/e2e/Makefile
  examples/e2e/README.md
  examples/e2e/artifacts/__init__.py
  examples/e2e/artifacts/materializer.py
  examples/e2e/artifacts/model_metadata.py
  examples/e2e/config.py
  examples/e2e/pipelines/__init__.py
  examples/e2e/pipelines/batch_inference.py
  examples/e2e/pipelines/training.py
  examples/e2e/requirements.txt
  examples/e2e/run.py
  examples/e2e/steps/__init__.py
  examples/e2e/steps/alerts/__init__.py
  examples/e2e/steps/alerts/notify_on.py
  examples/e2e/steps/data_quality/__init__.py
  examples/e2e/steps/data_quality/drift_quality_gate.py
  examples/e2e/steps/etl/__init__.py
  examples/e2e/steps/etl/data_loader.py
  examples/e2e/steps/etl/inference_data_preprocessor.py
  examples/e2e/steps/etl/train_data_preprocessor.py
  examples/e2e/steps/etl/train_data_splitter.py
  examples/e2e/steps/hp_tuning/__init__.py
  examples/e2e/steps/hp_tuning/hp_tuning_select_best_model.py
  examples/e2e/steps/hp_tuning/hp_tuning_single_search.py
  examples/e2e/steps/inference/__init__.py
  examples/e2e/steps/inference/inference_get_current_version.py
  examples/e2e/steps/inference/inference_predict.py
  examples/e2e/steps/promotion/__init__.py
  examples/e2e/steps/promotion/promote_get_metric.py
  examples/e2e/steps/promotion/promote_get_versions.py
  examples/e2e/steps/promotion/promote_metric_compare_promoter.py
  examples/e2e/steps/training/__init__.py
  examples/e2e/steps/training/model_evaluator.py
  examples/e2e/steps/training/model_trainer.py
  examples/e2e/utils/misc.py
  examples/e2e/utils/preprocess.py
Labels: enhancement, internal

#1784 Fix CI step names
  .github/workflows/ci.yml
Labels: bug, internal

#1776 Add vulnerability scanner
  .github/workflows/codeql.yml
  .github/workflows/trivy-zenml-core.yml
  .github/workflows/trivy-zenserver.yml
Labels: enhancement, internal, tests

#1788 Stop CI from running on push to `develop`
  .github/workflows/ci.yml
Labels: enhancement, internal, tests

#1786 Skip update templates outside PR
  .github/workflows/update-e2e-template.yml
Labels: bug, internal

#1789 Add auto-population of E2E example from template (#1766)
  .github/workflows/ci.yml
  .github/workflows/update-e2e-template.yml
  examples/e2e/.assets/00_pipelines_composition.png
  examples/e2e/.copier-answers.yml
  examples/e2e/.dockerignore
  examples/e2e/LICENSE
  examples/e2e/Makefile
  examples/e2e/README.md
  examples/e2e/artifacts/__init__.py
  examples/e2e/artifacts/materializer.py
  examples/e2e/artifacts/model_metadata.py
  examples/e2e/config.py
  examples/e2e/pipelines/__init__.py
  examples/e2e/pipelines/batch_inference.py
  examples/e2e/pipelines/training.py
  examples/e2e/requirements.txt
  examples/e2e/run.py
  examples/e2e/steps/__init__.py
  examples/e2e/steps/alerts/__init__.py
  examples/e2e/steps/alerts/notify_on.py
  examples/e2e/steps/data_quality/__init__.py
  examples/e2e/steps/data_quality/drift_quality_gate.py
  examples/e2e/steps/etl/__init__.py
  examples/e2e/steps/etl/data_loader.py
  examples/e2e/steps/etl/inference_data_preprocessor.py
  examples/e2e/steps/etl/train_data_preprocessor.py
  examples/e2e/steps/etl/train_data_splitter.py
  examples/e2e/steps/hp_tuning/__init__.py
  examples/e2e/steps/hp_tuning/hp_tuning_select_best_model.py
  examples/e2e/steps/hp_tuning/hp_tuning_single_search.py
  examples/e2e/steps/inference/__init__.py
  examples/e2e/steps/inference/inference_get_current_version.py
  examples/e2e/steps/inference/inference_predict.py
  examples/e2e/steps/promotion/__init__.py
  examples/e2e/steps/promotion/promote_get_metric.py
  examples/e2e/steps/promotion/promote_get_versions.py
  examples/e2e/steps/promotion/promote_metric_compare_promoter.py
  examples/e2e/steps/training/__init__.py
  examples/e2e/steps/training/model_evaluator.py
  examples/e2e/steps/training/model_trainer.py
  examples/e2e/utils/misc.py
  examples/e2e/utils/preprocess.py
Labels: internal, backport

#1778 Fix azure service connector docs
  docs/book/stacks-and-components/auth-management/azure-service-connector.md
Labels: documentation, internal

#1791 Page limit adjustment
  src/zenml/constants.py
  src/zenml/models/filter_models.py
  src/zenml/models/pipeline_models.py
Labels: enhancement, internal

#1792 Prevent simultaneous connection to local and remote servers
  src/zenml/cli/server.py
Labels: bug, enhancement, internal

#1782 Update `MLflow` version to allow support for 2.6.0
  src/zenml/integrations/mlflow/__init__.py
Labels: internal

#1740 Publish server helm chart as part of CI
  .github/workflows/publish_helm_chart.yaml
  .github/workflows/release.yml
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/templates/_helpers.tpl
  src/zenml/zen_server/deploy/helm/templates/hpa.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
Labels: enhancement, internal

#1796 Docs on the use of ZenML-specific environment variables
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/environment-management/environment-variables.md
Labels: documentation, internal

#1780 Add support for newer Evidently versions
  src/zenml/cli/integration.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
  src/zenml/integrations/evidently/materializers/__init__.py
  src/zenml/integrations/evidently/materializers/evidently_profile_materializer.py
  src/zenml/integrations/evidently/steps/__init__.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  tests/unit/integrations/evidently/materializers/__init__.py
  tests/unit/integrations/evidently/materializers/test_evidently_profile_materializer.py
  tests/unit/integrations/evidently/steps/__init__.py
  tests/unit/integrations/evidently/steps/test_ignore_columns.py
Labels: enhancement, internal, dependencies

#1790 Link E2E example to docs
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/pipelining-features/hyper-parameter-tuning.md
  docs/book/user-guide/advanced-guide/pipelining-features/use-failure-success-hooks.md
  docs/book/user-guide/starter-guide/follow-best-practices.md
  docs/book/user-guide/starter-guide/using-project-templates.md
Labels: enhancement, internal

#1798 Copy step instance before applying configuration
  src/zenml/orchestrators/step_runner.py
Labels: bug, internal

#1797 Fix AWS container registry image pushing with service connectors
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
Labels: bug, internal

#1799 Make Sagemaker orchestrator work with connectors
  docs/book/user-guide/advanced-guide/pipelining-features/use-failure-success-hooks.md
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: enhancement, internal

#1801 Add rebase Pre-requisite to PRs template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, enhancement, internal

#1803 Prepare release 0.44.2
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_stores/migrations/versions/0.44.2_release.py
Labels: internal

#1808 Add support for empty API token in Kubernetes service connector.
  docs/book/stacks-and-components/auth-management/kubernetes-service-connector.md
  src/zenml/integrations/kubernetes/service_connectors/kubernetes_service_connector.py
Labels: bug, internal

#1804 Use the container registry credentials to build images with the local image builder
  src/zenml/image_builders/local_image_builder.py
Labels: bug, internal

#1809 Fix CI
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/image-optimiser.yml
  src/zenml/integrations/azure/__init__.py
  tests/integration/examples/xgboost/steps/loader/loader_step.py
Labels: bug, internal

#1802 Implementation of Model table
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/model_models.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/3b68abe58f44_add_model_entity.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/schemas/workspace_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1810 Add documentation on how to debug the SageMaker orchestrator
  docs/book/.gitbook/assets/sagemaker-cloudwatch-logs.png
  docs/book/.gitbook/assets/sagemaker-logs.png
  docs/book/stacks-and-components/component-guide/orchestrators/sagemaker.md
Labels: documentation, internal

#1750 Bump `rich` and `uvicorn`
  pyproject.toml
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_provider.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
Labels: bug, dependencies

#1805 SageMaker: Enable configuring authentication credentials explicitly
  docs/book/stacks-and-components/component-guide/orchestrators/sagemaker.md
  pyproject.toml
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/materializers/numpy_materializer.py
Labels: enhancement, internal

#1811 [Model Watch Tower] Adding ModelVersion and ModelVersionLink entities
  .gitignore
  src/zenml/constants.py
  src/zenml/model/__init__.py
  src/zenml/model/model_stages.py
  src/zenml/models/__init__.py
  src/zenml/models/model_models.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/cdd9599a008d_add_model_version_and_links.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/schemas/workspace_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1815 Fix: ZenML DB migrations don't run if zenml is installed in path with spaces
  src/zenml/zen_stores/migrations/alembic.py
Labels: bug, internal

#1813 [Model Watch Tower] Implement `zenml.log_artifact_metadata()`
  src/zenml/__init__.py
  src/zenml/client.py
  src/zenml/models/run_metadata_models.py
  src/zenml/new/steps/log_artifact_metadata.py
  src/zenml/new/steps/step_context.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/utils/artifact_utils.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/steps/test_log_artifact_metadata.py
  tests/integration/functional/test_client.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/utils/test_secret_utils.py
Labels: enhancement, internal

#1821 Fix mlflow 'run_name' variable overwriting
  src/zenml/integrations/mlflow/steps/mlflow_registry.py
Labels: bug, good first issue

#1824 Add `SECURITY.md` file for vulnerability disclosures.
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation, internal

#1827 Add MFA limitation to service-connectors docs
  docs/book/stacks-and-components/auth-management/aws-service-connector.md
Labels: documentation, internal

#1807 Documentation to get started with a quick cloud stack on GCP
  docs/book/.gitbook/assets/Create_Artifact_Store.png
  docs/book/.gitbook/assets/Create_Container_Registry.png
  docs/book/.gitbook/assets/Create_Container_Registry_Connector.png
  docs/book/.gitbook/assets/Create_Orchestrator.png
  docs/book/.gitbook/assets/Create_Stack.png
  docs/book/.gitbook/assets/GCP_Connector_Key.png
  docs/book/.gitbook/assets/GCP_Connector_Resources.png
  docs/book/.gitbook/assets/GCP_Service_Connector.png
  docs/book/.gitbook/assets/Register_Artifact_Store_Connector.png
  docs/book/.gitbook/assets/Register_Orchestrator_Connector.png
  docs/book/.gitbook/assets/artifact_visualization_dashboard (1).png
  docs/book/.gitbook/assets/data-integrity-results (1).png
  docs/book/.gitbook/assets/data-integrity-results (2).png
  docs/book/.gitbook/assets/data-integrity-results (3).png
  docs/book/.gitbook/assets/data-integrity-results (4).png
  docs/book/.gitbook/assets/statistics-boston-housing (1).png
  docs/book/getting-started/core-concepts.md
  docs/book/stacks-and-components/stack-deployment/cloud-stacks/minimal-gcp-stack.md
  docs/book/toc.md
Labels: documentation, internal

#1819 [Model WatchTower] add ModelConfig to step and pipeline decorators
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/model/model_config.py
  src/zenml/models/__init__.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/pipeline_decorator.py
  src/zenml/new/steps/step_context.py
  src/zenml/new/steps/step_decorator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#1831 Fix missing text in git repo docs
  docs/book/user-guide/advanced-guide/environment-management/connect-your-git-repository.md
Labels: documentation, internal

#1828 Connect stack to a service account
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
Labels: enhancement, internal

#1765 SkyPilot Integration with VM Orchestrators
  docs/book/stacks-and-components/auth-management/aws-service-connector.md
  docs/book/stacks-and-components/auth-management/azure-service-connector.md
  docs/book/stacks-and-components/auth-management/gcp-service-connector.md
  docs/book/stacks-and-components/component-guide/orchestrators/orchestrators.md
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
  docs/book/toc.md
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/integrations/__init__.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/integrations/integration.py
  src/zenml/integrations/skypilot/__init__.py
  src/zenml/integrations/skypilot/flavors/__init__.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_aws_vm_flavor.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_azure_vm_flavor.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_gcp_vm_flavor.py
  src/zenml/integrations/skypilot/orchestrators/__init__.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_aws_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_azure_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_gcp_vm_orchestrator.py
  src/zenml/utils/integration_utils.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  tests/unit/integrations/skypilot/__init__.py
  tests/unit/integrations/skypilot/orchestrators/__init__.py
  tests/unit/integrations/skypilot/orchestrators/test_skypilot_orchestrator.py
  tests/unit/utils/test_integration_utils.py
Labels: enhancement, internal

#1829 Add interactive CLI flow for `zenml stack deploy`
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-using-mlstacks.md
  src/zenml/cli/stack.py
  src/zenml/constants.py
Labels: enhancement, internal

#1830 Add `README` file for helm chart
  src/zenml/zen_server/deploy/helm/README.md
Labels: documentation, enhancement, internal

#1836 Fix slack environment variable in in `generative_chat` example README
  examples/generative_chat/README.md
Labels: documentation, fix

#1822 [Model WatchTower] Add ArtifactConfig (+OSS-2427) & model version management in context (partially)
  .gitignore
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/model/__init__.py
  src/zenml/model/artifact_config.py
  src/zenml/model/link_output_to_model.py
  src/zenml/model/model_config.py
  src/zenml/model/model_stages.py
  src/zenml/models/__init__.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/steps/step_context.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/utils.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_stores/migrations/versions/cdd9599a008d_add_model_version_and_links.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/conftest.py
  tests/unit/steps/test_step_context.py
  tests/unit/steps/test_utils.py
Labels: enhancement, internal

#1838 Prepare release 0.44.3
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.44.3_release.py
Labels: internal

#1818 Discord alerter integration
  docs/book/stacks-and-components/component-guide/alerters/alerters.md
  docs/book/stacks-and-components/component-guide/alerters/discord.md
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/discord/__init__.py
  src/zenml/integrations/discord/alerters/__init__.py
  src/zenml/integrations/discord/alerters/discord_alerter.py
  src/zenml/integrations/discord/flavors/__init__.py
  src/zenml/integrations/discord/flavors/discord_alerter_flavor.py
  src/zenml/integrations/discord/steps/__init__.py
  src/zenml/integrations/discord/steps/discord_alerter_ask_step.py
  src/zenml/integrations/discord/steps/discord_alerter_post_step.py
  tests/integration/examples/discord/__init__.py
  tests/integration/examples/discord/pipelines/__init__.py
  tests/integration/examples/discord/pipelines/ask_pipeline.py
  tests/integration/examples/discord/pipelines/post_pipeline.py
  tests/integration/examples/discord/run.py
  tests/integration/examples/discord/steps/__init__.py
  tests/integration/examples/discord/steps/data_loader.py
  tests/integration/examples/discord/steps/evaluator.py
  tests/integration/examples/discord/steps/formatter.py
  tests/integration/examples/discord/steps/trainer.py
  tests/integration/examples/discord/steps/trainer_mlflow.py
Labels: enhancement, good-second-issue

#1837 Update Neptune dependency: `neptune-client` > `neptune`
  src/zenml/cli/integration.py
  src/zenml/cli/utils.py
  src/zenml/integrations/neptune/__init__.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
  tests/unit/integrations/label_studio/label_config_generators/test_label_config_generators.py
Labels: enhancement, internal, dependencies

#1842 Disable codeql on pushes to `develop`
  .github/workflows/codeql.yml
Labels: enhancement, internal

#1844 Template not updating due to git diff misuse
  .github/workflows/update-e2e-template.yml
  .gitignore
  examples/e2e/Makefile
  examples/e2e/README.md
Labels: bug, internal

#1825 [Model WatchTower] Delete running versions on failed pipelines with `delete_new_version_on_failure ` option
  src/zenml/model/model_config.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/zen_stores/schemas/model_schemas.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#1845 Bump feast version to fix api docs generation
  src/zenml/integrations/feast/__init__.py
Labels: internal
