Repository zenml-io/zenml, pull requests merged in 2023-01, with the labels that each got.

#1209 Test for `enum_utils`
  tests/unit/utils/test_enum_utils.py
Labels: internal, tests

#1218 Add missing space in Azure docs
  docs/book/component-gallery/secrets-managers/azure.md
Labels: documentation, internal

#1202 Test for `dashboard_utils`
  tests/unit/utils/test_dashboard_utils.py
Labels: internal, tests

#1219 Cloud version gets love
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
Labels: documentation, internal

#1220 ZenFiles to ZenML Projects
  README.md
  RELEASE_NOTES.md
  docs/book/drafts/organization.md
  docs/book/getting-started/examples.md
  docs/book/guidelines/best-practices.md
  examples/quickstart/notebooks/quickstart.ipynb
Labels: documentation, internal

#1207 Tests for `pydantic_utils`
  .pyspelling-ignore-words
  tests/unit/utils/test_analytics_utils.py
  tests/unit/utils/test_pydantic_utils.py
Labels: internal, tests

#1224 Customizing Default Materializers for Custom Artifact Stores
  docs/book/advanced-guide/pipelines/materializers.md
Labels: documentation, internal

#1208 Test `typed_model` utilities
  .pyspelling-ignore-words
  tests/unit/utils/test_typed_model_utils.py
Labels: internal, tests

#1222 Enable Airflow<2.4
  src/zenml/integrations/airflow/orchestrators/dag_generator.py
  src/zenml/io/fileio.py
Labels: bug, internal

#1214 Fix `alembic_start` migration if tables exist
  src/zenml/zen_stores/migrations/versions/alembic_start.py
Labels: bug, internal

#1201 Tests for `network_utils`
  tests/unit/utils/test_networking_utils.py
Labels: internal, tests

#1199 Tests for `io_utils` and removal of duplicate code
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/azure/artifact_stores/azure_artifact_store.py
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/io/fileio.py
  src/zenml/utils/io_utils.py
  tests/integration/functional/test_client.py
  tests/unit/io/test_fileio.py
  tests/unit/utils/test_io_utils.py
Labels: internal, tests

#1221 Test `materializer` utilities
  tests/unit/utils/test_materializer_utils.py
Labels: internal, tests

#1229 Add information whether pipeline is running on a stack created by the active user
  src/zenml/pipelines/base_pipeline.py
Labels: enhancement, internal

#1210 Test `daemon` util functions
  src/zenml/utils/daemon.py
  tests/unit/utils/test_daemon.py
Labels: internal, tests

#1230 Test `filesync_model` utils
  tests/unit/utils/test_filesync_model.py
Labels: internal, tests

#1216 Track Source Code of Steps
  src/zenml/config/step_configurations.py
  src/zenml/models/constants.py
  src/zenml/models/step_run_models.py
  src/zenml/models/team_models.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/post_execution/step.py
  src/zenml/steps/base_step.py
  src/zenml/zen_stores/migrations/versions/4a3087070f4e_add_step_source_code.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  tests/integration/functional/post_execution/__init__.py
  tests/integration/functional/post_execution/test_pipeline_run.py
  tests/integration/functional/post_execution/test_step_run.py
  tests/unit/config/test_compiler.py
Labels: enhancement, internal

#1227 Track Pipeline Run Schedules
  src/zenml/cli/__init__.py
  src/zenml/cli/pipeline.py
  src/zenml/client.py
  src/zenml/config/pipeline_deployment.py
  src/zenml/config/schedule.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/pipeline_run_models.py
  src/zenml/models/schedule_model.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/schedule_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/d7b3acf9aa46_create_schedule_table.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/project_schemas.py
  src/zenml/zen_stores/schemas/schedule_schema.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/cli/test_pipeline.py
  tests/integration/functional/post_execution/test_pipeline_run.py
  tests/integration/functional/zen_stores/conftest.py
  tests/integration/functional/zen_stores/test_sql_zen_store.py
Labels: enhancement, internal

#1228 Tests for analytics
  .pyspelling-ignore-words
  src/zenml/utils/analytics_utils.py
  tests/unit/utils/test_analytics_utils.py
Labels: enhancement, internal

#1223 Allow specifying Kubernetes container resource requests and limits
  src/zenml/integrations/kubeflow/utils.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
Labels: enhancement, internal

#1217 Enable cache for all steps that have explicit `enable_cache=True`
  docs/book/starter-guide/pipelines/parameters-and-caching.md
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/orchestrators/cache_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/step_environment.py
  src/zenml/zen_stores/migrations/versions/4a3087070f4e_add_step_source_code.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal, breaking-change

#1225 Make shared stacks visible again
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
Labels: bug, internal

#1232 Bump ruff version
  pyproject.toml
Labels: internal, dependencies

#1234 Fix class resolution in notebooks under Python>=3.10
  src/zenml/utils/source_utils.py
Labels: bug, internal

#1239 Fix Sagemaker README images & pipeline addition
  examples/sagemaker_orchestration/README.md
  examples/sagemaker_orchestration/pipelines/__init__.py
  examples/sagemaker_orchestration/pipelines/fashion_mnist_pipeline.py
  examples/sagemaker_orchestration/run.py
  examples/sagemaker_orchestration/steps/__init__.py
  examples/sagemaker_orchestration/steps/evaluators.py
  examples/sagemaker_orchestration/steps/importers.py
  examples/sagemaker_orchestration/steps/trainers.py
Labels: bug, internal

#1240 Fix Sagemaker README images & pipeline addition (#1239)
  examples/sagemaker_orchestration/README.md
  examples/sagemaker_orchestration/pipelines/__init__.py
  examples/sagemaker_orchestration/pipelines/fashion_mnist_pipeline.py
  examples/sagemaker_orchestration/run.py
  examples/sagemaker_orchestration/steps/__init__.py
  examples/sagemaker_orchestration/steps/evaluators.py
  examples/sagemaker_orchestration/steps/importers.py
  examples/sagemaker_orchestration/steps/trainers.py
Labels: bug, internal, backport

#1233 Step/Pipeline configuration tests
  .pyspelling-ignore-words
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/steps/base_step.py
  tests/unit/config/test_base_settings.py
  tests/unit/config/test_compiler.py
  tests/unit/config/test_secret_reference_mixin.py
  tests/unit/config/test_settings_resolver.py
  tests/unit/config/test_step_configurations.py
  tests/unit/conftest.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/steps/test_base_step.py
Labels: internal, tests

#1242 Removed gRPC from diagrams
  docs/book/assets/diagrams/RemoteServer.png
  docs/book/assets/diagrams/Remote_with_deployer.png
  docs/book/assets/diagrams/Remote_with_exp_tracker.png
  docs/book/assets/diagrams/Remote_with_git_ops.png
  docs/book/assets/diagrams/Remote_with_secrets_manager.png
Labels: enhancement, internal

#1243 Fix copy function to copyfile in registered filesystem
  src/zenml/artifact_stores/base_artifact_store.py
Labels: bug, internal

#1198 Image builder abstraction
  .pyspelling-ignore-words
  docs/book/advanced-guide/pipelines/containerization.md
  docs/book/component-gallery/categories.md
  docs/book/component-gallery/image-builders/custom.md
  docs/book/component-gallery/image-builders/image-builders.md
  docs/book/component-gallery/image-builders/kaniko.md
  docs/book/component-gallery/image-builders/local.md
  docs/book/component-gallery/orchestrators/custom.md
  docs/book/toc.md
  src/zenml/cli/stack.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/image_builders/__init__.py
  src/zenml/image_builders/base_image_builder.py
  src/zenml/image_builders/build_context.py
  src/zenml/image_builders/local_image_builder.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/github/orchestrators/github_actions_orchestrator.py
  src/zenml/integrations/kaniko/__init__.py
  src/zenml/integrations/kaniko/flavors/__init__.py
  src/zenml/integrations/kaniko/flavors/kaniko_image_builder_flavor.py
  src/zenml/integrations/kaniko/image_builders/__init__.py
  src/zenml/integrations/kaniko/image_builders/kaniko_image_builder.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/__init__.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/integrations/spark/step_operators/kubernetes_step_operator.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/stack/flavor_registry.py
  src/zenml/stack/stack.py
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/unit/image_builders/__init__.py
  tests/unit/image_builders/test_build_context.py
  tests/unit/image_builders/test_local_image_builder.py
  tests/unit/integrations/aws/__init__.py
  tests/unit/integrations/aws/orchestrators/__init__.py
  tests/unit/integrations/aws/orchestrators/test_sagemaker_orchestrator.py
  tests/unit/integrations/kaniko/__init__.py
  tests/unit/integrations/kaniko/image_builders/__init__.py
  tests/unit/integrations/kaniko/image_builders/test_kaniko_image_builder.py
  tests/unit/stack/conftest.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal

#1247 Add support for modular recipes to the recipe CLI
  examples/kserve_deployment/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/mlflow_tracking/README.md
  examples/seldon_deployment/README.md
  examples/tekton_pipelines_orchestration/README.md
  src/zenml/cli/stack_recipes.py
  src/zenml/recipes/stack_recipe_service.py
Labels: enhancement, internal

#1244 Add docs on upgrading and troubleshooting zenml server
  docs/book/getting-started/deploying-zenml/cli.md
  docs/book/getting-started/deploying-zenml/docker.md
  docs/book/getting-started/deploying-zenml/helm.md
  docs/book/getting-started/deploying-zenml/troubleshooting.md
  docs/book/toc.md
Labels: documentation, internal

#1236 Improve Seldon and Kserve Docs
  docs/book/component-gallery/model-deployers/kserve.md
  docs/book/component-gallery/model-deployers/seldon.md
Labels: documentation, internal

#1250 Fix SQLAlchemy deprecation warning
  src/zenml/models/filter_models.py
Labels: bug, internal

#1252 satisfy Azure MySQL password requirements
  src/zenml/zen_server/deploy/terraform/recipes/azure/sql.tf
Labels: internal

#1246 Update and improve docker and helm deployment docs
  docs/book/getting-started/deploying-zenml/docker.md
  docs/book/getting-started/deploying-zenml/helm.md
Labels: documentation, internal

#1257 Fixed broken link returned form pipeline runs
  src/zenml/utils/dashboard_utils.py
Labels: bug, internal

#1256 Fix project scoping on `list_project_...` endpoints
  src/zenml/zen_server/routers/projects_endpoints.py
Labels: bug, internal

#1258 Orchestrator tests
  .pyspelling-ignore-words
  src/zenml/orchestrators/cache_utils.py
  src/zenml/orchestrators/step_runner.py
  tests/unit/conftest.py
  tests/unit/orchestrators/local/__init__.py
  tests/unit/orchestrators/local/test_local_orchestrator.py
  tests/unit/orchestrators/local_docker/__init__.py
  tests/unit/orchestrators/local_docker/test_local_docker_orchestrator.py
  tests/unit/orchestrators/test_base_orchestrator.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/orchestrators/test_input_utils.py
  tests/unit/orchestrators/test_output_utils.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/orchestrators/test_step_launcher.py
  tests/unit/orchestrators/test_step_runner.py
  tests/unit/test_general.py
Labels: enhancement, internal

#1261 Always instantiate a zen_store before startup.
  .pyspelling-ignore-words
  src/zenml/zen_server/deploy/deployer.py
Labels: bug, internal

#1263 Fix post execution run fetching
  src/zenml/post_execution/pipeline_run.py
Labels: bug, internal

#1260 Implemented the option to choose between ascending and descending on list calls
  .pyspelling-ignore-words
  src/zenml/enums.py
  src/zenml/models/filter_models.py
  src/zenml/orchestrators/cache_utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/models/test_filter_models.py
  tests/unit/orchestrators/test_cache_utils.py
Labels: enhancement, internal

#1267 Fix logger warning message
  src/zenml/stack/stack.py
Labels: bug, internal

#1264 Integration tests for post execution functions
  src/zenml/post_execution/pipeline_run.py
  tests/integration/functional/post_execution/test_pipeline.py
  tests/integration/functional/post_execution/test_pipeline_run.py
Labels: enhancement, internal

#1238 Introduce `post_execution.BaseView`
  .pyspelling-ignore-words
  src/zenml/post_execution/artifact.py
  src/zenml/post_execution/base_view.py
  src/zenml/post_execution/lineage/lineage_graph.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  tests/unit/post_execution/test_base_view.py
Labels: enhancement, internal

#1268 Make `/cloud` point to enterprise page
  docs/book/getting-started/deploying-zenml/deploying-zenml.md
  examples/spark_distributed_programming/README.md
Labels: documentation, internal

#1249 update mlflow to verion greater than 2.0
  .github/workflows/integration-test.yml
  .pyspelling-ignore-words
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
Labels: enhancement, internal

#1271 Store run start time
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/zen_stores/schemas/schedule_schema.py
Labels: bug, internal

#1276 Fix failing filter on stacks by component id
  src/zenml/models/artifact_models.py
  src/zenml/models/stack_models.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal
