Repository zenml-io/zenml, pull requests merged in 2023-07, with the labels that each got.

#1667 Update Pipeline Migration Page
  docs/book/user-guide/advanced-guide/migrate-your-old-pipelines-and-steps.md
Labels: documentation, internal

#1651 Fix the `zenml deploy` story
  docs/book/platform-guide/set-up-your-mlops-platform/deploy-zenml/deploy-with-zenml-cli.md
  src/zenml/cli/stack_recipes.py
  src/zenml/zen_server/deploy/terraform/recipes/aws/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/vpc.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/sql.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
Labels: bug, documentation, internal

#1647 Fix BentoML deployer
  examples/bentoml_deployment/steps/predictor.py
  src/zenml/integrations/bentoml/__init__.py
  src/zenml/integrations/bentoml/services/bentoml_deployment.py
  src/zenml/integrations/bentoml/steps/bentoml_deployer.py
Labels: bug, internal

#1669 Corrected all mentions in docs form API docs to SDK docs.
  docs/README.md
  docs/book/platform-guide/set-up-your-mlops-platform/deploy-and-set-up-a-cloud-stack/deploy-a-stack-using-stack-recipes.md
  docs/book/platform-guide/set-up-your-mlops-platform/use-the-secret-store/custom-secret-stores.md
  docs/book/user-guide/advanced-guide/configure-steps-pipelines.md
  docs/book/user-guide/component-guide/artifact-stores/azure.md
  docs/book/user-guide/component-guide/artifact-stores/custom.md
  docs/book/user-guide/component-guide/artifact-stores/gcp.md
  docs/book/user-guide/component-guide/artifact-stores/local.md
  docs/book/user-guide/component-guide/artifact-stores/s3.md
  docs/book/user-guide/component-guide/container-registries/custom.md
  docs/book/user-guide/component-guide/data-validators/deepchecks.md
  docs/book/user-guide/component-guide/data-validators/evidently.md
  docs/book/user-guide/component-guide/data-validators/great-expectations.md
  docs/book/user-guide/component-guide/data-validators/whylogs.md
  docs/book/user-guide/component-guide/experiment-trackers/mlflow.md
  docs/book/user-guide/component-guide/experiment-trackers/neptune.md
  docs/book/user-guide/component-guide/experiment-trackers/wandb.md
  docs/book/user-guide/component-guide/model-deployers/custom.md
  docs/book/user-guide/component-guide/model-registries/mlflow.md
  docs/book/user-guide/component-guide/orchestrators/airflow.md
  docs/book/user-guide/component-guide/orchestrators/kubeflow.md
  docs/book/user-guide/component-guide/orchestrators/kubernetes.md
  docs/book/user-guide/component-guide/orchestrators/local-docker.md
  docs/book/user-guide/component-guide/orchestrators/tekton.md
  docs/book/user-guide/component-guide/orchestrators/vertex.md
  docs/book/user-guide/component-guide/step-operators/azureml.md
  docs/book/user-guide/component-guide/step-operators/custom.md
  docs/book/user-guide/component-guide/step-operators/sagemaker.md
  docs/book/user-guide/component-guide/step-operators/spark-kubernetes.md
  docs/book/user-guide/component-guide/step-operators/vertex.md
Labels: enhancement, internal

#1670 Fix CI
  src/zenml/integrations/sklearn/__init__.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: internal

#1674 Add missing quote in docs
  docs/book/user-guide/component-guide/artifact-stores/s3.md
Labels: documentation, internal

#1676 Update Local Docker orchestrator docs
  docs/book/user-guide/component-guide/orchestrators/local-docker.md
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
Labels: documentation, internal

#1675 Relax `fastapi` dependency version
  pyproject.toml
  src/zenml/steps/utils.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: internal

#1671 Improve flavor registration error message
  src/zenml/cli/stack_components.py
  src/zenml/stack/flavor.py
Labels: enhancement, internal

#1679 Simplified Page Iteration
  src/zenml/models/page_model.py
  src/zenml/new/pipelines/pipeline.py
Labels: enhancement, internal

#1672 Document how to deploy ZenML with custom Docker image
  docs/book/platform-guide/set-up-your-mlops-platform/deploy-zenml/deploy-with-custom-image.md
  docs/book/platform-guide/set-up-your-mlops-platform/deploy-zenml/deploy-with-zenml-cli.md
  docs/book/toc.md
  docs/book/user-guide/component-guide/artifact-stores/custom.md
Labels: documentation, internal

#1678 Document the ZenML Client and Models
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/client.md
  docs/book/user-guide/starter-guide/fetch-runs-after-execution.md
Labels: documentation, internal

#1658 Add Label Studio text classification integration and example
  examples/label_studio_text_annotation/README.md
  examples/label_studio_text_annotation/__init__.py
  examples/label_studio_text_annotation/cloud_config/aws/cors.json
  examples/label_studio_text_annotation/data/batch_1/data1.txt
  examples/label_studio_text_annotation/data/batch_1/data2.txt
  examples/label_studio_text_annotation/data/batch_1/data3.txt
  examples/label_studio_text_annotation/data/batch_1/data4.txt
  examples/label_studio_text_annotation/data/batch_1/data5.txt
  examples/label_studio_text_annotation/pipelines/__init__.py
  examples/label_studio_text_annotation/pipelines/inference_pipeline.py
  examples/label_studio_text_annotation/pipelines/training_pipeline.py
  examples/label_studio_text_annotation/requirements.txt
  examples/label_studio_text_annotation/run.py
  examples/label_studio_text_annotation/steps/__init__.py
  examples/label_studio_text_annotation/steps/configuration.py
  examples/label_studio_text_annotation/steps/convert_annotations_step.py
  examples/label_studio_text_annotation/steps/deployment_triggers.py
  examples/label_studio_text_annotation/steps/get_labeled_data.py
  examples/label_studio_text_annotation/steps/get_or_create_dataset.py
  examples/label_studio_text_annotation/steps/load_image_data_step.py
  examples/label_studio_text_annotation/steps/model_deployers.py
  examples/label_studio_text_annotation/steps/prediction_steps.py
  examples/label_studio_text_annotation/steps/pytorch_trainer.py
  examples/label_studio_text_annotation/steps/sync_new_data_to_label_studio.py
  src/zenml/enums.py
  src/zenml/integrations/label_studio/label_config_generators/label_config_generators.py
  tests/unit/integrations/label_studio/label_config_generators/test_label_config_generators.py
Labels: enhancement

#1680 Improve yaml config docs page
  docs/book/user-guide/advanced-guide/configure-steps-pipelines.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: documentation, internal

#1681 Catch correct exception when trying to access step context
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
Labels: bug, internal

#1682 Add option to only export requirements for installed integrations
  examples/label_studio_text_annotation/data/batch_1/data3.txt
  pyproject.toml
  src/zenml/cli/integration.py
  src/zenml/integrations/label_studio/label_config_generators/__init__.py
  tests/integration/functional/cli/test_integration.py
Labels: enhancement, internal

#1687 Fix copy-paste error (Seldon / KServe docstring)
  src/zenml/integrations/kserve/__init__.py
Labels: documentation, internal

#1688 Add avishniakov to `teams.yaml`
  .github/teams.yml
Labels: internal

#1686 Misc slack fixes
  src/zenml/steps/base_step.py
  src/zenml/utils/source_utils.py
Labels: bug, internal

#1689 Make the workspace statistics endpoint more performant
  src/zenml/models/user_models.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal

#1693 Deprecate examples CLI
  src/zenml/cli/example.py
  src/zenml/cli/utils.py
Labels: internal

#1699 Add cloud server deployment type
  src/zenml/models/server_models.py
Labels: enhancement, internal

#1695 Fix Python 3.10 PyYAML Installation Issues
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint-unit-test.yml
  pyproject.toml
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/kubeflow/__init__.py
  src/zenml/integrations/tekton/__init__.py
Labels: bug, internal

#1652 Remove Python 3.7 Support
  README.md
  docs/book/getting-started/installation.md
  examples/quickstart/README.md
  examples/quickstart_py37/README.md
  examples/quickstart_py37/__init__.py
  examples/quickstart_py37/notebooks/_assets/data_drift.png
  examples/quickstart_py37/notebooks/_assets/data_skew.png
  examples/quickstart_py37/notebooks/_assets/inference_pipeline.png
  examples/quickstart_py37/notebooks/_assets/mlflow_ui.png
  examples/quickstart_py37/notebooks/_assets/quickstart_pipelines.png
  examples/quickstart_py37/notebooks/_assets/stack_overview.png
  examples/quickstart_py37/notebooks/_assets/stack_overview_2.png
  examples/quickstart_py37/notebooks/_assets/train_pipeline.png
  examples/quickstart_py37/notebooks/_assets/zenml-up.gif
  examples/quickstart_py37/notebooks/quickstart.ipynb
  examples/quickstart_py37/pipelines/__init__.py
  examples/quickstart_py37/pipelines/inference_pipeline.py
  examples/quickstart_py37/pipelines/training_pipeline.py
  examples/quickstart_py37/requirements.txt
  examples/quickstart_py37/run.py
  examples/quickstart_py37/setup.sh
  examples/quickstart_py37/steps/__init__.py
  examples/quickstart_py37/steps/data_loaders.py
  examples/quickstart_py37/steps/deployment_triggers.py
  examples/quickstart_py37/steps/drift_detection.py
  examples/quickstart_py37/steps/evaluators.py
  examples/quickstart_py37/steps/model_deployers.py
  examples/quickstart_py37/steps/prediction_steps.py
  examples/quickstart_py37/steps/trainers.py
  pyproject.toml
  release-cloudbuild.yaml
  src/zenml/materializers/numpy_materializer.py
  tests/integration/examples/test_mlflow_registry.py
  tests/integration/examples/test_quickstart.py
  tests/integration/examples/test_quickstart_py37.py
  tests/unit/integrations/langchain/materializers/test_langchain_document_materializer.py
  tests/unit/integrations/langchain/materializers/test_openai_embedding_materializer_materializer.py
  tests/unit/integrations/llama_index/materializers/test_llama_index_document_materializer.py
Labels: internal, dependencies

#1704 Disable implicit auth methods for service connectors by default
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/aws-service-connector.md
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/azure-service-connector.md
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/best-security-practices.md
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/gcp-service-connector.md
  src/zenml/constants.py
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
Labels: internal

#1705 Set `MLflow` configuration as environment variables before deployment subprocess
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
Labels: bug, internal

#1706 Fix Migration Guide Links
  docs/book/reference/migration-guide/migration-zero-forty.md
Labels: documentation, internal

#1712 Improve Input Validation Error Message
  src/zenml/steps/entrypoint_function_utils.py
Labels: enhancement, internal

#1703 catch exceptions in `list_model_versions`
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
Labels: bug, internal

#1707 Rename `transition_model_stage` to `transition_model_version_stage`
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
Labels: bug, internal

#1714 Small fixes to global config docs page
  docs/book/user-guide/advanced-guide/environment-management/global-settings-of-zenml.md
Labels: documentation, internal

#1709 Allow specifying extra hosts for LocalDockerOrchestrator
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
Labels: enhancement, internal

#1711 Flexible use of `ignore_cols` in `evidently_report_step`
  src/zenml/integrations/evidently/steps/evidently_report.py
Labels: bug, internal

#1718 Add external artifacts and direct links to run DAG
  src/zenml/lineage_graph/lineage_graph.py
  src/zenml/lineage_graph/node/artifact_node.py
  src/zenml/lineage_graph/node/base_node.py
  src/zenml/lineage_graph/node/step_node.py
  tests/integration/functional/test_lineage_graph.py
Labels: enhancement, internal
