Repository zenml-io/zenml, pull requests merged in 2023-02, with the labels that each got.

#1265 Track server version
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_deployment.py
  src/zenml/models/pipeline_run_models.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/utils/pydantic_utils.py
  src/zenml/zen_stores/migrations/versions/72722dee4686_track_server_version.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  tests/unit/utils/test_pydantic_utils.py
Labels: enhancement, internal, breaking-change

#1279 Bump ruff, drop `autoflake`, add `darglint` back
  .darglint
  .github/workflows/ci.yml
  .github/workflows/docstring.yml
  docs/mkdocstrings_helper.py
  pyproject.toml
  scripts/docstring.sh
  scripts/format.sh
  scripts/lint.sh
  src/zenml/cli/artifact.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/role.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/cli/workspace.py
  src/zenml/client.py
  src/zenml/integrations/great_expectations/visualizers/ge_visualizer.py
  src/zenml/materializers/pandas_materializer.py
  src/zenml/models/component_models.py
  src/zenml/models/filter_models.py
  src/zenml/models/page_model.py
  src/zenml/post_execution/base_view.py
  src/zenml/steps/base_step.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, enhancement, internal, dependencies

#1278 Fixed startswith and endswith
  src/zenml/client.py
  src/zenml/models/filter_models.py
Labels: bug, internal

#1284 Fix workspace scoping on `list_workspace_... endpoints` again
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: bug, internal

#1282 Bug: local ZenML server ignores ip-address CLI argument
  src/zenml/cli/server.py
Labels: bug, internal

#1273 Configure the zenml-server docker image and helm chart to run as non-privileged user
  docker/base.Dockerfile
  docker/local-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docs/book/getting-started/deploying-zenml/docker.md
  docs/book/getting-started/deploying-zenml/helm.md
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/server-service.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  tests/harness/deployment/server_docker_compose.py
Labels: enhancement, internal

#1185 Disentangle K3D code from ZenML
  .github/workflows/ci.yml
  .github/workflows/integration-test.yml
  .pyspelling-ignore-words
  docs/book/advanced-guide/stacks/stack-state-management.md
  docs/book/component-gallery/model-deployers/seldon.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/tekton.md
  docs/book/guidelines/best-practices.md
  docs/book/starter-guide/stacks/registering-stacks.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubeflow_pipelines_orchestration/ZenML Walkthrough Kubeflow Pipelines.ipynb
  examples/kubeflow_pipelines_orchestration/setup.sh
  examples/tekton_pipelines_orchestration/README.md
  src/zenml/cli/server.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/seldon/flavors/seldon_model_deployer_flavor.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/stack/stack.py
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/README.md
  tests/harness/cfg/cloud/aws/environments.yaml
  tests/harness/cfg/cloud/gcp/environments.yaml
  tests/harness/cfg/environments.yaml
  tests/harness/cfg/requirements.yaml
  tests/unit/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
  tests/unit/integrations/kubernetes/orchestrators/test_kubernetes_orchestrator.py
Labels: enhancement, internal

#1277 Rework params / artifact docs
  docs/book/reference/glossary.md
  docs/book/starter-guide/pipelines/parameters-and-caching.md
  docs/book/starter-guide/pipelines/pipelines.md
  docs/book/toc.md
Labels: documentation, internal

#1286 Always add active user to analytics
  src/zenml/utils/analytics_utils.py
Labels: bug, internal

#1288 Fix step and pipeline run metadata in LineageGraph
  src/zenml/post_execution/lineage/lineage_graph.py
  tests/integration/functional/post_execution/lineage/test_lineage_graph.py
Labels: bug, internal

#1189 add validator to endpoint url to replace hostname with k3d or docker …
  src/zenml/integrations/s3/flavors/s3_artifact_store_flavor.py
Labels: enhancement, internal

#1287 Add option to use project templates to initialize a repository
  docs/book/getting-started/examples.md
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
Labels: enhancement, internal

#1206 Add example for Hyperparameter Tuning with ZenML
  examples/dynamic_pipelines/README.md
  examples/dynamic_pipelines/__init__.py
  examples/dynamic_pipelines/dynamic_pipelines/__init__.py
  examples/dynamic_pipelines/dynamic_pipelines/dynamic_pipeline.py
  examples/dynamic_pipelines/dynamic_pipelines/gather_step.py
  examples/dynamic_pipelines/pipelines/__init__.py
  examples/dynamic_pipelines/pipelines/hyperparameter_tuning.py
  examples/dynamic_pipelines/run.py
  examples/dynamic_pipelines/setup.sh
  examples/dynamic_pipelines/steps/__init__.py
  examples/dynamic_pipelines/steps/classifier/__init__.py
  examples/dynamic_pipelines/steps/classifier/random_forest_classifier.py
  examples/dynamic_pipelines/steps/data/__init__.py
  examples/dynamic_pipelines/steps/data/load_breast_cancer_data.py
  examples/dynamic_pipelines/steps/data/load_iris_data.py
  examples/dynamic_pipelines/steps/data/split_data.py
  examples/dynamic_pipelines/steps/evaluation/__init__.py
  examples/dynamic_pipelines/steps/evaluation/accuracy.py
  examples/dynamic_pipelines/steps/evaluation/compare_scores.py
  examples/dynamic_pipelines/steps/evaluation/evaluation_parameters.py
Labels: enhancement

#1289 Bump `ruff` version to 241
  pyproject.toml
Labels: internal, dependencies

#1290 Add docs for run name templates
  docs/book/component-gallery/orchestrators/custom.md
  docs/book/starter-guide/pipelines/pipelines.md
Labels: documentation, internal

#1291 Remove excess help text for `zenml connect` command
  src/zenml/cli/server.py
Labels: bug, enhancement, internal

#1294 Increase default service timeout to 60
  src/zenml/constants.py
Labels: bug, internal

#1297 increase timeout on quickstart example (#1296)
  examples/quickstart/steps/model_deployers.py
Labels: internal, backport

#1303 Add warning about MacOS not being supported
  examples/kserve_deployment/README.md
  examples/seldon_deployment/README.md
Labels: documentation, internal

#1292 Always include .zen in docker builds
  src/zenml/image_builders/build_context.py
  tests/unit/image_builders/test_build_context.py
Labels: bug, internal

#1299 Add warning and docs update for `label_studio` installation issue
  docs/book/component-gallery/annotators/label-studio.md
  src/zenml/cli/integration.py
Labels: bug, documentation, internal

#1302 Loosen version requirements for Great Expectations integration
  src/zenml/integrations/great_expectations/__init__.py
Labels: enhancement, internal, dependencies

#1298 Change zenml init --template to optionally prompt and track email
  docs/book/getting-started/deploying-zenml/docker.md
  docs/book/getting-started/deploying-zenml/helm.md
  docs/book/getting-started/installation/installation.md
  src/zenml/cli/base.py
  src/zenml/cli/text_utils.py
  src/zenml/enums.py
  src/zenml/utils/analytics_utils.py
Labels: enhancement, internal

#1307 Update docs for Neptune experiment tracker integration
  docs/book/advanced-guide/practical/tracking-experiments.md
  docs/book/assets/neptune/neptune_charts.png
  docs/book/component-gallery/experiment-trackers/neptune.md
  examples/neptune_tracking/README.md
Labels: documentation, internal

#1311 Add warning and docs update for `label_studio` installation issue
  docs/book/component-gallery/annotators/label-studio.md
  src/zenml/cli/integration.py
Labels: internal, backport

#1301 Fix the destroy function on the stack recipe CLI
  src/zenml/cli/stack_recipes.py
Labels: bug, internal

#1315 Add missing flavor migrations, make workspace ID optional
  src/zenml/zen_stores/migrations/versions/bea8a6ce3015_port_flavors_into_database.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
Labels: bug, internal

#1316 Bump ruff 246
  pyproject.toml
Labels: enhancement, internal, dependencies

#1317 Remove tag from image name in gcp image builder
  src/zenml/integrations/gcp/image_builders/gcp_image_builder.py
Labels: bug, internal

#1318 Fix docs typo
  docs/book/component-gallery/image-builders/gcp.md
Labels: documentation, internal

#1320 Fix step parameter merging
  src/zenml/steps/base_step.py
  tests/unit/steps/test_base_step.py
Labels: bug, internal

#1308 Increase timeout for mlflow deployment example
  examples/mlflow_deployment/README.md
  examples/mlflow_deployment/run.py
  examples/mlflow_deployment/steps/predictor/predictor_step.py
Labels: bug, documentation, internal

#1322 Workspace/projects fix for dashboard URL output when running pipeline
  src/zenml/utils/dashboard_utils.py
Labels: bug, internal

#1319 Component Metadata Tracking Docs
  docs/book/advanced-guide/pipelines/materializers.md
  docs/book/component-gallery/experiment-trackers/experiment-trackers.md
  docs/book/component-gallery/model-deployers/model-deployers.md
  docs/book/component-gallery/orchestrators/airflow.md
  docs/book/component-gallery/orchestrators/kubeflow.md
  docs/book/component-gallery/orchestrators/orchestrators.md
  docs/book/component-gallery/orchestrators/vertex.md
  docs/book/starter-guide/pipelines/fetching-pipelines.md
Labels: internal

#1312 Add user environment `zenml info` command to CLI for debugging
  .github/ISSUE_TEMPLATE/bug_report.yml
  .pyspelling-ignore-words
  docs/book/misc/debugging.md
  src/zenml/cli/base.py
  src/zenml/cli/utils.py
Labels: enhancement, internal

#1321 Added caching to quickstart
  examples/quickstart/notebooks/quickstart.ipynb
  src/zenml/client.py
  src/zenml/services/local/local_service.py
Labels: internal

#1275 Renovation of the zenstore tests
  .pyspelling-ignore-words
  src/zenml/config/global_config.py
  src/zenml/models/filter_models.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/harness/deployment/server_docker_compose.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/cli/test_user_management.py
  tests/integration/functional/cli/test_utils.py
  tests/integration/functional/post_execution/lineage/test_lineage_graph.py
  tests/integration/functional/post_execution/test_pipeline_run.py
  tests/integration/functional/post_execution/test_step_run.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/conftest.py
  tests/integration/functional/zen_stores/test_sql_zen_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1327 Fixes GCP docs typo
  docs/book/component-gallery/container-registries/gcp.md
Labels: documentation

#1325 Remove deprecated CLI options
  src/zenml/cli/example.py
  src/zenml/cli/integration.py
  src/zenml/cli/model.py
  src/zenml/cli/secret.py
Labels: enhancement, internal, breaking-change

#1323 GCP Image Builder network
  docs/book/component-gallery/image-builders/gcp.md
  src/zenml/integrations/gcp/flavors/gcp_image_builder_flavor.py
  src/zenml/integrations/gcp/image_builders/gcp_image_builder.py
Labels: bug

#1324 improved flavor docs
  .pyspelling-ignore-words
  docs/book/advanced-guide/stacks/custom-flavors.md
  docs/book/component-gallery/alerters/custom.md
  docs/book/component-gallery/artifact-stores/custom.md
  docs/book/component-gallery/container-registries/custom.md
  docs/book/component-gallery/data-validators/custom.md
  docs/book/component-gallery/experiment-trackers/custom.md
  docs/book/component-gallery/image-builders/custom.md
  docs/book/component-gallery/model-deployers/custom.md
  docs/book/component-gallery/orchestrators/custom.md
  docs/book/component-gallery/secrets-managers/custom.md
  docs/book/component-gallery/step-operators/custom.md
  docs/book/misc/integrating.md
  src/zenml/cli/stack_components.py
  src/zenml/integrations/README.md
Labels: documentation, internal

#1304 Validate kserve model name
  .github/workflows/unit-test.yml
  .pyspelling-ignore-words
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/kserve/steps/kserve_step_utils.py
  tests/unit/integrations/kserve/__init__.py
  tests/unit/integrations/kserve/test_kserve_step_utils.py
Labels: bug, internal

#1332 Fix post-execution run sorting
  src/zenml/post_execution/pipeline.py
  tests/integration/examples/utils.py
  tests/integration/functional/cli/test_stack.py
  tests/unit/image_builders/test_build_context.py
  tests/unit/post_execution/test_pipeline.py
Labels: bug, internal

#1313 Secrets store with SQL back-end
  .pyspelling-ignore-words
  docs/book/advanced-guide/practical/secrets-management.md
  docs/book/component-gallery/secrets-managers/secrets-managers.md
  docs/book/getting-started/deploying-zenml/docker.md
  src/zenml/cli/__init__.py
  src/zenml/cli/secret.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/config/secret_reference_mixin.py
  src/zenml/config/secrets_store_config.py
  src/zenml/config/store_config.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/__init__.py
  src/zenml/models/base_models.py
  src/zenml/models/page_model.py
  src/zenml/models/secret_models.py
  src/zenml/stack/authentication_mixin.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/analytics_utils.py
  src/zenml/utils/proxy_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/deploy/deployer.py
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/routers/secrets_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/env.py
  src/zenml/zen_stores/migrations/versions/03742aa7fdd7_add_secrets.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/schemas/workspace_schemas.py
  src/zenml/zen_stores/secrets_stores/__init__.py
  src/zenml/zen_stores/secrets_stores/base_secrets_store.py
  src/zenml/zen_stores/secrets_stores/rest_secrets_store.py
  src/zenml/zen_stores/secrets_stores/secrets_store_interface.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_role.py
  tests/integration/functional/cli/test_secret.py
  tests/integration/functional/cli/test_stack.py
  tests/integration/functional/cli/test_user_management.py
  tests/integration/functional/cli/test_utils.py
  tests/integration/functional/cli/test_workspace.py
  tests/integration/functional/cli/utils.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_secrets_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1314 Add warning when attempting server connection without user permissions
  .pyspelling-ignore-words
  src/zenml/cli/server.py
  tests/integration/functional/cli/test_server.py
Labels: bug, internal, breaking-change

#1338 Keep CLI help text for `zenml pipeline` to a single line
  src/zenml/cli/pipeline.py
Labels: enhancement, internal

#1266 Rename page attributes
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/models/page_model.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/zen_stores/test_secrets_store.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/orchestrators/test_input_utils.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#1355 Fix `secret create` docs error for secret store
  docs/book/advanced-guide/practical/secrets-management.md
  src/zenml/cli/__init__.py
Labels: documentation, internal

#1356 Fix `secret create` docs error for secret store (#1355)
  docs/book/advanced-guide/practical/secrets-management.md
  src/zenml/cli/__init__.py
Labels: documentation, internal, backport

#1336 Update README for test environment provisioning
  tests/README.md
Labels: bug, internal, dependencies

#1345 Disable name prefix matching when updating/deleting entities
  src/zenml/cli/base.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/client.py
  tests/integration/functional/cli/test_stack.py
  tests/integration/functional/cli/test_stack_components.py
  tests/integration/functional/secrets_manager/utils.py
  tests/integration/functional/test_client.py
Labels: bug, internal

#1358 Add Kubeflow Pipeline UI Port to deprecated config
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
Labels: bug, internal
