Repository zenml-io/zenml, pull requests merged in 2023-12, with the labels that each got.

#2099 Fix migration for unowned stacks/components
  src/zenml/zen_stores/migrations/versions/7500f434b71c_remove_shared_columns.py
Labels: bug, internal

#2064 Polymorthic `run_metadata`
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/enums.py
  src/zenml/models/v2/core/run_metadata.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/zen_server/routers/run_metadata_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/8ed03137cacc_polymorthic_run_metadata.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/test_client.py
  tests/integration/functional/test_lineage_graph.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2108 Lock in airflow version as higher versions will fail
  docs/book/stacks-and-components/component-guide/orchestrators/airflow.md
Labels: documentation, internal

#2110 Swap contents for HTMLString and MarkdownString in docs
  docs/book/user-guide/advanced-guide/artifact-management/visualize-artifacts.md
Labels: documentation

#2107 Fix secrets list with cloud secrets stores and RBAC
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
Labels: bug, internal

#2112 More track events
  src/zenml/analytics/enums.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2104 Fix pipeline run cascade deletion
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  tests/integration/functional/cli/test_pipeline.py
  tests/integration/functional/steps/test_model_version.py
Labels: bug, internal

#2114 Allow extra values when dehydrating response models
  src/zenml/zen_server/rbac/utils.py
Labels: bug, internal

#2103 Request optimizations
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/component.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/stack/stack.py
  src/zenml/utils/code_repository_utils.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/conftest.py
  tests/unit/orchestrators/test_publish_utils.py
Labels: enhancement, internal

#2115 Pagination in model versions
  src/zenml/models/v2/core/model.py
Labels: bug, internal

#2105 Add `StepContext.inputs` property
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
  src/zenml/new/steps/step_context.py
  src/zenml/stack/stack_component.py
  tests/integration/functional/steps/test_step_context.py
Labels: enhancement, internal

#2123 bump timeout for mlflow example
  tests/integration/examples/mlflow/pipelines/deployment_pipelines/deployment_training_pipeline.py
  tests/integration/examples/mlflow/steps/predictor_step.py
Labels: internal

#2127 pin langchain version
  src/zenml/integrations/langchain/__init__.py
Labels: internal

#2128 Fix wandb
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
Labels: bug, internal

#2125 Prepare release 0.51.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.51.0_release.py
Labels: internal

#2130 Revert "Prepare release 0.51.0"
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.51.0_release.py
Labels: internal

#2131 Fixing the colab issues with stack cache
  src/zenml/models/v2/core/stack.py
  src/zenml/stack/stack.py
Labels: bug, internal

#2132 Misc/prepare release 0.51.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.51.0_release.py
Labels: internal

#2058 Passing pipeline parameters as yaml config
  .github/workflows/update-templates-to-examples.yml
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  examples/e2e/.copier-answers.yml
  examples/e2e/configs/train_config.yaml
  examples/e2e/pipelines/training.py
  src/zenml/cli/base.py
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/steps/base_step.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/unit/steps/test_base_step_new.py
Labels: enhancement, internal, breaking-change

#2065 Side-effect free tests
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/logs.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/cli/test_base.py
  tests/integration/functional/cli/test_model.py
  tests/integration/functional/cli/test_pipeline.py
  tests/integration/functional/cli/test_stack.py
  tests/integration/functional/cli/test_stack_components.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/integration/functional/steps/test_model_version.py
  tests/integration/functional/test_client.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/conftest.py
  tests/unit/models/test_artifact_models.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/pipelines/test_build_utils.py
Labels: enhancement, internal

#2124 Fix various bugs
  examples/e2e/.copier-answers.yml
  src/zenml/cli/service_connectors.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/stack/stack.py
  src/zenml/zen_stores/migrations/versions/e5225281b4d3_add_connector_skew_tolerance.py
  src/zenml/zen_stores/schemas/service_connector_schemas.py
  tests/integration/functional/zen_stores/utils.py
Labels: bug, internal

#2140 Adding a condition to the PR template
  .github/pull_request_template.md
Labels: internal

#2148 trying local caching for custom runners
  .github/actions/setup_environment/action.yml
  .github/workflows/integration-test.yml
  .github/workflows/setup-python-environment.yml
  src/zenml/utils/source_utils.py
Labels: enhancement, internal

#2150 make template tests runs on ubunut latest instead of custom runners
  .github/workflows/ci.yml
Labels: enhancement, internal

#2147 Fix various bugs
  src/zenml/orchestrators/utils.py
Labels: bug, internal

#2160 Fix `importlib` calling to `importlib.metadata`
  pyproject.toml
Labels: internal

#2119 Debugging `zenml clean`
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/zen_server/deploy/deployer.py
Labels: bug, internal

#2109 Add metadata to model versions
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  examples/e2e/configs/train_config.yaml
  examples/e2e/pipelines/training.py
  examples/e2e/steps/deployment/deployment_deploy.py
  examples/e2e/steps/promotion/promote_with_metric_compare.py
  examples/e2e/steps/training/model_trainer.py
  src/zenml/cli/base.py
  src/zenml/cli/model.py
  src/zenml/enums.py
  src/zenml/model/model_version.py
  src/zenml/model/utils.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2146 Adding a link from pipeline runs to code repositories
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
Labels: bug, internal

#2138 Moving tags to the body for artifacts and artifact versions
  examples/e2e/.copier-answers.yml
  examples/e2e/configs/train_config.yaml
  examples/e2e/pipelines/training.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  tests/unit/conftest.py
Labels: enhancement, internal

#2129 Fix Client doesn't recover from remote connection resets
  examples/nlp-case/run.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#2061 [backport/0.43] Backport important patches
  .github/workflows/publish_api_docs.yml
  .github/workflows/publish_to_pypi.yml
  README.md
  RELEASE_NOTES.md
  docs/book/toc.md
  pyproject.toml
  release-cloudbuild.yaml
  scripts/install-zenml-dev.sh
  src/zenml/VERSION
  src/zenml/integrations/langchain/__init__.py
  src/zenml/integrations/llama_index/materializers/document_materializer.py
  src/zenml/integrations/llama_index/materializers/gpt_index_materializer.py
  src/zenml/integrations/openai/__init__.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  tests/unit/integrations/langchain/materializers/test_openai_embedding_materializer_materializer.py
  tests/unit/integrations/llama_index/__init__.py
  tests/unit/integrations/llama_index/materializers/__init__.py
  tests/unit/integrations/llama_index/materializers/test_llama_index_document_materializer.py
Labels: internal

#2062 [backport/0.42] Backport important patches
  .github/actions/setup_environment/action.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/publish_to_pypi.yml
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  release-cloudbuild.yaml
  src/zenml/VERSION
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/langchain/__init__.py
  src/zenml/integrations/llama_index/materializers/document_materializer.py
  src/zenml/integrations/llama_index/materializers/gpt_index_materializer.py
  src/zenml/integrations/openai/__init__.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  tests/unit/integrations/langchain/materializers/test_openai_embedding_materializer_materializer.py
  tests/unit/integrations/llama_index/__init__.py
  tests/unit/integrations/llama_index/materializers/__init__.py
  tests/unit/integrations/llama_index/materializers/test_llama_index_document_materializer.py
Labels: internal

#2162 Fix `get_pipeline_context().model_version.get_artifact(...)` flow
  examples/e2e/.copier-answers.yml
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/model/model_version.py
  src/zenml/orchestrators/step_runner.py
  tests/integration/functional/steps/test_model_version.py
Labels: bug, internal

#2165 Add CodeRabbit config to repo base
  .coderabbit.yaml
Labels: enhancement, internal

#2087 Add dependabot updates for Github Actions on CI
  .github/dependabot.yml
Labels: enhancement, internal

#2113 Run DB migration testing using MySQL alongside SQLite
  .github/workflows/release.yml
  scripts/test-migrations.sh
Labels: enhancement, internal

#2164 Remove `precommit`
  .pre-commit-config.yaml
  pyproject.toml
Labels: internal, dependencies

#2167 Prepare release 0.53.0
  README.md
  RELEASE_NOTES.md
  examples/quickstart/.copier-answers.yml
  examples/quickstart/quickstart.ipynb
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.53.0_release.py
Labels: internal

#2169 Update copier command in test-migrations.sh
  scripts/test-migrations.sh
Labels: bug, internal

#2171 Importlib import fix for DB migration testing
  scripts/test-migrations.sh
Labels: bug, internal

#2182 Remove secrets manager flavors from DB
  examples/quickstart/README.md
  examples/quickstart/pipelines/inference.py
  examples/quickstart/quickstart.ipynb
  examples/quickstart/steps/model_evaluator.py
  examples/quickstart/steps/model_promoter.py
  examples/quickstart/steps/model_trainer.py
  src/zenml/zen_stores/migrations/versions/a39c4184c8ce_remove_secrets_manager_flavors.py
Labels: bug, internal

#2183 Prepare 0.53.1 release
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.53.1_release.py
  src/zenml/zen_stores/migrations/versions/a39c4184c8ce_remove_secrets_manager_flavors.py
Labels: internal

#2172 Update package name for nightly build
  .github/workflows/publish_to_pypi_nightly.yml
  docs/book/getting-started/installation.md
Labels: bug, internal

#2174 Remove space saver action + upgrade other actions
  .github/actions/setup_environment/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/image-optimiser.yml
  .github/workflows/integration-test.yml
  .github/workflows/mixpanel-test-data.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_helm_chart.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/publish_to_pypi_nightly.yml
  .github/workflows/release.yml
  .github/workflows/replace_api_docs_version
  .github/workflows/setup-python-environment.yml
  .github/workflows/trivy-zenml-core.yml
  .github/workflows/trivy-zenserver.yml
  .github/workflows/update-templates-to-examples.yml
Labels: enhancement, internal, dependencies

#2185 mutable names in Model and MV
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2189 Fix image building for nightly container builds
  release-cloudbuild-nightly.yaml
Labels: bug, internal

#2188 Test that artifacts not get linked to model version not from context
  tests/integration/functional/model/test_model_version.py
Labels: bug, internal

#2153 Add blocks field to SlackAlerterParameters for custom slack blocks
  docs/book/stacks-and-components/component-guide/alerters/slack.md
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/integrations/slack/steps/slack_alerter_post_step.py
Labels: enhancement

#2111 Model control plane technical documentation
  docs/book/.gitbook/assets/model-control-plane-dashboard.png
  docs/book/getting-started/core-concepts.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/advanced-guide.md
  docs/book/user-guide/advanced-guide/artifact-management/model-management.md
Labels: documentation, internal

#2194 Backporting MCP docs
  docs/book/.gitbook/assets/model-control-plane-dashboard.png
  docs/book/getting-started/core-concepts.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/advanced-guide.md
  docs/book/user-guide/advanced-guide/artifact-management/model-management.md
Labels: internal, backport

#2197 Alembic branching issue fix
  src/zenml/zen_stores/migrations/versions/4e1972485075_endpoint_artifact_deployment_artifact.py
Labels: bug, internal
