Repository zenml-io/zenml, pull requests merged in 2023-11, with the labels that each got.

#2003 Model scoped endpoints
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/model/artifact_config.py
  src/zenml/models/model_models.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2006 Delete model version in cli
  src/zenml/cli/model.py
  tests/integration/functional/cli/test_model.py
Labels: enhancement, internal

#2007 Add latest version to model list response
  src/zenml/models/model_models.py
  src/zenml/zen_stores/schemas/model_schemas.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2018 Fix `gcs bucket` docs error message
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: documentation, internal

#2017 Fix `Skypilot` docs configuration
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
Labels: documentation, internal

#1992 Fix Build Options of `GCPImageBuilder`
  src/zenml/integrations/gcp/image_builders/gcp_image_builder.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal

#2015 Small improvements to Hub docs page
  docs/book/user-guide/advanced-guide/environment-management/use-the-hub.md
Labels: documentation, internal

#2022 Release 0.46.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.46.0_release.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: internal

#2027 Pin OpenAI integration to `<1.0.0`
  src/zenml/integrations/openai/__init__.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
Labels: bug, internal, dependencies

#2023 Make error message nicer for when two artifacts that share a prefix are found
  src/zenml/client.py
Labels: bug, enhancement, internal

#2032 Fix stuck/broken CI
  src/zenml/client.py
Labels: internal

#2025 Increase `step.source_code` Cut-Off Limit
  src/zenml/orchestrators/step_launcher.py
  tests/integration/functional/models/test_step_run.py
Labels: enhancement, internal

#2016 Improve artifact linkage logging in MCP
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
Labels: enhancement, internal

#1947 [Artifacts Tab] Rework External Artifact
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  tests/integration/functional/steps/test_external_artifact.py
  tests/integration/functional/steps/test_model_config.py
  tests/unit/steps/test_external_artifact.py
Labels: enhancement, internal, breaking-change

#2028 Upgrade feast so apidocs don't fail no mo
  scripts/generate-docs.sh
Labels: bug, internal

#2033 Remove NumPy Visualizations for 2D Arrays
  src/zenml/materializers/numpy_materializer.py
Labels: internal

#2037 Fix user activation bug
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/users_endpoints.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: bug, internal

#2030 Remove `create_new_model_version` arg of `ModelConfig`
  .gitignore
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/enums.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_config.py
  src/zenml/models/model_models.py
  src/zenml/new/pipelines/model_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/integration/functional/steps/test_external_artifact.py
  tests/integration/functional/steps/test_model_config.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/model/test_model_config_init.py
Labels: enhancement, internal, breaking-change

#2029 Extend the wait period in between PyPi package publication and Docker image building for releases
  .github/workflows/release.yml
Labels: bug, enhancement, internal

#2024 Make `zenml up` prefill username when launching dashboard
  src/zenml/api.py
  src/zenml/cli/server.py
Labels: enhancement, internal

#2011 Add warning when artifact store cannot be loaded
  src/zenml/utils/artifact_utils.py
Labels: enhancement, internal

#2019 Add extra config to `Kaniko` docs
  docs/book/stacks-and-components/component-guide/image-builders/kaniko.md
  src/zenml/integrations/kaniko/flavors/kaniko_image_builder_flavor.py
Labels: internal

#1840 ZenML API Keys and Service Accounts
  docs/book/user-guide/starter-guide/switch-to-production.md
  src/zenml/cli/__init__.py
  src/zenml/cli/service_accounts.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/__init__.py
  src/zenml/models/api_key_models.py
  src/zenml/models/service_account_models.py
  src/zenml/models/user_models.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/jwt.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/service_accounts_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/93cbda80a732_add_service_accounts.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/api_key_schemas.py
  src/zenml/zen_stores/schemas/device_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_secrets_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/conftest.py
  tests/unit/zen_server/test_jwt.py
Labels: enhancement, internal

#2036 Create tags table
  .github/workflows/setup-python-environment.yml
  examples/quickstart/steps/training_data_loader.py
  scripts/check-alembic-branches.sh
  src/zenml/cli/__init__.py
  src/zenml/cli/model.py
  src/zenml/cli/tag.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/model/model_config.py
  src/zenml/models/__init__.py
  src/zenml/models/model_base_model.py
  src/zenml/models/model_models.py
  src/zenml/models/tag_models.py
  src/zenml/utils/tag_utils.py
  src/zenml/zen_server/routers/tags_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/6119cd9b93c2_tags_table.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/cli/test_model.py
  tests/integration/functional/cli/test_tag.py
  tests/integration/functional/cli/utils.py
  tests/integration/functional/model/test_model_config.py
  tests/integration/functional/utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/models/test_model_models.py
Labels: enhancement, internal

#2045 Fix duplicate default user
  src/zenml/zen_stores/migrations/versions/722392c91006_make_is_service_account_mandatory.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#2047 Prepare release 0.47.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.47.0_release.py
Labels: internal

#2050 Connectors docs small fixes
  docs/book/stacks-and-components/auth-management/auth-management.md
  docs/book/stacks-and-components/auth-management/aws-service-connector.md
  docs/book/stacks-and-components/auth-management/azure-service-connector.md
  docs/book/stacks-and-components/auth-management/gcp-service-connector.md
  docs/book/stacks-and-components/auth-management/kubernetes-service-connector.md
  docs/book/stacks-and-components/auth-management/service-connectors-guide.md
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/integrations/kubernetes/service_connectors/kubernetes_service_connector.py
Labels: documentation, enhancement, internal

#2035 Feature/revamp model endpoints
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/model/artifact_config.py
  src/zenml/model/model_version.py
  src/zenml/models/model_models.py
  src/zenml/zen_server/routers/model_versions_endpoints.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_artifact_config.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#2053 Make helm chart more robust to accidental secret deletions
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
Labels: enhancement, internal

#2055 Separate helm hook resources from regular resources
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/templates/serviceaccount.yaml
Labels: bug, internal

#2060 Model version endpoint fixes
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: bug, internal

#1725 Feature/configurable service account for seldon predictor service
  docs/book/stacks-and-components/component-guide/model-deployers/seldon.md
  src/zenml/integrations/seldon/seldon_client.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
Labels: enhancement

#2051 Adding NLP Template Example
  .github/workflows/templates-test.yml
  .github/workflows/update-templates-to-examples.yml
  examples/nlp-case/.assets/00_pipelines_composition.png
  examples/nlp-case/.copier-answers.yml
  examples/nlp-case/.dockerignore
  examples/nlp-case/LICENSE
  examples/nlp-case/Makefile
  examples/nlp-case/README.md
  examples/nlp-case/config.yaml
  examples/nlp-case/gradio/Dockerfile
  examples/nlp-case/gradio/__init__.py
  examples/nlp-case/gradio/app.py
  examples/nlp-case/gradio/requirements.txt
  examples/nlp-case/gradio/serve.yaml
  examples/nlp-case/pipelines/__init__.py
  examples/nlp-case/pipelines/deploying.py
  examples/nlp-case/pipelines/promoting.py
  examples/nlp-case/pipelines/training.py
  examples/nlp-case/requirements.txt
  examples/nlp-case/run.py
  examples/nlp-case/steps/__init__.py
  examples/nlp-case/steps/alerts/__init__.py
  examples/nlp-case/steps/alerts/notify_on.py
  examples/nlp-case/steps/dataset_loader/__init__.py
  examples/nlp-case/steps/dataset_loader/data_loader.py
  examples/nlp-case/steps/deploying/__init__.py
  examples/nlp-case/steps/deploying/local_deployment.py
  examples/nlp-case/steps/deploying/save_model.py
  examples/nlp-case/steps/promotion/__init__.py
  examples/nlp-case/steps/promotion/promote_get_metrics.py
  examples/nlp-case/steps/promotion/promote_metric_compare_promoter.py
  examples/nlp-case/steps/register/__init__.py
  examples/nlp-case/steps/register/model_log_register.py
  examples/nlp-case/steps/registrer/__init__.py
  examples/nlp-case/steps/registrer/model_log_register.py
  examples/nlp-case/steps/tokenizer_loader/__init__.py
  examples/nlp-case/steps/tokenizer_loader/tokenizer_loader.py
  examples/nlp-case/steps/tokenzation/__init__.py
  examples/nlp-case/steps/tokenzation/tokenization.py
  examples/nlp-case/steps/training/__init__.py
  examples/nlp-case/steps/training/model_trainer.py
  examples/nlp-case/utils/misc.py
Labels: enhancement, internal

#2069 Fix CI
  scripts/install-zenml-dev.sh
  src/zenml/integrations/langchain/__init__.py
Labels: internal

#2067 Remove user name from orchestrator run name
  src/zenml/orchestrators/utils.py
Labels: bug, internal

#2052 Add warnings/updates to Huggingface Spaces deployment docs
  docs/book/deploying-zenml/zenml-self-hosted/deploy-using-huggingface-spaces.md
Labels: documentation, internal

#2031 Nightly builds
  .github/workflows/nightly_build.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_to_pypi_nightly.yml
  .github/workflows/setup-python-environment.yml
  release-cloudbuild-nightly.yaml
Labels: enhancement, internal

#2059 Fixes for `k3d` deployments via `mlstacks` using the ZenML CLI wrapper
  examples/e2e/.copier-answers.yml
  examples/e2e/pipelines/batch_inference.py
  examples/e2e/run.py
  examples/e2e/steps/deployment/deployment_deploy.py
  examples/e2e/steps/etl/inference_data_preprocessor.py
  examples/e2e/steps/hp_tuning/hp_tuning_select_best_model.py
  examples/e2e/steps/hp_tuning/hp_tuning_single_search.py
  examples/e2e/steps/inference/inference_predict.py
  examples/e2e/steps/promotion/compute_performance_metrics_on_current_data.py
  examples/e2e/steps/promotion/promote_with_metric_compare.py
  examples/e2e/steps/training/model_trainer.py
  src/zenml/utils/mlstacks_utils.py
  tests/unit/utils/test_mlstacks_utils.py
Labels: bug, internal

#2077 Set nightly builds to run at half-past the hour
  .github/workflows/nightly_build.yml
Labels: enhancement, internal

#2076 Set DCP template tag
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  src/zenml/cli/base.py
Labels: enhancement, internal

#2078 Fix some filter options for pipeline runs
  src/zenml/models/v2/core/pipeline_run.py
Labels: bug, internal

#2080 Add missing dehydration in get_service_connector endpoint
  src/zenml/zen_server/routers/service_connectors_endpoints.py
Labels: bug, internal

#2082 Replace `black` with `ruff format` / bump `mypy`
  examples/e2e/utils/__init__.py
  pyproject.toml
  scripts/format.sh
  scripts/lint.sh
  src/zenml/cli/utils.py
  src/zenml/constants.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/seldon/custom_deployer/zenml_custom_model.py
  src/zenml/integrations/spark/materializers/spark_model_materializer.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
  src/zenml/models/v2/base/page.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
  src/zenml/zen_stores/migrations/alembic.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/config/test_compiler.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/stack/test_stack.py
Labels: enhancement, internal, dependencies

#2079 ModelVersion in pipeline context to pass in steps
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/model/model_version.py
  src/zenml/new/pipelines/pipeline_context.py
  tests/integration/functional/pipelines/test_pipeline_context.py
Labels: enhancement, internal

#2083 Pin `bcrypt`
  pyproject.toml
Labels: bug, internal, dependencies

#2085 Enable Skypilot deployment on ZenML CLI
  src/zenml/cli/stack.py
Labels: bug, enhancement, internal

#2092 Updated to one quickstart again
  examples/quickstart/notebooks/quickstart-zenml-cloud.ipynb
  examples/quickstart/notebooks/quickstart.ipynb
Labels: internal

#2070 Adding NLP Template Example (#2051)
  .github/workflows/templates-test.yml
  .github/workflows/update-templates-to-examples.yml
  examples/nlp-case/.assets/00_pipelines_composition.png
  examples/nlp-case/.copier-answers.yml
  examples/nlp-case/.dockerignore
  examples/nlp-case/LICENSE
  examples/nlp-case/Makefile
  examples/nlp-case/README.md
  examples/nlp-case/config.yaml
  examples/nlp-case/gradio/Dockerfile
  examples/nlp-case/gradio/__init__.py
  examples/nlp-case/gradio/app.py
  examples/nlp-case/gradio/requirements.txt
  examples/nlp-case/gradio/serve.yaml
  examples/nlp-case/pipelines/__init__.py
  examples/nlp-case/pipelines/deploying.py
  examples/nlp-case/pipelines/promoting.py
  examples/nlp-case/pipelines/training.py
  examples/nlp-case/requirements.txt
  examples/nlp-case/run.py
  examples/nlp-case/steps/__init__.py
  examples/nlp-case/steps/alerts/__init__.py
  examples/nlp-case/steps/alerts/notify_on.py
  examples/nlp-case/steps/dataset_loader/__init__.py
  examples/nlp-case/steps/dataset_loader/data_loader.py
  examples/nlp-case/steps/deploying/__init__.py
  examples/nlp-case/steps/deploying/local_deployment.py
  examples/nlp-case/steps/deploying/save_model.py
  examples/nlp-case/steps/promotion/__init__.py
  examples/nlp-case/steps/promotion/promote_get_metrics.py
  examples/nlp-case/steps/promotion/promote_metric_compare_promoter.py
  examples/nlp-case/steps/register/__init__.py
  examples/nlp-case/steps/register/model_log_register.py
  examples/nlp-case/steps/tokenizer_loader/__init__.py
  examples/nlp-case/steps/tokenizer_loader/tokenizer_loader.py
  examples/nlp-case/steps/tokenzation/__init__.py
  examples/nlp-case/steps/tokenzation/tokenization.py
  examples/nlp-case/steps/training/__init__.py
  examples/nlp-case/steps/training/model_trainer.py
  examples/nlp-case/utils/misc.py
Labels: enhancement, internal

#2093 Backport - Adding NLP Template Example (#2051) (#2070)
  .github/workflows/templates-test.yml
  .github/workflows/update-templates-to-examples.yml
  examples/nlp-case/.assets/00_pipelines_composition.png
  examples/nlp-case/.copier-answers.yml
  examples/nlp-case/.dockerignore
  examples/nlp-case/LICENSE
  examples/nlp-case/Makefile
  examples/nlp-case/README.md
  examples/nlp-case/config.yaml
  examples/nlp-case/gradio/Dockerfile
  examples/nlp-case/gradio/__init__.py
  examples/nlp-case/gradio/app.py
  examples/nlp-case/gradio/requirements.txt
  examples/nlp-case/gradio/serve.yaml
  examples/nlp-case/pipelines/__init__.py
  examples/nlp-case/pipelines/deploying.py
  examples/nlp-case/pipelines/promoting.py
  examples/nlp-case/pipelines/training.py
  examples/nlp-case/requirements.txt
  examples/nlp-case/run.py
  examples/nlp-case/steps/__init__.py
  examples/nlp-case/steps/alerts/__init__.py
  examples/nlp-case/steps/alerts/notify_on.py
  examples/nlp-case/steps/dataset_loader/__init__.py
  examples/nlp-case/steps/dataset_loader/data_loader.py
  examples/nlp-case/steps/deploying/__init__.py
  examples/nlp-case/steps/deploying/local_deployment.py
  examples/nlp-case/steps/deploying/save_model.py
  examples/nlp-case/steps/promotion/__init__.py
  examples/nlp-case/steps/promotion/promote_get_metrics.py
  examples/nlp-case/steps/promotion/promote_metric_compare_promoter.py
  examples/nlp-case/steps/register/__init__.py
  examples/nlp-case/steps/register/model_log_register.py
  examples/nlp-case/steps/tokenizer_loader/__init__.py
  examples/nlp-case/steps/tokenizer_loader/tokenizer_loader.py
  examples/nlp-case/steps/tokenzation/__init__.py
  examples/nlp-case/steps/tokenzation/tokenization.py
  examples/nlp-case/steps/training/__init__.py
  examples/nlp-case/steps/training/model_trainer.py
  examples/nlp-case/utils/misc.py
Labels: internal, backport

#2090 Fix Nightly Build workflow files
  .github/workflows/nightly_build.yml
  .github/workflows/setup-python-environment.yml
Labels: bug, internal

#2088 Make PyPi release depend on DB migration tests passing
  .github/workflows/release.yml
Labels: bug, enhancement, internal

#2091 Bump `mlstacks` version in ZenML extra
  pyproject.toml
Labels: internal, dependencies

#2098 Fix SQL schema imports
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/artifact_visualization_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/stack_schemas.py
Labels: bug, internal
