Repository zenml-io/zenml, pull requests merged in 2023-06, with the labels that each got.

#1579 Add orchestrator outputs for sandbox examples
  examples/great_expectations_data_validation/run.py
  examples/mlflow_tracking/run.py
Labels: enhancement, internal

#1583 Add orchestrator outputs for sandbox examples (#1579)
  examples/great_expectations_data_validation/run.py
  examples/mlflow_tracking/run.py
Labels: internal, backport

#1582 Docs: Added some adjustments to the code repository page.
  docs/book/user-guide/advanced-guide/connect-your-git-repository.md
Labels: documentation, internal

#1587 readme update (#1586)
  README.md
Labels: documentation, internal, backport

#1581 Fix failing `mlflow_tracking` example test
  examples/mlflow_tracking/README.md
  examples/mlflow_tracking/run.py
  tests/integration/examples/test_mlflow_tracking.py
  tests/integration/examples/utils.py
Labels: bug, internal, tests

#1590 Bump `ruff` and `mypy`
  pyproject.toml
Labels: enhancement, internal, dependencies

#1598 update mlflow tracking example and reduce number of epochs
  examples/mlflow_tracking/pipelines/training_pipeline/training_pipeline.py
Labels: enhancement, internal

#1596 Improve error message when requirements file does not exist
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal

#1594 Fix build reuse for integrations with apt packages
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal

#1573 Add option to list all resources when verifying service connector config
  src/zenml/cli/service_connectors.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/models/service_connector_models.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#1602 Fix sandbox time limit
  docs/book/user-guide/starter-guide/switch-to-production.md
Labels: documentation, internal

#1600 Fixing the analytics for the Hub
  src/zenml/_hub/client.py
  src/zenml/models/server_models.py
  src/zenml/zen_stores/base_zen_store.py
Labels: enhancement, internal

#1599 Adding the ability to tag the source of an event for the analytics
  src/zenml/_hub/client.py
  src/zenml/analytics/__init__.py
  src/zenml/analytics/client.py
  src/zenml/analytics/consumer.py
  src/zenml/analytics/request.py
  src/zenml/cli/cli.py
  src/zenml/enums.py
  src/zenml/models/server_models.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#1605 Move all the logic into the script to make it as easy as possible to …
  .github/workflows/publish_api_docs.yml
  scripts/generate-docs.sh
Labels: bug, internal

#1568 Only set mysql session variables when necessary
  src/zenml/zen_stores/migrations/versions/728c6369cfaa_add_name_column_to_input_artifact_pk.py
Labels: bug, internal

#1526 Added logs endpoint to display on the dashboard
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  docs/book/user-guide/starter-guide/follow-best-practices.md
  src/zenml/artifact_stores/__init__.py
  src/zenml/artifact_stores/base_artifact_store_logging_handler.py
  src/zenml/artifact_stores/step_logging_utils.py
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/logs_models.py
  src/zenml/models/step_run_models.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/steps/step_decorator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/post_execution/step.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/utils/artifact_utils.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_stores/migrations/versions/ade72effebaf_added_logs_table.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/logs_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/conftest.py
  tests/integration/functional/test_step_logs.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#1612 Fix CI
  RELEASE_NOTES.md
  docs/book/platform-guide/set-up-your-mlops-platform/implement-a-custom-stack-component.md
  docs/book/user-guide/advanced-guide/use-failure-success-hooks.md
  scripts/install-dashboard.sh
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/kserve/steps/kserve_step_utils.py
Labels: bug, internal

#1615 Fix Azure Integration Imports and Improve Flavor Registration Error Handling
  src/zenml/integrations/azure/flavors/azure_artifact_store_flavor.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/stack/flavor_registry.py
Labels: bug, internal

#1608 Deprecation Cleanup
  src/zenml/cli/model.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/repository.py
  src/zenml/services/service.py
  src/zenml/step_operators/base_step_operator.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/step_environment.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
Labels: internal

#1621 Cleanup Local Logging Temp Files
  src/zenml/artifact_stores/base_artifact_store_logging_handler.py
  src/zenml/orchestrators/step_launcher.py
Labels: bug, internal

#1418 Add cloud orchestrator warning message
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/new/pipelines/pipeline.py
Labels: enhancement, internal

#1623 Update custom code run in sandbox docs
  docs/book/user-guide/advanced-guide/sandbox.md
  docs/book/user-guide/starter-guide/switch-to-production.md
Labels: internal, backport

#1624 Remove the GH Actions review reminder bot
  .github/workflows/pull-request-reviewer-reminder.yml
Labels: internal

#1626 Automatically optimise image sizes on PR creation
  .github/workflows/image-optimiser.yml
Labels: enhancement, internal

#1630 Fix unnecessary / extra deprecation warnings
  src/zenml/integrations/bentoml/__init__.py
  src/zenml/integrations/kserve/__init__.py
Labels: bug, internal

#1607 Add `zenml secret export` CLI command
  src/zenml/cli/secret.py
  tests/integration/functional/cli/test_secret.py
Labels: enhancement, internal

#1619 Missing pipeline features docs
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/advanced-guide.md
  docs/book/user-guide/advanced-guide/compose-pipelines.md
  docs/book/user-guide/advanced-guide/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/migrate-your-old-pipelines-and-steps.md
  docs/book/user-guide/starter-guide/fetch-runs-after-execution.md
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/step_decorator.py
Labels: documentation, internal

#1606 Fix and document Vertex AI orchestrator and step operator
  docs/book/platform-guide/set-up-your-mlops-platform/connect-zenml-to-infrastructure/gcp-service-connector.md
  docs/book/user-guide/component-guide/orchestrators/vertex.md
  docs/book/user-guide/component-guide/step-operators/vertex.md
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/google_cloud_scheduler.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal

#1614 Adjust BentoML Steps and Example to New Pipeline Interface
  docs/book/user-guide/component-guide/model-deployers/bentoml.md
  examples/bentoml_deployment/README.md
  examples/bentoml_deployment/pipelines/inference_fashion_mnist.py
  examples/bentoml_deployment/pipelines/training_fashion_mnist.py
  examples/bentoml_deployment/run.py
  examples/bentoml_deployment/steps/bento_builder.py
  examples/bentoml_deployment/steps/deployer.py
  examples/bentoml_deployment/steps/deployment_trigger_step.py
  examples/bentoml_deployment/steps/evaluators.py
  examples/bentoml_deployment/steps/importers.py
  examples/bentoml_deployment/steps/inference_loader.py
  examples/bentoml_deployment/steps/prediction_service_loader.py
  examples/bentoml_deployment/steps/predictor.py
  examples/bentoml_deployment/steps/trainers.py
  src/zenml/integrations/bentoml/__init__.py
  src/zenml/integrations/bentoml/steps/__init__.py
  src/zenml/integrations/bentoml/steps/bento_builder.py
  src/zenml/integrations/bentoml/steps/bentoml_deployer.py
  src/zenml/services/local/local_service.py
Labels: enhancement, internal

#1641 Fix the s3 integration dependencies
  src/zenml/integrations/s3/__init__.py
Labels: bug, internal

#1644 Don't run whylogs example on windows
  tests/harness/cfg/tests.yaml
Labels: bug, internal

#1640 Adding the missing pages to our docs
  docs/book/platform-guide/set-up-your-mlops-platform/implement-a-custom-integration.md
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/debug-and-solve-issues.md
Labels: documentation, internal

#1616 Fixing the listing functionality of several objects in our CLI
  src/zenml/cli/service_connectors.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
  src/zenml/cli/workspace.py
Labels: bug, internal

#1638 Fix run configuration parameter merging
  src/zenml/config/compiler.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_invocation.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/steps/test_base_step_new.py
Labels: bug, internal

#1637 Simplify email opt-in telemetry
  src/zenml/cli/base.py
  src/zenml/config/global_config.py
  src/zenml/utils/analytics_utils.py
  src/zenml/zen_server/routers/users_endpoints.py
Labels: enhancement, internal

#1649 Improve config section of containerization docs page
  docs/book/user-guide/advanced-guide/containerize-your-pipeline.md
Labels: documentation, internal

#1650 CI: Python 3.7 Mac Runners
  .github/workflows/ci.yml
Labels: internal

#1648 Redesign `StepContext`
  docs/book/user-guide/advanced-guide/fetch-metadata-within-steps.md
  docs/book/user-guide/advanced-guide/hyper-parameter-tuning.md
  docs/book/user-guide/advanced-guide/use-failure-success-hooks.md
  docs/book/user-guide/component-guide/feature-stores/feast.md
  docs/book/user-guide/component-guide/model-deployers/model-deployers.md
  docs/book/user-guide/component-guide/model-deployers/seldon.md
  docs/book/user-guide/component-guide/secrets-managers/secrets-managers.md
  docs/book/user-guide/starter-guide/fetch-runs-after-execution.md
  examples/label_studio_annotation/steps/load_image_data_step.py
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/label_studio_annotation/steps/pytorch_trainer.py
  src/zenml/__init__.py
  src/zenml/alerter/alerter_utils.py
  src/zenml/environment.py
  src/zenml/hooks/alerter_hooks.py
  src/zenml/hooks/hook_validators.py
  src/zenml/integrations/bentoml/steps/bento_builder.py
  src/zenml/integrations/bentoml/steps/bentoml_deployer.py
  src/zenml/integrations/deepchecks/data_validators/deepchecks_data_validator.py
  src/zenml/integrations/great_expectations/data_validators/ge_data_validator.py
  src/zenml/integrations/great_expectations/utils.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/label_studio/steps/label_studio_standard_steps.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/mlflow/steps/mlflow_registry.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/integrations/slack/steps/slack_alerter_ask_step.py
  src/zenml/integrations/slack/steps/slack_alerter_post_step.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/pipeline_decorator.py
  src/zenml/new/steps/step_context.py
  src/zenml/new/steps/step_decorator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
  src/zenml/steps/__init__.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/step_environment.py
  src/zenml/utils/singleton.py
  tests/unit/conftest.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/orchestrators/test_step_runner.py
  tests/unit/steps/test_step_context.py
  tests/unit/utils/test_singleton.py
Labels: enhancement, internal

#1629 Fix output of dashboard url on pipeline run
  src/zenml/new/pipelines/pipeline.py
  src/zenml/utils/dashboard_utils.py
Labels: bug, internal

#1659 Fix Image Builder Warning Message
  src/zenml/stack/stack.py
Labels: bug, internal

#1653 New step output annotations
  docs/book/user-guide/advanced-guide/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/handle-custom-data-types.md
  docs/book/user-guide/advanced-guide/schedule-pipeline-runs.md
  docs/book/user-guide/component-guide/data-validators/evidently.md
  docs/book/user-guide/component-guide/data-validators/whylogs.md
  docs/book/user-guide/component-guide/model-deployers/mlflow.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  docs/book/user-guide/starter-guide/fetch-runs-after-execution.md
  docs/book/user-guide/starter-guide/version-pipelines.md
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/integrations/evidently/steps/evidently_profile.py
  src/zenml/integrations/evidently/steps/evidently_report.py
  src/zenml/integrations/evidently/steps/evidently_test.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_output.py
  src/zenml/steps/utils.py
  tests/unit/steps/test_base_step.py
  tests/unit/steps/test_utils.py
Labels: enhancement, internal

#1662 Add Python 3.10 to listed versions supported via PyPi
  pyproject.toml
Labels: enhancement, internal

#1661 Fixing broken links in our examples folder
  CONTRIBUTING.md
  README.md
  examples/README.md
  examples/airflow_orchestration/README.md
  examples/bentoml_deployment/README.md
  examples/code_repository/README.md
  examples/custom_code_deployment/README.md
  examples/evidently_data_validation/README.md
  examples/feast_feature_store/README.md
  examples/kubeflow_pipelines_orchestration/README.md
  examples/kubernetes_orchestration/README.md
  examples/label_studio_annotation/README.md
  examples/mlflow_deployment/README.md
  examples/mlflow_registry/README.md
  examples/mlflow_tracking/README.md
  examples/neptune_tracking/README.md
  examples/quickstart/README.md
  examples/quickstart/notebooks/quickstart.ipynb
  examples/quickstart_py37/README.md
  examples/quickstart_py37/notebooks/quickstart.ipynb
  examples/sagemaker_orchestration/README.md
  examples/secrets_management/README.md
  examples/seldon_deployment/README.md
  examples/slack_alert/README.md
  examples/spark_distributed_programming/README.md
  examples/step_operator_remote_training/README.md
  examples/tekton_pipelines_orchestration/README.md
  examples/vertex_ai_orchestration/README.md
  examples/wandb_tracking/README.md
Labels: documentation, internal

#1639 Feature/frw 2013 docs
  docs/book/platform-guide/set-up-your-mlops-platform/set-up-your-mlops-platform.md
  docs/book/user-guide/starter-guide/cache-previous-executions.md
  docs/book/user-guide/starter-guide/connect-to-a-deployed-zenml.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: enhancement, internal
