Repository zenml-io/zenml, pull requests merged in 2024-10, with the labels that each got.

#3050 Release 0.67.0 migration testing
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#3048 Prevent too large requests
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal, run-slow-ci

#3055 Fix Neptune linting after 1.12.0 release
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
Labels: internal

#3058 Fix Lightning Orchestrator (remove -y from pip install)
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator_entrypoint.py
Labels: internal

#3052 Fix artifact pruning endpoint path
  src/zenml/zen_server/routers/artifact_version_endpoints.py
Labels: bug, internal

#3059 Update python versioning in docs
  .github/workflows/ci-slow.yml
  README.md
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/getting-started/installation.md
Labels: documentation, internal, run-slow-ci

#3061 Fix infinite loop while fetching artifact store in logs storage class
  src/zenml/client_lazy_loader.py
  src/zenml/logging/step_logging.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
Labels: bug, internal, run-slow-ci

#3062 Make sync a setting for sagemaker/azureml orchestrator
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/azure/flavors/azureml_orchestrator_flavor.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
Labels: bug, internal

#3051 Fix MySQL warning when filtering pipelines by latest run
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3063 Remove more deprecated stuff
  src/zenml/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/model/model.py
  src/zenml/model/model_version.py
  src/zenml/model/utils.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/pipeline_context.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/post_execution/__init__.py
  src/zenml/post_execution/pipeline.py
  src/zenml/post_execution/pipeline_run.py
  src/zenml/stack/stack.py
  src/zenml/stack/stack_component.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_context.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/step_invocation.py
  tests/harness/environment.py
  tests/harness/model/test.py
  tests/integration/functional/cli/test_artifact.py
  tests/integration/functional/cli/test_pipeline.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/test_client.py
  tests/unit/conftest.py
  tests/unit/stack/test_stack.py
  tests/unit/stack/test_stack_component.py
  tests/unit/steps/test_step_context.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3060 Remove log versions from versioned buckets in S3
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/integrations/s3/flavors/s3_artifact_store_flavor.py
  src/zenml/integrations/s3/utils.py
  src/zenml/logging/step_logging.py
  tests/conftest.py
  tests/integration/integrations/s3/artifact_stores/test_s3_artifact_store.py
  tests/integration/integrations/s3/test_utils.py
Labels: enhancement, internal, run-slow-ci

#3066 add docs on k8s per pod settings
  docs/book/component-guide/orchestrators/kubernetes.md
Labels: documentation, internal

#3053 `register_artifact ` function
  docs/book/how-to/handle-data-artifacts/registering-existing-data.md
  docs/book/toc.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  examples/e2e/Makefile
  src/zenml/__init__.py
  src/zenml/artifacts/load_directory_materializer.py
  src/zenml/artifacts/utils.py
  tests/integration/functional/artifacts/test_utils.py
Labels: enhancement, internal, run-slow-ci

#3069 Fix bad link in docs
  docs/book/toc.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
Labels: documentation, internal

#3083 Fix pipeline and model URLs for ZenML Pro on-prem deployments
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/feature_gate/zenml_cloud_feature_gate.py
Labels: bug, internal, run-slow-ci

#3085 Fix mlflow linting
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/mlflow/steps/mlflow_registry.py
Labels: bug, internal

#3084 Add docs for factory generation of artifact names
  docs/book/.gitbook/assets/dynamic_artifact_pipeline.png
  docs/book/.gitbook/assets/metadata_artifact_pipeline.png
  docs/book/how-to/build-pipelines/dynamically-generate-steps-artifacts.md
  docs/book/toc.md
Labels: documentation, internal

#3088 Remove unnecessary metadata fields in UUID materializer test
  src/zenml/materializers/uuid_materializer.py
  tests/unit/materializers/test_uuid_materializer.py
Labels: enhancement, internal

#3068 Client-side computation of cached steps
  docs/book/user-guide/starter-guide/cache-previous-executions.md
  src/zenml/artifacts/artifact_config.py
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/external_artifact_config.py
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/model/model.py
  src/zenml/model/utils.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_context.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_run.py
  tests/integration/functional/steps/test_external_artifact.py
  tests/integration/functional/steps/test_model_version.py
  tests/integration/functional/test_lineage_graph.py
  tests/unit/conftest.py
  tests/unit/steps/test_external_artifact.py
Labels: enhancement, internal, run-slow-ci

#3092 Add docs on common stacks best practices
  docs/book/how-to/popular-integrations/aws-guide.md
  docs/book/how-to/popular-integrations/gcp-guide.md
  docs/book/how-to/popular-integrations/skypilot.md
Labels: documentation, internal

#3082 [docs] Update stacks page and add azure 1-click from dashboard docs
  .gitbook.yaml
  docs/book/.gitbook/assets/deploy_stack_azure_cloud_shell.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloud_shell_terraform_outputs.png
  docs/book/.gitbook/assets/deploy_stack_azure_dashboard_output.png
  docs/book/.gitbook/assets/deploy_stack_azure_deployment_page.png
  docs/book/.gitbook/assets/deploy_stack_azure_location.png
  docs/book/.gitbook/assets/deploy_stack_azure_resources.png
  docs/book/.gitbook/assets/deploy_stack_selection.png
  docs/book/.gitbook/assets/register_stack_page.png
  docs/book/.gitbook/assets/service_con_workflow.png
  docs/book/.gitbook/assets/stack-wizard-cloud-selection.png
  docs/book/.gitbook/assets/stack-wizard-options.png
  docs/book/.gitbook/assets/stack_envs.png
  docs/book/how-to/contribute-to-zenml/README.md
  docs/book/how-to/contribute-to-zenml/implement-a-custom-integration.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  docs/book/toc.md
Labels: documentation, internal

#3090 Local development how-to section
  docs/book/how-to/build-pipelines/dynamically-assign-artifact-names.md
  docs/book/how-to/develop-locally/README.md
  docs/book/how-to/develop-locally/keep-your-dashboard-server-clean.md
  docs/book/how-to/develop-locally/local-prod-pipeline-variants.md
  docs/book/toc.md
Labels: documentation, internal

#3087 [docs] best practices for upgrading zenml server
  .gitbook.yaml
  docs/book/.gitbook/assets/aws-rds-backups.png
  docs/book/.gitbook/assets/cloudrun_autoscaling.png
  docs/book/.gitbook/assets/cloudrun_metrics.png
  docs/book/.gitbook/assets/ecs_autoscaling.png
  docs/book/.gitbook/assets/ecs_cpu_utilization.png
  docs/book/.gitbook/assets/grafana_dashboard.png
  docs/book/.gitbook/assets/server_migration_1.png
  docs/book/.gitbook/assets/server_migration_2.png
  docs/book/getting-started/deploying-zenml/manage-the-deployed-services/README.md
  docs/book/getting-started/deploying-zenml/manage-the-deployed-services/custom-secret-stores.md
  docs/book/how-to/manage-the-zenml-server/README.md
  docs/book/how-to/manage-the-zenml-server/best-practices-upgrading-zenml.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/README.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/migration-guide.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/migration-zero-forty.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/migration-zero-sixty.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/migration-zero-thirty.md
  docs/book/how-to/manage-the-zenml-server/migration-guide/migration-zero-twenty.md
  docs/book/how-to/manage-the-zenml-server/troubleshoot-your-deployed-server.md
  docs/book/how-to/manage-the-zenml-server/upgrade-zenml-server.md
  docs/book/how-to/manage-the-zenml-server/using-zenml-server-in-prod.md
  docs/book/how-to/stack-deployment/troubleshoot-stack-components.md
  docs/book/toc.md
Labels: documentation, internal

#3086 Fix S3 ArtifactStore auth issue
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/auth-management/aws-service-connector.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  infra/aws/aws-ecr-s3-sagemaker.yaml
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/stack_deployments/aws_stack_deployment.py
Labels: bug, internal

#3078 Reduce migration testing runtime
  scripts/test-migrations.sh
Labels: internal, run-slow-ci

#3097 Fix filtering by tag for pipeline runs
  src/zenml/models/v2/core/pipeline_run.py
Labels: bug, internal

#3098 Do not tag model via `Model` class on creation
  docs/book/how-to/handle-data-artifacts/tagging.md
  src/zenml/model/model.py
  src/zenml/models/v2/core/model.py
  tests/integration/functional/model/test_model_version.py
Labels: enhancement, internal

#3080 Sagemaker add pipeline tags
  docs/book/component-guide/orchestrators/sagemaker.md
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal

#3091 [docs] Add custom Dataset classes and Materializers in ZenML
  docs/book/how-to/handle-data-artifacts/datasets.md
  docs/book/how-to/handle-data-artifacts/manage-big-data.md
  docs/book/toc.md
Labels: internal

#3103 Delete Scarf related scripts and workflow files
  .github/workflows/scarf-check.yml
  scripts/format.sh
  scripts/scarf-checker.sh
Labels: enhancement, internal

#3065 Add more detailed docs for ZenML Pro
  .gitbook.yaml
  docs/book/.gitbook/assets/Scenario1.png
  docs/book/.gitbook/assets/Scenario2.png
  docs/book/.gitbook/assets/Scenario3.2.png
  docs/book/.gitbook/assets/add_org_members.png
  docs/book/.gitbook/assets/add_team_members.png
  docs/book/.gitbook/assets/admin_role.png
  docs/book/.gitbook/assets/assign_permissions.png
  docs/book/.gitbook/assets/assign_team_to_tenant.png
  docs/book/.gitbook/assets/business-logic-tenants.png
  docs/book/.gitbook/assets/cloud_architecture_saas_detailed.png
  docs/book/.gitbook/assets/cloud_architecture_saas_detailed_2.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_3.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_5.png
  docs/book/.gitbook/assets/cloud_architecture_self_hosted_detailed.png
  docs/book/.gitbook/assets/cloudapi_swagger.png
  docs/book/.gitbook/assets/core_concepts_oss.png
  docs/book/.gitbook/assets/create_role_modal.png
  docs/book/.gitbook/assets/create_team.png
  docs/book/.gitbook/assets/custom_role_settings_page.png
  docs/book/.gitbook/assets/new_tenant.png
  docs/book/.gitbook/assets/new_tenant_modal.png
  docs/book/.gitbook/assets/org_hierarchy_pro.png
  docs/book/.gitbook/assets/org_members.png
  docs/book/.gitbook/assets/org_settings.png
  docs/book/.gitbook/assets/oss_simple_deployment.png
  docs/book/.gitbook/assets/pro_deployment_simple.png
  docs/book/.gitbook/assets/rbac_admin_permissions.png
  docs/book/.gitbook/assets/role_page.png
  docs/book/.gitbook/assets/share_dialog.png
  docs/book/.gitbook/assets/staging-production-tenants.png
  docs/book/.gitbook/assets/swagger_docs_zenml.png
  docs/book/.gitbook/assets/team_roles.png
  docs/book/.gitbook/assets/tenant_onboarding.png
  docs/book/.gitbook/assets/tenant_roles_page.png
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/getting-started/deploying-zenml/secret-management.md
  docs/book/getting-started/system-architectures.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/core-concepts.md
  docs/book/getting-started/zenml-pro/organization.md
  docs/book/getting-started/zenml-pro/pro-api.md
  docs/book/getting-started/zenml-pro/roles.md
  docs/book/getting-started/zenml-pro/system-architectures.md
  docs/book/getting-started/zenml-pro/teams.md
  docs/book/getting-started/zenml-pro/tenants.md
  docs/book/getting-started/zenml-pro/user-management.md
  docs/book/getting-started/zenml-pro/zenml-pro.md
  docs/book/introduction.md
  docs/book/toc.md
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: documentation, internal

#3094 Add missing code hash filter in client method
  src/zenml/client.py
Labels: bug, internal

#3064 Remove lineage graph and legacy dashboard support
  docs/book/getting-started/deploying-zenml/README.md
  scripts/install-dashboard.sh
  src/zenml/cli/server.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/lineage_graph/__init__.py
  src/zenml/lineage_graph/edge.py
  src/zenml/lineage_graph/lineage_graph.py
  src/zenml/lineage_graph/node/__init__.py
  src/zenml/lineage_graph/node/artifact_node.py
  src/zenml/lineage_graph/node/base_node.py
  src/zenml/lineage_graph/node/step_node.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/test_lineage_graph.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3101 Automating the release process using Github workflows
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
  docker/zenml-quickstart-dev.Dockerfile
  release-cloudbuild-preparation.yaml
  scripts/add-migration-test-version.sh
  scripts/deprecate-previous-docs-to-legacy.sh
  scripts/redeploy-release-prep-tenant.py
  scripts/sync-gitbook-release-spaces.py
  scripts/validate-new-version.sh
Labels: enhancement, internal, run-slow-ci

#3107 Bugfix for release automation
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3108 Bugfix for new version in the release automation
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3109 using the right parent image name
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3110 Making the new release automation scripts executable
  scripts/add-migration-test-version.sh
  scripts/deprecate-previous-docs-to-legacy.sh
  scripts/validate-new-version.sh
Labels: bug, internal

#3111 Fixing the env variables for the release automation
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3112 Adding the right Github configuration before using the `gh` CLI to fetch the version
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3113 Fixing the outputs of the first step in the release automation
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3114 Handling github auth and release notes for release automation
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3116 Fixing the cloudbuild call for release automation
  .github/workflows/release_prepare.yml
  release-cloudbuild-preparation.yaml
Labels: bug, internal

#3118 Fixing the update tenant call in the script
  scripts/redeploy-release-prep-tenant.py
Labels: bug, internal

#3120 Release automation with the new redeploy logic
  scripts/redeploy-release-prep-tenant.py
Labels: bug, internal

#3125 Fixing the automation triggers for other branches
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
  scripts/format.sh
  scripts/validate-new-version.sh
Labels: bug, internal

#3128 Update link for `llm-complete-guide` repository.- Updated link to poi…
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings.md
Labels: internal

#3127 Fixing the migration testing for the release branches
  scripts/lint.sh
  scripts/test-migrations.sh
Labels: bug, internal

#3123 Update pipeline deletion docs
  docs/book/how-to/build-pipelines/delete-a-pipeline.md
Labels: documentation, internal

#3133 Disabling the cache for the quickstart tests
  .github/workflows/release_prepare.yml
Labels: bug, internal

#2915 Update Argilla integration for v2.x SDK
  docs/book/.gitbook/assets/argilla_annotator.png
  docs/book/component-guide/annotators/annotators.md
  docs/book/component-guide/annotators/argilla.md
  docs/mocked_libs.json
  scripts/install-zenml-dev.sh
  src/zenml/integrations/argilla/__init__.py
  src/zenml/integrations/argilla/annotators/argilla_annotator.py
  src/zenml/integrations/argilla/flavors/argilla_annotator_flavor.py
Labels: enhancement, run-slow-ci

#3136 Using pip instead of `gh` CLI in the migration tests
  scripts/test-migrations.sh
Labels: bug, internal, run-slow-ci

#3135 Adapting tags to work with older versions of Sagemaker
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal

#3137 Manual trigger for the `release_finalize` workflow
  .github/workflows/release_finalize.yml
Labels: bug, internal

#3144 Adding 0.68.0 to the migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#3046 Move step durations to body
  src/zenml/models/v2/core/step_run.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
Labels: enhancement, internal, breaking-change, requires-frontend-changes

#3100 Docs on ZenML setup
  .gitbook.yaml
  docs/book/.gitbook/assets/argilla_annotator.png
  docs/book/.gitbook/assets/data_scientist_connector_role.png
  docs/book/.gitbook/assets/model_pipeline_artifact.png
  docs/book/.gitbook/assets/platform_engineer_connector_role.png
  docs/book/how-to/customize-docker-builds/how-to-reuse-builds.md
  docs/book/how-to/customize-docker-builds/how-to-use-a-private-pypi-repository.md
  docs/book/how-to/manage-the-zenml-server/best-practices-upgrading-zenml.md
  docs/book/how-to/setting-up-a-project-repository/README.md
  docs/book/how-to/setting-up-a-project-repository/access-management.md
  docs/book/how-to/setting-up-a-project-repository/connect-your-git-repository.md
  docs/book/how-to/setting-up-a-project-repository/create-your-own-template.md
  docs/book/how-to/setting-up-a-project-repository/set-up-repository.md
  docs/book/how-to/setting-up-a-project-repository/shared-components-for-teams.md
  docs/book/how-to/setting-up-a-project-repository/stacks-pipelines-models.md
  docs/book/how-to/setting-up-a-project-repository/using-project-templates.md
  docs/book/how-to/training-with-gpus/accelerate-distributed-training.md
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
Labels: documentation, internal

#3129 Remove wrongly set Model.was_created_in_this_run attribute
  docs/book/how-to/use-configuration-files/autogenerate-a-template-yaml-file.md
  src/zenml/model/model.py
  src/zenml/models/v2/core/model_version.py
Labels: bug, internal

#3130 Allow specifying run tags in pipeline configuration
  .gitbook.yaml
  docs/book/how-to/build-pipelines/name-your-pipeline-runs.md
  docs/book/how-to/build-pipelines/tag-your-pipeline-runs.md
  docs/book/toc.md
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/pipelines/run_utils.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#3146 Remove unavailable upstream steps during cache precomputation
  src/zenml/orchestrators/base_orchestrator.py
Labels: bug, internal

#3105 Fix materializer type compatibility check during loading
  src/zenml/artifacts/utils.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/utils/materializer_utils.py
  tests/unit/materializers/test_base_materializer.py
Labels: bug, internal

#3148 Prepare release 0.68.1
  README.md
  RELEASE_NOTES.md
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements.txt
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.68.1_release.py
Labels: internal

#3149 [docs] Add icons to headers in docs
  docs/book/component-guide/README.md
  docs/book/component-guide/alerters/alerters.md
  docs/book/component-guide/annotators/annotators.md
  docs/book/component-guide/artifact-stores/artifact-stores.md
  docs/book/component-guide/container-registries/container-registries.md
  docs/book/component-guide/data-validators/data-validators.md
  docs/book/component-guide/experiment-trackers/experiment-trackers.md
  docs/book/component-guide/feature-stores/feature-stores.md
  docs/book/component-guide/image-builders/image-builders.md
  docs/book/component-guide/model-deployers/model-deployers.md
  docs/book/component-guide/model-registries/model-registries.md
  docs/book/component-guide/orchestrators/orchestrators.md
  docs/book/component-guide/step-operators/step-operators.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/getting-started/installation.md
  docs/book/getting-started/system-architectures.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/build-pipelines/README.md
  docs/book/how-to/configure-python-environments/README.md
  docs/book/how-to/connecting-to-zenml/README.md
  docs/book/how-to/contribute-to-zenml/README.md
  docs/book/how-to/control-logging/README.md
  docs/book/how-to/customize-docker-builds/README.md
  docs/book/how-to/debug-and-solve-issues.md
  docs/book/how-to/develop-locally/README.md
  docs/book/how-to/handle-data-artifacts/README.md
  docs/book/how-to/interact-with-secrets.md
  docs/book/how-to/manage-the-zenml-server/README.md
  docs/book/how-to/popular-integrations/README.md
  docs/book/how-to/run-remote-steps-and-pipelines-from-notebooks/README.md
  docs/book/how-to/setting-up-a-project-repository/README.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/track-metrics-metadata/README.md
  docs/book/how-to/training-with-gpus/training-with-gpus.md
  docs/book/how-to/trigger-pipelines/README.md
  docs/book/how-to/use-configuration-files/README.md
  docs/book/how-to/use-the-model-control-plane/README.md
  docs/book/how-to/visualize-artifacts/README.md
  docs/book/introduction.md
  docs/book/reference/api-reference.md
  docs/book/reference/community-and-content.md
  docs/book/reference/environment-variables.md
  docs/book/reference/faq.md
  docs/book/reference/global-settings.md
  docs/book/reference/how-do-i.md
  docs/book/reference/python-client.md
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/README.md
  docs/book/user-guide/production-guide/production-guide.md
  docs/book/user-guide/starter-guide/starter-guide.md
Labels: documentation, internal

#3150 fix icons and remove redundant file
  docs/book/user-guide/production-guide/README.md
  docs/book/user-guide/production-guide/production-guide.md
  docs/book/user-guide/starter-guide/README.md
  docs/book/user-guide/starter-guide/starter-guide.md
Labels: documentation, internal

#3152 Deprecating the docs for version 0.68.0 to the legacy docs
  docs/book/introduction.md
Labels: documentation, internal

#3153 Merge 0.68.1 release into develop
  README.md
  RELEASE_NOTES.md
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements.txt
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
  pyproject.toml
  src/zenml/VERSION
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.68.1_release.py
Labels: internal

#3134 Allow artifact response as step input
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_invocation.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#3126 Filter component by user name
  src/zenml/client.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/component.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/model_version_artifact.py
  src/zenml/models/v2/core/model_version_pipeline_run.py
  src/zenml/models/v2/core/pipeline.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/run_template.py
  src/zenml/models/v2/core/stack.py
Labels: enhancement, internal

#3119 Fix in-process main module source loading
  src/zenml/utils/source_utils.py
  tests/unit/utils/source_utils_test_helper.py
  tests/unit/utils/test_source_utils.py
Labels: bug, internal

#3160 Catch assertion in GH library
  src/zenml/integrations/github/code_repositories/github_code_repository.py
Labels: bug, internal

#3156 Enable cache precomputation for run templates
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/pipelines/run_utils.py
  src/zenml/stack/stack.py
  src/zenml/zen_server/template_execution/runner_entrypoint_configuration.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/stack/test_stack.py
Labels: enhancement, internal

#3159 Add LLM and ML engineering books to README
  README.md
  docs/book/.gitbook/assets/llm_engineering_handbook_cover.jpg
  docs/book/.gitbook/assets/ml_engineering_with_python.jpg
Labels: documentation, internal

#3155 Add helper method to quickly create run template from pipeline
  docs/book/how-to/pipeline-development/trigger-pipelines/use-templates-python.md
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/utils.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/template_utils.py
Labels: enhancement, internal, run-slow-ci

#3158 Add CLI command to export stack requirements
  docs/book/how-to/infrastructure-deployment/stack-deployment/README.md
  docs/book/how-to/infrastructure-deployment/stack-deployment/export-stack-requirements.md
  docs/book/toc.md
  docs/book/user-guide/production-guide/understand-stacks.md
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/utils/requirements_utils.py
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3095 Scalability improvements: Increment artifact version server side
  src/zenml/artifacts/utils.py
  src/zenml/metadata/metadata_types.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/zen_stores/migrations/versions/c22561cbb3a9_add_artifact_unique_constraints.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/steps/test_step_context.py
  tests/unit/artifacts/test_utils.py
Labels: enhancement, internal, breaking-change, run-slow-ci
