Repository zenml-io/zenml, pull requests merged in 2024-07, with the labels that each got.

#2820 Update triggers docs with information on previously-run pipelines
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-client.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-rest-api.md
Labels: documentation, internal

#2817 Use shared cloud connection to reduce M2M token usage
  scripts/test-migrations.sh
  src/zenml/utils/function_utils.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/feature_gate/zenml_cloud_feature_gate.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
  src/zenml/zen_stores/migrations/utils.py
  tests/unit/materializers/test_built_in_materializer.py
Labels: enhancement, internal, run-slow-ci

#2828 Login to dockerhub to solve rate limiting
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow.yml
Labels: enhancement, internal, run-slow-ci

#2808 Stack wizard CLI + Endpoints
  src/zenml/cli/__init__.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/component.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/models/v2/core/stack.py
  src/zenml/models/v2/misc/full_stack.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/0d707865f404_adding_labels_to_stacks.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal, run-slow-ci

#2816 In-browser assisted full cloud stack deployments
  .github/workflows/publish_stack_templates.yml
  .github/workflows/release.yml
  infra/README.md
  infra/aws/aws-ecr-s3-sagemaker.yaml
  infra/gcp/gcp-gar-gcs-vertex-config.yaml
  infra/gcp/gcp-gar-gcs-vertex.jinja
  infra/gcp/gcp-gar-gcs-vertex.txt
  infra/gcp/main.py
  infra/gcp/requirements.txt
  src/zenml/analytics/enums.py
  src/zenml/cli/stack.py
  src/zenml/cli/text_utils.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/config/docker_settings.py
  src/zenml/constants.py
  src/zenml/container_registries/base_container_registry.py
  src/zenml/enums.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/integrations/seldon/model_deployers/seldon_model_deployer.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/misc/stack_deployment.py
  src/zenml/stack_deployments/__init__.py
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/stack_deployments/utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: run-slow-ci

#2829 Fix Kubeflow v2 integration
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
Labels: bug, internal

#2815 fix skypilot jobs failing on VMs (sky bumped to 0.6.0)
  docs/book/component-guide/orchestrators/skypilot-vm.md
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_orchestrator_entrypoint.py
  src/zenml/integrations/skypilot_aws/__init__.py
  src/zenml/integrations/skypilot_azure/__init__.py
  src/zenml/integrations/skypilot_gcp/__init__.py
  src/zenml/integrations/skypilot_lambda/__init__.py
  src/zenml/integrations/skypilot_lambda/flavors/skypilot_orchestrator_lambda_vm_flavor.py
Labels: internal, run-slow-ci

#2807 Fix unicode decode errors in k8s pod logs read operation
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
Labels: internal, run-slow-ci

#2821 Small improvements and bug fixes
  src/zenml/cli/artifact.py
  src/zenml/client.py
  src/zenml/event_hub/event_hub.py
  src/zenml/models/v2/core/model.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/stack/stack.py
  src/zenml/utils/pagination_utils.py
  src/zenml/utils/pydantic_utils.py
  src/zenml/zen_server/pipeline_deployment/utils.py
  tests/harness/model/requirements.py
  tests/unit/utils/test_pydantic_utils.py
Labels: enhancement, internal, run-slow-ci

#2791 TF tests + various integration (un)install improvements
  .github/workflows/integration-test-slow.yml
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/image-builders/gcp.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/vertex.md
  docs/book/how-to/popular-integrations/gcp-guide.md
  src/zenml/cli/integration.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/discord/__init__.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/facets/__init__.py
  src/zenml/integrations/feast/__init__.py
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/integration.py
  src/zenml/integrations/kubeflow/__init__.py
  src/zenml/integrations/kubernetes/__init__.py
  src/zenml/integrations/langchain/__init__.py
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/neural_prophet/__init__.py
  src/zenml/integrations/polars/__init__.py
  src/zenml/integrations/prodigy/__init__.py
  src/zenml/integrations/pycaret/__init__.py
  src/zenml/integrations/registry.py
  src/zenml/integrations/seldon/__init__.py
  src/zenml/integrations/slack/__init__.py
  src/zenml/integrations/tekton/__init__.py
  src/zenml/integrations/tensorboard/__init__.py
  src/zenml/integrations/tensorflow/__init__.py
  src/zenml/integrations/wandb/__init__.py
  tests/integration/examples/huggingface/steps/data_importer/data_importer_step.py
  tests/integration/examples/test_huggingface.py
  tests/integration/examples/test_tensorflow.py
  tests/integration/integrations/huggingface/steps/helpers.py
Labels: bug, internal, run-slow-ci

#2819 Fixed bug in the MacOS version check
  src/zenml/cli/utils.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  tests/integration/functional/cli/test_utils.py
Labels: bug, internal, run-slow-ci

#2831 Remove prefix for analytics labels
  src/zenml/models/v2/core/component.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/models/v2/core/stack.py
Labels: enhancement, internal

#2832 Prepare release 0.61.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/cli/stack.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.61.0_release.py
Labels: internal, run-slow-ci

#2837 Fix release action docker limit
  .github/workflows/release.yml
  RELEASE_NOTES.md
Labels: bug, internal

#2838 Fix release action docker limit (#2837)
  .github/workflows/release.yml
  RELEASE_NOTES.md
Labels: internal, backport

#2577 Upgrade ruff and yamlfix to latest versions before running formatting
  scripts/format.sh
Labels: enhancement, dependencies, run-slow-ci

#2814 Docs for stack registration + deployment wizards
  README.md
  docs/book/.gitbook/assets/deploy_stack_aws.png
  docs/book/.gitbook/assets/deploy_stack_aws_2.png
  docs/book/.gitbook/assets/deploy_stack_aws_cloudformation.png
  docs/book/.gitbook/assets/deploy_stack_aws_cloudformation_intro.png
  docs/book/.gitbook/assets/deploy_stack_selection.png
  docs/book/.gitbook/assets/one-click-deployment.gif
  docs/book/.gitbook/assets/register_stack_button.png
  docs/book/.gitbook/assets/register_stack_page.png
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/container-registries/aws.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/how-to/popular-integrations/aws-guide.md
  docs/book/how-to/popular-integrations/gcp-guide.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/how-to/stack-deployment/deploy-a-stack-component.md
  docs/book/how-to/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-client.md
  docs/book/introduction.md
  docs/book/toc.md
  docs/book/user-guide/production-guide/cloud-orchestration.md
  docs/book/user-guide/production-guide/configure-pipeline.md
  docs/book/user-guide/production-guide/production-guide.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: internal

#2840 Backporting docs for stack registration + deployment wizards
  README.md
  docs/book/.gitbook/assets/deploy_stack_aws.png
  docs/book/.gitbook/assets/deploy_stack_aws_2.png
  docs/book/.gitbook/assets/deploy_stack_aws_cloudformation.png
  docs/book/.gitbook/assets/deploy_stack_aws_cloudformation_intro.png
  docs/book/.gitbook/assets/deploy_stack_selection.png
  docs/book/.gitbook/assets/one-click-deployment.gif
  docs/book/.gitbook/assets/register_stack_button.png
  docs/book/.gitbook/assets/register_stack_page.png
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/container-registries/aws.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/how-to/popular-integrations/aws-guide.md
  docs/book/how-to/popular-integrations/gcp-guide.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/how-to/stack-deployment/deploy-a-stack-component.md
  docs/book/how-to/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-client.md
  docs/book/introduction.md
  docs/book/toc.md
  docs/book/user-guide/production-guide/cloud-orchestration.md
  docs/book/user-guide/production-guide/configure-pipeline.md
  docs/book/user-guide/production-guide/production-guide.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: internal, backport

#2839 Make upgrade checks in formatting script optional
  scripts/format.sh
Labels: internal

#2836 Enable migration testing for version 0.61.0
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#2833 One-click GCP stack deployments
  .github/workflows/publish_stack_templates.yml
  docs/book/component-guide/image-builders/gcp.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  infra/README.md
  infra/aws/aws-ecr-s3-sagemaker.yaml
  infra/gcp/gcp-gar-gcs-vertex-config.yaml
  infra/gcp/gcp-gar-gcs-vertex-deploy.sh
  infra/gcp/gcp-gar-gcs-vertex.jinja
  infra/gcp/gcp-gar-gcs-vertex.md
  infra/gcp/gcp-gar-gcs-vertex.txt
  infra/gcp/main.py
  src/zenml/cli/stack.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/misc/stack_deployment.py
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/stack_deployments/utils.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal, run-slow-ci

#2842 Only login to docker for PRs with secret access
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow.yml
Labels: bug, internal, run-slow-ci

#2826 Add GCP Stack creation Wizard (CLI)
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  src/zenml/cli/stack.py
  src/zenml/constants.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: run-slow-ci

#2794 Update onboarding
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/models/v2/core/server_settings.py
  src/zenml/zen_server/routers/devices_endpoints.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_stores/migrations/versions/b4fca5241eea_migrate_onboarding_state.py
  src/zenml/zen_stores/schemas/server_settings_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2795 Merged log files in Step Ops steps might be not available on main process, due to merge in the step op
  src/zenml/logging/step_logging.py
  src/zenml/orchestrators/step_launcher.py
Labels: bug, internal, run-slow-ci

#2848 Fix some broken links, copy paste commands, and made secrets more visible
  docs/book/component-guide/artifact-stores/azure.md
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/data-validators/whylogs.md
  docs/book/component-guide/experiment-trackers/comet.md
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/getting-started/deploying-zenml/deploy-with-docker.md
  docs/book/getting-started/deploying-zenml/deploy-with-helm.md
  docs/book/getting-started/deploying-zenml/deploy-with-zenml-cli.md
  docs/book/getting-started/deploying-zenml/secret-management.md
  docs/book/getting-started/installation.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/auth-management/aws-service-connector.md
  docs/book/how-to/auth-management/azure-service-connector.md
  docs/book/how-to/auth-management/docker-service-connector.md
  docs/book/how-to/auth-management/gcp-service-connector.md
  docs/book/how-to/auth-management/hyperai-service-connector.md
  docs/book/how-to/auth-management/kubernetes-service-connector.md
  docs/book/how-to/build-pipelines/access-secrets-in-a-step.md
  docs/book/toc.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: internal

#2846 Update stack deployment docs and other small fixes
  .github/workflows/publish_stack_templates.yml
  docs/book/.gitbook/assets/deploy_stack_aws_cf_progress.png
  docs/book/.gitbook/assets/deploy_stack_aws_cli.png
  docs/book/.gitbook/assets/deploy_stack_aws_cli_output.png
  docs/book/.gitbook/assets/deploy_stack_aws_cloudformation_intro.png
  docs/book/.gitbook/assets/deploy_stack_gcp.png
  docs/book/.gitbook/assets/deploy_stack_gcp_2.png
  docs/book/.gitbook/assets/deploy_stack_gcp_3.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cli.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cli_output.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_intro.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_start.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_step_1.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_step_2.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_step_3.png
  docs/book/.gitbook/assets/deploy_stack_gcp_cloudshell_step_4.png
  docs/book/.gitbook/assets/deploy_stack_gcp_dashboard_output.png
  docs/book/.gitbook/assets/deploy_stack_gcp_dm_progress.png
  docs/book/.gitbook/assets/deploy_stack_pending.png
  docs/book/.gitbook/assets/deploy_stack_selection.png
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  infra/README.md
  infra/gcp/gcp-gar-gcs-vertex-deploy.sh
  infra/gcp/gcp-gar-gcs-vertex.jinja
  infra/gcp/gcp-gar-gcs-vertex.md
  infra/gcp/main.py
  infra/gcp/requirements.txt
  src/zenml/cli/stack.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#2847 add image pull secrets to k8s pod settings
  docs/book/component-guide/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
Labels: internal, run-slow-ci

#2813 Include apt installation of libgomp1 for docker iamges with lightgbm
  src/zenml/integrations/lightgbm/__init__.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/cloudpickle_materializer.py
  src/zenml/utils/function_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal, run-slow-ci

#2798 Patch filter mflow by stage
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
Labels: bug, run-slow-ci

#2825 Bump mlflow to version 2.14.2
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/steps/base_step.py
Labels: run-slow-ci

#2850 Fix CI
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/unit/steps/test_base_step_new.py
Labels: bug, internal

#2851 Added some visualizations for the HF dataset
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  tests/integration/integrations/huggingface/materializers/test_huggingface_datasets_materializer.py
Labels: enhancement, internal, run-slow-ci

#2853 Fix skypilot versioning for the lambda integration
  src/zenml/integrations/skypilot_lambda/__init__.py
Labels: internal

#2823 Databricks integrations
  docs/book/.gitbook/assets/DatabricksPermessions.png
  docs/book/.gitbook/assets/DatabricksRunUI.png
  docs/book/.gitbook/assets/DatabricksUI.png
  docs/book/.gitbook/assets/Databricks_How_It_works.png
  docs/book/component-guide/model-deployers/databricks.md
  docs/book/component-guide/orchestrators/databricks.md
  docs/book/toc.md
  src/zenml/__init__.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/databricks/__init__.py
  src/zenml/integrations/databricks/flavors/__init__.py
  src/zenml/integrations/databricks/flavors/databricks_model_deployer_flavor.py
  src/zenml/integrations/databricks/flavors/databricks_orchestrator_flavor.py
  src/zenml/integrations/databricks/model_deployers/__init__.py
  src/zenml/integrations/databricks/model_deployers/databricks_model_deployer.py
  src/zenml/integrations/databricks/orchestrators/__init__.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator_entrypoint_config.py
  src/zenml/integrations/databricks/services/__init__.py
  src/zenml/integrations/databricks/services/databricks_deployment.py
  src/zenml/integrations/databricks/utils/__init__.py
  src/zenml/integrations/databricks/utils/databricks_utils.py
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
  src/zenml/model/model.py
  src/zenml/orchestrators/__init__.py
  src/zenml/orchestrators/wheeled_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#2852 Prepare release 0.62.0
  README.md
  RELEASE_NOTES.md
  docs/book/component-guide/model-deployers/databricks.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/VERSION
  src/zenml/cli/stack_components.py
  src/zenml/constants.py
  src/zenml/entrypoints/entrypoint.py
  src/zenml/integrations/databricks/flavors/databricks_model_deployer_flavor.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator_entrypoint_config.py
  src/zenml/integrations/databricks/services/databricks_deployment.py
  src/zenml/integrations/databricks/utils/databricks_utils.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.62.0_release.py
Labels: internal, run-slow-ci

#2864 Enable cloud build service in GCP stack deployment
  infra/gcp/gcp-gar-gcs-vertex-deploy.sh
Labels: bug, internal

#2866 Adding a `logo_url` and the of the `integration` to component responses
  src/zenml/models/v2/core/component.py
  src/zenml/zen_stores/schemas/component_schemas.py
Labels: enhancement, internal, run-slow-ci

#2834 Use REST in Model tests
  .github/workflows/integration-test-slow.yml
  tests/integration/examples/test_tensorflow.py
  tests/integration/functional/model/test_model_version.py
Labels: internal, run-slow-ci

#2841 Add Azure stack wizard
  src/zenml/cli/stack.py
  src/zenml/enums.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/skypilot_azure/__init__.py
  src/zenml/models/v2/misc/stack_deployment.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/stack_deployments/azure_stack_deployment.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/stack_deployments/utils.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2860 Migration testing for 0.62.0
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#2869 Fix RBAC in combination with lazy loaders
  examples/e2e_nlp/config.yaml
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/routers/steps_endpoints.py
Labels: bug, internal

#2861 Misc cleanup after release
  src/zenml/entrypoints/entrypoint.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator.py
  src/zenml/utils/source_utils.py
  src/zenml/zen_server/routers/steps_endpoints.py
Labels: enhancement, internal, run-slow-ci

#2872 Added ability to add labels to k8s pod
  docs/book/component-guide/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
Labels: enhancement, internal, run-slow-ci

#2875 Fix zenml pro links
  README.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/zenml-cloud.md
  docs/book/how-to/handle-data-artifacts/tagging.md
  docs/book/user-guide/production-guide/deploying-zenml.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  docs/book/user-guide/starter-guide/track-ml-models.md
  src/zenml/new/pipelines/run_utils.py
Labels: documentation, internal

#2879 Feature/dirtyrepo
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/entrypoints/step_entrypoint_configuration.py
  src/zenml/new/pipelines/build_utils.py
  src/zenml/new/pipelines/pipeline.py
Labels: enhancement, internal

#2881 Fixed some minor docs things i noticed
  docs/book/component-guide/step-operators/azureml.md
  docs/book/component-guide/step-operators/vertex.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: internal

#2880 Serialize source as Any to keep subclass attributes
  pyproject.toml
  src/zenml/config/pipeline_spec.py
  src/zenml/config/step_configurations.py
  src/zenml/models/v2/core/code_repository.py
Labels: bug, internal, run-slow-ci

#2876 Fix node selectors for Vertex orchestrator
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/how-to/training-with-gpus/training-with-gpus.md
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
Labels: bug, internal, run-slow-ci

#2883 Kubernetes step operator
  docs/book/component-guide/orchestrators/kubernetes.md
  docs/book/component-guide/step-operators/kubernetes.md
  docs/book/component-guide/step-operators/step-operators.md
  docs/book/how-to/popular-integrations/kubernetes.md
  docs/book/toc.md
  src/zenml/integrations/kubernetes/__init__.py
  src/zenml/integrations/kubernetes/flavors/__init__.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_step_operator_flavor.py
  src/zenml/integrations/kubernetes/step_operators/__init__.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  tests/integration/integrations/kubernetes/step_operators/__init__.py
  tests/integration/integrations/kubernetes/step_operators/test_kubernetes_step_operator.py
Labels: enhancement, internal, run-slow-ci

#2886 Automatically populate GCP/azure path when using wizard from the frontend
  src/zenml/service_connectors/service_connector_utils.py
Labels: bug, internal

#2887 Implement the Azure 1-click stack deployment
  docs/book/.gitbook/assets/deploy_stack_azure_cli.png
  docs/book/.gitbook/assets/deploy_stack_azure_cli_output.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloudshell.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloudshell_create_file.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloudshell_terraform_apply.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloudshell_terraform_init.png
  docs/book/.gitbook/assets/deploy_stack_azure_cloudshell_terraform_ouputs.png
  docs/book/component-guide/artifact-stores/azure.md
  docs/book/component-guide/container-registries/azure.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  src/zenml/cli/stack.py
  src/zenml/models/v2/misc/stack_deployment.py
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/azure_stack_deployment.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2863 Docs update mlflow deploy function call
  docs/book/component-guide/model-deployers/mlflow.md
Labels: documentation, internal

#2889 Fix databricks resource setting
  src/zenml/integrations/databricks/flavors/databricks_orchestrator_flavor.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator.py
  src/zenml/utils/package_utils.py
  tests/unit/utils/test_package_utils.py
Labels: internal

#2891 Prepare release 0.63.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.63.0_release.py
Labels: internal, run-slow-ci

#2893 Add 0.63.0 to migration testing
  scripts/test-migrations.sh
Labels: internal, run-slow-ci
