Repository zenml-io/zenml, pull requests merged in 2024-06, with the labels that each got.

#2725 Handle error when using `zenml info` with missing dependencies
  src/zenml/cli/base.py
Labels: bug, internal

#2735 Add Discord Alerter into TOC
  docs/book/toc.md
Labels: documentation, internal

#2745 Allow deleting all versions of a pipeline using the Client/CLI
  src/zenml/cli/__init__.py
  src/zenml/cli/pipeline.py
  src/zenml/client.py
  tests/integration/functional/cli/test_pipeline.py
Labels: enhancement, internal, run-slow-ci

#2732 Misc fixes
  src/zenml/integrations/kaniko/flavors/kaniko_image_builder_flavor.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/s3/flavors/s3_artifact_store_flavor.py
  src/zenml/integrations/spark/flavors/spark_step_operator_flavor.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/dashboard_utils.py
  tests/integration/integrations/kubernetes/orchestrators/test_manifest_utils.py
  tests/unit/stack/test_stack_component.py
Labels: enhancement, internal, run-slow-ci

#2743 Move full SQLite DB migration test to slow CI
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
Labels: enhancement, internal, CI, run-slow-ci

#2748 Add system flag as default for uv
  examples/llm_finetuning/README.md
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal

#2738 Add support for function types in source utils
  src/zenml/utils/source_utils.py
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal, run-slow-ci

#2751 Fix Sentencepiece tokenizer materializer
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
Labels: bug, internal, run-slow-ci

#2754 Prepare release 0.58.1
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.58.1_release.py
Labels: internal, run-slow-ci

#2757 update test-migrations.sh with latest versions
  scripts/test-migrations.sh
Labels: internal

#2753 Fix overriding expiration date for api tokens
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/jwt.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal, run-slow-ci

#2731 Step logs pagination
  src/zenml/artifacts/utils.py
  src/zenml/zen_server/routers/steps_endpoints.py
Labels: bug, internal

#2760 Fix broken links (round 2)
  docs/book/component-guide/annotators/label-studio.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/data-validators/great-expectations.md
  docs/book/component-guide/model-deployers/bentoml.md
  docs/book/component-guide/model-deployers/seldon.md
  docs/book/component-guide/orchestrators/airflow.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/getting-started/deploying-zenml/manage-the-deployed-services/secret-management.md
  docs/book/getting-started/installation.md
  docs/book/getting-started/zenml-pro/zenml-cloud.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/build-pipelines/run-pipelines-asynchronously.md
  docs/book/introduction.md
  docs/book/reference/how-do-i.md
  docs/book/reference/migration-guide/migration-zero-twenty.md
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/production-guide/README.md
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: documentation, internal

#2761 Fix broken links (round 2) (#2760)
  docs/book/component-guide/annotators/label-studio.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/data-validators/great-expectations.md
  docs/book/component-guide/model-deployers/bentoml.md
  docs/book/component-guide/model-deployers/seldon.md
  docs/book/component-guide/orchestrators/airflow.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/getting-started/deploying-zenml/manage-the-deployed-services/secret-management.md
  docs/book/getting-started/installation.md
  docs/book/getting-started/zenml-pro/zenml-cloud.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/build-pipelines/run-pipelines-asynchronously.md
  docs/book/introduction.md
  docs/book/reference/how-do-i.md
  docs/book/reference/migration-guide/migration-zero-twenty.md
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/production-guide/README.md
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: internal, backport

#2764 Remove default system flag in docker UV
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: internal

#2762 Another batch of small fixes and expansions
  docs/book/how-to/build-pipelines/README.md
  docs/book/how-to/build-pipelines/access-secrets-in-a-step.md
  docs/book/how-to/build-pipelines/run-pipelines-asynchronously.md
  docs/book/how-to/build-pipelines/schedule-a-pipeline.md
  docs/book/how-to/build-pipelines/specify-pip-or-apt-requirements.md
  docs/book/how-to/build-pipelines/step-output-typing-and-annotation.md
  docs/book/how-to/customize-docker-builds/specify-pip-dependencies-and-apt-packages.md
  docs/book/toc.md
Labels: documentation, internal

#2752 Server scalability improvements
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal, run-slow-ci

#2758 Add option to start parallel kubernetes steps with delay
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/orchestrators/dag_runner.py
Labels: enhancement, internal, run-slow-ci

#2765 Move `thread_limiter` to app startup event
  docs/sys_modules_mock.py
  src/zenml/integrations/airflow/__init__.py
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal

#2755 Logging performance improvements and GCP logging fix
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/integrations/gcp/artifact_stores/gcp_artifact_store.py
  src/zenml/integrations/gcp/flavors/gcp_artifact_store_flavor.py
  src/zenml/logging/__init__.py
  src/zenml/logging/step_logging.py
  src/zenml/zen_server/routers/steps_endpoints.py
  tests/integration/functional/artifacts/test_artifact_store.py
  tests/integration/functional/steps/test_logging.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2768 Extend migration testing
  scripts/test-migrations.sh
Labels: internal

#2770 Add retry docs
  docs/book/how-to/build-pipelines/retry-steps.md
  docs/book/how-to/build-pipelines/run-pipelines-asynchronously.md
  docs/book/toc.md
Labels: internal

#2769 Fix nightly Docker build
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_to_pypi_nightly.yml
Labels: bug, internal

#2773 Start CTA and Cloud -> Pro renaming
  README.md
Labels: enhancement, internal

#2777 Add star CTA to `README`
  README.md
Labels: documentation, enhancement, internal

#2775 Use build python version if available
  src/zenml/zen_server/pipeline_deployment/utils.py
Labels: enhancement, internal

#2778 Fixing the nlp template for the upcoming pydantic upgrade
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/steps/deploying/skypilot_deployment.py
  examples/e2e_nlp/steps/promotion/promote_metric_compare_promoter.py
  src/zenml/cli/base.py
Labels: bug, internal

#2733 Update KFP, Tekton and Vertex for Pydantic 2.x
  pyproject.toml
  src/zenml/integrations/evidently/data_validators/evidently_data_validator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubeflow/utils.py
  src/zenml/integrations/tekton/flavors/tekton_orchestrator_flavor.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  tests/integration/integrations/gcp/artifact_stores/test_gcp_artifact_store.py
  tests/integration/integrations/gcp/image_builders/test_gcp_image_builder.py
  tests/integration/integrations/gcp/orchestrators/test_vertex_orchestrator.py
  tests/integration/integrations/kubeflow/orchestrators/test_kubeflow_orchestrator.py
  tests/integration/integrations/kubeflow/test_utils.py
Labels: enhancement, internal, dependencies, run-slow-ci

#2782 Full renaming away from cloud to pro
  RELEASE_NOTES.md
  docs/book/getting-started/deploying-zenml/manage-the-deployed-services/secret-management.md
  docs/book/getting-started/installation.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/system-architectures.md
  docs/book/getting-started/zenml-pro/user-management.md
  docs/book/getting-started/zenml-pro/zenml-cloud.md
  docs/book/how-to/handle-data-artifacts/tagging.md
  docs/book/how-to/use-the-model-control-plane/README.md
  docs/book/how-to/use-the-model-control-plane/promote-a-model.md
  docs/book/how-to/use-the-model-control-plane/register-a-model.md
  docs/book/reference/migration-guide/migration-zero-twenty.md
  docs/book/user-guide/llmops-guide/rag-with-zenml/understanding-rag.md
  docs/book/user-guide/production-guide/configure-pipeline.md
  docs/book/user-guide/production-guide/deploying-zenml.md
  docs/book/user-guide/production-guide/remote-storage.md
  src/zenml/new/pipelines/run_utils.py
  src/zenml/utils/cloud_utils.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/feature_gate/zenml_cloud_feature_gate.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
Labels: enhancement, internal

#2772 Adjust docs url for flavors
  src/zenml/stack/flavor.py
  src/zenml/utils/package_utils.py
Labels: documentation, internal

#2785 Fixed brokend unit test on develop and fixed duplicate /
  src/zenml/stack/flavor.py
  tests/unit/test_flavor.py
Labels: bug, internal

#2786 Added timeout
  src/zenml/utils/package_utils.py
Labels: bug, internal, run-slow-ci

#2787 Bump NLP template
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/steps/dataset_loader/data_loader.py
  examples/e2e_nlp/utils/misc.py
  src/zenml/cli/base.py
Labels: bug, internal

#2776 Raise error if Dockerfile does not exist
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal

#2789 Pin `numpy<2.0.0`
  .github/workflows/integration-test-slow.yml
  pyproject.toml
  scripts/test-migrations.sh
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/langchain/__init__.py
  src/zenml/integrations/neural_prophet/__init__.py
Labels: internal, dependencies, run-slow-ci

#2788 Fix partial logs loss in step operators with immutable FS in the backend
  src/zenml/config/step_run_info.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/spark/step_operators/spark_step_operator.py
  src/zenml/logging/step_logging.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/step_operators/step_operator_entrypoint_configuration.py
  tests/unit/conftest.py
  tests/unit/orchestrators/test_step_runner.py
  tests/unit/test_environment.py
Labels: bug, internal, run-slow-ci

#2781 Improvements for running pipelines from the dashboard
  src/zenml/zen_server/pipeline_deployment/utils.py
Labels: enhancement, internal, run-slow-ci

#2780 Add `--ignore-errors` flag for `zenml artifact prune`
  docs/book/how-to/handle-data-artifacts/delete-an-artifact.md
  src/zenml/cli/__init__.py
  src/zenml/cli/artifact.py
Labels: enhancement, internal, run-slow-ci

#2736 Enable running a pipeline through the client
  src/zenml/client.py
  src/zenml/exceptions.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/zen_server/exceptions.py
  src/zenml/zen_server/pipeline_deployment/utils.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal, run-slow-ci

#2793 Fix hook type definition and improve code completion for pipeline decorator
  src/zenml/hooks/hook_validators.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/pipeline_decorator.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/new/steps/step_decorator.py
  src/zenml/pipelines/base_pipeline.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/types.py
Labels: bug, internal, run-slow-ci

#2749 Allow specifying build options for main image build
  docs/book/how-to/customize-docker-builds/docker-settings-on-a-pipeline.md
  docs/book/how-to/customize-docker-builds/use-your-own-docker-files.md
  docs/book/how-to/customize-docker-builds/which-files-are-built-into-the-image.md
  src/zenml/config/docker_settings.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal, run-slow-ci

#2796 Small improvements for yaml config files
  src/zenml/config/compiler.py
  src/zenml/new/pipelines/pipeline.py
  tests/unit/config/test_compiler.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: bug, internal, run-slow-ci

#2801 Docs for the `pydantic` migration guide
  docs/book/reference/migration-guide/migration-guide.md
  docs/book/reference/migration-guide/migration-zero-sixty.md
  docs/book/toc.md
Labels: documentation, internal

#2779 Bump mlflow to v2.14.1
  src/zenml/integrations/mlflow/__init__.py
Labels: dependencies, run-slow-ci

#2803 Bugfix fixing the installation script to use the right mlstacks branch
  scripts/install-zenml-dev.sh
Labels: bug, internal

#2802 Fix S3 artifact store memory leak and other improvements
  .typos.toml
  docs/mocked_libs.json
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifacts/utils.py
  src/zenml/cli/service_connectors.py
  src/zenml/client.py
  src/zenml/integrations/s3/artifact_stores/s3_artifact_store.py
  src/zenml/logging/step_logging.py
  src/zenml/stack/stack_component.py
Labels: bug, internal, run-slow-ci

#2805 Fix the `mlstacks` dependency
  pyproject.toml
Labels: bug, internal, dependencies

#2708 Extract project ID from GCP service connector SA credentials
  src/zenml/integrations/gcp/google_credentials_mixin.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal, run-slow-ci

#2804 Prepare release 0.60.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.60.0_release.py
Labels: internal, run-slow-ci

#2771 Add service connector support for Google Artifact Registry
  docs/book/component-guide/container-registries/gcp.md
  docs/book/how-to/auth-management/gcp-service-connector.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: enhancement, internal, run-slow-ci

#2806 Added docs for trigger interface
  .typos.toml
  docs/book/.gitbook/assets/rest_api_step_1.png
  docs/book/.gitbook/assets/rest_api_step_2.png
  docs/book/component-guide/container-registries/aws.md
  docs/book/how-to/auth-management/docker-service-connector.md
  docs/book/how-to/build-pipelines/compose-pipelines.md
  docs/book/how-to/build-pipelines/configuring-a-pipeline-at-runtime.md
  docs/book/how-to/build-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/handle-data-artifacts/handle-custom-data-types.md
  docs/book/how-to/handle-data-artifacts/unmaterialized-artifacts.md
  docs/book/how-to/trigger-pipelines/README.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-client.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-rest-api.md
  docs/book/reference/api-reference.md
  docs/book/toc.md
Labels: documentation, internal
