Repository zenml-io/zenml, pull requests merged in 2024-04, with the labels that each got.

#2580 [DOCS] Fix code block in Vertex docs
  docs/book/stacks-and-components/component-guide/orchestrators/vertex.md
Labels: documentation, internal

#2570 Added an AWS cloud guide
  docs/book/.gitbook/assets/vpc_zenml.png
  docs/book/toc.md
  docs/book/user-guide/cloud-guide/aws-guide.md
  docs/book/user-guide/cloud-guide/cloud-guide.md
  docs/book/user-guide/cloud-guide/gcp-guide.md
Labels: documentation, internal

#2585 More docs fixes
  docs/book/user-guide/production-guide/end-to-end.md
  docs/book/user-guide/production-guide/understand-stacks.md
  docs/book/user-guide/starter-guide/starter-project.md
  examples/quickstart/README.md
Labels: documentation

#2588 Backport AWS docs update
  docs/book/.gitbook/assets/vpc_zenml.png
  docs/book/toc.md
  docs/book/user-guide/cloud-guide/aws-guide.md
  docs/book/user-guide/cloud-guide/cloud-guide.md
  docs/book/user-guide/cloud-guide/gcp-guide.md
  docs/book/user-guide/production-guide/end-to-end.md
  docs/book/user-guide/production-guide/understand-stacks.md
  docs/book/user-guide/starter-guide/starter-project.md
  examples/quickstart/README.md
Labels: documentation, backport

#2586 Bugfix for the `pyyaml_include` version for `copier`
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/llm_finetuning/.copier-answers.yml
  examples/quickstart/.copier-answers.yml
  examples/quickstart/README.md
  examples/quickstart/quickstart.ipynb
  pyproject.toml
  scripts/test-migrations-mysql.sh
  src/zenml/cli/base.py
  tests/integration/functional/cli/test_hub.py
  tests/integration/functional/model/test_model_version.py
Labels: bug, internal, run-slow-ci

#2582 Update fastapi and orjson to fix python-multipart and orjson vulnerabilities
  examples/llm_finetuning/.copier-answers.yml
  examples/quickstart/.copier-answers.yml
  pyproject.toml
Labels: bug, internal, run-slow-ci

#2583 Add security headers to the ZenML server
  docker/base.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docker/zenml-server-hf-spaces.Dockerfile
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  pyproject.toml
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
Labels: security, run-slow-ci, P2

#2591 Fix and update AWS cloud guide
  docs/book/user-guide/cloud-guide/aws-guide.md
Labels: documentation, enhancement, internal

#2572 Add `start_time` support to HyperAI orchestrator scheduled pipelines
  docs/book/stacks-and-components/component-guide/orchestrators/hyperai.md
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/pipelining-features/schedule-pipeline-runs.md
  src/zenml/client.py
  src/zenml/config/schedule.py
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
  src/zenml/models/v2/core/schedule.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/zen_stores/migrations/versions/1d74e596abb8_add_run_once_start_time_to_schedule.py
  src/zenml/zen_stores/schemas/schedule_schema.py
  tests/unit/pipelines/test_schedule.py
Labels: enhancement, run-slow-ci

#2592 Make `secure` an optional import
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/llm_finetuning/.copier-answers.yml
  src/zenml/cli/base.py
  src/zenml/zen_server/utils.py
Labels: bug, internal, run-slow-ci

#2525 RAG guide for docs
  .gitignore
  docs/book/.gitbook/assets/llm-data-ingestion-metadata.png
  docs/book/.gitbook/assets/rag-and-zenml.png
  docs/book/.gitbook/assets/rag-inference.png
  docs/book/.gitbook/assets/rag-overview.png
  docs/book/.gitbook/assets/rag-process-whole.png
  docs/book/.gitbook/assets/rag-stage-1.png
  docs/book/.gitbook/assets/rag-stage-2.png
  docs/book/.gitbook/assets/rag-stage-3.png
  docs/book/.gitbook/assets/rag-stage-4.png
  docs/book/.gitbook/assets/rag-when.png
  docs/book/.gitbook/assets/supabase-editor-interface.png
  docs/book/.gitbook/assets/tsne.png
  docs/book/.gitbook/assets/umap.png
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-for-better-retrieval-performance.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/integrating-finetuned-embeddings-into-zenml-pipelines.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms-for-specific-tasks.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/synthetic-data-generation.md
  docs/book/user-guide/llmops-guide/finetuning-llms/tracking-finetuned-llm-models.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/rag/basic-rag-inference-pipeline.md
  docs/book/user-guide/llmops-guide/rag/data-ingestion.md
  docs/book/user-guide/llmops-guide/rag/embeddings-generation.md
  docs/book/user-guide/llmops-guide/rag/rag-with-zenml.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/llmops-guide/rag/understanding-rag.md
  docs/book/user-guide/llmops-guide/reranking/implementing-reranking.md
  docs/book/user-guide/llmops-guide/reranking/reranking.md
  docs/book/user-guide/llmops-guide/reranking/understanding-reranking.md
Labels: documentation, internal

#2593 Add a note about the `f` prefix being needed for template strings
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: documentation, internal

#2594 RAG guide for docs (#2525)
  .gitignore
  docs/book/.gitbook/assets/llm-data-ingestion-metadata.png
  docs/book/.gitbook/assets/rag-and-zenml.png
  docs/book/.gitbook/assets/rag-inference.png
  docs/book/.gitbook/assets/rag-overview.png
  docs/book/.gitbook/assets/rag-process-whole.png
  docs/book/.gitbook/assets/rag-stage-1.png
  docs/book/.gitbook/assets/rag-stage-2.png
  docs/book/.gitbook/assets/rag-stage-3.png
  docs/book/.gitbook/assets/rag-stage-4.png
  docs/book/.gitbook/assets/rag-when.png
  docs/book/.gitbook/assets/supabase-editor-interface.png
  docs/book/.gitbook/assets/tsne.png
  docs/book/.gitbook/assets/umap.png
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-for-better-retrieval-performance.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/integrating-finetuned-embeddings-into-zenml-pipelines.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms-for-specific-tasks.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/synthetic-data-generation.md
  docs/book/user-guide/llmops-guide/finetuning-llms/tracking-finetuned-llm-models.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/rag/basic-rag-inference-pipeline.md
  docs/book/user-guide/llmops-guide/rag/data-ingestion.md
  docs/book/user-guide/llmops-guide/rag/embeddings-generation.md
  docs/book/user-guide/llmops-guide/rag/rag-with-zenml.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/llmops-guide/rag/understanding-rag.md
  docs/book/user-guide/llmops-guide/reranking/implementing-reranking.md
  docs/book/user-guide/llmops-guide/reranking/reranking.md
  docs/book/user-guide/llmops-guide/reranking/understanding-reranking.md
Labels: documentation, internal, backport

#2589 Use the correct validity for EKS API tokens and handle long-running Kubernetes pipelines
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/utils/docker_utils.py
Labels: bug, internal, run-slow-ci

#2595 Allow resources required for the fastapi OpenAPI docs in the CSP header
  src/zenml/constants.py
Labels: bug, internal

#2599 Fix mariadb test script
  scripts/test-migrations-mariadb.sh
Labels: bug, internal

#2598 Disable CSP headers for the openAPI docs pages and fix API docs building
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/constants.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal, run-slow-ci

#2596 Add short motivating example for RAG pipeline
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/rag/rag-85-loc.md
Labels: documentation, internal

#2606 Add short motivating example for RAG pipeline (#2596)
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/rag/rag-85-loc.md
Labels: documentation, internal, backport

#2607 Fix DB backup and restore and add database upgrade testing improvements
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/release.yml
  examples/e2e/.copier-answers.yml
  examples/e2e_nlp/.copier-answers.yml
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
  scripts/test-migrations.sh
  src/zenml/zen_stores/migrations/utils.py
  src/zenml/zen_stores/migrations/versions/2d201872e23c_remove_db_dependency_loop.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal, tests, CI, run-slow-ci

#2603 Fix for #2556
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2611 Fix AWS service connector resource ID regexp
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
Labels: bug, internal, run-slow-ci

#2612 Add dry run for docs CI
  scripts/generate-docs.sh
Labels: bug, internal

#2605 Completing and refining the CLI documentation
  src/zenml/cli/__init__.py
Labels: documentation, internal

#2613 Allow DB backup failures if the database version is 0.56.3 or earlier
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2609 Add support for `uv` package installer for `zenml integration ...` commands
  docs/book/stacks-and-components/component-guide/integration-overview.md
  src/zenml/cli/__init__.py
  src/zenml/cli/integration.py
  src/zenml/cli/utils.py
Labels: enhancement, internal, run-slow-ci

#2615 Evaluation guide (backport)
  docs/book/.gitbook/assets/evaluation-65-loc.png
  docs/book/.gitbook/assets/evaluation-two-parts.png
  docs/book/.gitbook/assets/generation-eval-automated.png
  docs/book/.gitbook/assets/generation-eval-manual.png
  docs/book/.gitbook/assets/hf-qa-embedding-questions.png
  docs/book/.gitbook/assets/retrieval-eval-automated.png
  docs/book/.gitbook/assets/retrieval-eval-manual.png
  docs/book/.gitbook/assets/supabase-editor-interface.png
  docs/book/.gitbook/assets/tsne.png
  docs/book/.gitbook/assets/umap.png
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/data-management/visualize-artifacts.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-65-loc.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-practice.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation.md
  docs/book/user-guide/llmops-guide/evaluation/generation.md
  docs/book/user-guide/llmops-guide/evaluation/retrieval.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/rag/basic-rag-inference-pipeline.md
  docs/book/user-guide/llmops-guide/rag/data-ingestion.md
  docs/book/user-guide/llmops-guide/rag/embeddings-generation.md
  docs/book/user-guide/llmops-guide/rag/rag-85-loc.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/llmops-guide/rag/understanding-rag.md
Labels: documentation, internal, backport

#2625 Updated security email
  SECURITY.md
Labels: internal

#2620 Add Comet Experiment Tracker integration
  docs/book/stacks-and-components/component-guide/experiment-trackers/comet.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/experiment-trackers.md
  docs/mocked_libs.json
  src/zenml/integrations/__init__.py
  src/zenml/integrations/comet/__init__.py
  src/zenml/integrations/comet/experiment_trackers/__init__.py
  src/zenml/integrations/comet/experiment_trackers/comet_experiment_tracker.py
  src/zenml/integrations/comet/flavors/__init__.py
  src/zenml/integrations/comet/flavors/comet_experiment_tracker_flavor.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
Labels: enhancement, internal, run-slow-ci

#2619 Fix cached artifacts produced via `save_artifact` inside steps linkage to MCP
  src/zenml/model/utils.py
  src/zenml/orchestrators/step_launcher.py
  tests/integration/functional/model/test_model_version.py
Labels: bug, internal, run-slow-ci

#2632 Update MCP instructions
  src/zenml/model/model.py
Labels: internal

#2623 Replace parse_obj
  src/zenml/orchestrators/step_runner.py
  tests/unit/orchestrators/test_step_runner.py
Labels: bug, enhancement, internal, run-slow-ci

#2624 Return up-to-date `PipelineRunResponse` from pipeline run
  src/zenml/new/pipelines/pipeline.py
  tests/integration/functional/pipelines/test_pipeline_run.py
Labels: bug, internal, run-slow-ci

#2637 Add Comet to Experiment Trackers in TOC
  docs/book/toc.md
Labels: documentation, internal

#2638 Add comet to TOC (#2637)
  docs/book/toc.md
Labels: documentation, internal, backport

#2630 ZenML Server activation and user on-boarding
  docker/zenml-server-hf-spaces.Dockerfile
  docs/book/deploying-zenml/zenml-self-hosted/deploy-using-huggingface-spaces.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-zenml-cli.md
  examples/e2e/.copier-answers.yml
  examples/e2e/README.md
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/README.md
  examples/quickstart/.copier-answers.yml
  src/zenml/analytics/context.py
  src/zenml/analytics/enums.py
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/base/base.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/run_metadata.py
  src/zenml/models/v2/core/server_settings.py
  src/zenml/models/v2/core/user.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_server/deploy/helm/templates/NOTES.txt
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/deploy/terraform/recipes/aws/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/aws/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/azure/zen_server.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/outputs.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/variables.tf
  src/zenml/zen_server/deploy/terraform/recipes/gcp/zen_server.tf
  src/zenml/zen_server/deploy/terraform/terraform_zen_server.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/46506f72f0ed_add_server_settings.py
  src/zenml/zen_stores/migrations/versions/cc9894cb58aa_add_user_metadata.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/identity_schemas.py
  src/zenml/zen_stores/schemas/server_settings_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/harness/deployment/server_docker_mariadb.py
  tests/harness/deployment/server_docker_mysql.py
  tests/integration/functional/cli/test_user_management.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2617 Slimmer and more secure Docker container images
  .dockerignore
  .github/workflows/trivy-zenml-core.yml
  .github/workflows/trivy-zenserver.yml
  .trivyignore
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  release-cloudbuild-nightly.yaml
  release-cloudbuild.yaml
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/logging/step_logging.py
  tests/harness/deployment/base.py
  trivy-secret.yaml
Labels: bug, internal, breaking-change, run-slow-ci

#2642 Add dashboard v2 source context
  src/zenml/enums.py
Labels: enhancement, internal

#2635 Support New Dashboard release
  scripts/install-dashboard.sh
  scripts/install-zenml-dev.sh
  src/zenml/cli/server.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2643 Add rate limiting to user password reset operations
  src/zenml/zen_server/rate_limit.py
  src/zenml/zen_server/routers/users_endpoints.py
Labels: bug, internal, run-slow-ci

#2647 Set zenml server name to default if not customized
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#2649 Docker release fix
  docker/base.Dockerfile
Labels: bug, internal

#2648 Fix dashboard urls
  src/zenml/utils/dashboard_utils.py
Labels: bug, internal, run-slow-ci

#2652 Enable analytics during db initialization if specified
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
Labels: bug, internal

#2622 Better checks for user account updates to avoid Mass Assignment attacks
  src/zenml/cli/__init__.py
  src/zenml/models/v2/core/user.py
  src/zenml/zen_server/routers/users_endpoints.py
  tests/integration/functional/cli/test_user_management.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal, run-slow-ci

#2651 Prepare 0.57.0-rc2
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  scripts/install-dashboard.sh
  src/zenml/VERSION
  src/zenml/constants.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.57.0.rc2_release.py
Labels: internal, run-slow-ci

#2653 Fix frontend analytics calls
  src/zenml/constants.py
Labels: bug, internal

#2628 Label studio settings and optional port
  docs/book/stacks-and-components/component-guide/annotators/label-studio.md
  pyproject.toml
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/label_studio/flavors/__init__.py
  src/zenml/integrations/label_studio/flavors/label_studio_annotator_flavor.py
Labels: enhancement, internal, run-slow-ci
