Repository zenml-io/zenml, pull requests merged in 2024-05, with the labels that each got.

#2654 Introduce default value fro enable_analytics
  src/zenml/models/v2/misc/server_models.py
Labels: enhancement, internal

#2656 Fix helm chart notes syntax
  src/zenml/zen_server/deploy/helm/templates/NOTES.txt
Labels: internal

#2657 Add server env variable to fix activation
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
Labels: bug, internal

#2658 Respect analytic ENV in local servers
  src/zenml/cli/server.py
  src/zenml/constants.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2659 Small fixes in helm docs
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
Labels: documentation, internal

#2660 Prepare release 0.57.0
  README.md
  RELEASE_NOTES.md
  docs/book/.gitbook/assets/new_dashboard_rn_2.png
  docs/book/.gitbook/assets/new_dashboard_rn_3.png
  docs/book/.gitbook/assets/new_dashboard_rn_4.png
  pyproject.toml
  scripts/install-dashboard.sh
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.57.0_release.py
Labels: internal, run-slow-ci

#2663 Add new versions to migration testing
  scripts/test-migrations.sh
Labels: internal

#2664 Resource settings import fix
  docs/book/stacks-and-components/component-guide/model-deployers/seldon.md
  docs/book/user-guide/advanced-guide/infrastructure-management/scale-compute-to-the-cloud.md
Labels: documentation, internal

#2668 Fix env variable for legacy dashboard
  RELEASE_NOTES.md
Labels: bug, internal

#2669 Fix env variable for legacy dashboard (#2668)
  RELEASE_NOTES.md
Labels: documentation, backport

#2672 Fix broken links in code examples
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-65-loc.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-practice.md
  docs/book/user-guide/llmops-guide/evaluation/generation.md
  docs/book/user-guide/llmops-guide/evaluation/retrieval.md
Labels: documentation, internal

#2673 Fix eval guide links (#2672)
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-65-loc.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation-in-practice.md
  docs/book/user-guide/llmops-guide/evaluation/generation.md
  docs/book/user-guide/llmops-guide/evaluation/retrieval.md
Labels: documentation, internal, backport

#2674 Improve error message when trying to unpack a step artifact
  src/zenml/steps/entrypoint_function_utils.py
  tests/unit/steps/test_base_step_new.py
Labels: enhancement, internal, run-slow-ci

#2665 Prevent special whitespaces in the names of entities
  scripts/test-coverage-xml.sh
  src/zenml/constants.py
  src/zenml/utils/string_utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal, run-slow-ci

#2670 Ensure extra flags aren't passed into `uv` integration install command
  src/zenml/cli/utils.py
Labels: bug, internal, run-slow-ci

#2574 `enable_cache` option shouldn't be set to `False` for one of the steps
  docs/book/user-guide/starter-guide/cache-previous-executions.md
Labels: documentation

#2678 Add new dashboard links to create/deactivate CLI commands
  src/zenml/cli/user_management.py
Labels: bug, internal

#2679 Add reranking section to LLMOps guide
  docs/book/.gitbook/assets/reranker_evaluation_metrics.png
  docs/book/.gitbook/assets/reranking-evaluation.png
  docs/book/.gitbook/assets/reranking-workflow.png
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/llmops-guide.md
  docs/book/user-guide/llmops-guide/reranking/evaluating-reranking-performance.md
  docs/book/user-guide/llmops-guide/reranking/implementing-reranking.md
  docs/book/user-guide/llmops-guide/reranking/reranking.md
  docs/book/user-guide/llmops-guide/reranking/understanding-reranking.md
Labels: documentation, internal

#2684 Added Thumbnail
  README.md
  docs/book/.gitbook/assets/readme_youtube_thumbnail.png
Labels: documentation, enhancement, internal

#2671 [k8s orchestrator] Fix credentials refresh and don't use service connector for incluster auth
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
Labels: bug, internal, run-slow-ci

#2683 Prepare Release 0.57.1
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.57.1_release.py
Labels: internal, run-slow-ci

#2692 Include email in event
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#2694 Set newsletter flag from email opted in
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2680 Only report usage once pipeline run starts
  src/zenml/constants.py
  src/zenml/zen_server/feature_gate/endpoint_utils.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2690 Fix intermittent timeout issues with service connector sessions
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal, run-slow-ci

#2695 Include unique constraints in the database backup
  scripts/test-migrations.sh
  src/zenml/analytics/context.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/utils.py
Labels: bug, internal, run-slow-ci

#2688 [k8s orch] Add option to specify separate service account for step pods
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
Labels: enhancement, internal, run-slow-ci

#2676 Update GCP registry docs
  docs/book/stacks-and-components/component-guide/container-registries/gcp.md
Labels: enhancement, internal, run-slow-ci

#2682 Use service connector for boto session if possible
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
Labels: enhancement, internal, run-slow-ci

#2696 Send missing user enriched events
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2698 Re-Prepare release 0.57.1
  RELEASE_NOTES.md
  src/zenml/zen_stores/migrations/versions/0.57.1_release.py
Labels: internal, run-slow-ci

#2655 Prodigy annotator
  docs/book/.gitbook/assets/prodigy-annotator.png
  docs/book/stacks-and-components/component-guide/annotators/annotators.md
  docs/book/stacks-and-components/component-guide/annotators/prodigy.md
  docs/book/toc.md
  docs/mocked_libs.json
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/annotators/base_annotator.py
  src/zenml/cli/annotator.py
  src/zenml/cli/utils.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
  src/zenml/integrations/prodigy/__init__.py
  src/zenml/integrations/prodigy/annotators/__init__.py
  src/zenml/integrations/prodigy/annotators/prodigy_annotator.py
  src/zenml/integrations/prodigy/flavors/__init__.py
  src/zenml/integrations/prodigy/flavors/prodigy_annotator_flavor.py
Labels: enhancement, internal, run-slow-ci

#2702 add 0.57.1 to migration test scripts
  scripts/test-migrations.sh
Labels: internal, run-slow-ci

#2641 Pigeon annotator
  docs/book/.gitbook/assets/pigeon.png
  docs/book/stacks-and-components/component-guide/annotators/annotators.md
  docs/book/stacks-and-components/component-guide/annotators/pigeon.md
  docs/book/toc.md
  scripts/install-zenml-dev.sh
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/pigeon/__init__.py
  src/zenml/integrations/pigeon/annotators/__init__.py
  src/zenml/integrations/pigeon/annotators/pigeon_annotator.py
  src/zenml/integrations/pigeon/flavors/__init__.py
  src/zenml/integrations/pigeon/flavors/pigeon_annotator_flavor.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#2704 Allow credentials expiry to be configured for service connectors
  src/zenml/cli/service_connectors.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
Labels: bug, internal, run-slow-ci

#2687 Argilla annotator
  docs/book/.gitbook/assets/argilla_annotator.png
  docs/book/stacks-and-components/component-guide/annotators/annotators.md
  docs/book/stacks-and-components/component-guide/annotators/argilla.md
  docs/book/toc.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/annotators/base_annotator.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/argilla/__init__.py
  src/zenml/integrations/argilla/annotators/__init__.py
  src/zenml/integrations/argilla/annotators/argilla_annotator.py
  src/zenml/integrations/argilla/flavors/__init__.py
  src/zenml/integrations/argilla/flavors/argilla_annotator_flavor.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/label_studio/annotators/label_studio_annotator.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#2686 Add `MySQL` and `mariadb` migration tests to Slow CI
  .github/workflows/ci-slow.yml
Labels: internal, tests, CI, run-slow-ci

#2712 Misc small fixes
  docs/book/stacks-and-components/component-guide/container-registries/gcp.md
  src/zenml/container_registries/github_container_registry.py
Labels: enhancement, internal

#2666 Allow resetting server and user metadata
  src/zenml/zen_stores/schemas/server_settings_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
Labels: bug, internal, run-slow-ci

#2709 Add note about helm dependencies
  docs/book/stacks-and-components/component-guide/orchestrators/kubeflow.md
Labels: documentation, internal

#2627 Add retry config for failing steps
  docs/book/user-guide/advanced-guide/pipelining-features/managing-steps.md
  src/zenml/config/__init__.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/config/retry_config.py
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/new/steps/step_decorator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  tests/unit/conftest.py
Labels: enhancement, internal, run-slow-ci

#2710 Update pyparsing version
  pyproject.toml
Labels: internal, dependencies, run-slow-ci

#2718 New ruff issue
  src/zenml/zen_server/zen_server_api.py
Labels: bug, internal

#2703 Add `model_version_id` as part of the Model config
  src/zenml/client.py
  src/zenml/model/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/test_model_version.py
Labels: bug, internal, run-slow-ci

#2706 Add more runners to fast CI
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-fast.yml
  scripts/test-migrations.sh
Labels: enhancement, internal, CI, run-slow-ci

#2721 Fail faster on notebook installation and only clone / download the branch we need for `zenml go`
  src/zenml/cli/base.py
Labels: bug, internal, run-slow-ci

#2722 Make a clear separation between server and dashboard API in the server configuration
  .github/actions/setup_environment/action.yml
  scripts/install-zenml-dev.sh
  src/zenml/config/server_config.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/utils/dashboard_utils.py
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/pipeline_deployment/utils.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2714 Update pymysql to fix CVE-2024-36039
  pyproject.toml
Labels: bug, internal, run-slow-ci

#2717 Allow specifying privileged mode for Kubernetes orchestrator containers
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
Labels: enhancement, internal

#2707 Don't use pod resources/affinity for kubernetes orchestrator pod
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#2715 Extra test for artifact listing
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: internal, run-slow-ci

#2726 Prepare release 0.58.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.58.0_release.py
Labels: internal, run-slow-ci

#2730 Add 0.58.0 to migration testing
  scripts/test-migrations.sh
Labels: internal

#2728 Print step names in color, again
  src/zenml/config/compiler.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/new/steps/step_context.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/base_step.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal

#2724 Workflow to create JIRA tickets when Github Issues are created
  .github/workflows/jira.yml
Labels: enhancement, internal, CI

#2727 Allow specifying python package installer args
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docs/book/user-guide/advanced-guide/infrastructure-management/containerize-your-pipeline.md
  src/zenml/config/docker_settings.py
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal, run-slow-ci

#2737 Documentation updates (4 sections)
  docs/book/.gitbook/assets/metadata-in-dashboard.png
  docs/book/.gitbook/assets/opendev_search_bar.png
  docs/book/.gitbook/assets/tags-in-dashboard.png
  docs/book/.gitbook/assets/zenml_artifact_store_underthehood_1.png
  docs/book/.gitbook/assets/zenml_artifact_store_underthehood_2.png
  docs/book/.gitbook/assets/zenml_artifact_store_underthehood_3.png
  docs/book/component-guide/README.md
  docs/book/component-guide/component-guide.md
  docs/book/component-guide/integration-overview.md
  docs/book/how-to/debug-and-solve-issues.md
  docs/book/how-to/handle-data-artifacts/README.md
  docs/book/how-to/handle-data-artifacts/artifact-versioning.md
  docs/book/how-to/handle-data-artifacts/attach-metadata-to-a-artifact.md
  docs/book/how-to/handle-data-artifacts/get-arbitrary-artifacts-in-a-step.md
  docs/book/how-to/handle-data-artifacts/load-artifacts-into-memory.md
  docs/book/how-to/handle-data-artifacts/passing-artifacts-between-pipelines.md
  docs/book/how-to/handle-data-artifacts/return-multiple-outputs-from-a-step.md
  docs/book/how-to/handle-data-artifacts/tagging.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/stack-deployment/contribute-flavors-or-components.md
  docs/book/how-to/stack-deployment/deploy-a-stack-component.md
  docs/book/how-to/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/how-to/stack-deployment/implement-a-custom-integration.md
  docs/book/how-to/stack-deployment/reference-secrets-in-stack-configuration.md
  docs/book/toc.md
Labels: documentation, internal

#2711 Fix Nightly Release
  .github/workflows/nightly_build.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_to_pypi_nightly.yml
  .github/workflows/release.yml
  docker/base.Dockerfile
  examples/quickstart/license
  examples/quickstart/license_header
  examples/quickstart/pipelines/inference.py
  release-cloudbuild-nightly.yaml
Labels: bug, internal, CI, run-slow-ci

#2741 Docs updates (Hamza)
  docs/book/how-to/configure-python-environments/README.md
  docs/book/how-to/configure-python-environments/configure-the-server-environment.md
  docs/book/how-to/configure-python-environments/handling-dependencies.md
  docs/book/how-to/control-logging/README.md
  docs/book/how-to/control-logging/disable-colorful-logging.md
  docs/book/how-to/control-logging/disable-rich-traceback.md
  docs/book/how-to/control-logging/enable-or-disable-logs-storing.md
  docs/book/how-to/control-logging/set-logging-verbosity.md
  docs/book/how-to/control-logging/view-logs-on-the-dasbhoard.md
  docs/book/how-to/customize-docker-builds/README.md
  docs/book/how-to/customize-docker-builds/build-the-pipeline-without-running.md
  docs/book/how-to/customize-docker-builds/define-where-an-image-is-built.md
  docs/book/how-to/customize-docker-builds/docker-settings-on-a-pipeline.md
  docs/book/how-to/customize-docker-builds/docker-settings-on-a-step.md
  docs/book/how-to/customize-docker-builds/reuse-docker-builds.md
  docs/book/how-to/customize-docker-builds/use-code-repositories-to-speed-up-docker-build-times.md
  docs/book/how-to/customize-docker-builds/use-your-own-docker-files.md
  docs/book/how-to/customize-docker-builds/which-files-are-built-into-the-image.md
  docs/book/how-to/overview/specify-pip-or-apt-requirements.md
  docs/book/how-to/setting-up-a-project-repository/README.md
  docs/book/how-to/setting-up-a-project-repository/best-practices.md
  docs/book/how-to/setting-up-a-project-repository/connect-your-git-repository.md
  docs/book/reference/environment-variables.md
  docs/book/toc.md
Labels: documentation, internal
