Repository zenml-io/zenml, pull requests merged in 2024-08, with the labels that each got.

#2898 Document terraform stack deployment modules
  docs/book/component-guide/artifact-stores/azure.md
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/container-registries/aws.md
  docs/book/component-guide/container-registries/azure.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/image-builders/gcp.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/how-to/popular-integrations/aws-guide.md
  docs/book/how-to/popular-integrations/gcp-guide.md
  docs/book/how-to/stack-deployment/README.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/how-to/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/how-to/stack-deployment/register-a-cloud-stack.md
  docs/book/toc.md
  docs/book/user-guide/production-guide/cloud-orchestration.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: documentation, internal

#2897 Added untested azure schedule
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
Labels: enhancement, internal

#2901 README update
  README.md
  docs/book/.gitbook/assets/header.png
Labels: internal

#2900 Enable `Databricks` Unity Catalog for MLflow
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
  src/zenml/integrations/mlflow/flavors/mlflow_experiment_tracker_flavor.py
Labels: internal

#2894 Make urls pop out from the sea of purple/cyan in the logs
  src/zenml/logger.py
Labels: enhancement, internal

#2902 Add terraform as a supported stack deployment provider
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/azure_stack_deployment.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
Labels: enhancement, internal, run-slow-ci

#2907 Fix `Model` imports in docs
  docs/book/how-to/use-the-model-control-plane/associate-a-pipeline-with-a-model.md
Labels: documentation, internal

#2905 Remove hub references
  docs/book/how-to/customize-docker-builds/specify-pip-dependencies-and-apt-packages.md
  docs/book/how-to/use-configuration-files/autogenerate-a-template-yaml-file.md
  src/zenml/__init__.py
  src/zenml/_hub/__init__.py
  src/zenml/_hub/client.py
  src/zenml/_hub/constants.py
  src/zenml/_hub/utils.py
  src/zenml/analytics/enums.py
  src/zenml/cli/__init__.py
  src/zenml/cli/hub.py
  src/zenml/client.py
  src/zenml/config/docker_settings.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/logger.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/user.py
  src/zenml/models/v2/misc/hub_plugin_models.py
  src/zenml/models/v2/misc/user_auth.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/migrations/versions/909550c7c4da_remove_user_hub_token.py
  src/zenml/zen_stores/schemas/user_schemas.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/_hub/test_client.py
  tests/unit/_hub/test_utils.py
  tests/unit/conftest.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal, run-slow-ci

#2912 Bump NLP template
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/gradio/requirements.txt
  examples/e2e_nlp/requirements.txt
  src/zenml/cli/base.py
Labels: internal

#2908 Updated step operator docs
  docs/book/component-guide/step-operators/vertex.md
  docs/book/getting-started/zenml-pro/system-architectures.md
  docs/book/reference/global-settings.md
Labels: internal

#2895 Upload code to artifact store
  docs/book/how-to/customize-docker-builds/which-files-are-built-into-the-image.md
  docs/book/how-to/use-configuration-files/autogenerate-a-template-yaml-file.md
  docs/book/toc.md
  src/zenml/config/build_configuration.py
  src/zenml/config/docker_settings.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/image_builders/base_image_builder.py
  src/zenml/image_builders/build_context.py
  src/zenml/integrations/kaniko/image_builders/kaniko_image_builder.py
  src/zenml/models/v2/core/pipeline_deployment.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/new/pipelines/build_utils.py
  src/zenml/new/pipelines/code_archive.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/utils/archivable.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_stores/migrations/versions/026d4577b6a0_add_code_path.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  tests/unit/image_builders/test_build_context.py
  tests/unit/pipelines/test_build_utils.py
Labels: enhancement, internal, run-slow-ci

#2873 AzureML orchestrator
  docs/book/.gitbook/assets/azure_1.png
  docs/book/.gitbook/assets/azure_2.png
  docs/book/.gitbook/assets/azure_3.png
  docs/book/.gitbook/assets/azure_4.png
  docs/book/.gitbook/assets/azure_5.png
  docs/book/.gitbook/assets/azure_6.png
  docs/book/.gitbook/assets/azure_7.png
  docs/book/.gitbook/assets/azureml-pipelines.png
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/orchestrators/orchestrators.md
  docs/book/how-to/build-pipelines/schedule-a-pipeline.md
  docs/book/how-to/popular-integrations/aws-guide.md
  docs/book/how-to/popular-integrations/azure-guide.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  docs/book/toc.md
  docs/mocked_libs.json
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/azure/flavors/__init__.py
  src/zenml/integrations/azure/flavors/azureml_orchestrator_flavor.py
  src/zenml/integrations/azure/orchestrators/__init__.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator_entrypoint_config.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/stack_deployments/azure_stack_deployment.py
Labels: enhancement, internal, run-slow-ci

#2899 Run steps defined in notebooks with remote orchestrators
  docs/book/how-to/run-remote-pipelines-from-notebooks/README.md
  docs/book/how-to/run-remote-pipelines-from-notebooks/define-steps-in-notebook-cells.md
  docs/book/toc.md
  docs/mocked_libs.json
  src/zenml/config/source.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/environment.py
  src/zenml/image_builders/build_context.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/databricks/flavors/databricks_orchestrator_flavor.py
  src/zenml/new/pipelines/build_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/steps/base_step.py
  src/zenml/utils/code_utils.py
  src/zenml/utils/notebook_utils.py
  src/zenml/utils/source_utils.py
Labels: enhancement, internal, run-slow-ci

#2916 Fix broken / unparseable md docs file
  docs/book/how-to/run-remote-pipelines-from-notebooks/README.md
Labels: bug, documentation, internal

#2896 Bump mlflow to 2.15.0
  src/zenml/integrations/mlflow/__init__.py
Labels: run-slow-ci

#2918 Remove extra button
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/how-to/run-remote-pipelines-from-notebooks/README.md
Labels: documentation, internal

#2913 Added last timestamp to zenserver
  src/zenml/cli/web_login.py
  src/zenml/constants.py
  src/zenml/models/v2/core/server_settings.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/3dcc5d20e82f_add_last_user_activity.py
  src/zenml/zen_stores/schemas/server_settings_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2914 Fix the GCP Workload Identity Federation support in the GCP Service Connector
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal, run-slow-ci

#2921 Allow non-ascii characters in requests
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal, run-slow-ci

#2920 Prepare release 0.64.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.64.0_release.py
Labels: internal, run-slow-ci

#2924 Remove broken JIRA sync workflow
  .github/workflows/jira.yml
Labels: internal

#2925 Fix Hugging Face Spaces permissions
  docker/zenml-server-hf-spaces.Dockerfile
  docs/book/.gitbook/assets/hf-spaces-chart.png
  docs/book/getting-started/deploying-zenml/deploy-using-huggingface-spaces.md
  src/zenml/config/server_config.py
Labels: bug, documentation, internal

#2936 Add accelerate docs
  docs/book/how-to/training-with-gpus/accelerate-distributed-training.md
  docs/book/toc.md
Labels: documentation, internal

#2923 Adding 0.64.0 to migration tests
  scripts/test-migrations.sh
Labels: internal

#2938 Removed docker build docs + fixed CLI command for zenml pipeline build list
  docs/book/how-to/configure-python-environments/README.md
  docs/book/how-to/customize-docker-builds/build-the-pipeline-without-running.md
  docs/book/how-to/customize-docker-builds/reuse-docker-builds.md
  docs/book/how-to/customize-docker-builds/use-code-repositories-to-speed-up-docker-build-times.md
  docs/book/toc.md
  src/zenml/cli/pipeline.py
Labels: bug, internal

#2930 Throw an error when running integration installs when uv == False but pip is not installed
  src/zenml/cli/integration.py
  src/zenml/cli/utils.py
Labels: bug, run-slow-ci

#2927 Update AzureML step operator to SDK v2 and add service connector support
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack.md
  src/zenml/integrations/azure/azureml_utils.py
  src/zenml/integrations/azure/flavors/azureml.py
  src/zenml/integrations/azure/flavors/azureml_orchestrator_flavor.py
  src/zenml/integrations/azure/flavors/azureml_step_operator_flavor.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/stack_deployments/azure_stack_deployment.py
Labels: enhancement, internal, run-slow-ci

#2940 Improving the AzureML orchestrator docs
  docs/book/component-guide/orchestrators/azureml.md
Labels: documentation, internal

#2941 Update mlflow docs
  docs/book/component-guide/experiment-trackers/mlflow.md
Labels: internal

#2947 Tell users where they can import `DockerSettings` from
  docs/book/how-to/customize-docker-builds/specify-pip-dependencies-and-apt-packages.md
Labels: documentation, internal

#2949 Add GitHub Codespaces and VS Code Remote Container support
  src/zenml/enums.py
  src/zenml/environment.py
Labels: enhancement, internal

#2942 Enable running a single step on the active stack
  docs/book/how-to/build-pipelines/run-an-individual-step.md
  docs/book/how-to/run-remote-steps-and-pipelines-from-notebooks/README.md
  docs/book/how-to/run-remote-steps-and-pipelines-from-notebooks/limitations-of-defining-steps-in-notebook-cells.md
  docs/book/how-to/run-remote-steps-and-pipelines-from-notebooks/run-a-single-step-from-a-notebook.md
  docs/book/toc.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  src/zenml/constants.py
  src/zenml/steps/base_step.py
  src/zenml/steps/utils.py
  tests/unit/materializers/test_materializer_registry.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal, run-slow-ci

#2909 Dynamic (templated) names for model versions
  .typos.toml
  RELEASE_NOTES.md
  docs/book/component-guide/annotators/prodigy.md
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/orchestrators/databricks.md
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/how-to/build-pipelines/README.md
  docs/book/how-to/build-pipelines/schedule-a-pipeline.md
  docs/book/reference/environment-variables.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-with-sentence-transformers.md
  docs/book/user-guide/llmops-guide/reranking/evaluating-reranking-performance.md
  scripts/format.sh
  src/zenml/cli/__init__.py
  src/zenml/integrations/airflow/flavors/airflow_orchestrator_flavor.py
  src/zenml/integrations/azure/flavors/azureml.py
  src/zenml/integrations/azure/flavors/azureml_orchestrator_flavor.py
  src/zenml/integrations/databricks/flavors/databricks_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/huggingface/steps/accelerate_runner.py
  src/zenml/integrations/hyperai/flavors/hyperai_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/prodigy/annotators/prodigy_annotator.py
  src/zenml/model/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/new/pipelines/model_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/new/steps/step_context.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/utils/cloud_utils.py
  src/zenml/utils/function_utils.py
  src/zenml/utils/pydantic_utils.py
  src/zenml/utils/secret_utils.py
  src/zenml/utils/string_utils.py
  src/zenml/zen_server/template_execution/runner_entrypoint_configuration.py
  src/zenml/zen_stores/migrations/versions/bf2120261b5a_add_configured_model_version_id.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/constants.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/models/test_pipeline_run.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/test_model_version.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal, run-slow-ci

#2952 Adding an orchestrator URL to the AzureML orchestrator
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
Labels: enhancement, internal

#2954 Update python version of latest docker image
  release-cloudbuild.yaml
Labels: enhancement, internal

#2943 Make `run_with_accelerate` a pythonic decorator
  src/zenml/integrations/huggingface/steps/accelerate_runner.py
  src/zenml/utils/function_utils.py
  tests/integration/integrations/huggingface/steps/test_accelerate_runner.py
Labels: bug, internal, run-slow-ci

#2928 Bugfix for artifacts coming from a different artifact store
  src/zenml/artifacts/utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  tests/unit/artifacts/test_utils.py
  tests/unit/orchestrators/test_utils.py
Labels: bug, internal, run-slow-ci

#2906 Stack Request cleanup and improvements
  src/zenml/cli/stack.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/stack.py
  src/zenml/models/v2/misc/full_stack.py
  src/zenml/models/v2/misc/info_models.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2955 Silence pydantic protected namespace warnings
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
Labels: enhancement, internal

#2919 Extend notebook source replacement code to other objects apart from ZenML steps
  src/zenml/config/source.py
  src/zenml/materializers/base_materializer.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/utils/code_utils.py
  src/zenml/utils/notebook_utils.py
  src/zenml/utils/source_utils.py
Labels: enhancement, internal, run-slow-ci

#2958 Fix stack register CLI command
  src/zenml/cli/stack.py
Labels: bug, internal

#2931 Lightening studio orchestrator
  docs/book/.gitbook/assets/lightning_studio_ui.png
  docs/book/.gitbook/assets/lightning_studio_vscode.png
  docs/book/component-guide/orchestrators/lightning.md
  docs/book/toc.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/constants.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/lightning/__init__.py
  src/zenml/integrations/lightning/flavors/__init__.py
  src/zenml/integrations/lightning/flavors/lightning_orchestrator_flavor.py
  src/zenml/integrations/lightning/orchestrators/__init__.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator_entrypoint.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator_entrypoint_configuration.py
  src/zenml/integrations/lightning/orchestrators/utils.py
  src/zenml/utils/code_utils.py
Labels: enhancement, internal, run-slow-ci

#2959 Bugfix for the required prompts for the AzureML wizard
  src/zenml/cli/stack.py
Labels: bug, internal

#2960 Prepare release 0.65.0
  README.md
  RELEASE_NOTES.md
  docs/book/how-to/build-pipelines/run-an-individual-step.md
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements.txt
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.65.0_release.py
Labels: internal, run-slow-ci

#2961 Hotfix for release flow
  release-cloudbuild.yaml
Labels: bug, internal

#2964 Fix the one-click AWS and GCP stack deployments
  infra/aws/aws-ecr-s3-sagemaker.yaml
  infra/gcp/gcp-gar-gcs-vertex-deploy.sh
  infra/gcp/gcp-gar-gcs-vertex.jinja
Labels: bug, internal, breaking-change

#2967 Fix wandb mypy error
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
Labels: internal, CI

#2969 Backport fix accelerate docs to 0.65.0 docs
  docs/book/how-to/training-with-gpus/accelerate-distributed-training.md
Labels: internal, backport

#2971 Dynamic model version names docs
  docs/book/how-to/use-the-model-control-plane/model-versions.md
Labels: internal, backport

#2968 Fix accelerate docs for 0.65.0+
  docs/book/how-to/training-with-gpus/accelerate-distributed-training.md
Labels: internal

#2970 Dynamic model version names docs
  docs/book/how-to/use-the-model-control-plane/model-versions.md
Labels: internal

#2972 Logging nits
  src/zenml/model/utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/utils/cloud_utils.py
Labels: internal

#2975 Allow running docker-orchestrators on default config
  examples/quickstart/configs/training_local.yaml
Labels: internal

#2965 Fix excess Azure logging
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
Labels: bug, internal, run-slow-ci
