Repository zenml-io/zenml, pull requests merged in 2024-09, with the labels that each got.

#2976 Fix typo in docs
  docs/book/getting-started/deploying-zenml/deploy-with-docker.md
Labels: documentation, internal

#2973 Pass code path to template run
  src/zenml/zen_server/template_execution/utils.py
Labels: bug, internal

#2978 Prevent extra attributes in component configs
  src/zenml/stack/utils.py
  tests/unit/stack/test_utils.py
Labels: bug, internal, run-slow-ci

#2983 Few nits in docs based on integrations review
  docs/book/component-guide/orchestrators/sagemaker.md
Labels: documentation, internal

#2981 Update slack alerter docs
  docs/book/.gitbook/assets/slack-alerter-oauth-permissions.png
  docs/book/component-guide/alerters/slack.md
Labels: bug, internal

#2985 Update Kubeflow orchestrator docs
  docs/book/component-guide/orchestrators/kubeflow.md
Labels: bug, internal

#2988 Build docker images for python 3.12
  release-cloudbuild.yaml
Labels: enhancement, internal

#2957 Allow shortcut keys for component settings
  docs/book/component-guide/data-validators/whylogs.md
  docs/book/component-guide/experiment-trackers/comet.md
  docs/book/component-guide/experiment-trackers/mlflow.md
  docs/book/component-guide/experiment-trackers/neptune.md
  docs/book/component-guide/experiment-trackers/wandb.md
  docs/book/component-guide/orchestrators/airflow.md
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/orchestrators/databricks.md
  docs/book/component-guide/orchestrators/kubeflow.md
  docs/book/component-guide/orchestrators/kubernetes.md
  docs/book/component-guide/orchestrators/local-docker.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/component-guide/orchestrators/tekton.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/component-guide/step-operators/kubernetes.md
  docs/book/component-guide/step-operators/vertex.md
  docs/book/how-to/build-pipelines/run-pipelines-asynchronously.md
  docs/book/how-to/popular-integrations/kubeflow.md
  docs/book/how-to/popular-integrations/mlflow.md
  docs/book/how-to/popular-integrations/skypilot.md
  docs/book/how-to/training-with-gpus/training-with-gpus.md
  docs/book/how-to/use-configuration-files/runtime-configuration.md
  docs/book/user-guide/production-guide/configure-pipeline.md
  src/zenml/config/compiler.py
  src/zenml/utils/settings_utils.py
  tests/unit/config/test_compiler.py
  tests/unit/orchestrators/test_cache_utils.py
Labels: enhancement, internal, run-slow-ci

#2991 Remove references to workspaces from docs
  docs/book/component-guide/artifact-stores/azure.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/container-registries/aws.md
  docs/book/component-guide/container-registries/azure.md
  docs/book/component-guide/container-registries/default.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/image-builders/gcp.md
  docs/book/component-guide/model-deployers/seldon.md
  docs/book/component-guide/model-registries/mlflow.md
  docs/book/component-guide/orchestrators/kubeflow.md
  docs/book/component-guide/orchestrators/kubernetes.md
  docs/book/component-guide/orchestrators/tekton.md
  docs/book/component-guide/step-operators/kubernetes.md
  docs/book/getting-started/deploying-zenml/deploy-with-docker.md
  docs/book/how-to/auth-management/README.md
  docs/book/how-to/auth-management/aws-service-connector.md
  docs/book/how-to/auth-management/azure-service-connector.md
  docs/book/how-to/auth-management/best-security-practices.md
  docs/book/how-to/auth-management/gcp-service-connector.md
  docs/book/how-to/auth-management/kubernetes-service-connector.md
  docs/book/how-to/auth-management/service-connectors-guide.md
  docs/book/how-to/debug-and-solve-issues.md
  docs/book/how-to/interact-with-secrets.md
  docs/book/reference/global-settings.md
  docs/book/user-guide/production-guide/understand-stacks.md
Labels: documentation, internal

#2966 Added some adjustments for colab
  .github/workflows/publish_docker_image.yml
  examples/quickstart/README.md
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_default.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/pipelines/training.py
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
  examples/quickstart/run.py
  examples/quickstart/steps/data_splitter.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
Labels: enhancement, internal, run-slow-ci

#2980 Reverting the installation of `mlstacks` after its new release
  .github/workflows/ci-slow.yml
  pyproject.toml
  scripts/install-zenml-dev.sh
Labels: enhancement, internal, run-slow-ci

#2982 Small dependency and docs updates
  docs/book/component-guide/annotators/label-studio.md
  docs/book/component-guide/annotators/prodigy.md
  src/zenml/integrations/feast/__init__.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
Labels: internal, dependencies, run-slow-ci

#2993 Prepare release 0.66.0
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.66.0_release.py
Labels: run-slow-ci

#2995 Bump quickstart images
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements.txt
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
Labels: enhancement, internal

#2998 Enable migration testing for version 0.66.0
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#2999 Add permissions to workflow to enable assuming AWS role
  .github/workflows/publish_docker_image.yml
Labels: bug, internal

#3001 Add option to write api key to file instead of CLI
  src/zenml/cli/service_accounts.py
Labels: enhancement, internal, run-slow-ci

#3007 Update ZenML Pro links for consistency.- Update ZenML Pro links for c…
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/deploying-zenml/README.md
  docs/book/introduction.md
Labels: internal

#3008 Fix incorrect method name in Pigeon docs
  docs/book/component-guide/annotators/pigeon.md
Labels: documentation, internal

#3000 Add filter option for templatable runs
  src/zenml/client.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/unit/conftest.py
Labels: enhancement, internal, run-slow-ci

#3009 Add missing analytics event
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3002 Fix expired credentials error when using the docker service connector
  src/zenml/service_connectors/docker_service_connector.py
Labels: bug, internal

#3013 Fix Lightning docs
  docs/book/component-guide/orchestrators/lightning.md
Labels: documentation, internal

#3014 Remove image builder warning
  src/zenml/stack/stack.py
Labels: enhancement, internal

#3018 Fixed kubeflow docs
  docs/book/component-guide/orchestrators/kubeflow.md
Labels: internal

#3019 Update Comet experiment tracker docs
  docs/book/.gitbook/assets/comet_experiment_confusion_matrix.png
  docs/book/.gitbook/assets/comet_experiment_model.png
  docs/book/.gitbook/assets/comet_pipeline.png
  docs/book/.gitbook/assets/comet_stack.png
  docs/book/component-guide/experiment-trackers/comet.md
Labels: internal

#3023 Feature/cleanup unused file
  .github/workflows/replace_api_docs_version
Labels: enhancement, internal

#3011 MLFlow integration requirements duplicate fix
  src/zenml/integrations/mlflow/__init__.py
  tests/integration/functional/cli/test_integration.py
Labels: bug, internal, run-slow-ci

#3026 Fix Neptune docs
  docs/book/.gitbook/assets/zenml_neptune_dag.png
  docs/book/.gitbook/assets/zenml_neptune_table.png
  docs/book/.gitbook/assets/zenml_neptune_zen2.png
  docs/book/component-guide/experiment-trackers/neptune.md
Labels: internal

#3024 Fix huggingface deployer docs
  docs/book/component-guide/experiment-trackers/comet.md
  docs/book/component-guide/model-deployers/huggingface.md
Labels: internal

#3029 Fix step output annotation in Discord test
  tests/integration/examples/discord/steps/data_loader.py
Labels: internal

#3031 Fix RBAC for subpages in response models
  src/zenml/zen_server/rbac/utils.py
  tests/integration/examples/discord/steps/data_loader.py
Labels: bug, internal

#3003 Allow env variable placeholders in configurations
  docs/book/how-to/build-pipelines/reference-environment-variables-in-configurations.md
  docs/book/toc.md
  src/zenml/config/step_configurations.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/utils/env_utils.py
  src/zenml/utils/string_utils.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/utils/test_env_utils.py
  tests/unit/utils/test_string_utils.py
Labels: enhancement, internal, run-slow-ci

#3027 Leverage warm pools for AWS Sagemaker
  docs/book/component-guide/orchestrators/sagemaker.md
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#3030 Updated wandb docs
  docs/book/.gitbook/assets/wandb_dag.png
  docs/book/component-guide/experiment-trackers/wandb.md
Labels: internal

#3035 Add hyperlint
  .hyperlint/config.yaml
Labels: documentation, internal

#3036 Bump NLP template
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/config.yaml
  examples/e2e_nlp/requirements.txt
  src/zenml/cli/base.py
Labels: bug, internal

#3038 Bump starter template version
  .github/workflows/update-templates-to-examples.yml
  examples/mlops_starter/.copier-answers.yml
  examples/mlops_starter/README.md
  examples/mlops_starter/configs/feature_engineering.yaml
  examples/mlops_starter/configs/inference.yaml
  examples/mlops_starter/configs/training_rf.yaml
  examples/mlops_starter/configs/training_sgd.yaml
  examples/mlops_starter/quickstart.ipynb
  examples/mlops_starter/requirements.txt
  src/zenml/cli/base.py
Labels: enhancement, internal

#3028 Docs for run templates
  docs/book/.gitbook/assets/run-templates-create-1.png
  docs/book/.gitbook/assets/run-templates-create-2.png
  docs/book/.gitbook/assets/run-templates-run-1.png
  docs/book/.gitbook/assets/run-templates.gif
  docs/book/getting-started/zenml-pro/README.md
  docs/book/how-to/build-pipelines/compose-pipelines.md
  docs/book/how-to/build-pipelines/configuring-a-pipeline-at-runtime.md
  docs/book/how-to/create-and-run-templates/README.md
  docs/book/how-to/create-and-run-templates/create-a-run-template.md
  docs/book/how-to/create-and-run-templates/run-a-template.md
  docs/book/how-to/handle-data-artifacts/unmaterialized-artifacts.md
  docs/book/how-to/trigger-pipelines/README.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-another.md
  docs/book/how-to/trigger-pipelines/trigger-a-pipeline-from-client.md
  docs/book/how-to/trigger-pipelines/use-templates-dashboard.md
  docs/book/how-to/trigger-pipelines/use-templates-python.md
  docs/book/how-to/trigger-pipelines/use-templates-rest-api.md
  docs/book/toc.md
Labels: documentation, internal

#3016 Update Lightning AI orchestrator documentation
  docs/book/component-guide/orchestrators/lightning.md
Labels: documentation, internal

#3040 Add default value for PipelineRun.is_templatable
  src/zenml/models/v2/core/pipeline_run.py
Labels: enhancement, internal

#3041 Use a generic OAuth2 client credentials flow to login to the Cloud API
  src/zenml/zen_server/cloud_utils.py
Labels: enhancement, internal

#3010 fix lightning orchestrator
  src/zenml/integrations/lightning/__init__.py
  src/zenml/integrations/lightning/flavors/lightning_orchestrator_flavor.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator_entrypoint.py
Labels: internal, run-slow-ci

#3005 Enhancing the orchestrator UX for major cloud providers
  docker/base.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docs/book/.gitbook/assets/azure-role-assignment-1.png
  docs/book/.gitbook/assets/azure-role-assignment-2.png
  docs/book/.gitbook/assets/azure-role-assignment-3.png
  docs/book/how-to/popular-integrations/azure-guide.md
  docs/book/how-to/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/cli/__init__.py
  src/zenml/cli/pipeline.py
  src/zenml/constants.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/stack/stack.py
  src/zenml/zen_server/routers/runs_endpoints.py
  tests/unit/pipelines/test_base_pipeline.py
  tests/unit/stack/test_stack.py
Labels: enhancement, internal, run-slow-ci

#3033 Skypilot with Kubernetes
  docs/book/component-guide/orchestrators/skypilot-vm.md
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot_kubernetes/__init__.py
  src/zenml/integrations/skypilot_kubernetes/flavors/__init__.py
  src/zenml/integrations/skypilot_kubernetes/flavors/skypilot_orchestrator_kubernetes_vm_flavor.py
  src/zenml/integrations/skypilot_kubernetes/orchestrators/__init__.py
  src/zenml/integrations/skypilot_kubernetes/orchestrators/skypilot_kubernetes_vm_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#2987 Update deepchecks integration
  docs/book/component-guide/data-validators/deepchecks.md
  docs/mocked_libs.json
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/deepchecks/data_validators/deepchecks_data_validator.py
  src/zenml/integrations/deepchecks/validation_checks.py
Labels: internal, run-slow-ci

#3047 Fixing the azureml numpy dependency issue
  src/zenml/integrations/azure/__init__.py
Labels: bug, internal

#3044 Prepare release 0.67.0
  README.md
  RELEASE_NOTES.md
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
  examples/quickstart/requirements.txt
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
  pyproject.toml
  src/zenml/VERSION
  src/zenml/integrations/pytorch/materializers/base_pytorch_materializer.py
  src/zenml/integrations/pytorch/materializers/pytorch_module_materializer.py
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.67.0_release.py
Labels: internal, run-slow-ci
