Repository zenml-io/zenml, pull requests merged in 2024-01, with the labels that each got.

#2097 Added more pod spec properties for k8s orchestrator
  src/zenml/integrations/kubeflow/utils.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
  tests/integration/integrations/kubernetes/test_serialization_utils.py
Labels: enhancement, internal

#2190 Fix API docs environment setup
  docs/requirements-docs-frozen.txt
  scripts/generate-docs.sh
Labels: bug, internal

#2048 Use placeholder runs to show pipeline runs in the dashboard without delay
  src/zenml/cli/utils.py
  src/zenml/enums.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_stores/migrations/versions/6917bce75069_add_pipeline_run_unique_constraint.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/examples/utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/conftest.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: internal

#2220 Update README and CONTRIBUTING.md docs with links to good first issues for contribution
  CONTRIBUTING.md
  README.md
Labels: documentation, internal

#2215 Rename log_model_version_metadata to log_model_metadata
  src/zenml/__init__.py
  src/zenml/model/utils.py
  tests/integration/functional/model/test_model_version.py
Labels: enhancement, internal

#2223 Fix typo
  docs/book/user-guide/advanced-guide/data-management/model-management.md
Labels: bug, internal

#2116 Consolidate Custom Filter Logic
  src/zenml/client.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version_artifact.py
  src/zenml/models/v2/core/model_version_pipeline_run.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/stack.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2195 Force forward slashes when saving artifacts
  src/zenml/artifacts/utils.py
  src/zenml/integrations/deepchecks/materializers/deepchecks_results_materializer.py
  src/zenml/integrations/facets/materializers/facets_materializer.py
  src/zenml/integrations/pillow/materializers/pillow_image_materializer.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/materializers/pandas_materializer.py
  src/zenml/materializers/structured_string_materializer.py
  tests/unit/test_general.py
Labels: bug

#2186 Temporarily disable two MLflow tests for MacOS with Python 3.9 and 3.10
  tests/integration/examples/test_mlflow_deployment.py
  tests/integration/examples/test_mlflow_registry.py
Labels: bug, internal, tests

#2222 Disable template updates for forked repositories
  .github/workflows/ci.yml
Labels: bug, internal

#2225 Remove Label Studio text annotation example
  examples/label_studio_text_annotation/README.md
  examples/label_studio_text_annotation/__init__.py
  examples/label_studio_text_annotation/cloud_config/aws/cors.json
  examples/label_studio_text_annotation/data/batch_1/data1.txt
  examples/label_studio_text_annotation/data/batch_1/data2.txt
  examples/label_studio_text_annotation/data/batch_1/data3.txt
  examples/label_studio_text_annotation/data/batch_1/data4.txt
  examples/label_studio_text_annotation/data/batch_1/data5.txt
  examples/label_studio_text_annotation/pipelines/__init__.py
  examples/label_studio_text_annotation/pipelines/inference_pipeline.py
  examples/label_studio_text_annotation/pipelines/training_pipeline.py
  examples/label_studio_text_annotation/requirements.txt
  examples/label_studio_text_annotation/run.py
  examples/label_studio_text_annotation/steps/__init__.py
  examples/label_studio_text_annotation/steps/configuration.py
  examples/label_studio_text_annotation/steps/convert_annotations_step.py
  examples/label_studio_text_annotation/steps/deployment_triggers.py
  examples/label_studio_text_annotation/steps/get_labeled_data.py
  examples/label_studio_text_annotation/steps/get_or_create_dataset.py
  examples/label_studio_text_annotation/steps/load_image_data_step.py
  examples/label_studio_text_annotation/steps/model_deployers.py
  examples/label_studio_text_annotation/steps/prediction_steps.py
  examples/label_studio_text_annotation/steps/pytorch_trainer.py
  examples/label_studio_text_annotation/steps/sync_new_data_to_label_studio.py
Labels: internal

#2227 Add scarf checker script and CI workflow
  .github/workflows/scarf-check.yml
  docs/book/deploying-zenml/zenml-cloud/user-management.md
  docs/book/reference/how-do-i.md
  docs/book/stacks-and-components/custom-solutions/custom-stack-solutions.md
  docs/book/stacks-and-components/stack-deployment/cloud-stacks/minimal-gcp-stack.md
  docs/book/user-guide/advanced-guide/best-practices/debug-and-solve-issues.md
  docs/book/user-guide/advanced-guide/best-practices/handling-dependencies.md
  docs/book/user-guide/advanced-guide/environment-management/environment-variables.md
  docs/book/user-guide/advanced-guide/pipelining-features/pipelining-features.md
  scripts/format.sh
  scripts/scarf-checker.sh
Labels: documentation, enhancement, internal

#2228 Add `mlstacks` installation instructions to docs
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-component.md
  docs/book/stacks-and-components/stack-deployment/deploy-a-stack-using-mlstacks.md
  docs/book/stacks-and-components/stack-deployment/stack-deployment.md
Labels: documentation, internal

#2120 Adding the `hydrate` flag to the client methods
  src/zenml/client.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#2230 Fixing the remaining docs pages for `run_metadata`
  docs/book/stacks-and-components/component-guide/experiment-trackers/experiment-trackers.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/mlflow.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/neptune.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/wandb.md
  docs/book/stacks-and-components/component-guide/model-deployers/model-deployers.md
  docs/book/stacks-and-components/component-guide/orchestrators/airflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/kubeflow.md
  docs/book/stacks-and-components/component-guide/orchestrators/orchestrators.md
  docs/book/stacks-and-components/component-guide/orchestrators/vertex.md
Labels: documentation, internal

#2237 Fix fork check syntax
  .github/workflows/ci.yml
Labels: bug, internal

#2234 Add missing annotations section to zenml service account
  src/zenml/zen_server/deploy/helm/templates/serviceaccount.yaml
Labels: bug, internal

#2236 Adjust migration settings based on database engine
  src/zenml/zen_stores/migrations/versions/728c6369cfaa_add_name_column_to_input_artifact_pk.py
Labels: bug, internal

#2229 Add Polars materializer
  docs/book/user-guide/advanced-guide/data-management/handle-custom-data-types.md
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/polars/__init__.py
  src/zenml/integrations/polars/materializers/__init__.py
  src/zenml/integrations/polars/materializers/dataframe_materializer.py
  tests/integration/integrations/polars/__init__.py
  tests/integration/integrations/polars/materializers/__init__.py
  tests/integration/integrations/polars/materializers/test_polars_materializer.py
Labels: enhancement

#2239 Prepare release 0.54.0
  README.md
  RELEASE_NOTES.md
  docs/book/user-guide/starter-guide/structuring-a-project.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.54.0_release.py
Labels: internal

#2224 Add YAML formatting standardisation to formatting & linting scripts
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/actions/setup_environment/action.yml
  .github/branch-labels.yml
  .github/codecov.yml
  .github/dependabot.yml
  .github/teams.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/image-optimiser.yml
  .github/workflows/integration-test.yml
  .github/workflows/mixpanel-test-data.yml
  .github/workflows/nightly_build.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/publish_api_docs.yml
  .github/workflows/publish_docker_image.yml
  .github/workflows/publish_helm_chart.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/publish_to_pypi_nightly.yml
  .github/workflows/release.yml
  .github/workflows/scarf-check.yml
  .github/workflows/setup-python-environment.yml
  .github/workflows/templates-test.yml
  .github/workflows/trivy-zenml-core.yml
  .github/workflows/trivy-zenserver.yml
  .github/workflows/update-templates-to-examples.yml
  pyproject.toml
  scripts/format.sh
  scripts/lint.sh
  tests/harness/cfg/deployments.yaml
  tests/harness/cfg/environments.yaml
  tests/harness/cfg/requirements.yaml
  tests/harness/cfg/tests.yaml
Labels: enhancement, internal, dependencies

#2246 Remove text annotation
  examples/README.md
Labels: internal

#2170 Add MariaDB migration testing
  .github/workflows/release.yml
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: enhancement, internal

#2191 Delete artifact links from model version via Client, ModelVersion and API
  src/zenml/client.py
  src/zenml/model/model_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/zen_server/routers/model_versions_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2247 Default/Non-Default step params produce conflict with yaml ones as defaults are set in code
  .github/workflows/setup-python-environment.yml
  scripts/lint.sh
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_invocation.py
  tests/integration/functional/pipelines/test_pipeline_config.py
  tests/unit/orchestrators/test_cache_utils.py
Labels: bug, internal

#2221 Rename nlp example
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.assets/00_pipelines_composition.png
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/.dockerignore
  examples/e2e_nlp/LICENSE
  examples/e2e_nlp/Makefile
  examples/e2e_nlp/README.md
  examples/e2e_nlp/config.yaml
  examples/e2e_nlp/gradio/Dockerfile
  examples/e2e_nlp/gradio/__init__.py
  examples/e2e_nlp/gradio/app.py
  examples/e2e_nlp/gradio/requirements.txt
  examples/e2e_nlp/gradio/serve.yaml
  examples/e2e_nlp/pipelines/__init__.py
  examples/e2e_nlp/pipelines/deploying.py
  examples/e2e_nlp/pipelines/promoting.py
  examples/e2e_nlp/pipelines/training.py
  examples/e2e_nlp/requirements.txt
  examples/e2e_nlp/run.py
  examples/e2e_nlp/steps/__init__.py
  examples/e2e_nlp/steps/alerts/__init__.py
  examples/e2e_nlp/steps/alerts/notify_on.py
  examples/e2e_nlp/steps/dataset_loader/__init__.py
  examples/e2e_nlp/steps/dataset_loader/data_loader.py
  examples/e2e_nlp/steps/deploying/__init__.py
  examples/e2e_nlp/steps/deploying/huggingface_deployment.py
  examples/e2e_nlp/steps/deploying/local_deployment.py
  examples/e2e_nlp/steps/deploying/save_model.py
  examples/e2e_nlp/steps/deploying/skypilot_deployment.py
  examples/e2e_nlp/steps/promotion/__init__.py
  examples/e2e_nlp/steps/promotion/promote_get_metrics.py
  examples/e2e_nlp/steps/promotion/promote_metric_compare_promoter.py
  examples/e2e_nlp/steps/register/__init__.py
  examples/e2e_nlp/steps/register/model_log_register.py
  examples/e2e_nlp/steps/tokenizer_loader/__init__.py
  examples/e2e_nlp/steps/tokenizer_loader/tokenizer_loader.py
  examples/e2e_nlp/steps/tokenzation/__init__.py
  examples/e2e_nlp/steps/tokenzation/tokenization.py
  examples/e2e_nlp/steps/training/__init__.py
  examples/e2e_nlp/steps/training/model_trainer.py
  examples/e2e_nlp/utils/misc.py
Labels: internal

#2198 Support refreshing service connector credentials in the Vertex step operator to support long-running jobs
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
Labels: bug, internal

#2193 Refactor secrets stores to store all secret metadata in the DB
  docker/zenml-server-hf-spaces.Dockerfile
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
  docs/book/stacks-and-components/component-guide/artifact-stores/s3.md
  src/zenml/config/store_config.py
  src/zenml/enums.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/models/v2/core/secret.py
  src/zenml/zen_server/deploy/deployer.py
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/enums.py
  src/zenml/zen_stores/migrations/alembic.py
  src/zenml/zen_stores/migrations/env.py
  src/zenml/zen_stores/migrations/versions/1ac1b9c04da1_make_secrets_values_optional.py
  src/zenml/zen_stores/migrations/versions/7b651bf6822e_track_secrets_in_db.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/base_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/rest_secrets_store.py
  src/zenml/zen_stores/secrets_stores/secrets_store_interface.py
  src/zenml/zen_stores/secrets_stores/service_connector_secrets_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_secrets_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal

#2266 Add `latest_version_id` to the `ModelResponse`
  src/zenml/cli/model.py
  src/zenml/models/v2/core/model.py
  src/zenml/zen_stores/schemas/model_schemas.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal

#2272 Remove `link_artifact` from docs for MCP
  docs/book/user-guide/advanced-guide/data-management/model-management.md
Labels: documentation, internal

#2273 Remove manual linkage from docs (#2272)
  docs/book/user-guide/advanced-guide/data-management/model-management.md
Labels: internal, backport

#2265 Improve action by adding advice to KeyError when configured steps are not present in pipeline
  src/zenml/config/compiler.py
Labels: enhancement

#2166 Allow multi step configuration for skypilot
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/integrations/skypilot/__init__.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_orchestrator_entrypoint.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_orchestrator_entrypoint_configuration.py
  src/zenml/orchestrators/step_launcher.py
Labels: enhancement, internal

#2259 Reworking the examples
  docs/book/learning/examples.md
  docs/book/learning/projects.md
  docs/book/toc.md
  examples/README.md
  examples/__init__.py
  examples/generative_chat/README.md
  examples/generative_chat/pipelines/__init__.py
  examples/generative_chat/pipelines/index_builder.py
  examples/generative_chat/requirements.txt
  examples/generative_chat/run.py
  examples/generative_chat/steps/__init__.py
  examples/generative_chat/steps/docs_loader.py
  examples/generative_chat/steps/index_generator.py
  examples/generative_chat/steps/slack_loader.py
  examples/generative_chat/steps/utils.py
  examples/label_studio_annotation/README.md
  examples/label_studio_annotation/__init__.py
  examples/label_studio_annotation/cloud_config/aws/cors.json
  examples/label_studio_annotation/cloud_config/gcp/cors-config.json
  examples/label_studio_annotation/data/batch_1/2dc5fe08-152d-47d0-bdd4-f70ddbfb6486.jpeg
  examples/label_studio_annotation/data/batch_1/7f5d8d61-c507-434f-9d4b-de28f93dad1e.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_95ffaa51-3894-4773-a8c6-a4e7d09de050.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0584.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0688.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_0728.jpeg
  examples/label_studio_annotation/data/batch_1/ARIA_IMG_1481.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_1892.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_2262.jpeg
  examples/label_studio_annotation/data/batch_1/IMG_2640.jpeg
  examples/label_studio_annotation/data/batch_2/11f096cb-4749-4a8b-ace0-f534bc7ed07d.jpeg
  examples/label_studio_annotation/data/batch_2/24cbc5d8-ca52-4974-841c-f91a2dfb46a7.jpeg
  examples/label_studio_annotation/data/batch_2/94f69181-2a52-43d3-9982-2cdbd018ff28.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_1507.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5514.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5515.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5530.jpeg
  examples/label_studio_annotation/data/batch_2/ARIA_IMG_5587.jpeg
  examples/label_studio_annotation/data/batch_2/IMG_3154.jpeg
  examples/label_studio_annotation/data/batch_2/IMG_4813.jpeg
  examples/label_studio_annotation/pipelines/__init__.py
  examples/label_studio_annotation/pipelines/inference_pipeline.py
  examples/label_studio_annotation/pipelines/training_pipeline.py
  examples/label_studio_annotation/run.py
  examples/label_studio_annotation/steps/__init__.py
  examples/label_studio_annotation/steps/convert_annotations_step.py
  examples/label_studio_annotation/steps/get_or_create_dataset.py
  examples/label_studio_annotation/steps/load_image_data_step.py
  examples/label_studio_annotation/steps/prediction_steps.py
  examples/label_studio_annotation/steps/pytorch_trainer.py
  examples/label_studio_annotation/steps/sync_new_data_to_label_studio.py
Labels: documentation, internal

#2271 Allow `sklearn` versions > 1.3
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  src/zenml/integrations/sklearn/__init__.py
  tests/conftest.py
Labels: internal, dependencies

#2281 Free `sklearn` dependency to allow all versions
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  src/zenml/integrations/sklearn/__init__.py
Labels: bug, documentation, internal, dependencies

#2260 Misc CI bugfixes
  .github/dependabot.yml
  .github/workflows/publish_api_docs.yml
  .typos.toml
  release-cloudbuild-nightly.yaml
  scripts/generate-docs.sh
Labels: bug, internal

#2280 Fix `yamlfix` script to use `--no-yamlfix` flag
  CONTRIBUTING.md
  scripts/format.sh
Labels: bug, documentation, internal

#2282 Fix dependabot settings autoformatting by `yamlfix`
  .github/dependabot.yml
  scripts/format.sh
  scripts/lint.sh
Labels: bug, internal

#2264 Add advice for next step to error on AuthorizationException
  src/zenml/zen_server/auth.py
Labels: enhancement

#2275 Comment-driven CI
  .github/workflows/ci-slow.yml
Labels: enhancement, internal

#2274 Fast/slow CI core scaffold
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/ci.yml
  .github/workflows/nightly_build.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
Labels: enhancement, internal

#2284 Prepare release 0.54.1
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.54.1_release.py
Labels: internal

#2283 Add Escan to `teams.yml`
  .github/teams.yml
Labels: internal

#2287 Fix typos from docs updates
  .github/workflows/setup-python-environment.yml
  .github/workflows/spellcheck.yml
  docs/book/user-guide/advanced-guide/configuring-zenml/ci-cd.md
  docs/book/user-guide/advanced-guide/configuring-zenml/configuring-zenml.md
  docs/book/user-guide/advanced-guide/pipelining-features/configure-steps-pipelines.md
  docs/book/user-guide/advanced-guide/pipelining-features/pipeline-settings.md
  docs/book/user-guide/production-guide/cloud-orchestration.md
Labels: documentation, internal

#2288 Fix to file path for notebook quickstart
  src/zenml/cli/base.py
Labels: bug

#2291 Fix `zenml-tutorial` path assignment in `cli.go()`
  src/zenml/cli/base.py
Labels: bug, internal

#2295 Remove --name from service account creation in docs
  docs/book/user-guide/advanced-guide/infrastructure-management/connecting-to-zenml.md
Labels: documentation, internal

#2277 Secrets store hot backup and restore
  docs/book/.gitbook/assets/secrets-store-architecture.png
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
  docs/book/user-guide/advanced-guide/secret-management/custom-secret-stores.md
  docs/book/user-guide/advanced-guide/secret-management/secret-management.md
  src/zenml/cli/secret.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/config/store_config.py
  src/zenml/constants.py
  src/zenml/exceptions.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/rbac/models.py
  src/zenml/zen_server/routers/secrets_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/azure_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#2299 Updating the README of the e2e template
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  examples/e2e/README.md
  src/zenml/cli/base.py
Labels: documentation, internal

#2305 Add missing docstring for Skypilot setting
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
Labels: bug, internal

#2306 Backport skypilot docstring
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
Labels: internal, backport

#2297 Add some tiny details and moved around a page
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/configuring-zenml/connecting-to-zenml.md
  docs/book/user-guide/advanced-guide/configuring-zenml/environment-variables.md
  docs/book/user-guide/advanced-guide/data-management/logging-metadata.md
  docs/book/user-guide/advanced-guide/infrastructure-management/infrastructure-management.md
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: documentation, internal

#2205 Model links lazy evaluation in pipeline code
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/steps/deployment/deployment_deploy.py
  examples/e2e/steps/promotion/promote_with_metric_compare.py
  src/zenml/__init__.py
  src/zenml/cli/model.py
  src/zenml/config/step_configurations.py
  src/zenml/metadata/lazy_load.py
  src/zenml/metadata/metadata_types.py
  src/zenml/model/lazy_load.py
  src/zenml/model/model_version.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/run_metadata.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/pipeline_context.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_invocation.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/unit/materializers/test_materializer_registry.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#2298 Link artifact to MCP entity via function call or implicitly in `save_artifact`
  docs/book/user-guide/advanced-guide/data-management/model-management.md
  src/zenml/__init__.py
  src/zenml/artifacts/utils.py
  src/zenml/model/utils.py
  tests/integration/functional/model/test_model_version.py
Labels: enhancement, internal

#2285 Extend MCP/ACP listing capabilties
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  src/zenml/cli/__init__.py
  src/zenml/cli/artifact.py
  src/zenml/cli/base.py
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/model/model_version.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_model.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: bug, enhancement, internal

#2294 Add latest `zenml` version to migration testing scripts
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal, tests

#2308 Remove Python 3.7 check for Langchain Integration
  src/zenml/integrations/__init__.py
Labels: internal

#2315 Fix secret migration from external store in helm deployment
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/templates/serviceaccount.yaml
  src/zenml/zen_stores/migrations/versions/7b651bf6822e_track_secrets_in_db.py
Labels: bug, internal

#2314 Small docs fixes
  docs/book/user-guide/advanced-guide/configuring-zenml/environment-variables.md
Labels: documentation, internal

#2286 Sharded integration tests for Ubuntu
  .github/actions/setup_environment/action.yml
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  .test_durations
  pyproject.toml
  scripts/test-coverage-html.sh
  scripts/test-coverage-xml.sh
Labels: enhancement, internal

#2311 Updating the docs after the Skypilot tests
  docs/book/user-guide/production-guide/cloud-orchestration.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: documentation, internal

#2327 Updating the docs after the Skypilot tests (#2311)
  docs/book/user-guide/production-guide/cloud-orchestration.md
  docs/book/user-guide/production-guide/remote-storage.md
Labels: internal, backport

#2319 Remove unused Segment / Mixpanel generation workflow and script
  .github/workflows/mixpanel-test-data.yml
  scripts/mixpanel_filters_test.py
Labels: internal

#2322 Add `log_step_metadata` utility function
  docs/book/user-guide/advanced-guide/data-management/logging-metadata.md
  examples/e2e/.copier-answers.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/quickstart/.copier-answers.yml
  src/zenml/__init__.py
  src/zenml/steps/utils.py
  tests/integration/functional/steps/test_utils.py
Labels: enhancement, internal

#2333 Add warning for GCP integration when using Python >=3.11
  docs/book/stacks-and-components/component-guide/artifact-stores/gcp.md
  docs/book/stacks-and-components/component-guide/container-registries/gcp.md
  docs/book/stacks-and-components/component-guide/image-builders/gcp.md
  docs/book/stacks-and-components/component-guide/orchestrators/vertex.md
  docs/book/stacks-and-components/component-guide/step-operators/vertex.md
  docs/book/user-guide/advanced-guide/infrastructure-management/cloud-stacks/minimal-gcp-stack.md
  src/zenml/cli/integration.py
Labels: bug, documentation, internal

#2338 Prepare release `0.55.0`
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.55.0_release.py
Labels: internal

#2344 Update skypilot docs
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
Labels: documentation, internal

#2345 update skypilot docs (#2344)
  docs/book/stacks-and-components/component-guide/orchestrators/skypilot-vm.md
Labels: internal, backport

#2268 Fast CI / Slow CI
  .github/actions/setup_environment/action.yml
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/ci.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/nightly_build.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  .test_durations
  pyproject.toml
  scripts/test-coverage-html.sh
  scripts/test-coverage-xml.sh
Labels: enhancement, internal

#2334 Add repeating tests and instafail error logging to testing in CI
  pyproject.toml
  scripts/test-coverage-xml.sh
Labels: enhancement, internal, dependencies

#2346 Added more info about metadata
  docs/book/user-guide/advanced-guide/data-management/logging-metadata.md
  docs/book/user-guide/starter-guide/track-ml-models.md
Labels: documentation, internal

#2340 Fix code in docs/questions about MCP
  docs/book/user-guide/advanced-guide/data-management/model-management.md
Labels: documentation, internal

#2350 Fixed metadata docs
  docs/book/stacks-and-components/component-guide/experiment-trackers/mlflow.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/neptune.md
  docs/book/stacks-and-components/component-guide/experiment-trackers/wandb.md
  docs/book/user-guide/advanced-guide/data-management/logging-metadata.md
  docs/book/user-guide/advanced-guide/pipelining-features/fetch-metadata-within-steps.md
  docs/book/user-guide/starter-guide/fetching-pipelines.md
  docs/book/user-guide/starter-guide/track-ml-models.md
Labels: internal

#2347 Add generate test duration file cron
  .github/workflows/generate-test-duration.yml
  .test_durations
Labels: enhancement, internal

#2356 CI comments for slow CI and more conditional membership checking
  .github/workflows/ci-slow.yml
Labels: bug, enhancement, internal

#2352 Add model version created to analytics
  src/zenml/analytics/enums.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal

#2358 Make CI run on the appropriate branch
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/unit-test.yml
Labels: bug, enhancement, internal

#2353 Add MVP pipeline namespace support
  src/zenml/client.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/pipeline.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2342 Apply docker run args to skypilot orchestrator VM
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
Labels: bug, internal

#2348 📝 Minor docs improvements (basic step example)
  docs/book/getting-started/core-concepts.md
Labels: documentation

#2361 Prepare release 0.55.1
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.55.1_release.py
Labels: internal

#2158 Add DB backup and recovery during DB schema migrations
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-helm.md
  scripts/format.sh
  src/zenml/cli/base.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-db-pvc.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_stores/migrations/alembic.py
  src/zenml/zen_stores/migrations/utils.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2363 Fix CI issues
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/unit-test.yml
Labels: bug, internal

#2364 Prepare release 0.55.1
  RELEASE_NOTES.md
Labels: internal

#2368 `0.55.1` in migration testing
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal

#2365 Credential-less AWS/GCP/Azure Secrets Store support
  docs/book/stacks-and-components/auth-management/aws-service-connector.md
  docs/book/stacks-and-components/auth-management/gcp-service-connector.md
  examples/e2e/steps/training/model_trainer.py
  examples/e2e/utils/promote_in_model_registry.py
  src/zenml/integrations/aws/service_connectors/aws_service_connector.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_stores/secrets_stores/service_connector_secrets_store.py
Labels: enhancement, internal

#2323 generic `Client()` getters lazy loading
  docs/book/toc.md
  docs/book/user-guide/advanced-guide/data-management/late-materialization.md
  docs/book/user-guide/starter-guide/structuring-a-project.md
  src/zenml/client.py
  src/zenml/client_lazy_loader.py
  src/zenml/config/step_configurations.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_invocation.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/test_client.py
  tests/unit/materializers/test_materializer_registry.py
  tests/unit/orchestrators/test_cache_utils.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#2378 Added slack settings OSSK-382
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/integrations/slack/flavors/__init__.py
  src/zenml/integrations/slack/flavors/slack_alerter_flavor.py
Labels: bug, internal
