Repository zenml-io/zenml, pull requests merged in 2024-03, with the labels that each got.

#2483 Uniquely constrained users table
  src/zenml/zen_stores/migrations/versions/72675226b2de_unique_users.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal, security, run-slow-ci

#2464 Add option to add base URL for zenml server (with support for cloud)
  src/zenml/analytics/context.py
  src/zenml/config/server_config.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2490 Improve Artifact Store isolation
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifacts/utils.py
  src/zenml/logging/step_logging.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/cloudpickle_materializer.py
  src/zenml/materializers/numpy_materializer.py
  src/zenml/materializers/pandas_materializer.py
  src/zenml/materializers/service_materializer.py
  src/zenml/materializers/structured_string_materializer.py
  src/zenml/orchestrators/output_utils.py
  tests/integration/functional/artifacts/test_base_artifact_store.py
  tests/integration/functional/artifacts/test_utils.py
  tests/unit/artifacts/test_utils.py
  tests/unit/materializers/test_built_in_materializer.py
  tests/unit/materializers/test_cloudpickle_materializer.py
  tests/unit/test_general.py
Labels: bug, internal, security, run-slow-ci

#2491 Don't write the global config to file on server
  src/zenml/config/global_config.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, security, run-slow-ci

#2496 Prepare release 0.55.5
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.55.5_release.py
Labels: internal, run-slow-ci

#2452 Upgrading SQLModel to the latest version
  pyproject.toml
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/zen_server/deploy/local/local_provider.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/artifact_visualization_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/device_schemas.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2495 Remove KServe integration
  .gitignore
  docs/book/user-guide/advanced-guide/best-practices/debug-and-solve-issues.md
  docs/mocked_libs.json
  pyproject.toml
  scripts/install-zenml-dev.sh
  src/zenml/cli/stack.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/bentoml/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/kserve/__init__.py
  src/zenml/integrations/kserve/constants.py
  src/zenml/integrations/kserve/custom_deployer/__init__.py
  src/zenml/integrations/kserve/custom_deployer/zenml_custom_model.py
  src/zenml/integrations/kserve/flavors/__init__.py
  src/zenml/integrations/kserve/flavors/kserve_model_deployer_flavor.py
  src/zenml/integrations/kserve/model_deployers/__init__.py
  src/zenml/integrations/kserve/model_deployers/kserve_model_deployer.py
  src/zenml/integrations/kserve/secret_schemas/__init__.py
  src/zenml/integrations/kserve/secret_schemas/secret_schemas.py
  src/zenml/integrations/kserve/services/__init__.py
  src/zenml/integrations/kserve/services/kserve_deployment.py
  src/zenml/integrations/kserve/steps/__init__.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/kserve/steps/kserve_step_utils.py
  src/zenml/utils/mlstacks_utils.py
Labels: internal, run-slow-ci

#2501 Upgrade migration testing with 0.55.5
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal

#2498 Relax azure, gcfs and s3 dependencies
  pyproject.toml
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/s3/__init__.py
Labels: internal, dependencies, run-slow-ci

#2499 Use HTTP forwarded headers to detect the real origin of client devices
  docker/base.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docker/zenml-server-hf-spaces.Dockerfile
  src/zenml/zen_server/routers/auth_endpoints.py
Labels: bug, internal, run-slow-ci

#2505 Update README.md for quickstart colab link
  examples/quickstart/README.md
Labels: bug, documentation, internal

#2502 Add sequential migration tests for MariaDB and MySQL
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: enhancement, internal, tests, CI, run-slow-ci

#2376 Huggingface Model Deployer
  docs/book/stacks-and-components/component-guide/model-deployers/huggingface.md
  docs/book/stacks-and-components/component-guide/model-deployers/model-deployers.md
  docs/book/toc.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/huggingface/flavors/__init__.py
  src/zenml/integrations/huggingface/flavors/huggingface_model_deployer_flavor.py
  src/zenml/integrations/huggingface/model_deployers/__init__.py
  src/zenml/integrations/huggingface/model_deployers/huggingface_model_deployer.py
  src/zenml/integrations/huggingface/services/__init__.py
  src/zenml/integrations/huggingface/services/huggingface_deployment.py
  src/zenml/integrations/huggingface/steps/__init__.py
  src/zenml/integrations/huggingface/steps/huggingface_deployer.py
  tests/harness/cfg/tests.yaml
  tests/integration/examples/huggingface/pipelines/__init__.py
  tests/integration/examples/huggingface/pipelines/deployment_pipelines/__init__.py
  tests/integration/examples/huggingface/pipelines/deployment_pipelines/deployment_pipeline.py
  tests/integration/examples/huggingface/pipelines/deployment_pipelines/inference_pipeline.py
  tests/integration/examples/huggingface/run.py
  tests/integration/examples/huggingface/steps/prediction_service_loader/prediction_service_loader.py
  tests/integration/examples/huggingface/steps/predictor/predictor.py
  tests/integration/examples/test_huggingface.py
  tests/integration/examples/test_huggingface_deployment.py
Labels: enhancement, dependencies, run-slow-ci

#2442 Use `uv` to speed up pip installs & the CI in general
  .github/actions/setup_environment/action.yml
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/generate-test-duration.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  examples/quickstart/README.md
  scripts/generate-docs.sh
  scripts/install-zenml-dev.sh
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal, run-slow-ci

#2508 Handle corrupted or empty global configuration file
  src/zenml/config/global_config.py
Labels: bug, internal, run-slow-ci

#2494 Add admin users notion
  examples/quickstart/README.md
  src/zenml/cli/user_management.py
  src/zenml/client.py
  src/zenml/models/v2/core/service_account.py
  src/zenml/models/v2/core/user.py
  src/zenml/models/v2/misc/external_user.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/migrations/versions/1a9a9d2a836d_admin_users.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/conftest.py
  tests/unit/models/test_user_models.py
Labels: bug, internal, security, run-slow-ci, P1

#2517 Remove dashboard from gitignore
  .gitignore
Labels: internal

#2518 [HELM] Remove extra environment variable assignment
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
Labels: internal

#2510 Allow installing packages using UV
  src/zenml/config/docker_settings.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal

#2507 Additional fields for track events
  src/zenml/analytics/context.py
Labels: enhancement, internal, run-slow-ci

#2511 Check if environment key is set before deleting in HyperAI orchestrator
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
Labels: enhancement, run-slow-ci

#2522 Fix the pagination in the database backup
  src/zenml/zen_stores/migrations/utils.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2524 Bump mlflow to version 2.11.1
  src/zenml/integrations/mlflow/__init__.py
Labels: dependencies, run-slow-ci

#2527 Add docs for uv installation
  docs/book/user-guide/advanced-guide/infrastructure-management/containerize-your-pipeline.md
Labels: documentation, internal

#2523 Fix bug in HyperAI orchestrator depends_on parallelism
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
Labels: run-slow-ci

#2528 Upgrade pip in docker images
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
Labels: enhancement, internal, run-slow-ci

#2531 Fix node selector and other fields for DB job in helm chart
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
Labels: bug, internal

#2515 Revert "Upgrading SQLModel to the latest version"
  pyproject.toml
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/zen_server/deploy/local/local_provider.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/artifact_visualization_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/device_schemas.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2509 Add `pod_running_timeout` attribute to `Kaniko` image builder
  docs/book/stacks-and-components/component-guide/image-builders/kaniko.md
  src/zenml/integrations/kaniko/flavors/kaniko_image_builder_flavor.py
  src/zenml/integrations/kaniko/image_builders/kaniko_image_builder.py
Labels: enhancement, run-slow-ci

#2484 Rate limiting for login API
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docs/book/deploying-zenml/zenml-self-hosted/deploy-with-docker.md
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/utils.py
  tests/integration/functional/zen_server/test_zen_server.py
Labels: bug, internal, security, run-slow-ci, P2

#2513 Try/catch for Docker client
  src/zenml/container_registries/base_container_registry.py
  src/zenml/image_builders/local_image_builder.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/service_connectors/docker_service_connector.py
  src/zenml/services/container/container_service.py
  src/zenml/utils/docker_utils.py
Labels: enhancement, run-slow-ci

#2534 Fix config file in starter guide
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: documentation, internal

#2506 Log URL for pipelines and model versions when running a pipeline
  src/zenml/model/model.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/utils/cloud_utils.py
  src/zenml/utils/dashboard_utils.py
Labels: enhancement, internal, run-slow-ci

#2541 Add security exclude
  scripts/check-security.sh
Labels: bug, internal, run-slow-ci

#2536 Update error message around notebook use
  src/zenml/utils/source_utils.py
Labels: documentation, internal

#2542 Cap `fsspec` for Huggingface integration
  src/zenml/integrations/huggingface/__init__.py
Labels: bug, internal, run-slow-ci

#2538 Fix integration materializers' URLs in docs
  docs/book/user-guide/advanced-guide/data-management/handle-custom-data-types.md
Labels: documentation, internal

#2535 Bug fix HyperAI orchestrator: Offload scheduled pipeline execution to bash script
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
Labels: bug, run-slow-ci

#2546 Prepare release 0.56.0
  README.md
  RELEASE_NOTES.md
  examples/llm_finetuning/.assets/model.png
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.56.0_release.py
Labels: internal, run-slow-ci

#2549 Fix formatting and release workflow
  .github/workflows/release.yml
Labels: bug, internal, CI

#2553 Make starlette non-must for client
  src/zenml/zen_server/rate_limit.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/utils.py
Labels: bug, internal, run-slow-ci

#2552 Bump MLFlow to version 2.11.2
  src/zenml/integrations/mlflow/__init__.py
Labels: dependencies, run-slow-ci

#2555 Prepare release 0.56.1
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.56.1_release.py
Labels: internal, run-slow-ci

#2548 Updated neptune documentation
  docs/book/stacks-and-components/component-guide/experiment-trackers/neptune.md
Labels: documentation

#2557 0.56.0 and 0.56.1 in testing
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal

#2558 Only install uv once
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal, run-slow-ci

#2559 Bump MLFlow to version 2.11.3
  src/zenml/integrations/mlflow/__init__.py
Labels: run-slow-ci

#2561 Update docs with warning about pickle materializer insecurity
  docs/book/user-guide/advanced-guide/data-management/artifact-versioning.md
  docs/book/user-guide/advanced-guide/data-management/handle-custom-data-types.md
  docs/book/user-guide/advanced-guide/pipelining-features/managing-steps.md
Labels: bug, documentation, internal

#2563 Add service table migration
  src/zenml/zen_stores/migrations/versions/0701da9951a0_added_service_table.py
Labels: run-slow-ci

#2564 Prepare release 0.56.2
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.56.2_release.py
Labels: internal, run-slow-ci

#2562 Really run migration testing
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: bug, internal, run-slow-ci

#2492 Interact with feature gate
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/exceptions.py
  src/zenml/model/model.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/exceptions.py
  src/zenml/zen_server/feature_gate/__init__.py
  src/zenml/zen_server/feature_gate/endpoint_utils.py
  src/zenml/zen_server/feature_gate/feature_gate_interface.py
  src/zenml/zen_server/feature_gate/zenml_cloud_feature_gate.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  tests/unit/test_constants.py
Labels: run-slow-ci

#2544 Allow for logs to be unformatted / without colours
  docs/book/user-guide/advanced-guide/configuring-zenml/environment-variables.md
  src/zenml/constants.py
  src/zenml/logger.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: enhancement, internal, run-slow-ci
