Repository zenml-io/zenml, pull requests merged in 2024-11, with the labels that each got.

#3163 Update OpenAI integration
  pyproject.toml
  src/zenml/integrations/langchain/__init__.py
  src/zenml/integrations/langchain/materializers/openai_embedding_materializer.py
  src/zenml/integrations/openai/__init__.py
  src/zenml/integrations/openai/hooks/open_ai_failure_hook.py
  tests/integration/integrations/langchain/materializers/test_openai_embedding_materializer_materializer.py
  tests/integration/integrations/langchain/materializers/test_vector_store_materializer.py
Labels: internal, dependencies

#3166 Remove deprecated torch version constraint
  scripts/install-zenml-dev.sh
Labels: internal, dependencies

#3168 Don't initialize client during flavor sync
  src/zenml/stack/flavor.py
Labels: bug, internal

#3162 Cleanup materializer temporary directories after step execution
  docs/book/how-to/data-artifact-management/handle-data-artifacts/handle-custom-data-types.md
  src/zenml/artifacts/preexisting_data_materializer.py
  src/zenml/artifacts/utils.py
  src/zenml/integrations/bentoml/materializers/bentoml_bento_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_datasets_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_pt_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_t5_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tf_model_materializer.py
  src/zenml/integrations/huggingface/materializers/huggingface_tokenizer_materializer.py
  src/zenml/integrations/lightgbm/materializers/lightgbm_booster_materializer.py
  src/zenml/integrations/lightgbm/materializers/lightgbm_dataset_materializer.py
  src/zenml/integrations/pillow/materializers/pillow_image_materializer.py
  src/zenml/integrations/polars/materializers/dataframe_materializer.py
  src/zenml/integrations/pycaret/materializers/model_materializer.py
  src/zenml/integrations/tensorflow/materializers/keras_materializer.py
  src/zenml/integrations/tensorflow/materializers/tf_dataset_materializer.py
  src/zenml/integrations/whylogs/materializers/whylogs_materializer.py
  src/zenml/integrations/xgboost/materializers/xgboost_booster_materializer.py
  src/zenml/integrations/xgboost/materializers/xgboost_dmatrix_materializer.py
  src/zenml/materializers/base_materializer.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/step_context.py
  src/zenml/utils/callback_registry.py
  tests/integration/functional/materializers/__init__.py
  tests/integration/functional/materializers/test_base_materializer.py
Labels: enhancement, internal, run-slow-ci

#3171 Fix langchain in API docs
  docs/mocked_libs.json
Labels: internal

#3157 Finetuning guide
  docs/book/.gitbook/assets/finetuning-pipeline.png
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/evaluating-finetuned-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
  docs/book/user-guide/llmops-guide/finetuning-llms/evaluation-for-finetuning.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-100-loc.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-with-accelerate.md
  docs/book/user-guide/llmops-guide/finetuning-llms/next-steps.md
  docs/book/user-guide/llmops-guide/finetuning-llms/starter-choices-for-finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/why-and-when-to-finetune-llms.md
  docs/book/user-guide/llmops-guide/rag/basic-rag-inference-pipeline.md
  docs/book/user-guide/llmops-guide/rag/data-ingestion.md
  docs/book/user-guide/llmops-guide/rag/embeddings-generation.md
  docs/book/user-guide/llmops-guide/rag/rag-85-loc.md
  docs/book/user-guide/llmops-guide/rag/rag-with-zenml.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/llmops-guide/rag/understanding-rag.md
Labels: documentation, internal

#3169 Fix mypy issue vllm evidently
  pyproject.toml
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/vllm/services/vllm_deployment.py
Labels: internal

#3164 Add artifact version batch request
  src/zenml/artifacts/utils.py
  src/zenml/constants.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/routers/artifact_version_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#3172 Add missing section links
  docs/book/user-guide/llmops-guide/README.md
Labels: documentation, internal

#3173 Backport LLM finetuning guide
  docs/book/.gitbook/assets/finetuning-pipeline.png
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/README.md
  docs/book/user-guide/llmops-guide/evaluation/evaluation.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/evaluating-finetuned-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
  docs/book/user-guide/llmops-guide/finetuning-llms/evaluation-for-finetuning.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-100-loc.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-with-accelerate.md
  docs/book/user-guide/llmops-guide/finetuning-llms/next-steps.md
  docs/book/user-guide/llmops-guide/finetuning-llms/starter-choices-for-finetuning-llms.md
  docs/book/user-guide/llmops-guide/finetuning-llms/why-and-when-to-finetune-llms.md
  docs/book/user-guide/llmops-guide/rag/basic-rag-inference-pipeline.md
  docs/book/user-guide/llmops-guide/rag/data-ingestion.md
  docs/book/user-guide/llmops-guide/rag/embeddings-generation.md
  docs/book/user-guide/llmops-guide/rag/rag-85-loc.md
  docs/book/user-guide/llmops-guide/rag/rag-with-zenml.md
  docs/book/user-guide/llmops-guide/rag/storing-embeddings-in-a-vector-database.md
  docs/book/user-guide/llmops-guide/rag/understanding-rag.md
Labels: internal, backport

#3174 Fix uvloop mypy
  pyproject.toml
Labels: internal, run-slow-ci

#3072 Multiple output versions for a step outputs
  .github/workflows/update-templates-to-examples.yml
  examples/llm_finetuning/.copier-answers.yml
  examples/llm_finetuning/steps/log_metadata.py
  src/zenml/artifacts/external_artifact.py
  src/zenml/artifacts/utils.py
  src/zenml/cli/base.py
  src/zenml/enums.py
  src/zenml/integrations/tensorboard/visualizers/tensorboard_visualizer.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/utils.py
  src/zenml/zen_stores/migrations/versions/1cb6477f72d6_move_artifact_save_type.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/examples/test_whylogs.py
  tests/integration/functional/artifacts/test_artifacts_linage.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/models/test_artifact.py
  tests/integration/functional/steps/test_model_version.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/conftest.py
  tests/unit/models/test_artifact_models.py
  tests/unit/orchestrators/test_input_utils.py
  tests/unit/orchestrators/test_step_runner.py
Labels: enhancement, internal, run-slow-ci, requires-frontend-changes

#3096 Simplify Metadata handling
  .github/workflows/update-templates-to-examples.yml
  docs/book/component-guide/orchestrators/kubeflow.md
  examples/e2e/.copier-answers.yml
  examples/e2e/steps/deployment/deployment_deploy.py
  examples/e2e/steps/hp_tuning/hp_tuning_select_best_model.py
  examples/e2e/steps/promotion/promote_with_metric_compare.py
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/gradio/requirements.txt
  examples/e2e_nlp/steps/promotion/promote_get_metrics.py
  examples/mlops_starter/.copier-answers.yml
  examples/mlops_starter/quickstart.ipynb
  examples/mlops_starter/run.py
  examples/mlops_starter/steps/model_promoter.py
  src/zenml/cli/base.py
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/metadata/lazy_load.py
  src/zenml/model/model.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/run_metadata.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/routers/run_metadata_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/models/test_artifact.py
  tests/integration/functional/steps/test_step_context.py
  tests/integration/functional/steps/test_utils.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, breaking-change, run-slow-ci, requires-frontend-changes

#3177 Updating the template versions with `zenml login`
  .github/workflows/update-templates-to-examples.yml
  examples/e2e/.copier-answers.yml
  examples/e2e/README.md
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/Makefile
  examples/e2e_nlp/README.md
  examples/llm_finetuning/.copier-answers.yml
  examples/llm_finetuning/steps/log_metadata.py
  examples/mlops_starter/.copier-answers.yml
  examples/mlops_starter/README.md
  examples/mlops_starter/quickstart.ipynb
  src/zenml/cli/base.py
Labels: internal

#3099 Better input artifacts typing
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/enums.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/steps/step_context.py
  src/zenml/zen_stores/migrations/versions/1cb6477f72d6_move_artifact_save_type.py
  src/zenml/zen_stores/migrations/versions/b557b2871693_update_step_run_input_types.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_artifacts_linage.py
  tests/unit/orchestrators/test_input_utils.py
Labels: enhancement, internal, run-slow-ci

#3181 Fix spelling errors
  docs/book/component-guide/data-validators/data-validators.md
  docs/book/component-guide/data-validators/deepchecks.md
  docs/book/component-guide/data-validators/evidently.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
  docs/book/user-guide/llmops-guide/finetuning-llms/evaluation-for-finetuning.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-with-accelerate.md
  docs/book/user-guide/llmops-guide/finetuning-llms/starter-choices-for-finetuning-llms.md
  src/zenml/data_validators/base_data_validator.py
  src/zenml/integrations/deepchecks/data_validators/deepchecks_data_validator.py
Labels: internal

#3167 Prevent some race conditions
  src/zenml/exceptions.py
  src/zenml/model/model.py
  src/zenml/zen_server/exceptions.py
  src/zenml/zen_stores/migrations/versions/904464ea4041_add_pipeline_model_run_unique_constraints.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3183 Update stack deployments with latest features
  docs/book/how-to/infrastructure-deployment/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/infrastructure-deployment/stack-deployment/deploy-a-cloud-stack.md
  infra/aws/aws-ecr-s3-sagemaker.yaml
  infra/gcp/gcp-gar-gcs-vertex.jinja
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/azure_stack_deployment.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/stack_deployments/stack_deployment.py
Labels: enhancement, internal

#3131 Terraform best practices
  docs/book/.gitbook/assets/terraform_providers_screenshot.png
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/README.md
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/best-practices.md
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/terraform-stack-management.md
  docs/book/toc.md
Labels: documentation, internal

#3176 Fix sagemaker pipeline URLs
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal, run-slow-ci

#3170 Fix lightning orchestrator for multi-step pipelines
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator.py
Labels: internal, run-slow-ci

#3179 Port bugfixes from #2497
  .github/workflows/update-templates-to-examples.yml
  examples/llm_finetuning/.copier-answers.yml
  examples/llm_finetuning/requirements.txt
  examples/llm_finetuning/steps/log_metadata.py
  src/zenml/cli/base.py
  src/zenml/client.py
  src/zenml/zen_server/routers/logs_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  tests/integration/integrations/gcp/orchestrators/test_vertex_orchestrator.py
Labels: bug, internal

#3184 Removing the `enable_cache` from the config files
  .github/workflows/release_finalize.yml
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_gcp.yaml
Labels: bug, internal

#3182 New `log_metadata` function, new `oneof` filtering, additional `run_metadata` filtering
  src/zenml/__init__.py
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/enums.py
  src/zenml/model/utils.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/steps/utils.py
  src/zenml/utils/metadata_utils.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/test_step_context.py
  tests/integration/functional/steps/test_utils.py
  tests/integration/functional/test_client.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/models/test_filter_models.py
Labels: enhancement, internal, run-slow-ci

#3154 Refactored workload API token management for better security and implemented generic API token dispenser
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/cache.py
  src/zenml/zen_server/jwt.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  tests/unit/zen_server/test_jwt.py
Labels: enhancement, internal, run-slow-ci

#3194 Adjustments to the PR template
  .github/pull_request_template.md
Labels: internal

#3195 Fixing sagemaker urls to take the settings into consideration
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal

#3199 Add cached run into testing of migrations
  scripts/test-migrations.sh
Labels: bug, internal

#3202 Fix service connector type registry race conditions
  src/zenml/service_connectors/service_connector_registry.py
Labels: bug, internal

#3203 Refactor container resource configuration in Vertex Orchestrator test
  .github/workflows/unit-test.yml
  tests/integration/integrations/gcp/orchestrators/test_vertex_orchestrator.py
Labels: bug, internal, run-slow-ci

#3200 [docs] Add missing redirects
  .gitbook.yaml
Labels: documentation, internal

#3207 [backport][docs] Add missing redirects (#3200)
  .gitbook.yaml
Labels: internal, backport

#3204 Add links to `uv` new PyTorch documentation
  docs/book/component-guide/README.md
  docs/book/component-guide/integration-overview.md
  docs/book/how-to/infrastructure-deployment/customize-docker-builds/specify-pip-dependencies-and-apt-packages.md
Labels: documentation, internal

#3208 Fix broken docs link
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: documentation, internal

#3198 Bugfix for getting out of an inaccessible active stack with no permissions
  src/zenml/zen_stores/base_zen_store.py
Labels: bug, internal, run-slow-ci

#3175 Simplify model version artifact linkage
  .github/workflows/update-templates-to-examples.yml
  docs/book/how-to/data-artifact-management/handle-data-artifacts/registering-existing-data.md
  docs/book/how-to/model-management-metrics/model-control-plane/linking-model-binaries-data-to-models.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-a-model.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-steps.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  examples/e2e/.copier-answers.yml
  examples/e2e/steps/hp_tuning/hp_tuning_select_best_model.py
  src/zenml/artifacts/artifact_config.py
  src/zenml/artifacts/utils.py
  src/zenml/cli/base.py
  src/zenml/client.py
  src/zenml/model/utils.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/model_version_artifact.py
  src/zenml/models/v2/core/model_version_pipeline_run.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/zen_server/routers/model_versions_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/ec6307720f92_simplify_model_version_links.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/schemas/workspace_schemas.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/integration/functional/artifacts/test_artifacts_linage.py
  tests/integration/functional/cli/conftest.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
  tests/unit/steps/test_utils.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3205 Reenable macos testing
  .github/workflows/ci-slow.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/unit-test.yml
  tests/integration/examples/test_mlflow_deployment.py
  tests/integration/examples/test_mlflow_registry.py
  tests/integration/examples/test_mlflow_tracking.py
  tests/integration/integrations/huggingface/steps/test_accelerate_runner.py
  tests/integration/integrations/tensorflow/materializers/test_keras_materializer.py
Labels: internal, run-slow-ci

#3212 Pass config path during zenml pipeline build
  src/zenml/pipelines/pipeline_definition.py
Labels: bug, internal

#3192 Add test for running templates
  tests/integration/functional/zen_server/template_execution/test_template_execution_utils.py
Labels: enhancement, internal

#3216 Fix service connector docstring
  src/zenml/cli/service_connectors.py
Labels: bug, internal

#3218 Remove `--check` from format script and fix naming
  scripts/format.sh
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: internal

#3206 More scalability improvements
  src/zenml/model/model.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/utils/cloud_utils.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/models.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3220 Use correct keyword for artifact store open
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifacts/utils.py
  src/zenml/io/filesystem.py
  src/zenml/io/local_filesystem.py
Labels: bug, internal

#3222 Add hint when trying to connect with api key
  docs/book/how-to/project-setup-and-management/connecting-to-zenml/connect-with-a-service-account.md
  src/zenml/cli/__init__.py
  src/zenml/cli/login.py
Labels: documentation, internal

#3215 Allow passing None values as parameter for optional complex types
  src/zenml/steps/entrypoint_function_utils.py
  tests/unit/steps/test_entrypoint_function_utils.py
Labels: enhancement, internal

#3217 Limit kubernetes pod and label length
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  src/zenml/orchestrators/utils.py
  tests/integration/integrations/kubernetes/orchestrators/test_manifest_utils.py
  tests/unit/orchestrators/test_utils.py
Labels: bug, internal

#3188 Updating the quickstart example to use the new `log_metadata`
  examples/quickstart/steps/model_evaluator.py
  examples/quickstart/steps/model_tester.py
Labels: internal

#3223 Allow skipping type annotations for step inputs
  src/zenml/orchestrators/step_runner.py
  tests/unit/orchestrators/test_step_runner.py
Labels: enhancement, internal

#2948 Modal Step Operator
  docs/book/component-guide/step-operators/modal.md
  docs/book/component-guide/step-operators/step-operators.md
  docs/book/toc.md
  docs/mocked_libs.json
  src/zenml/integrations/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/modal/__init__.py
  src/zenml/integrations/modal/flavors/__init__.py
  src/zenml/integrations/modal/flavors/modal_step_operator_flavor.py
  src/zenml/integrations/modal/step_operators/__init__.py
  src/zenml/integrations/modal/step_operators/modal_step_operator.py
  tests/integration/integrations/modal/__init__.py
  tests/integration/integrations/modal/step_operators/__init__.py
  tests/integration/integrations/modal/step_operators/test_modal_step_operator.py
Labels: enhancement, internal, run-slow-ci

#3201 Add dynamic artifacts naming, documentation and tests
  .gitbook.yaml
  docs/book/how-to/data-artifact-management/handle-data-artifacts/artifacts-naming.md
  docs/book/how-to/model-management-metrics/model-control-plane/model-versions.md
  docs/book/how-to/pipeline-development/build-pipelines/dynamically-assign-artifact-names.md
  docs/book/how-to/pipeline-development/build-pipelines/name-your-pipeline-runs.md
  docs/book/toc.md
  src/zenml/artifacts/artifact_config.py
  src/zenml/artifacts/utils.py
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/config/step_configurations.py
  src/zenml/model/model.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/pipelines/run_utils.py
  src/zenml/steps/base_step.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/steps/step_decorator.py
  src/zenml/steps/utils.py
  src/zenml/utils/string_utils.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/pipelines/test_pipeline_naming.py
  tests/integration/functional/steps/test_step_naming.py
  tests/unit/orchestrators/test_publish_utils.py
  tests/unit/steps/test_utils.py
Labels: enhancement, internal, run-slow-ci

#3225 Run template CLI command and bugfix
  src/zenml/cli/pipeline.py
  src/zenml/pipelines/pipeline_definition.py
Labels: enhancement, internal

#2882 Make dicts/lists visualizable and add JSON as viz type
  docs/book/how-to/advanced-topics/control-logging/disable-colorful-logging.md
  docs/book/how-to/data-artifact-management/visualize-artifacts/creating-custom-visualizations.md
  src/zenml/enums.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/structured_string_materializer.py
  src/zenml/types.py
  src/zenml/utils/visualization_utils.py
Labels: enhancement, internal

#3227 Quickstart fixes
  examples/quickstart/quickstart.ipynb
  src/zenml/materializers/built_in_materializer.py
  src/zenml/types.py
  src/zenml/utils/visualization_utils.py
Labels: bug, internal

#3226 Add missing docs
  docs/book/how-to/pipeline-development/trigger-pipelines/README.md
  docs/book/how-to/pipeline-development/trigger-pipelines/use-templates-cli.md
  docs/book/how-to/pipeline-development/use-configuration-files/retrieve-used-configuration-of-a-run.md
  docs/book/toc.md
  src/zenml/cli/__init__.py
Labels: documentation, internal

#3229 Misc cleanup
  src/zenml/artifacts/artifact_config.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/model/model.py
  src/zenml/models/v2/core/component.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/run_utils.py
  src/zenml/utils/string_utils.py
  src/zenml/zen_stores/migrations/versions/b73bc71f1106_remove_component_spec_path.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
Labels: enhancement, internal

#3228 Fix input resolution for steps with dynamic artifact names
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_run_utils.py
  tests/integration/functional/steps/test_dynamic_artifact_names.py
  tests/unit/conftest.py
  tests/unit/orchestrators/test_input_utils.py
Labels: bug, internal

#3193 Follow-up on the `run_metadata` changes
  .gitbook.yaml
  .github/workflows/update-templates-to-examples.yml
  docs/book/how-to/model-management-metrics/track-metrics-metadata/README.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-a-model.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-a-run.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-a-step.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-an-artifact.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/attach-metadata-to-steps.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/fetch-metadata-within-steps.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/grouping-metadata.md
  docs/book/how-to/model-management-metrics/track-metrics-metadata/logging-metadata.md
  docs/book/how-to/pipeline-development/build-pipelines/README.md
  docs/book/toc.md
  examples/e2e/.copier-answers.yml
  examples/e2e/steps/hp_tuning/hp_tuning_single_search.py
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/steps/training/model_trainer.py
  examples/llm_finetuning/.copier-answers.yml
  examples/llm_finetuning/steps/log_metadata.py
  examples/llm_finetuning/steps/prepare_datasets.py
  examples/mlops_starter/.copier-answers.yml
  examples/mlops_starter/steps/data_preprocessor.py
  examples/mlops_starter/steps/model_evaluator.py
  examples/quickstart/steps/model_evaluator.py
  examples/quickstart/steps/model_tester.py
  src/zenml/artifacts/utils.py
  src/zenml/cli/base.py
  src/zenml/client.py
  src/zenml/model/model.py
  src/zenml/model/utils.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/run_metadata.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/models/v2/misc/run_metadata.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/steps/utils.py
  src/zenml/utils/metadata_utils.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/migrations/versions/cc269488e5a9_separate_run_metadata.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/test_step_context.py
  tests/integration/functional/test_client.py
  tests/integration/functional/utils/test_metadata_utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci
