Repository zenml-io/zenml, pull requests merged in 2024-02, with the labels that each got.

#2379 Label triggered slow ci
  .github/workflows/ci-slow.yml
  .github/workflows/update-templates-to-examples.yml
Labels: enhancement, internal, run-slow-ci

#2375 Add deprecation warning for `ExternalArtifact` non-value features
  .github/workflows/update-templates-to-examples.yml
  docs/book/user-guide/starter-guide/manage-artifacts.md
  examples/e2e/.copier-answers.yml
  examples/e2e/pipelines/batch_inference.py
  examples/quickstart/.copier-answers.yml
  examples/quickstart/pipelines/training.py
  examples/quickstart/quickstart.ipynb
  src/zenml/artifacts/external_artifact.py
  src/zenml/cli/base.py
Labels: enhancement, internal

#2377 Add telemetry pipeline run ends
  docs/book/user-guide/starter-guide/fetching-pipelines.md
  src/zenml/analytics/enums.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2136 Updating the `update_model` decorator
  src/zenml/client.py
  src/zenml/models/v2/base/update.py
  src/zenml/stack/flavor_registry.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2360 Mocked API docs building
  .github/workflows/ci-fast.yml
  .github/workflows/publish_api_docs.yml
  .typos.toml
  docs/README.md
  docs/mkdocs.yml
  docs/mkdocstrings_helper.py
  docs/mocked_libs.json
  docs/requirements-docs-frozen.txt
  docs/sys_modules_mock.py
  scripts/generate-docs.sh
  src/zenml/materializers/base_materializer.py
  src/zenml/utils/source_utils.py
Labels: documentation, enhancement, internal, run-slow-ci

#2383 Add outputs tags function
  docs/book/user-guide/starter-guide/manage-artifacts.md
  src/zenml/artifacts/artifact_config.py
  src/zenml/artifacts/utils.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/new/steps/step_context.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/models/test_artifact.py
  tests/integration/functional/steps/test_step_context.py
Labels: enhancement, internal, run-slow-ci

#2374 Bump mlflow to v2.10.0
  src/zenml/integrations/mlflow/__init__.py
Labels: dependencies, run-slow-ci

#2387 Fixed linter errors and renamed a few things
  examples/e2e/steps/training/model_trainer.py
  examples/e2e/utils/promote_in_model_registry.py
  src/zenml/actions/__init__.py
  src/zenml/actions/base_action.py
  src/zenml/actions/pipeline_run/__init__.py
  src/zenml/actions/pipeline_run/pipeline_run_action.py
  src/zenml/enums.py
  src/zenml/event_sources/base_event_source.py
  src/zenml/event_sources/schedules/base_schedule_event_source.py
  src/zenml/event_sources/utils.py
  src/zenml/event_sources/webhooks/base_webhook_event_source.py
  src/zenml/integrations/github/plugins/event_sources/github_webhook_event_source.py
  src/zenml/integrations/github/plugins/github_webhook_event_source_flavor.py
  src/zenml/models/v2/core/trigger.py
  src/zenml/models/v2/plugin/action_flavor.py
  src/zenml/scheduler/scheduler_event_source.py
  src/zenml/scheduler/scheduler_event_source_flavor.py
  src/zenml/zen_server/routers/event_endpoints.py
  src/zenml/zen_server/routers/webhook_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/schemas/event_source_schemas.py
  src/zenml/zen_stores/schemas/trigger_schemas.py
Labels: enhancement, internal

#2392 Fix GCP service connector login to overwrite existing valid credentials
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal, run-slow-ci

#2384 Update `has_custom_name` for legacy artifacts
  src/zenml/artifacts/utils.py
  src/zenml/client.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/orchestrators/output_utils.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  tests/integration/functional/artifacts/test_artifact_config.py
  tests/unit/orchestrators/test_output_utils.py
Labels: bug, internal, run-slow-ci

#2310 Use native VertexAI scheduler capability instead of old GCP official workaround
  docs/book/stacks-and-components/component-guide/orchestrators/vertex.md
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/google_cloud_function.py
  src/zenml/integrations/gcp/google_cloud_scheduler.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/__init__.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/main.py
  src/zenml/integrations/gcp/orchestrators/vertex_scheduler/requirements.txt
Labels: enhancement, run-slow-ci

#2372 HyperAI integration: orchestrator and service connector
  docs/book/stacks-and-components/auth-management/auth-management.md
  docs/book/stacks-and-components/auth-management/hyperai-service-connector.md
  docs/book/stacks-and-components/component-guide/orchestrators/hyperai.md
  docs/book/stacks-and-components/component-guide/orchestrators/orchestrators.md
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/cli/utils.py
  src/zenml/integrations/__init__.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/constants.py
  src/zenml/integrations/hyperai/__init__.py
  src/zenml/integrations/hyperai/flavors/__init__.py
  src/zenml/integrations/hyperai/flavors/hyperai_orchestrator_flavor.py
  src/zenml/integrations/hyperai/orchestrators/__init__.py
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
  src/zenml/integrations/hyperai/service_connectors/__init__.py
  src/zenml/integrations/hyperai/service_connectors/hyperai_service_connector.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/service_connectors/service_connector_registry.py
  tests/integration/integrations/hyperai/__init__.py
  tests/integration/integrations/hyperai/orchestrators/__init__.py
  tests/integration/integrations/hyperai/orchestrators/test_hyperai_orchestrator.py
Labels: enhancement, run-slow-ci

#2391 Trigger executions
  src/zenml/actions/base_action.py
  src/zenml/actions/pipeline_run/pipeline_run_action.py
  src/zenml/client.py
  src/zenml/constants.py
  src/zenml/enums.py
  src/zenml/event_hub/event_hub.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/trigger_execution.py
  src/zenml/plugins/plugin_flavor_registry.py
  src/zenml/zen_server/rbac/models.py
  src/zenml/zen_server/routers/triggers_endpoints.py
  src/zenml/zen_stores/migrations/versions/b677988b61e1_add_trigger_executions.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/trigger_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
Labels: enhancement, internal

#2400 Let contributors shield link to ZenML contributors
  README.md
Labels: documentation, enhancement

#2401 Prepare release 0.55.2
  README.md
  RELEASE_NOTES.md
  examples/quickstart/quickstart.ipynb
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.55.2_release.py
Labels: internal, run-slow-ci

#2406 Add HyperAI to TOC
  docs/book/toc.md
Labels: documentation, internal

#2408 Correct docstring in integration init file
  src/zenml/integrations/hyperai/flavors/__init__.py
Labels: bug

#2409 Redesigned event source configuration hooks
  src/zenml/event_sources/base_event_source.py
  src/zenml/event_sources/schedules/base_schedule_event_source.py
  src/zenml/event_sources/webhooks/base_webhook_event_source.py
  src/zenml/integrations/github/plugins/event_sources/github_webhook_event_source.py
  src/zenml/models/v2/core/event_source.py
  src/zenml/models/v2/core/trigger.py
  src/zenml/plugins/base_plugin_flavor.py
  src/zenml/scheduler/scheduler_event_source.py
  src/zenml/zen_server/routers/event_endpoints.py
  src/zenml/zen_server/routers/plugin_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/schemas/event_source_schemas.py
  src/zenml/zen_stores/schemas/trigger_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#2407 Backport: Add HyperAI to TOC (#2406)
  docs/book/toc.md
Labels: internal, backport

#2411 Adding the new version to the migration tests
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal

#2399 Ensure proper spacing in error messages
  src/zenml/cli/stack_components.py
  src/zenml/integrations/kserve/steps/kserve_deployer.py
  src/zenml/integrations/mlflow/steps/mlflow_deployer.py
  src/zenml/integrations/seldon/steps/seldon_deployer.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
Labels: bug, run-slow-ci

#2426 Fix hyperai markdown table
  docs/book/stacks-and-components/component-guide/orchestrators/orchestrators.md
Labels: bug, documentation, internal

#2427 Fix hyperai markdown table (#2426)
  docs/book/stacks-and-components/component-guide/orchestrators/orchestrators.md
Labels: bug, documentation, internal, backport

#2428 Upgrade Vertex integration `google-cloud-aiplatform` minimum required version to 1.34.0
  src/zenml/integrations/gcp/__init__.py
Labels: dependencies, run-slow-ci

#2432 Close code block left open in the docs
  docs/book/getting-started/core-concepts.md
Labels: documentation

#2300 Simplify HF example and notify when cache is down
  .github/actions/setup_environment/action.yml
  .github/workflows/generate-test-duration.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/unit-test.yml
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
  src/zenml/integrations/hyperai/flavors/__init__.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  tests/integration/examples/huggingface/pipelines/sequence_classifier_pipeline/sequence_classifier_pipeline.py
  tests/integration/examples/huggingface/pipelines/token_classifier_pipeline/token_classifier_pipeline.py
  tests/integration/examples/huggingface/steps/evaluation/sequence_evaluation_step.py
  tests/integration/examples/huggingface/steps/load_tokenizer/load_tokenizer_step.py
  tests/integration/examples/huggingface/steps/training/sequence_training_step.py
  tests/integration/examples/neural_prophet/steps/data_loader/data_loader_step.py
  tests/integration/examples/neural_prophet/steps/trainer/trainer_step.py
Labels: enhancement, internal, run-slow-ci

#2433 Remove workspace scoping in route
  src/zenml/zen_server/routers/event_endpoints.py
  src/zenml/zen_server/routers/triggers_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal

#2430 Adding the latest version id and name to the artifact response
  src/zenml/models/v2/core/artifact.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
Labels: enhancement, internal, run-slow-ci

#2431 Adding the ID of the producer pipeline run to artifact versions
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
Labels: enhancement, internal, run-slow-ci

#2437 Add vulnerability notice to README
  README.md
Labels: internal, security

#2439 Link pipeline runs to trigger executions
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_stores/migrations/versions/23e4cabea464_link_pipeline_runs_to_trigger_executions.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
Labels: enhancement, internal

#2402 Allow more recent `adlfs` and `s3fs` versions
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/s3/__init__.py
Labels: internal, dependencies, run-slow-ci

#2434 Add `download_files` method for `ArtifactVersion`
  docs/book/user-guide/starter-guide/manage-artifacts.md
  src/zenml/artifacts/utils.py
  src/zenml/models/v2/core/artifact_version.py
  tests/integration/functional/artifacts/test_utils.py
Labels: enhancement, internal, run-slow-ci

#2440 Fixing `update_model`s and revert #2402
  src/zenml/client.py
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/s3/__init__.py
  src/zenml/models/v2/base/update.py
  src/zenml/stack/flavor_registry.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#2436 Improve services logging and status
  src/zenml/services/service.py
Labels: enhancement, internal, run-slow-ci

#2447 Add `save models to registry` setting of a model to CLI methods
  src/zenml/cli/model.py
  src/zenml/client.py
  src/zenml/models/v2/core/model.py
  tests/integration/functional/cli/test_model.py
Labels: bug, internal, run-slow-ci

#2446 Parallel pipelines can create entities in DB
  src/zenml/artifacts/utils.py
  src/zenml/constants.py
  src/zenml/model/model.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/artifacts/test_utils.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_parallel.py
  tests/integration/functional/pipelines/util_parallel_pipeline_script.py
  tests/integration/functional/test_client.py
Labels: bug, internal, run-slow-ci

#2449 Fix MlFlow TF autlogging excessive warnings
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
Labels: bug, internal, run-slow-ci

#2457 Disable methods for local case
  src/zenml/client.py
Labels: enhancement, internal

#2451 Handle urlencoded payloads
  src/zenml/event_sources/webhooks/base_webhook_event_source.py
  src/zenml/integrations/github/plugins/event_sources/github_webhook_event_source.py
Labels: enhancement, internal

#2450 Add migration test version + use self-hosted runners for release
  .github/workflows/release.yml
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: internal

#2389 Enable running pipeline via REST
  src/zenml/config/server_config.py
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/kubeflow/flavors/kubeflow_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/models/v2/core/pipeline_build.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/new/pipelines/build_utils.py
  src/zenml/new/pipelines/pipeline.py
  src/zenml/new/pipelines/run_utils.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/zen_server/pipeline_deployment/__init__.py
  src/zenml/zen_server/pipeline_deployment/runner_entrypoint_configuration.py
  src/zenml/zen_server/pipeline_deployment/utils.py
  src/zenml/zen_server/pipeline_deployment/workload_manager_interface.py
  src/zenml/zen_server/routers/pipeline_builds_endpoints.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/76a7b9451ccd_add_build_template_deployment_id.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  tests/integration/functional/steps/test_model_version.py
Labels: run-slow-ci

#2460 Faster mlflow `list_model_versions`
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
Labels: bug, internal, run-slow-ci

#2458 Avoid exposure of tracking uri to metadata
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
Labels: bug, internal, run-slow-ci

#2463 Some important docs updates
  README.md
  docs/book/.gitbook/assets/zenml-cloud-tenant-overview.png
  docs/book/.gitbook/assets/zenml-hero.png
  docs/book/.gitbook/assets/zenml-why.png
  docs/book/deploying-zenml/zenml-cloud/cloud-system-architecture.md
  docs/book/deploying-zenml/zenml-cloud/zenml-cloud.md
  docs/book/getting-started/installation.md
  docs/book/user-guide/advanced-guide/data-management/model-management.md
  docs/book/user-guide/production-guide/deploying-zenml.md
Labels: documentation, internal

#2467 Fix CI
  .github/actions/setup_environment/action.yml
  scripts/install-zenml-dev.sh
  scripts/run-ci-checks.sh
Labels: bug, internal, dependencies, breaking-change, fix, CI, run-slow-ci

#2459 Fix local Airflow install + docs instructions
  docs/book/stacks-and-components/component-guide/orchestrators/airflow.md
  src/zenml/integrations/airflow/__init__.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
Labels: bug, documentation, internal, run-slow-ci

#2470 Update `.coderabbit.yaml`
  .coderabbit.yaml
Labels: internal

#2469 Prevent templates update from formatting the whole codebase
  .github/workflows/update-templates-to-examples.yml
Labels: enhancement, internal

#2468 Telemetry guarding for CI & editable installs
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  scripts/test-migrations-mariadb.sh
  scripts/test-migrations-mysql.sh
Labels: bug, internal, run-slow-ci

#2398 Add Vertex Step Operator network parameter
  docs/book/stacks-and-components/component-guide/step-operators/vertex.md
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
Labels: enhancement, run-slow-ci

#2466 Allow integration export to overwrite a pre-existing file
  src/zenml/cli/integration.py
Labels: enhancement, internal, run-slow-ci

#2465 Fix `log_model_metadata` with explicit name and version
  src/zenml/model/utils.py
  tests/integration/functional/model/test_model_version.py
Labels: bug, internal, run-slow-ci

#2472 Mount zenml config path as empty dir
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
Labels: bug, internal

#2473 Fix broken docs links
  docs/book/user-guide/production-guide/cloud-orchestration.md
Labels: documentation, internal

#2474 Use `uv pip compile` for environment setup in CI
  scripts/install-zenml-dev.sh
  src/zenml/integrations/mlflow/__init__.py
Labels: internal, run-slow-ci

#2462 MLflow fix for tests on Mac Python 3.9 and 3.10
  tests/harness/cfg/tests.yaml
  tests/integration/examples/mlflow/pipelines/deployment_pipelines/deployment_inference_pipeline.py
  tests/integration/examples/mlflow/pipelines/deployment_pipelines/deployment_training_pipeline.py
  tests/integration/examples/mlflow/pipelines/registry_pipelines/registry_inference_pipeline.py
  tests/integration/examples/mlflow/pipelines/registry_pipelines/registry_training_pipeline.py
  tests/integration/examples/mlflow/pipelines/tracking_pipeline/tracking_pipeline.py
  tests/integration/examples/mlflow/steps/dynamic_importer_step.py
  tests/integration/examples/mlflow/steps/evaluator_step.py
  tests/integration/examples/mlflow/steps/loader_step.py
  tests/integration/examples/mlflow/steps/normalizer_step.py
  tests/integration/examples/mlflow/steps/predict_preprocessor_step.py
  tests/integration/examples/mlflow/steps/predictor_step.py
  tests/integration/examples/mlflow/steps/trainer_step.py
  tests/integration/examples/test_mlflow_deployment.py
  tests/integration/examples/test_mlflow_registry.py
Labels: bug, internal, run-slow-ci

#2476 Improve custom data types docs
  docs/book/user-guide/advanced-guide/data-management/handle-custom-data-types.md
Labels: documentation, internal

#2371 Reflect env variables on global configuration
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/config/global_config.py
  src/zenml/config/store_config.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_server/deploy/base_provider.py
  src/zenml/zen_server/deploy/deployer.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_server/deploy/local/local_zen_server.py
  src/zenml/zen_server/deploy/terraform/providers/terraform_provider.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_stores/migrations/env.py
  src/zenml/zen_stores/migrations/versions/7b651bf6822e_track_secrets_in_db.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/harness/deployment/base.py
  tests/harness/utils.py
  tests/integration/functional/cli/test_config.py
  tests/unit/config/test_global_config.py
  tests/unit/utils/test_io_utils.py
Labels: bug, internal, run-slow-ci

#2454 Fix zenml deploy secret stores
  src/zenml/zen_stores/secrets_stores/aws_secrets_store.py
  src/zenml/zen_stores/secrets_stores/gcp_secrets_store.py
Labels: bug, run-slow-ci

#2478 Don't fail when workload manager source fails to load
  src/zenml/zen_server/utils.py
Labels: enhancement, internal, run-slow-ci

#2456 Add analytics events for cloud onboarding
  src/zenml/analytics/context.py
  src/zenml/analytics/enums.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/devices_endpoints.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#2479 Race condition on creating new users allows duplicate usernames
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal, security, run-slow-ci

#2482 Misc/prepare-release-0.55.4
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  src/zenml/VERSION
  src/zenml/zen_server/deploy/helm/Chart.yaml
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_stores/migrations/versions/0.55.4_release.py
Labels: internal, run-slow-ci
