Repository zenml-io/zenml, pull requests merged in 2024-12, with the labels that each got.

#3232 Fixed broken links
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/config/secret_reference_mixin.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#3233 Fixed wandb login problem in Quickstart
  examples/quickstart/configs/training_aws.yaml
  examples/quickstart/configs/training_azure.yaml
  examples/quickstart/configs/training_default.yaml
  examples/quickstart/configs/training_gcp.yaml
  examples/quickstart/quickstart.ipynb
Labels: bug, internal

#3234 Misc bugfixes
  examples/e2e/.copier-answers.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/llm_finetuning/.copier-answers.yml
  examples/mlops_starter/.copier-answers.yml
  src/zenml/cli/pipeline.py
  src/zenml/integrations/neptune/experiment_trackers/neptune_experiment_tracker.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
  src/zenml/integrations/registry.py
Labels: bug, internal

#3231 Add additional way to fetch docker repo digest
  src/zenml/utils/docker_utils.py
Labels: bug, internal

#3235 Disable client-side caching for some orchestrators
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/lightning/flavors/lightning_orchestrator_flavor.py
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
  src/zenml/orchestrators/base_orchestrator.py
Labels: bug, internal

#3238 Materializer test fix on Windows
  src/zenml/materializers/built_in_materializer.py
Labels: bug, internal, run-slow-ci

#3240 Fix GET step run endpoint to return unhydrated response if requested
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3242 Pipeline run API token fixes and improvements
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal, run-slow-ci

#3247 Fix typo in readme
  README.md
Labels: documentation, internal

#3250 adding 0.71.0 to migration tests
  scripts/test-migrations.sh
Labels: internal

#3243 Fix workload token expiration for cached steps/runs
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/auth_endpoints.py
Labels: bug, internal

#3246 Implement wandb settings conversion for latest release
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
Labels: enhancement, internal

#3253 Add CPU usage note to Modal docs
  docs/book/component-guide/step-operators/modal.md
Labels: documentation, internal

#3256 Re-authenticate requests that failed authentication
  src/zenml/cli/server.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: run-slow-ci

#3236 Add step run unique constraint
  src/zenml/zen_stores/migrations/versions/26351d482b9e_add_step_run_unique_constraint.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3258 Fix fetching run template using the client
  src/zenml/client.py
Labels: bug, internal

#3230 Filtering and sorting
  src/zenml/client.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/code_repository.py
  src/zenml/models/v2/core/component.py
  src/zenml/models/v2/core/flavor.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/model_version_artifact.py
  src/zenml/models/v2/core/model_version_pipeline_run.py
  src/zenml/models/v2/core/pipeline.py
  src/zenml/models/v2/core/pipeline_build.py
  src/zenml/models/v2/core/pipeline_deployment.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/run_template.py
  src/zenml/models/v2/core/schedule.py
  src/zenml/models/v2/core/secret.py
  src/zenml/models/v2/core/service.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/models/v2/core/stack.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/models/v2/core/trigger.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3259 Fix hyperparam tuning docs
  docs/book/how-to/pipeline-development/build-pipelines/hyper-parameter-tuning.md
Labels: bug, internal

#3262 Include user of latest run in pipeline response
  src/zenml/models/v2/core/pipeline.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
Labels: enhancement, internal

#3254 Create model versions server-side to avoid race conditions
  src/zenml/model/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/zen_server/rbac/rbac_sql_zen_store.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/a1237ba94fd8_add_model_version_producer_run_unique_.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/pipelines/test_pipeline_context.py
  tests/integration/functional/steps/test_model_version.py
  tests/integration/integrations/gcp/orchestrators/test_vertex_orchestrator.py
  tests/unit/model/test_model_version_init.py
Labels: enhancement, internal, run-slow-ci

#3245 Fix request model validation
  src/zenml/models/v2/base/filter.py
  src/zenml/zen_server/utils.py
  tests/unit/models/test_filter_models.py
Labels: bug, internal

#3272 Improve docs to encourage using secrets
  docs/book/how-to/project-setup-and-management/setting-up-a-project-repository/connect-your-git-repository.md
Labels: documentation, internal
