Repository zenml-io/zenml, pull requests merged in 2025-03, with the labels that each got.

#3389 Deepchecks fix for the CI
  src/zenml/integrations/deepchecks/__init__.py
Labels: bug, internal

#3391 Fixing the CI
  .github/workflows/ci-fast.yml
  .github/workflows/ci-slow.yml
  .github/workflows/spellcheck.yml
  docker/zenml-server-dev.Dockerfile
  src/zenml/utils/dashboard_utils.py
  src/zenml/utils/visualization_utils.py
  tests/integration/integrations/gcp/orchestrators/test_vertex_orchestrator.py
Labels: bug, internal, run-slow-ci

#3388 Fixing the zenml login hint for separated names
  src/zenml/cli/login.py
Labels: bug, internal, run-slow-ci

#3394 Allow registering public gitlab repositories without token
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
Labels: enhancement, internal

#3390 Fix CLI command to describe flavors
  src/zenml/cli/utils.py
Labels: bug, internal

#3386 Store build duration
  src/zenml/client.py
  src/zenml/models/v2/core/pipeline_build.py
  src/zenml/pipelines/build_utils.py
  src/zenml/zen_stores/migrations/versions/0392807467dc_add_build_duration.py
  src/zenml/zen_stores/schemas/pipeline_build_schemas.py
  tests/integration/integrations/gitlab/code_repositories/test_gitlab_code_repository.py
Labels: enhancement, internal, run-slow-ci

#3395 Removed deprecated caveat from kubernetes docs
  docs/book/component-guide/orchestrators/kubernetes.md
Labels: enhancement, internal

#3360 Improved tagging
  docs/book/how-to/data-artifact-management/handle-data-artifacts/tagging.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  src/zenml/__init__.py
  src/zenml/cli/tag.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/tag.py
  src/zenml/models/v2/misc/tag.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/step_context.py
  src/zenml/utils/string_utils.py
  src/zenml/utils/tag_utils.py
  src/zenml/zen_server/routers/tag_resource_endpoints.py
  src/zenml/zen_server/routers/tags_endpoints.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/9e7bf0970266_adding_exclusive_attribute_to_tags.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/cli/utils.py
  tests/integration/functional/model/test_model_version.py
  tests/integration/functional/test_client.py
  tests/integration/functional/utils/test_tag_utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3403 Fix taggable filter model
  src/zenml/models/v2/base/scoped.py
Labels: bug, internal, run-slow-ci

#3400 Testing the CLI with the profiler
  .github/workflows/performance-profiling.yml
  scripts/compare_profiles.py
  scripts/profile-cli.sh
  src/zenml/cli/model.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/stack.py
Labels: bug, internal

#3408 Don't retry REST API calls if runtime errors occur
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#3398 Allow the service account project ID to be overriden in the GCP service connector
  docs/book/how-to/infrastructure-deployment/auth-management/gcp-service-connector.md
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: enhancement, internal

#3401 Allow passing step artifacts to specify upstream steps
  docs/book/how-to/pipeline-development/build-pipelines/control-execution-order-of-steps.md
  docs/book/how-to/pipeline-development/build-pipelines/fan-in-fan-out.md
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/base_step.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal, run-slow-ci

#3359 Enable Weave integration in Wandb settings
  docs/book/component-guide/experiment-trackers/wandb.md
  src/zenml/integrations/wandb/__init__.py
  src/zenml/integrations/wandb/experiment_trackers/wandb_experiment_tracker.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
Labels: enhancement, internal

#3396 Add persistent resource support for the vertex orchestrator
  docs/book/component-guide/orchestrators/vertex.md
  pyproject.toml
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/vertex_custom_job_parameters.py
Labels: enhancement, internal, run-slow-ci

#3406 Listing tags filtered by resource type
  src/zenml/client.py
  src/zenml/models/v2/core/tag.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3404 Adding removing tags with various update models
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/tag.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3405 Exclusive tag behaviour
  src/zenml/utils/tag_utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/utils/test_tag_utils.py
Labels: bug, internal, run-slow-ci

#3415 API Docs -> SDK Docs
  docs/mkdocs.yml
  docs/mkdocstrings_helper.py
  docs/sys_modules_mock.py
Labels: enhancement, internal

#3416 Removed step
  .github/actions/setup_environment/action.yml
  .github/workflows/generate-test-duration.yml
  .github/workflows/integration-test-fast-services.yml
  .github/workflows/integration-test-fast.yml
  .github/workflows/integration-test-slow-services.yml
  .github/workflows/integration-test-slow.yml
  .github/workflows/linting.yml
  .github/workflows/unit-test.yml
Labels: internal

#3412 Fix unbound variable access
  src/zenml/login/pro/utils.py
Labels: bug, internal

#3413 Allow setting environment variables through `KubernetesPodSettings`
  docs/book/component-guide/orchestrators/kubernetes.md
  docs/book/component-guide/step-operators/kubernetes.md
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#3418 Fix deprecation message for github code repository
  src/zenml/integrations/github/code_repositories/github_code_repository.py
Labels: internal

#3420 Fix project statistics endpoint
  src/zenml/zen_server/routers/projects_endpoints.py
Labels: bug, internal

#3423 Track project creation in onboarding state
  src/zenml/enums.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3424 Fix the ACR support in the Azure service connector
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
Labels: bug, internal

#3422 Limiting the `mlflow` dependency
  src/zenml/integrations/mlflow/__init__.py
Labels: bug, internal, run-slow-ci

#3421 Pass API token as kubernetes secret
  docs/book/component-guide/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
Labels: enhancement, internal

#3427 Fetch model hydrated during deletion process
  src/zenml/zen_server/rbac/endpoint_utils.py
Labels: bug, internal

#3428 Add missing functions and classes to root init exports
  src/zenml/__init__.py
Labels: bug, internal

#3430 Fix doc links and comment test out
  src/zenml/artifacts/artifact_config.py
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/config/compiler.py
  src/zenml/orchestrators/utils.py
  src/zenml/steps/entrypoint_function_utils.py
  tests/unit/test_flavor.py
Labels: enhancement, internal

#3429 Upgrading the `skypilot` dependency
  src/zenml/integrations/skypilot_aws/__init__.py
  src/zenml/integrations/skypilot_azure/__init__.py
  src/zenml/integrations/skypilot_gcp/__init__.py
  src/zenml/integrations/skypilot_kubernetes/__init__.py
  src/zenml/integrations/skypilot_lambda/__init__.py
Labels: bug, internal, run-slow-ci

#3410 Fixing filter models with multiple inputs
  src/zenml/client.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/test_flavor.py
Labels: bug, internal, run-slow-ci

#3435 Add project usage tracking
  src/zenml/constants.py
  src/zenml/zen_server/routers/projects_endpoints.py
Labels: enhancement, internal

#3439 Fix the backslash problem
  docs/book/component-guide/alerters/discord.md
  docs/book/component-guide/annotators/argilla.md
  docs/book/component-guide/annotators/label-studio.md
  docs/book/component-guide/artifact-stores/azure.md
  docs/book/component-guide/artifact-stores/gcp.md
  docs/book/component-guide/artifact-stores/s3.md
  docs/book/component-guide/component-guide.md
  docs/book/component-guide/container-registries/README.md
  docs/book/component-guide/container-registries/aws.md
  docs/book/component-guide/container-registries/azure.md
  docs/book/component-guide/container-registries/gcp.md
  docs/book/component-guide/experiment-trackers/README.md
  docs/book/component-guide/image-builders/README.md
  docs/book/component-guide/image-builders/aws.md
  docs/book/component-guide/image-builders/gcp.md
  docs/book/component-guide/orchestrators/README.md
  docs/book/component-guide/orchestrators/airflow.md
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/orchestrators/kubeflow.md
  docs/book/component-guide/orchestrators/lightning.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/tekton.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/README.md
  docs/book/how-to/pipeline-development/use-configuration-files/autogenerate-a-template-yaml-file.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/evaluating-finetuned-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-with-sentence-transformers.md
  docs/book/user-guide/llmops-guide/finetuning-llms/README.md
Labels: bug, documentation, internal

#3442 Adding `0.80.0` to the migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal

#3431 Adding the disabled flavor test back
  tests/unit/test_flavor.py
Labels: bug, internal

#3449 Stop CLI profiler running so much
  .github/workflows/performance-profiling.yml
Labels: internal, CI

#3434 Add missing fallback host for code repositories
  src/zenml/integrations/github/code_repositories/github_code_repository.py
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
Labels: bug, internal, run-slow-ci

#3451 Fix stack and component URL when connected to a cloud workspace
  .github/workflows/performance-profiling.yml
  src/zenml/utils/dashboard_utils.py
Labels: bug, internal

#3453 Fix 0.80.0 database migration
  src/zenml/zen_stores/migrations/versions/288f4fb6e112_make_tags_user_scoped.py
  src/zenml/zen_stores/migrations/versions/41b28cae31ce_make_artifacts_workspace_scoped.py
  src/zenml/zen_stores/migrations/versions/f1d723fd723b_add_secret_private_attr.py
Labels: bug, internal

#3443 Pin the ZenML Terraform provider version
  infra/aws/aws-ecr-s3-sagemaker.yaml
  infra/gcp/gcp-gar-gcs-vertex-deploy.sh
  src/zenml/stack_deployments/aws_stack_deployment.py
  src/zenml/stack_deployments/azure_stack_deployment.py
  src/zenml/stack_deployments/constants.py
  src/zenml/stack_deployments/gcp_stack_deployment.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
Labels: enhancement, internal, run-slow-ci

#3419 Import integrations lazily
  src/zenml/integrations/__init__.py
  src/zenml/integrations/registry.py
Labels: enhancement, internal, run-slow-ci

#3455 Remove Segment analytics script and scarf image load.
  docs/_templates/layout.html
Labels: internal

#3459 Removing redundant log messages
  src/zenml/cli/server.py
  src/zenml/zen_stores/base_zen_store.py
Labels: bug, internal

#3462 Fix broken link in API documentation table
  docs/book/api-docs/README.md
Labels: documentation, internal

#3457 Add the ability to store a default project for a user
  docs/book/getting-started/zenml-pro/projects.md
  src/zenml/cli/project.py
  src/zenml/client.py
  src/zenml/config/global_config.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/models/v2/core/user.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/1f1105204aaf_add_user_default_project.py
  src/zenml/zen_stores/schemas/user_schemas.py
Labels: enhancement, internal, run-slow-ci

#3464 Fixing the CLI combined with RestZenStore and filters with multiple entries
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal, run-slow-ci

#3465 Use the build python version to collect stack requirements for run templates
  src/zenml/integrations/databricks/__init__.py
  src/zenml/integrations/deepchecks/__init__.py
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/facets/__init__.py
  src/zenml/integrations/feast/__init__.py
  src/zenml/integrations/great_expectations/__init__.py
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/integrations/integration.py
  src/zenml/integrations/langchain/materializers/openai_embedding_materializer.py
  src/zenml/integrations/langchain/materializers/vector_store_materializer.py
  src/zenml/integrations/llama_index/materializers/document_materializer.py
  src/zenml/integrations/llama_index/materializers/gpt_index_materializer.py
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/seldon/__init__.py
  src/zenml/integrations/tensorboard/__init__.py
  src/zenml/integrations/tensorflow/__init__.py
  src/zenml/integrations/whylogs/__init__.py
  src/zenml/utils/requirements_utils.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3474 Backporting missing legacy docs
  docs/book/reference/legacy-docs.md
Labels: internal, backport

#3471 add new version to the migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal

#3478 Log job completion for Vertex orchestrator
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
Labels: enhancement, internal

#3480 Cleaning up the CI failures
  docs/mocked_libs.json
  pyproject.toml
  src/zenml/zen_stores/migrations/utils.py
Labels: bug, internal

#3481 Remove remaining use of tj-actions/changed-files
  .github/workflows/linting.yml
Labels: bug, internal

#3479 Fixing the timestamps in logs
  src/zenml/logging/step_logging.py
Labels: bug, internal, run-slow-ci
