Repository zenml-io/zenml, pull requests merged in 2025-06, with the labels that each got.

#3715 Add `0.82.1` to the legacy docs
  .github/workflows/release_finalize.yml
  docs/book/reference/legacy-docs.md
Labels: documentation, internal

#3710 Keep visualizations when using existing tag
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3721 Use the active artifact store as cache when loading artifacts
  src/zenml/artifacts/utils.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: bug, internal, run-slow-ci

#3709 Random cleanup and bugfixes
  src/zenml/client.py
  src/zenml/models/v2/core/stack.py
  tests/integration/functional/zen_stores/utils.py
Labels: internal

#3729 Fix some links
  src/zenml/artifacts/utils.py
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/server.py
  src/zenml/cli/stack.py
  src/zenml/config/compiler.py
  src/zenml/config/secret_reference_mixin.py
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/neptune/experiment_trackers/run_state.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/cloudpickle_materializer.py
  src/zenml/model/utils.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/stack/stack_component.py
  src/zenml/steps/entrypoint_function_utils.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: documentation, enhancement, internal

#3726 Fix run template fetching
  src/zenml/client.py
Labels: bug, internal

#3727 Fix missing artifact nodes in DAG
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3732 Revert "Keep visualizations when using existing tag"
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal

#3730 Better run template docs
  docs/book/how-to/templates/templates.md
Labels: documentation, internal

#3746 Fix line breaks in llms.txt docs
  docs/book/reference/llms-txt.md
Labels: documentation, internal

#3738 Idempotent POST requests, request caching and other performance improvements
  docker/base.Dockerfile
  docker/zenml-server-dev.Dockerfile
  examples/stress-test/results.ipynb
  examples/stress-test/run.py
  examples/stress-test/utils.py
  helm/templates/_environment.tpl
  helm/templates/server-deployment.yaml
  helm/values.yaml
  scripts/docker-entrypoint.sh
  src/zenml/analytics/context.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/api_transaction.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/utils/json_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/middleware.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/request_management.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/model_versions_endpoints.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/pipeline_builds_endpoints.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/run_templates_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/migrations/versions/3d7e39f3ac92_split_up_step_configurations.py
  src/zenml/zen_stores/migrations/versions/857843db1bcf_add_api_transaction_table.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/__init__.py
  src/zenml/zen_stores/schemas/api_transaction_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3756 Update issue template configurations and URLs
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_report.yml
  README.md
  RELEASE_NOTES.md
  docs/book/reference/faq.md
Labels: internal

#3764 Add new release to migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#3723 Split run submission and monitoring
  docs/book/component-guide/orchestrators/custom.md
  src/zenml/constants.py
  src/zenml/exceptions.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/azure/orchestrators/azureml_orchestrator.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/lightning/orchestrators/lightning_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot/utils.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
  src/zenml/orchestrators/__init__.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/orchestrators/local_docker/local_docker_orchestrator.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/pipelines/run_utils.py
  tests/integration/functional/pipelines/test_pipeline_run.py
  tests/unit/orchestrators/test_containerized_orchestrator.py
  tests/unit/stack/test_stack_component.py
Labels: enhancement, internal

#3767 Made --no-verify-ssl work for pro tenants as well
  src/zenml/cli/login.py
Labels: bug, internal

#3743 Unified config imports to match docs
  src/zenml/config/__init__.py
Labels: documentation, internal

#3759 Fixed misleading error message
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#3722 Switch from pkg_resources to importlib
  src/zenml/cli/base.py
  src/zenml/cli/utils.py
  src/zenml/integrations/databricks/orchestrators/databricks_orchestrator_entrypoint_config.py
  src/zenml/integrations/integration.py
  src/zenml/utils/integration_utils.py
  src/zenml/utils/package_utils.py
  tests/harness/model/requirements.py
  tests/integration/functional/cli/test_utils.py
  tests/unit/utils/test_integration_utils.py
  tests/unit/utils/test_package_utils.py
Labels: internal, run-slow-ci

#3770 Hide service connector secrets as internal implementation details
  .typos.toml
  src/zenml/cli/service_connectors.py
  src/zenml/cli/stack.py
  src/zenml/cli/utils.py
  src/zenml/client.py
  src/zenml/integrations/aws/container_registries/aws_container_registry.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/service_connector.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/service_connectors/service_connector_utils.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_stores/migrations/versions/5bb25e95849c_add_internal_secrets.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/schemas/service_connector_schemas.py
  src/zenml/zen_stores/secrets_stores/service_connector_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/functional/zen_stores/utils.py
Labels: enhancement, internal, run-slow-ci

#3777 Fix fetching model version by UUID passed as string
  src/zenml/client.py
Labels: bug, internal

#3769 Ensure visualizations are committed before potential transaction rollback
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3776 Improved pipeline/step run fetching
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3719 Improved Kubernetes orchestrator pod caching
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint_configuration.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/dag_runner.py
  src/zenml/orchestrators/input_utils.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/pipelines/run_utils.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/integrations/kubernetes/orchestrators/test_manifest_utils.py
Labels: enhancement, internal
