Repository zenml-io/zenml, pull requests merged in 2025-05, with the labels that each got.

#3632 Extending the Dockerfiles
  docker/base.Dockerfile
  release-cloudbuild.yaml
Labels: bug, internal

#3617 Use parent image digest for cache invalidation
  src/zenml/config/build_configuration.py
  src/zenml/container_registries/base_container_registry.py
Labels: enhancement, internal

#3625 Pro API login lock and other robustness improvements
  src/zenml/config/server_config.py
  src/zenml/zen_server/cloud_utils.py
Labels: bug, internal

#3636 Pin setuptools and remove it from scripts
  .github/workflows/performance-profiling.yml
  .trivyignore
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  pyproject.toml
  scripts/install-zenml-dev.sh
Labels: run-slow-ci

#3641 Update link validation to skip GitHub links and improve progress tracking
  docs/book/component-guide/artifact-stores/custom.md
  docs/book/component-guide/container-registries/custom.md
  docs/book/component-guide/data-validators/custom.md
  docs/book/component-guide/experiment-trackers/custom.md
  docs/book/component-guide/image-builders/custom.md
  docs/book/component-guide/model-deployers/custom.md
  docs/book/component-guide/orchestrators/custom.md
  docs/book/component-guide/step-operators/custom.md
  docs/book/user-guide/best-practices/set-up-your-repository.md
  docs/link_checker.py
Labels: internal

#3640 Added docs section
  docs/book/user-guide/best-practices/choose-orchestration-environment.md
  docs/book/user-guide/toc.md
Labels: documentation, internal

#3638 Various improvements to the release flow
  .github/workflows/release_finalize.yml
  .github/workflows/release_prepare.yml
  scripts/add-migration-test-version.sh
  scripts/add_version_to_legacy_docs.py
Labels: bug, internal

#3621 Fix Dockerhub repo digest detection
  src/zenml/utils/docker_utils.py
Labels: bug, internal

#3639 Add unique instance label to helm chart
  helm/templates/_helpers.tpl
  helm/templates/server-db-job.yaml
  helm/templates/server-deployment.yaml
  helm/values.yaml
Labels: enhancement, internal

#3646 Slight doc fix. Fixes #3645
  docs/book/how-to/stack-components/service_connectors.md
Labels: internal

#3633 Add 5-min quick wins page to docs
  RELEASE_NOTES.md
  docs/book/.gitbook/assets/pipeline-run-on-the-dashboard.png
  docs/book/.gitbook/assets/stack-deployment-options.png
  docs/book/component-guide/container-registries/dockerhub.md
  docs/book/component-guide/data-validators/great-expectations.md
  docs/book/user-guide/.gitbook/assets/code-repository-sha.png
  docs/book/user-guide/.gitbook/assets/experiment_comparison_video.png
  docs/book/user-guide/.gitbook/assets/filtering-by-tags.png
  docs/book/user-guide/.gitbook/assets/htmlstring-visualization.gif
  docs/book/user-guide/best-practices/quick-wins.md
  docs/book/user-guide/toc.md
  docs/book/user-guide/tutorial/managing-scheduled-pipelines.md
Labels: documentation, internal

#3647 Backporting small docs
  RELEASE_NOTES.md
  docs/book/.gitbook/assets/pipeline-run-on-the-dashboard.png
  docs/book/.gitbook/assets/stack-deployment-options.png
  docs/book/component-guide/container-registries/dockerhub.md
  docs/book/component-guide/data-validators/great-expectations.md
  docs/book/how-to/stack-components/service_connectors.md
  docs/book/user-guide/.gitbook/assets/code-repository-sha.png
  docs/book/user-guide/.gitbook/assets/experiment_comparison_video.png
  docs/book/user-guide/.gitbook/assets/filtering-by-tags.png
  docs/book/user-guide/.gitbook/assets/htmlstring-visualization.gif
  docs/book/user-guide/best-practices/quick-wins.md
  docs/book/user-guide/toc.md
  docs/book/user-guide/tutorial/managing-scheduled-pipelines.md
Labels: documentation, internal, backport

#3627 Limit max concurrent template runs
  src/zenml/actions/pipeline_run/pipeline_run_action.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/exceptions.py
  src/zenml/zen_server/exceptions.py
  src/zenml/zen_server/routers/run_templates_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
Labels: enhancement, internal

#3648 Fix bolt icon
  docs/book/user-guide/best-practices/quick-wins.md
Labels: documentation, internal

#3649 Fix bolt icon (#3648)
  docs/book/user-guide/best-practices/quick-wins.md
Labels: documentation, internal, backport

#3618 Workflow to deploy workspaces for PRs
  .github/workflows/pr_workspace_deploy.yml
  pull_request_cloudbuild.yaml
  scripts/manage_workspace.py
Labels: enhancement, internal, run-slow-ci, staging-workspace

#3656 Format link checker
  docs/link_checker.py
Labels: internal

#3602 Improve run template UX
  docs/book/user-guide/best-practices/quick-wins.md
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/step_configurations.py
  src/zenml/constants.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/run_utils.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/template_utils.py
  tests/integration/functional/zen_server/template_execution/test_template_execution_utils.py
  tests/unit/models/test_pipeline_deployment_models.py
  tests/unit/orchestrators/test_cache_utils.py
Labels: enhancement, internal, run-slow-ci

#3661 Fixing artifact visualization docs
  docs/book/.gitbook/assets/artifact_visualization_csv.png
  docs/book/.gitbook/assets/artifact_visualization_evidently copy.png
  docs/book/how-to/artifacts/visualizations.md
Labels: documentation, internal

#3663 Add stress test example
  examples/stress-test/run.py
Labels: enhancement, internal

#3654 Misc login fixes
  src/zenml/cli/login.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal

#3659 Report run template trigger usage
  src/zenml/constants.py
  src/zenml/zen_server/feature_gate/endpoint_utils.py
  src/zenml/zen_server/feature_gate/feature_gate_interface.py
  src/zenml/zen_server/feature_gate/zenml_cloud_feature_gate.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/rbac/rbac_sql_zen_store.py
  src/zenml/zen_server/routers/run_templates_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3664 Specify end date for template runs that failed during spinup
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3644 Make Kubernetes job cleanup options configurable
  docs/book/component-guide/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
Labels: enhancement, internal

#3665 Dashboard features documentation (#3662)
  .gitignore
  docs/book/.gitbook/assets/dashboard-v2-artifact-viz.png
  docs/book/.gitbook/assets/dashboard-v2-component-registration.png
  docs/book/.gitbook/assets/dashboard-v2-experiment-table.png
  docs/book/.gitbook/assets/dashboard-v2-integration-viz.png
  docs/book/.gitbook/assets/dashboard-v2-model-versions.png
  docs/book/.gitbook/assets/dashboard-v2-org-structure.png
  docs/book/.gitbook/assets/dashboard-v2-parallel-coords.png
  docs/book/.gitbook/assets/dashboard-v2-pipeline-dag.png
  docs/book/.gitbook/assets/dashboard-v2-pipeline-history.png
  docs/book/.gitbook/assets/dashboard-v2-stack-management.png
  docs/book/.gitbook/assets/dashboard-v2-step-logs.png
  docs/book/how-to/dashboard/dashboard-features.md
  docs/book/toc.md
Labels: documentation, internal

#3292 Pyproject.toml support for DockerSettings
  docs/book/how-to/containerization/containerization.md
  src/zenml/config/build_configuration.py
  src/zenml/config/docker_settings.py
  src/zenml/pipelines/build_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal

#3655 Utilizing cascading tags for cached step runs
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/utils/tag_utils.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/utils/test_tag_utils.py
Labels: enhancement, internal, run-slow-ci

#3671 Adding 0.82.0 to the legacy docs
  docs/book/reference/legacy-docs.md
Labels: documentation, internal

#3672 Adding 0.82.0 to the legacy docs (#3671)
  docs/book/reference/legacy-docs.md
Labels: internal, backport

#3666 New deployment scenarios
  docs/book/.gitbook/assets/cloud_architecture_scenario_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1_2.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2.png
  docs/book/component-guide/model-deployers/mlflow.md
  docs/book/getting-started/system-architectures.md
Labels: documentation, internal

#3674 Backporting quickstart and docs updates
  docs/book/.gitbook/assets/cloud_architecture_scenario_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1_1.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_1_2.png
  docs/book/.gitbook/assets/cloud_architecture_scenario_2.png
  docs/book/component-guide/model-deployers/mlflow.md
  docs/book/getting-started/system-architectures.md
  examples/quickstart/README.md
Labels: internal, backport

#3682 Fix stack component docs
  docs/book/component-guide/artifact-stores/custom.md
  docs/book/component-guide/contribute/custom-stack-component.md
Labels: documentation, internal, codex

#3679 Fix service connector docs example
  docs/book/how-to/stack-components/service_connectors.md
Labels: documentation, internal, codex

#3677 Fix YAML extension check
  src/zenml/utils/yaml_utils.py
  tests/unit/utils/test_yaml_utils.py
Labels: bug, internal, run-slow-ci, codex

#3678 Fix typos, bugs, and improve test precision
  scripts/find_orphaned_assets.py
  src/zenml/config/schedule.py
  src/zenml/services/local/local_service.py
  tests/unit/utils/test_io_utils.py
Labels: documentation, internal, run-slow-ci, codex

#3684 Performance boost fix: don't fetch entire pipeline run to verify pipeline API token validity
  src/zenml/zen_server/auth.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3685 Async wrapper for FastAPI endpoints to run serialization in event loop
  src/zenml/zen_server/routers/actions_endpoints.py
  src/zenml/zen_server/routers/artifact_endpoint.py
  src/zenml/zen_server/routers/artifact_version_endpoints.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/code_repositories_endpoints.py
  src/zenml/zen_server/routers/devices_endpoints.py
  src/zenml/zen_server/routers/event_source_endpoints.py
  src/zenml/zen_server/routers/flavors_endpoints.py
  src/zenml/zen_server/routers/logs_endpoints.py
  src/zenml/zen_server/routers/model_versions_endpoints.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/pipeline_builds_endpoints.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/plugin_endpoints.py
  src/zenml/zen_server/routers/projects_endpoints.py
  src/zenml/zen_server/routers/run_metadata_endpoints.py
  src/zenml/zen_server/routers/run_templates_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/routers/schedule_endpoints.py
  src/zenml/zen_server/routers/secrets_endpoints.py
  src/zenml/zen_server/routers/server_endpoints.py
  src/zenml/zen_server/routers/service_accounts_endpoints.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_server/routers/service_endpoints.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
  src/zenml/zen_server/routers/stacks_endpoints.py
  src/zenml/zen_server/routers/steps_endpoints.py
  src/zenml/zen_server/routers/tag_resource_endpoints.py
  src/zenml/zen_server/routers/tags_endpoints.py
  src/zenml/zen_server/routers/triggers_endpoints.py
  src/zenml/zen_server/routers/users_endpoints.py
  src/zenml/zen_server/routers/webhook_endpoints.py
  src/zenml/zen_server/utils.py
Labels: enhancement, internal, run-slow-ci

#3676 Don't log parent image digest warning if build is skipped
  src/zenml/config/build_configuration.py
Labels: enhancement, internal

#3687 Convert string to raw to avoid warnings in python 3.12+
  src/zenml/integrations/hyperai/orchestrators/hyperai_orchestrator.py
Labels: enhancement

#3670 Use correct artifact store for nested materializers
  src/zenml/materializers/built_in_materializer.py
Labels: bug, internal

#3691 Tiny Discord docs fix
  docs/book/component-guide/alerters/discord.md
Labels: documentation, internal

#3668 Store validated config with converted types in DB
  src/zenml/client.py
  src/zenml/zen_server/routers/stack_components_endpoints.py
Labels: bug, internal

#3686 Added zenml codespace env detection
  src/zenml/enums.py
  src/zenml/environment.py
Labels: enhancement, internal

#3694 Fix setuptools vulnerabilities and switch to UV as the DockerSettings default
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  docs/book/how-to/containerization/containerization.md
  src/zenml/config/docker_settings.py
Labels: enhancement, internal

#3693 Improve alerter documentation with comprehensive ask step coverage
  docs/book/component-guide/alerters/README.md
  docs/book/component-guide/alerters/custom.md
  docs/book/component-guide/alerters/discord.md
  docs/book/component-guide/alerters/slack.md
Labels: documentation, internal

#3680 Add comprehensive agent guidelines with `AGENTS.md` and `CLAUDE.md`
  .gitignore
  AGENTS.md
  CLAUDE.md
  docs/book/component-guide/artifact-stores/custom.md
  docs/book/component-guide/contribute/custom-stack-component.md
Labels: documentation, internal, codex

#3690 Performance test utilities, stats and stress test pipeline updates
  docker/zenml-server-dev.Dockerfile
  examples/stress-test/run.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3697 Fix GCP service connector expiry
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/service_connectors/gcp_service_connector.py
Labels: bug, internal

#3699 Fix trivy image scanning GitHub actions
  .github/workflows/trivy-zenml-core.yml
  .github/workflows/trivy-zenserver.yml
Labels: bug, internal

#3703 Add Caching in Kubernetes orchestrator entrypoint
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/orchestrators/cache_utils.py
Labels: enhancement, internal

#3704 New Pro onboarding
  src/zenml/enums.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3708 Project consistency fixes for `Model` and `ModelVersionResponse`
  src/zenml/model/model.py
  src/zenml/models/v2/core/model_version.py
  tests/unit/models/test_model_models.py
Labels: bug, internal

#3612 Update Skypilot orchestrator settings and features
  docs/book/component-guide/orchestrators/skypilot-vm.md
  scripts/install-zenml-dev.sh
  src/zenml/integrations/skypilot/flavors/skypilot_orchestrator_base_vm_config.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_base_vm_orchestrator.py
  src/zenml/integrations/skypilot/orchestrators/skypilot_orchestrator_entrypoint.py
  src/zenml/integrations/skypilot/utils.py
  src/zenml/integrations/skypilot_aws/__init__.py
  src/zenml/integrations/skypilot_azure/__init__.py
  src/zenml/integrations/skypilot_gcp/__init__.py
  src/zenml/integrations/skypilot_kubernetes/__init__.py
  src/zenml/integrations/skypilot_lambda/__init__.py
  tests/integration/integrations/skypilot/__init__.py
  tests/integration/integrations/skypilot/orchestrators/__init__.py
  tests/integration/integrations/skypilot/orchestrators/test_skypilot_orchestrator.py
Labels: enhancement, internal, run-slow-ci
