Repository zenml-io/zenml, pull requests merged in 2025-10, with the labels that each got.

#4013 Follow up fixes for deployments
  src/zenml/artifact_stores/base_artifact_store.py
  src/zenml/artifacts/utils.py
  src/zenml/cli/deployment.py
  src/zenml/cli/utils.py
  src/zenml/constants.py
  src/zenml/deployers/containerized_deployer.py
  src/zenml/deployers/docker/docker_deployer.py
  src/zenml/deployers/server/runtime.py
  src/zenml/deployers/server/service.py
  src/zenml/deployers/utils.py
  src/zenml/materializers/in_memory_materializer.py
  src/zenml/orchestrators/output_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/orchestrators/utils.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/utils/networking_utils.py
  src/zenml/zen_stores/schemas/deployment_schemas.py
  tests/unit/deployers/server/test_runtime.py
  tests/unit/deployers/server/test_service_outputs.py
  tests/unit/materializers/test_in_memory_materializer.py
Labels: bug, internal, run-slow-ci

#4002 Fixing race conditions for tags
  src/zenml/cli/tag.py
  src/zenml/client.py
  src/zenml/utils/tag_utils.py
  src/zenml/zen_server/routers/tags_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
  src/zenml/zen_stores/zen_store_interface.py
  tests/integration/functional/test_client.py
  tests/integration/functional/utils/test_tag_utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: internal, breaking-change, run-slow-ci

#4017 Document pipeline deployments and deployers
  docs/book/component-guide/.gitbook/assets/deployer.png
  docs/book/component-guide/component-guide.md
  docs/book/component-guide/deployers/README.md
  docs/book/component-guide/deployers/aws-app-runner.md
  docs/book/component-guide/deployers/docker.md
  docs/book/component-guide/deployers/gcp-cloud-run.md
  docs/book/component-guide/toc.md
  docs/book/how-to/deployment/deployment.md
  docs/book/how-to/infrastructure-deployment/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/stack-components/stack_components.md
  docs/book/toc.md
  src/zenml/cli/utils.py
  src/zenml/deployers/__init__.py
Labels: documentation, internal

#4023 Snapshot docs
  docs/book/.gitbook/assets/create-snapshot-1.png
  docs/book/.gitbook/assets/create-snapshot-2.png
  docs/book/.gitbook/assets/run-snapshot.png
  docs/book/.gitbook/assets/run-templates-create-1.png
  docs/book/.gitbook/assets/run-templates-create-2.png
  docs/book/.gitbook/assets/run-templates-run-1.png
  docs/book/.gitbook/assets/run-templates.gif
  docs/book/.gitbook/assets/snapshot-run-dag.png
  docs/book/api-docs/pro-api/pro-api/getting-started.md
  docs/book/getting-started/core-concepts.md
  docs/book/getting-started/hello-world.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/hierarchy.md
  docs/book/getting-started/zenml-pro/projects.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/getting-started/zenml-pro/workspaces.md
  docs/book/how-to/artifacts/materializers.md
  docs/book/how-to/manage-zenml-server/best-practices-upgrading-zenml.md
  docs/book/how-to/manage-zenml-server/upgrade-zenml-server.md
  docs/book/how-to/snapshots/snapshots.md
  docs/book/how-to/steps-pipelines/advanced_features.md
  docs/book/how-to/steps-pipelines/configuration.md
  docs/book/how-to/tags/tags.md
  docs/book/how-to/templates/templates.md
  docs/book/sdk-docs/example-usages.md
  docs/book/toc.md
  docs/book/user-guide/best-practices/quick-wins.md
  docs/book/user-guide/tutorial/trigger-pipelines-from-external-systems.md
Labels: documentation, internal

#4035 Better CLI error messages
  src/zenml/cli/artifact.py
  src/zenml/cli/authorized_device.py
  src/zenml/cli/code_repository.py
  src/zenml/cli/deployment.py
  src/zenml/cli/integration.py
  src/zenml/cli/model.py
  src/zenml/cli/pipeline.py
  src/zenml/cli/project.py
  src/zenml/cli/server.py
  src/zenml/cli/service_accounts.py
  src/zenml/cli/service_connectors.py
  src/zenml/cli/stack.py
  src/zenml/cli/stack_components.py
  src/zenml/cli/tag.py
  src/zenml/cli/user_management.py
  src/zenml/cli/utils.py
Labels: internal

#4039 Prevent MLX integration install on Intel Macs
  pyproject.toml
  src/zenml/integrations/mlx/__init__.py
  tests/integration/integrations/mlx/test_mlx_array_materializer.py
Labels: bug, internal, run-slow-ci

#3990 Feature:3973 Extend list pipeline filters
  src/zenml/client.py
  src/zenml/models/v2/core/pipeline.py
  tests/integration/functional/pipelines/test_multi_user_crud.py
  tests/unit/models/test_pipeline_models.py
Labels: enhancement, run-slow-ci
