Repository zenml-io/zenml, pull requests merged in 2025-04, with the labels that each got.

#3446 Relaxing the `mlflow` dependency
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/mlflow/model_registries/mlflow_model_registry.py
Labels: enhancement, internal, run-slow-ci

#3487 Add two mini-tutorials
  .gitignore
  docs/book/.gitbook/assets/pipeline-schedules-list.png
  docs/book/how-to/data-artifact-management/handle-data-artifacts/tagging.md
  docs/book/user-guide/toc.md
  docs/book/user-guide/tutorials/managing-scheduled-pipelines.md
  docs/book/user-guide/tutorials/organizing-pipelines-and-models.md
Labels: internal, backport

#3486 Adding step name to console logs
  docs/book/how-to/control-logging/disable-step-names-in-logs.md
  docs/book/toc.md
  src/zenml/constants.py
  src/zenml/logging/step_logging.py
Labels: enhancement, internal, run-slow-ci

#3493 Fix yanked fsspec pip resolution issue
  pyproject.toml
  src/zenml/client.py
  src/zenml/integrations/s3/__init__.py
  src/zenml/integrations/wandb/flavors/wandb_experiment_tracker_flavor.py
Labels: bug, internal, run-slow-ci

#3484 Fixed some docs here and there
  docs/book/.gitbook/assets/artifact_visualization_dashboard (1).png
  docs/book/.gitbook/assets/cloud_architecture_self_hosted_detailed (1).png
  docs/book/.gitbook/assets/expectation-suite (1).png
  docs/book/.gitbook/assets/validation-result (1).png
  docs/book/api-docs/.gitbook/assets/workspace_url.png
  docs/book/api-docs/README.md
  docs/book/api-docs/oss-api/oss-api/README.md
  docs/book/api-docs/oss-api/oss-api/getting-started.md
  docs/book/api-docs/pro-api/pro-api/README.md
  docs/book/api-docs/pro-api/pro-api/getting-started.md
  docs/book/api-docs/toc.md
  docs/book/component-guide/component-guide.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/hierarchy.md
  docs/book/getting-started/zenml-pro/organization.md
  docs/book/getting-started/zenml-pro/pro-api.md
  docs/book/getting-started/zenml-pro/projects.md
  docs/book/getting-started/zenml-pro/roles.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/getting-started/zenml-pro/teams.md
  docs/book/getting-started/zenml-pro/toc.md
  docs/book/getting-started/zenml-pro/workspaces.md
  docs/book/how-to/pipeline-development/build-pipelines/schedule-a-pipeline.md
  docs/book/how-to/trigger-pipelines/use-templates-rest-api.md
  docs/book/sdk-docs/README.md
  docs/book/sdk-docs/client.md
  docs/book/sdk-docs/toc.md
  docs/book/toc.md
  docs/book/user-guide/llmops-guide/finetuning-llms/deploying-finetuned-models.md
Labels: documentation, internal

#3491 Update error message for setting pipeline parameters via API
  src/zenml/pipelines/run_utils.py
Labels: enhancement, internal

#3492 Fix the service connector list-resources endpoint and CLI command
  src/zenml/models/v2/core/service_connector.py
  src/zenml/zen_server/routers/service_connectors_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: bug, internal, run-slow-ci

#3494 Add a sample visualization for Pandas materializer
  docs/book/how-to/data-artifact-management/handle-data-artifacts/handle-custom-data-types.md
  src/zenml/integrations/pandas/materializers/pandas_materializer.py
  tests/integration/integrations/pandas/test_pandas_materializer.py
Labels: enhancement, internal

#3489 Fix tutorials + small improvements to docs
  docs/book/user-guide/.gitbook/assets/pipeline-schedules-list.png
  docs/book/user-guide/README.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/evaluating-finetuned-embeddings.md
  docs/book/user-guide/llmops-guide/finetuning-embeddings/finetuning-embeddings-with-sentence-transformers.md
  docs/book/user-guide/production-guide/ci-cd.md
  docs/book/user-guide/production-guide/remote-storage.md
  docs/book/user-guide/toc.md
  docs/book/user-guide/tutorial/managing-scheduled-pipelines.md
  docs/book/user-guide/tutorial/organizing-pipelines-and-models.md
  docs/book/user-guide/tutorials/README.md
Labels: documentation, internal

#3472 Upgrading pydantic to 2.11
  .github/workflows/performance-profiling.yml
  examples/e2e_nlp/.copier-answers.yml
  pyproject.toml
  src/zenml/config/step_configurations.py
  src/zenml/integrations/mlflow/__init__.py
  src/zenml/integrations/mlflow/services/mlflow_deployment.py
  src/zenml/integrations/seldon/services/seldon_deployment.py
  src/zenml/integrations/vllm/services/vllm_deployment.py
  src/zenml/model/model.py
  src/zenml/models/__init__.py
  src/zenml/utils/secret_utils.py
Labels: enhancement, internal, run-slow-ci

#3503 Small run template improvements
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3504 Move uv env var to constants
  src/zenml/constants.py
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3500 Add hidden option for run templates
  src/zenml/client.py
  src/zenml/models/v2/core/run_template.py
  src/zenml/zen_stores/migrations/versions/6611d4bcc95b_add_hidden_option_for_templates.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
Labels: enhancement, internal, run-slow-ci

#3509 Fix security check for poetry
  src/zenml/cli/integration.py
Labels: bug, internal, run-slow-ci

#3512 Minor auth improvement
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
Labels: internal

#3496 Added a Path materializer to upload directories and files
  docs/book/how-to/data-artifact-management/handle-data-artifacts/handle-custom-data-types.md
  docs/book/how-to/data-artifact-management/handle-data-artifacts/pass-files-through-steps.md
  docs/book/toc.md
  src/zenml/constants.py
  src/zenml/materializers/__init__.py
  src/zenml/materializers/path_materializer.py
  tests/unit/materializers/test_path_materializer.py
Labels: enhancement, internal

#3518 Avoid extra newlines in logs
  src/zenml/logging/step_logging.py
Labels: fix

#3519 Use step ID instead of name in step logs
  src/zenml/orchestrators/step_launcher.py
Labels: enhancement, internal

#3508 Fix artifact control plane vs model control plane GIF links in docs
  docs/book/.gitbook/assets/mcp_walkthrough.gif
  docs/book/getting-started/zenml-pro/README.md
  docs/book/how-to/model-management-metrics/model-control-plane/README.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  docs/book/user-guide/starter-guide/track-ml-models.md
Labels: documentation, internal

#3521 Adding 0.80.1 to the legacy docs
  docs/book/reference/legacy-docs.md
Labels: documentation, internal

#3522 Adding 0.80.1 to the legacy docs
  docs/book/reference/legacy-docs.md
Labels: internal, backport

#3517 Adding 0.80.2 to the migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal

#3516 Enabling the `greatexpectations` test again
  tests/integration/examples/test_great_expectations.py
Labels: bug, internal

#3520 Add save_visualizations method to materializers
  src/zenml/materializers/built_in_materializer.py
Labels: enhancement, internal

#3495 Add triggering pipelines mini-tutorial
  docs/book/user-guide/toc.md
  docs/book/user-guide/tutorial/trigger-pipelines-from-external-systems.md
  src/zenml/cli/__init__.py
Labels: documentation, internal

#3514 ZenML artifact store provisioning scripts for AWS/GCP/Azure
  infra/scripts/aws-artifact-store-setup.sh
  infra/scripts/azure-artifact-store-setup.sh
  infra/scripts/gcp-artifact-store-setup.sh
Labels: enhancement, internal

#3528 Improve SDK Client documentation with thematic grouping
  docs/book/sdk-docs/client.md
Labels: documentation, internal

#3525 Track stack creation and pipeline run with remote artifact store for onboarding state
  src/zenml/enums.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3530 Add Kubernetes schedule documentation and fix heading hierarchy
  docs/book/component-guide/orchestrators/kubernetes.md
Labels: documentation, internal

#3534 Use step invocation ID in run template error message
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3535 Prevent path traversal attacks during file extraction
  src/zenml/materializers/path_materializer.py
  src/zenml/utils/io_utils.py
Labels: enhancement, internal, run-slow-ci

#3523 Implement failure retries and pending timeouts for the k8s orchestrator pod
  src/zenml/integrations/kubernetes/flavors/kubernetes_step_operator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
Labels: bug, internal, run-slow-ci

#3507 Add endpoint to download artifact data
  src/zenml/artifacts/utils.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/download_utils.py
  src/zenml/zen_server/routers/artifact_version_endpoints.py
Labels: enhancement, internal, run-slow-ci

#3461 Enable resource sharing for teams and external users
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/rbac/rbac_interface.py
  src/zenml/zen_server/rbac/utils.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
  src/zenml/zen_server/routers/users_endpoints.py
Labels: enhancement, internal, run-slow-ci

#3536 Add support for custom job parameters in Vertex orchestrator
  docs/book/component-guide/orchestrators/vertex.md
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/gcp/vertex_custom_job_parameters.py
Labels: enhancement, internal

#3526 Add configurable workload token expiration leeway
  src/zenml/constants.py
  src/zenml/login/credentials_store.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/download_utils.py
  src/zenml/zen_server/jwt.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
  tests/unit/zen_server/test_jwt.py
Labels: enhancement, internal, run-slow-ci

#3540 Fix llms.txt docs
  .github/workflows/docs_summarization_submit.yml
  docs/book/reference/llms-txt.md
  scripts/upload_to_huggingface.py
Labels: documentation, internal

#3498 Store client-side pipeline run logs in the artifact store
  docs/book/.gitbook/assets/zenml_pipeline_run_logs.png
  docs/book/how-to/control-logging/enable-or-disable-logs-storing.md
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/constants.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  src/zenml/logging/step_logging.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/pipelines/pipeline_context.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/pipelines/run_utils.py
  src/zenml/zen_server/routers/pipeline_deployments_endpoints.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/steps/test_logging.py
Labels: enhancement, internal, run-slow-ci

#3541 Add missing vertex orchestrator dependencies to server image
  pyproject.toml
Labels: bug, internal

#3542 Resolve pydantic 2.11 deprecation warnings
  src/zenml/cli/utils.py
  src/zenml/config/global_config.py
  src/zenml/models/v2/base/base.py
  src/zenml/models/v2/base/filter.py
  src/zenml/steps/utils.py
Labels: enhancement, internal, run-slow-ci

#3547 Adding 0.80.2 to legacy docs
  docs/book/reference/legacy-docs.md
Labels: enhancement, internal

#3549 adding 0.80.2 to legacy docs (#3547)
  docs/book/reference/legacy-docs.md
Labels: internal, backport

#3546 Add 0.81.0 to migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal

#3550 Adjusted github code repo regex pattern matching to work in more cases
  src/zenml/integrations/github/code_repositories/github_code_repository.py
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
Labels: bug, internal

#3585 Fixed broken absolute links and brought back some sections
  .gitbook.yaml
  RELEASE_NOTES.md
  docs/book/component-guide/contribute/custom-stack-component.md
  docs/book/component-guide/experiment-trackers/comet.md
  docs/book/component-guide/experiment-trackers/mlflow.md
  docs/book/component-guide/experiment-trackers/vertexai.md
  docs/book/component-guide/experiment-trackers/wandb.md
  docs/book/component-guide/model-deployers/seldon.md
  docs/book/component-guide/model-registries/README.md
  docs/book/component-guide/orchestrators/README.md
  docs/book/component-guide/orchestrators/airflow.md
  docs/book/component-guide/orchestrators/custom.md
  docs/book/component-guide/orchestrators/databricks.md
  docs/book/component-guide/orchestrators/hyperai.md
  docs/book/component-guide/orchestrators/kubeflow.md
  docs/book/component-guide/orchestrators/kubernetes.md
  docs/book/component-guide/orchestrators/lightning.md
  docs/book/component-guide/orchestrators/local-docker.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/component-guide/orchestrators/tekton.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/step-operators/README.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/component-guide/step-operators/custom.md
  docs/book/component-guide/step-operators/kubernetes.md
  docs/book/component-guide/step-operators/modal.md
  docs/book/component-guide/step-operators/sagemaker.md
  docs/book/component-guide/step-operators/spark-kubernetes.md
  docs/book/component-guide/step-operators/vertex.md
  docs/book/getting-started/deploying-zenml/deploy-with-helm.md
  docs/book/how-to/artifacts/materializers.md
  docs/book/how-to/containerization/containerization.md
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/best-practices.md
  docs/book/how-to/manage-zenml-server/migration-guide/migration-zero-forty.md
  docs/book/how-to/manage-zenml-server/migration-guide/migration-zero-twenty.md
  docs/book/how-to/steps-pipelines/configuration.md
  docs/book/how-to/templates/templates.md
  docs/book/user-guide/best-practices/keep-your-dashboard-server-clean.md
  docs/book/user-guide/best-practices/set-up-your-repository.md
  docs/book/user-guide/llmops-guide/finetuning-llms/finetuning-with-accelerate.md
  docs/book/user-guide/production-guide/ci-cd.md
  docs/book/user-guide/production-guide/configure-pipeline.md
  docs/book/user-guide/production-guide/end-to-end.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
  docs/book/user-guide/tutorial/fetching-pipelines.md
  docs/book/user-guide/tutorial/managing-scheduled-pipelines.md
  docs/book/user-guide/tutorial/run-remote-notebooks.md
  docs/link_checker.py
Labels: documentation, internal

#3587 Fix listing run templates
  src/zenml/client.py
Labels: bug, internal

#3586 Don't log missing active project warnings preemtively
  scripts/check_broken_links.py
  src/zenml/cli/server.py
  src/zenml/zen_stores/base_zen_store.py
Labels: enhancement, internal

#3551 Update scikit-learn requirement in SklearnIntegration
  src/zenml/integrations/sklearn/__init__.py
  tests/integration/examples/mlflow/steps/dynamic_importer_step.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3584 Small docs fixes
  docs/book/.gitbook/assets/workspace_url.png
  docs/book/component-guide/toc.md
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-01.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-02.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-03.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-04.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-05.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-06.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-07.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-08.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-09.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-10.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-11.png
  docs/book/getting-started/zenml-pro/.gitbook/assets/on-prem-12.png
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/how-to/containerization/containerization.md
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/README.md
  docs/book/how-to/infrastructure-deployment/infrastructure-as-code/terraform-stack-management.md
  docs/book/how-to/infrastructure-deployment/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/models/models.md
  docs/book/how-to/stack-components/service_connectors.md
  docs/book/how-to/steps-pipelines/configuration.md
  docs/book/how-to/steps-pipelines/logging.md
  docs/book/how-to/steps-pipelines/scheduling.md
  docs/book/how-to/steps-pipelines/steps_and_pipelines.md
  docs/book/user-guide/best-practices/iac.md
  docs/book/user-guide/toc.md
Labels: documentation, internal

#3601 More small docs fixes
  docs/book/how-to/manage-zenml-server/upgrade-zenml-server.md
  docs/book/how-to/templates/templates.md
Labels: documentation, internal

#3604 Add docs for run template TTL env var
  docs/book/getting-started/zenml-pro/self-hosted.md
Labels: documentation, internal

#3589 Make runner timeout easily configurable
  src/zenml/constants.py
  src/zenml/zen_server/template_execution/utils.py
Labels: enhancement, internal

#3605 Disable default project behaviour for pro workspaces
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3532 Update NumPy integration to work with 1.x and 2.x versions of the library
  src/zenml/integrations/evidently/__init__.py
  src/zenml/integrations/numpy/__init__.py
  src/zenml/integrations/numpy/materializers/numpy_materializer.py
  tests/integration/integrations/numpy/test_numpy_materializer.py
Labels: enhancement, internal, dependencies, run-slow-ci

#3607 Invalidate the build when parent dockerfile changes
  src/zenml/config/build_configuration.py
Labels: bug, internal

#3609 Ignore existing directories during code download
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/utils/code_utils.py
Labels: enhancement, internal

#3606 Max parallelism option for kubernetes orchestrator
  docs/book/component-guide/orchestrators/kubernetes.md
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/orchestrators/dag_runner.py
Labels: enhancement, internal

#3591 Add option to specify pod name prefix and add scheduler
  docs/book/component-guide/orchestrators/kubernetes.md
  scripts/find_orphaned_assets.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/integrations/kubernetes/orchestrators/manifest_utils.py
  src/zenml/integrations/kubernetes/pod_settings.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
Labels: enhancement, internal

#3610 Fix CVE-2024-6345 CVE-2024-6345 CVE-2022-40897 and CVE-2025-0508
  docker/base.Dockerfile
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
  pyproject.toml
  src/zenml/integrations/aws/__init__.py
Labels: bug, internal, dependencies, run-slow-ci

#3616 Docs: Starter guide fixes
  docs/book/user-guide/starter-guide/cache-previous-executions.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
Labels: documentation

#3613 Add option to set a private service connect to the Vertex AI orchestrator
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/integrations/gcp/orchestrators/vertex_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#3539 Add Pandas custom data type error handling and logging
  src/zenml/integrations/pandas/materializers/pandas_materializer.py
Labels: enhancement, internal

#3608 Store list of python packages
  src/zenml/environment.py
  src/zenml/models/v2/core/pipeline_deployment.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_stores/schemas/pipeline_deployment_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/models/test_pipeline_run.py
  tests/integration/integrations/gcp/experiment_trackers/test_vertex_experiment_tracker.py
  tests/unit/pipelines/test_base_pipeline.py
Labels: enhancement, internal

#3620 Allow (and ignore) extra attributes in all ZenML models
  src/zenml/config/docker_settings.py
  src/zenml/config/resource_settings.py
  src/zenml/config/strict_base_model.py
  src/zenml/integrations/evidently/metrics.py
  src/zenml/integrations/evidently/tests.py
  src/zenml/models/v2/core/user.py
  src/zenml/secret/base_secret.py
  src/zenml/stack/stack_component.py
  src/zenml/stack/utils.py
  src/zenml/zen_server/deploy/daemon/daemon_zen_server.py
  src/zenml/zen_server/deploy/docker/docker_zen_server.py
  src/zenml/zen_stores/secrets_stores/hashicorp_secrets_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/cli/test_stack_components.py
  tests/unit/config/test_settings_resolver.py
  tests/unit/stack/test_stack_component.py
  tests/unit/stack/test_utils.py
Labels: enhancement, internal, run-slow-ci

#3623 Utilizing uv in the quickstart dockerfiles
  docker/zenml-quickstart-dev.Dockerfile
  docker/zenml-quickstart.Dockerfile
Labels: enhancement, internal

#3626 Fixing the azure integration and marshmallow
  src/zenml/integrations/azure/__init__.py
  src/zenml/integrations/kubeflow/orchestrators/kubeflow_orchestrator.py
  src/zenml/integrations/tekton/orchestrators/tekton_orchestrator.py
Labels: bug, internal, run-slow-ci

#3630 Adding 0.81.0 to the legacy docs
  docs/book/reference/legacy-docs.md
Labels: documentation, internal

#3631 adding 0.81.0 to the legacy docs (#3630)
  docs/book/reference/legacy-docs.md
Labels: internal, backport
