Repository zenml-io/zenml, pull requests merged in 2025-09, with the labels that each got.

#3915 Delete run if model version doesn't exist during creation
  src/zenml/zen_stores/sql_zen_store.py
Labels: internal

#3900 Caching by value
  docs/book/user-guide/starter-guide/cache-previous-executions.md
  src/zenml/artifacts/utils.py
  src/zenml/config/__init__.py
  src/zenml/config/cache_policy.py
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/config/step_configurations.py
  src/zenml/materializers/base_materializer.py
  src/zenml/materializers/built_in_materializer.py
  src/zenml/materializers/pydantic_materializer.py
  src/zenml/materializers/structured_string_materializer.py
  src/zenml/materializers/uuid_materializer.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/orchestrators/cache_utils.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/pipelines/pipeline_decorator.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
  src/zenml/zen_stores/migrations/versions/aae4eed923b5_add_content_hash_column.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  tests/integration/functional/artifacts/test_artifacts_linage.py
  tests/unit/orchestrators/test_cache_utils.py
Labels: enhancement, internal

#3923 Prevent stopping runs without orchestrator run id
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/base_orchestrator.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3918 Run template config improvements
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_run_configuration.py
  src/zenml/config/step_configurations.py
  src/zenml/pipelines/run_utils.py
  src/zenml/steps/base_step.py
  src/zenml/zen_server/template_execution/utils.py
  src/zenml/zen_stores/template_utils.py
Labels: enhancement, internal

#3932 Fix unnecessary code upload
  src/zenml/pipelines/build_utils.py
Labels: bug, internal

#3935 Switch to uv as default package installer
  docs/book/component-guide/orchestrators/skypilot-vm.md
  docs/book/how-to/containerization/containerization.md
  docs/book/user-guide/tutorial/trigger-pipelines-from-external-systems.md
  src/zenml/config/docker_settings.py
Labels: internal, breaking-change, cleanup

#3944 Upgrade pydantic
  pyproject.toml
  src/zenml/services/container/container_service_endpoint.py
  src/zenml/services/local/local_service_endpoint.py
Labels: internal, run-slow-ci

#3957 Dedent exception info traceback
  src/zenml/utils/exception_utils.py
Labels: enhancement, internal

#3966 Backport: Fix cache policy docs formatting (#3965)
  docs/book/user-guide/starter-guide/cache-previous-executions.md
Labels: internal, backport

#3964 Bugfix for duplicated log records for exceptions
  src/zenml/logger.py
Labels: bug, internal

#3972 Track pipeline output spec and schema
  src/zenml/config/compiler.py
  src/zenml/config/pipeline_spec.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/steps/entrypoint_function_utils.py
Labels: enhancement, internal

#3916 Slimmer base package
  .github/workflows/base-package-functionality.yml
  .github/workflows/ci-slow.yml
  .github/workflows/linting.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/update-templates-to-examples.yml
  docs/book/getting-started/hello-world.md
  docs/book/getting-started/installation.md
  docs/book/user-guide/best-practices/project-templates.md
  examples/e2e/.copier-answers.yml
  examples/e2e/requirements.txt
  examples/llm_finetuning/.copier-answers.yml
  examples/llm_finetuning/requirements.txt
  pyproject.toml
  src/zenml/cli/__init__.py
  src/zenml/cli/base.py
  src/zenml/cli/login.py
  src/zenml/cli/server.py
  src/zenml/config/global_config.py
  src/zenml/integrations/airflow/flavors/airflow_orchestrator_flavor.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/core/api_key.py
  src/zenml/models/v2/core/device.py
  src/zenml/models/v2/core/model_version_pipeline_run.py
  src/zenml/models/v2/core/service.py
  src/zenml/models/v2/core/stack.py
  src/zenml/orchestrators/containerized_orchestrator.py
  src/zenml/orchestrators/local/local_orchestrator.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3997 Document WhyLabs shutdown in whylogs integration
  docs/book/component-guide/data-validators/README.md
  docs/book/component-guide/data-validators/whylogs.md
  src/zenml/cli/integration.py
Labels: internal, run-slow-ci, codex

#4014 Store visualizations for pydantic materializer
  src/zenml/materializers/pydantic_materializer.py
Labels: enhancement, internal
