Repository zenml-io/zenml, pull requests merged in 2025-07, with the labels that each got.

#3788 Add `llm-complete-guide` project to user guides
  docs/book/user-guide/.gitbook/assets/llm-complete-guide.jpg
  docs/book/user-guide/README.md
Labels: documentation, internal

#3774 Easier option to enable a step operator/experiment tracker for a step
  docs/book/component-guide/step-operators/README.md
  docs/book/component-guide/step-operators/azureml.md
  docs/book/component-guide/step-operators/kubernetes.md
  docs/book/component-guide/step-operators/modal.md
  docs/book/component-guide/step-operators/sagemaker.md
  docs/book/component-guide/step-operators/spark-kubernetes.md
  docs/book/component-guide/step-operators/vertex.md
  docs/book/how-to/steps-pipelines/configuration.md
  docs/book/user-guide/tutorial/run-remote-notebooks.md
  src/zenml/config/compiler.py
  src/zenml/config/step_configurations.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
  src/zenml/integrations/azure/step_operators/azureml_step_operator.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
  src/zenml/integrations/kubernetes/step_operators/kubernetes_step_operator.py
  src/zenml/integrations/modal/step_operators/modal_step_operator.py
  src/zenml/integrations/spark/step_operators/kubernetes_step_operator.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/stack/stack.py
Labels: enhancement, internal, breaking-change, planned

#3797 Always build pipeline image for Kubernetes orchestrator
  src/zenml/integrations/kubernetes/flavors/kubernetes_orchestrator_flavor.py
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator.py
  src/zenml/orchestrators/containerized_orchestrator.py
Labels: enhancement, internal

#3737 Add VSCode tutorial pipeline testing to CI
  .github/workflows/ci-slow.yml
  .github/workflows/vscode-tutorial-pipelines-test.yml
  CLAUDE.md
  scripts/test-tutorial-pipelines.sh
  tests/README.md
Labels: enhancement, CI, run-slow-ci

#3795 Update best practices for upgrading ZenML servers
  docs/book/.gitbook/assets/upgrading_zenml_gitops.png
  docs/book/.gitbook/assets/upgrading_zenml_prod_staging_env.png
  docs/book/.gitbook/assets/upgrading_zenml_stacks_env.png
  docs/book/.gitbook/assets/upgrading_zenml_staging_to_prod.png
  docs/book/how-to/manage-zenml-server/best-practices-upgrading-zenml.md
Labels: documentation, internal

#3778 Orchestrator pod logs for Kubernetes
  src/zenml/integrations/kubernetes/orchestrators/kubernetes_orchestrator_entrypoint.py
  src/zenml/logging/step_logging.py
  src/zenml/models/v2/core/logs.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/zen_server/routers/runs_endpoints.py
  src/zenml/zen_stores/migrations/versions/85289fea86ff_adding_source_to_logs.py
  src/zenml/zen_stores/schemas/logs_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci, planned

#3805 Warn if passing invalid kubernetes model data
  src/zenml/integrations/kubernetes/pod_settings.py
  src/zenml/integrations/kubernetes/serialization_utils.py
Labels: enhancement, internal

#3813 Update ZenML Pro URLs in documentation to use zenml.io/pro
  RELEASE_NOTES.md
  docs/book/api-docs/pro-api/pro-api/getting-started.md
  docs/book/component-guide/component-guide.md
  docs/book/getting-started/installation.md
  docs/book/getting-started/system-architectures.md
  docs/book/getting-started/zenml-pro/README.md
  docs/book/how-to/infrastructure-deployment/stack-deployment/deploy-a-cloud-stack-with-terraform.md
  docs/book/how-to/manage-zenml-server/using-zenml-server-in-prod.md
  docs/book/how-to/metadata/metadata.md
  docs/book/how-to/models/models.md
  docs/book/how-to/templates/templates.md
  docs/book/user-guide/best-practices/access-management.md
  docs/book/user-guide/production-guide/deploying-zenml.md
  docs/book/user-guide/tutorial/organizing-pipelines-and-models.md
  docs/book/user-guide/tutorial/trigger-pipelines-from-external-systems.md
Labels: internal

#3790 New zenml login and CLI style improvements
  src/zenml/cli/login.py
  src/zenml/cli/project.py
  src/zenml/cli/utils.py
  src/zenml/console.py
  src/zenml/logger.py
  src/zenml/login/web_login.py
Labels: enhancement, run-slow-ci, feature

#3817 Onboarding changes
  src/zenml/enums.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal

#3818 Tiny README fixes
  README.md
Labels: documentation, internal

#3820 Add docker tag sanitization
  src/zenml/pipelines/build_utils.py
  src/zenml/utils/docker_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
Labels: bug, internal

#3824 Upper limit datasets version
  examples/quickstart/requirements.txt
  examples/quickstart/requirements_aws.txt
  examples/quickstart/requirements_azure.txt
  examples/quickstart/requirements_gcp.txt
  src/zenml/integrations/huggingface/__init__.py
Labels: enhancement, internal

#3826 Add dynamic fan-out/fan-in with run templates
  docs/book/how-to/steps-pipelines/advanced_features.md
  src/zenml/enums.py
Labels: internal

#3833 Add version 0.84.0 to DB migration script
  scripts/test-migrations.sh
Labels: enhancement, internal, run-slow-ci

#3834 Remove deprecation warning in quickstart
  examples/quickstart/steps/model_trainer.py
Labels: enhancement, internal

#3836 Fix appending to DB migrations in release action
  scripts/add-migration-test-version.sh
Labels: bug, internal

#3853 Fix the retry logic and credential refresh for the Vertex step operator
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
Labels: bug, internal, planned

#3838 Collect step run exception info
  src/zenml/code_repositories/git/local_git_repository_context.py
  src/zenml/constants.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/step_run.py
  src/zenml/models/v2/misc/exception_info.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_runner.py
  src/zenml/utils/exception_utils.py
  src/zenml/zen_stores/migrations/versions/d4591f95ac07_step_exception_info.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
Labels: enhancement, internal

#3858 Block bot traffic from Segment analytics to prevent MTU quota exhaustion
  docs/mkdocs/overrides/main.html
Labels: documentation, internal

#3793 Add support for external service accounts
  docs/book/getting-started/zenml-pro/self-hosted.md
  src/zenml/client.py
  src/zenml/models/__init__.py
  src/zenml/models/v2/core/service_account.py
  src/zenml/models/v2/core/user.py
  src/zenml/models/v2/misc/external_user.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/rbac/zenml_cloud_rbac.py
  src/zenml/zen_server/routers/service_accounts_endpoints.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/migrations/versions/8d4b9ba22c1f_add_user_avatar.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci
