Repository zenml-io/zenml, pull requests merged in 2025-08, with the labels that each got.

#3876 Fix run creation deadlock
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal

#3873 Fix nonlinear scaling of pipeline compilation time
  src/zenml/config/compiler.py
Labels: bug, internal

#3878 Fix type annotations
  src/zenml/steps/base_step.py
  src/zenml/steps/step_decorator.py
Labels: bug, internal

#3882 Fix PyPI download stats badge
  README.md
Labels: documentation, internal, fix

#3880 Don't include decorator code in step cache key computation
  src/zenml/steps/base_step.py
  src/zenml/steps/decorated_step.py
  tests/unit/steps/test_base_step.py
Labels: enhancement, internal

#3890 Add an agent in production example
  README.md
  docs/book/.gitbook/assets/your_first_pipeline_analysis.png
  docs/book/.gitbook/assets/your_first_pipeline_pipeline_evaluation.png
  docs/book/.gitbook/assets/your_first_pipeline_ui.png
  docs/book/component-guide/annotators/argilla.md
  docs/book/getting-started/hello-world.md
  docs/book/getting-started/your-first-ai-pipeline.md
  docs/book/getting-started/zenml-pro/.gitbook/assets/pro-cover.png
  docs/book/toc.md
  docs/book/user-guide/.gitbook/assets/example-06.png
  docs/book/user-guide/.gitbook/assets/example-07.png
  docs/book/user-guide/README.md
  examples/minimal_agent_production/README.md
  examples/minimal_agent_production/__init__.py
  examples/minimal_agent_production/app/__init__.py
  examples/minimal_agent_production/app/main.py
  examples/minimal_agent_production/models.py
  examples/minimal_agent_production/pipelines/__init__.py
  examples/minimal_agent_production/pipelines/evaluation.py
  examples/minimal_agent_production/pipelines/production.py
  examples/minimal_agent_production/requirements.txt
  examples/minimal_agent_production/run_evaluation.py
  examples/minimal_agent_production/run_pipeline.py
  examples/minimal_agent_production/run_production.py
  examples/minimal_agent_production/static/css/evaluation.css
  examples/minimal_agent_production/static/css/main.css
  examples/minimal_agent_production/static/css/report.css
  examples/minimal_agent_production/static/images/app.png
  examples/minimal_agent_production/static/images/app_result.png
  examples/minimal_agent_production/static/images/architecture.png
  examples/minimal_agent_production/static/images/pipeline_analysis.png
  examples/minimal_agent_production/static/images/pipeline_evaluation.png
  examples/minimal_agent_production/static/js/main.js
  examples/minimal_agent_production/static/templates/index.html
  examples/minimal_agent_production/steps/__init__.py
  examples/minimal_agent_production/steps/analyze.py
  examples/minimal_agent_production/steps/evaluate.py
  examples/minimal_agent_production/steps/ingest.py
  examples/minimal_agent_production/steps/render.py
  examples/minimal_agent_production/steps/utils.py
  examples/quickstart/README.md
  pyproject.toml
Labels: internal

#3887 Fix kubernetes name sanitization
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
Labels: bug, internal

#3892 Fix SyntaxWarning in `exception_utils` regex pattern
  src/zenml/utils/exception_utils.py
  tests/unit/utils/test_exception_utils.py
Labels: bug, internal, run-slow-ci

#3895 Add ability to use a ZenML Pro API key with `zenml login`
  docs/book/.gitbook/assets/pro-service-account-auth-01.png
  docs/book/.gitbook/assets/pro-service-account-auth-02.png
  docs/book/.gitbook/assets/pro-service-accounts-01.png
  docs/book/.gitbook/assets/pro-service-accounts-02.png
  docs/book/.gitbook/assets/pro-service-accounts-03.png
  docs/book/.gitbook/assets/pro-service-accounts-04.png
  docs/book/.gitbook/assets/pro-service-accounts-05.png
  docs/book/.gitbook/assets/pro-service-accounts-06.png
  docs/book/.gitbook/assets/pro-service-accounts-07.png
  docs/book/.gitbook/assets/pro-service-accounts-08.png
  docs/book/.gitbook/assets/pro-service-accounts-09.png
  docs/book/.gitbook/assets/pro-service-accounts-10.png
  docs/book/.gitbook/assets/pro-service-accounts-11.png
  docs/book/.gitbook/assets/pro-service-accounts-12.png
  docs/book/.gitbook/assets/pro-service-accounts-13.png
  docs/book/.gitbook/assets/pro-service-accounts-14.png
  docs/book/api-docs/pro-api/pro-api/getting-started.md
  docs/book/getting-started/zenml-pro/service-accounts.md
  docs/book/getting-started/zenml-pro/toc.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-with-a-service-account.md
  src/zenml/cli/login.py
  src/zenml/cli/server.py
  src/zenml/login/credentials.py
  src/zenml/login/credentials_store.py
  src/zenml/login/pro/client.py
  src/zenml/login/pro/utils.py
  src/zenml/zen_server/routers/service_accounts_endpoints.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3907 Add docs for workload manager env vars
  docs/book/getting-started/zenml-pro/self-hosted.md
Labels: documentation, internal

#3908 Allow workspace service accounts and API keys to be created
  src/zenml/zen_server/routers/service_accounts_endpoints.py
Labels: bug, internal

#3896 Made connection docs easier to read
  docs/book/api-docs/oss-api/oss-api/getting-started.md
  docs/book/api-docs/pro-api/pro-api/getting-started.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/component-guide/service-connectors/best-security-practices.md
  docs/book/getting-started/zenml-pro/.gitbook/assets/procover.png
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/service-accounts.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/README.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-in-with-your-user-interactive.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-with-a-service-account.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-with-an-api-token.md
  docs/book/how-to/templates/templates.md
  docs/book/user-guide/tutorial/trigger-pipelines-from-external-systems.md
Labels: documentation, internal
