Repository zenml-io/zenml, pull requests merged in 2025-02, with the labels that each got.

#3332 Add support for symlinks in GH download
  src/zenml/integrations/github/code_repositories/github_code_repository.py
Labels: enhancement, internal

#3320 ZenML Helm chart improvements
  docs/book/getting-started/deploying-zenml/deploy-with-helm.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  src/zenml/zen_server/deploy/helm/README.md
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/templates/_helpers.tpl
  src/zenml/zen_server/deploy/helm/templates/custom-ca-secrets.yaml
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/templates/server-deployment.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_stores/sql_zen_store.py
Labels: enhancement, internal, run-slow-ci

#3335 Improve queries for pipelines, run templates, models and artifacts
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
Labels: enhancement, internal, run-slow-ci

#3339 Improve configured parameter detection when preparing pipeline
  src/zenml/pipelines/pipeline_definition.py
Labels: enhancement, internal

#3334 Minor fix for the Artifact filter model
  src/zenml/models/__init__.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/model_version.py
  src/zenml/models/v2/core/pipeline.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/run_template.py
Labels: bug, internal, run-slow-ci

#3342 Allow (un)installing integrations with system-wide uv installations
  src/zenml/cli/utils.py
Labels: enhancement, internal

#3344 Fix filtering by run metadata
  src/zenml/client.py
  src/zenml/models/v2/base/filter.py
  src/zenml/models/v2/core/artifact_version.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/models/v2/core/step_run.py
  tests/integration/functional/zen_stores/test_zen_store.py
Labels: bug, internal, run-slow-ci

#3351 Adding `0.74.0` to the migration tests
  scripts/test-migrations.sh
Labels: internal

#3348 Fixing the release preparation workflow
  .github/workflows/release_prepare.yml
Labels: bug, internal

#3340 Expand `fastapi` dependency range
  pyproject.toml
Labels: internal, dependencies, run-slow-ci

#3352 Document the programmatic API access options
  docs/book/.gitbook/assets/vertexai_experiment_tracker_tb.png
  docs/book/.gitbook/assets/vertexai_experiment_tracker_ui.png
  docs/book/.gitbook/assets/zenml-oss-api-token-01.png
  docs/book/.gitbook/assets/zenml-oss-api-token-02.png
  docs/book/.gitbook/assets/zenml-pro-api-token-01.png
  docs/book/.gitbook/assets/zenml-pro-api-token-02.png
  docs/book/getting-started/zenml-pro/pro-api.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-in-with-your-user-interactive.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-with-a-service-account.md
  docs/book/how-to/manage-zenml-server/connecting-to-zenml/connect-with-an-api-token.md
  docs/book/reference/api-reference.md
  docs/book/toc.md
Labels: documentation, internal

#3353 Fix some docs links
  docs/book/how-to/pipeline-development/build-pipelines/use-failure-success-hooks.md
Labels: bug, internal

#3346 [docs] Rename llms.txt file, add header and docs
  .github/workflows/docs_summarization_submit.yml
  docs/book/reference/llms-txt.md
  docs/book/toc.md
  scripts/upload_to_huggingface.py
Labels: internal

#3354 Add `llms.txt` YouTube video to docs
  docs/book/.gitbook/assets/llms-txt-thumb.png
  docs/book/reference/llms-txt.md
Labels: documentation, internal

#3356 Fix model deployers docs formatting
  docs/book/component-guide/model-deployers/bentoml.md
  docs/book/component-guide/model-deployers/model-deployers.md
Labels: documentation, internal

#3343 Get the latest artifact of a model by creation date instead of version name
  src/zenml/models/v2/core/model_version.py
  tests/unit/models/test_model_models.py
Labels: run-slow-ci

#3365 Fix GCP service connector docs
  docs/book/component-guide/container-registries/gcp.md
Labels: run-slow-ci

#3367 Allow auth method to be customized during auto-configuration of service connectors
  src/zenml/cli/service_connectors.py
Labels: bug, internal, run-slow-ci

#3358 Add some sdkdocs links
  README.md
  docs/book/user-guide/production-guide/README.md
  docs/book/user-guide/production-guide/understand-stacks.md
  docs/book/user-guide/starter-guide/README.md
  docs/book/user-guide/starter-guide/create-an-ml-pipeline.md
Labels: documentation, internal

#3366 Fix sorting when using custom fetching
  docs/book/component-guide/image-builders/kaniko.md
  src/zenml/integrations/gcp/flavors/vertex_orchestrator_flavor.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3368 Add sagemaker env settings
  docs/book/component-guide/orchestrators/sagemaker.md
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/flavors/sagemaker_step_operator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/aws/step_operators/sagemaker_step_operator.py
Labels: bug, internal, run-slow-ci

#3377 CI Linting fix
  pyproject.toml
Labels: bug, internal, run-slow-ci

#3373 Don't flush inner fsspec logs to the artifact store
  src/zenml/logging/step_logging.py
Labels: bug, internal, run-slow-ci

#3380 Bugfix for Sagemaker env variables
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal

#3382 Correct isintance check for sagemaker env variables
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: bug, internal

#3385 Update devel dockerfiles to make rebuilds faster
  docker/zenml-dev.Dockerfile
  docker/zenml-server-dev.Dockerfile
Labels: enhancement, internal
