Repository zenml-io/zenml, pull requests merged in 2025-01, with the labels that each got.

#3267 Include service connector requirements in custom flavor registration
  src/zenml/client.py
Labels: bug, internal

#3263 Improve the efficiency of some SQL queries
  src/zenml/models/v2/base/scoped.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/schemas/utils.py
Labels: enhancement, internal, run-slow-ci

#3275 Bump NLP template
  .github/workflows/update-templates-to-examples.yml
  examples/e2e_nlp/.copier-answers.yml
  examples/e2e_nlp/LICENSE
  examples/e2e_nlp/config.yaml
  examples/e2e_nlp/gradio/__init__.py
  examples/e2e_nlp/pipelines/__init__.py
  examples/e2e_nlp/pipelines/deploying.py
  examples/e2e_nlp/pipelines/promoting.py
  examples/e2e_nlp/pipelines/training.py
  examples/e2e_nlp/requirements.txt
  examples/e2e_nlp/run.py
  examples/e2e_nlp/steps/__init__.py
  examples/e2e_nlp/steps/alerts/__init__.py
  examples/e2e_nlp/steps/alerts/notify_on.py
  examples/e2e_nlp/steps/dataset_loader/__init__.py
  examples/e2e_nlp/steps/dataset_loader/data_loader.py
  examples/e2e_nlp/steps/deploying/__init__.py
  examples/e2e_nlp/steps/deploying/huggingface_deployment.py
  examples/e2e_nlp/steps/deploying/local_deployment.py
  examples/e2e_nlp/steps/deploying/save_model.py
  examples/e2e_nlp/steps/deploying/skypilot_deployment.py
  examples/e2e_nlp/steps/promotion/__init__.py
  examples/e2e_nlp/steps/promotion/promote_get_metrics.py
  examples/e2e_nlp/steps/promotion/promote_metric_compare_promoter.py
  examples/e2e_nlp/steps/register/__init__.py
  examples/e2e_nlp/steps/register/model_log_register.py
  examples/e2e_nlp/steps/tokenizer_loader/__init__.py
  examples/e2e_nlp/steps/tokenizer_loader/tokenizer_loader.py
  examples/e2e_nlp/steps/tokenzation/__init__.py
  examples/e2e_nlp/steps/tokenzation/tokenization.py
  examples/e2e_nlp/steps/training/__init__.py
  examples/e2e_nlp/steps/training/model_trainer.py
  examples/e2e_nlp/utils/misc.py
  src/zenml/cli/base.py
Labels: enhancement, internal

#3266 Fixed and improved sorting
  src/zenml/constants.py
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/artifact.py
  src/zenml/models/v2/core/model.py
  src/zenml/models/v2/core/pipeline.py
  src/zenml/models/v2/core/pipeline_run.py
  src/zenml/zen_stores/sql_zen_store.py
  tests/integration/functional/models/test_sorting.py
Labels: bug, internal, run-slow-ci

#3278 Add matplotlib visualization to ZenML dashboard
  docs/book/how-to/data-artifact-management/handle-data-artifacts/handle-custom-data-types.md
  docs/book/how-to/data-artifact-management/visualize-artifacts/creating-custom-visualizations.md
Labels: documentation, internal

#3283 Fix server spin-up integration tests
  scripts/install-zenml-dev.sh
Labels: bug, internal, run-slow-ci

#3264 On-prem Pro tenants: secure enrollment, CSRF tokens and cross-domain authorization flow
  pyproject.toml
  src/zenml/cli/login.py
  src/zenml/cli/server.py
  src/zenml/config/server_config.py
  src/zenml/constants.py
  src/zenml/login/credentials.py
  src/zenml/login/credentials_store.py
  src/zenml/login/pro/client.py
  src/zenml/login/pro/constants.py
  src/zenml/login/pro/tenant/models.py
  src/zenml/login/pro/utils.py
  src/zenml/login/server_info.py
  src/zenml/login/web_login.py
  src/zenml/models/v2/misc/auth_models.py
  src/zenml/models/v2/misc/server_models.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/cloud_utils.py
  src/zenml/zen_server/csrf.py
  src/zenml/zen_server/deploy/helm/templates/NOTES.txt
  src/zenml/zen_server/deploy/helm/templates/_environment.tpl
  src/zenml/zen_server/deploy/helm/templates/server-secret.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
  src/zenml/zen_server/feature_gate/feature_gate_interface.py
  src/zenml/zen_server/jwt.py
  src/zenml/zen_server/rbac/endpoint_utils.py
  src/zenml/zen_server/routers/auth_endpoints.py
  src/zenml/zen_server/routers/models_endpoints.py
  src/zenml/zen_server/routers/pipelines_endpoints.py
  src/zenml/zen_server/routers/stack_deployment_endpoints.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_server/utils.py
  src/zenml/zen_server/zen_server_api.py
  src/zenml/zen_stores/base_zen_store.py
  src/zenml/zen_stores/rest_zen_store.py
Labels: enhancement, internal, breaking-change, run-slow-ci

#3285 Add 0.72.0 to the migration tests
  scripts/test-migrations.sh
Labels: enhancement, internal

#3289 Fix links to Kubeflow Pipelines docs in `kubeflow.md`
  docs/book/component-guide/orchestrators/kubeflow.md
Labels: documentation

#3287 Add experiment comparison tool docs
  docs/book/.gitbook/assets/coordinates-view.png
  docs/book/.gitbook/assets/experiment_comparison_video.png
  docs/book/.gitbook/assets/table-view.png
  docs/book/how-to/model-management-metrics/track-metrics-metadata/README.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
Labels: documentation, internal

#3290 Add experiment comparison tool docs (#3287)
  docs/book/.gitbook/assets/coordinates-view.png
  docs/book/.gitbook/assets/experiment_comparison_video.png
  docs/book/.gitbook/assets/table-view.png
  docs/book/how-to/model-management-metrics/track-metrics-metadata/README.md
  docs/book/user-guide/starter-guide/manage-artifacts.md
Labels: documentation, internal, backport

#3282 Updated Slack Alerter
  docs/book/.gitbook/assets/slack-alerter-oauth-permissions.png
  docs/book/.gitbook/assets/slack-alerter-token.jpg
  docs/book/.gitbook/assets/slack-alerter-token.png
  docs/book/.gitbook/assets/slack-channel-settings.png
  docs/book/component-guide/alerters/slack.md
  src/zenml/integrations/slack/__init__.py
  src/zenml/integrations/slack/alerters/slack_alerter.py
  src/zenml/integrations/slack/flavors/slack_alerter_flavor.py
Labels: bug, internal

#3298 Remove gluon from mlflow log supression list
  src/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py
Labels: bug, internal

#3260 Vertex AI Experiment Tracker Integration
  docs/book/.gitbook/assets/vertexai_experiment_tracker_tb.png
  docs/book/.gitbook/assets/vertexai_experiment_tracker_ui.png
  docs/book/component-guide/experiment-trackers/vertexai.md
  docs/mocked_libs.json
  src/zenml/integrations/gcp/__init__.py
  src/zenml/integrations/gcp/experiment_trackers/__init__.py
  src/zenml/integrations/gcp/experiment_trackers/vertex_experiment_tracker.py
  src/zenml/integrations/gcp/flavors/__init__.py
  src/zenml/integrations/gcp/flavors/vertex_experiment_tracker_flavor.py
  tests/integration/integrations/gcp/experiment_trackers/__init__.py
  tests/integration/integrations/gcp/experiment_trackers/test_vertex_experiment_tracker.py
Labels: enhancement

#3294 Document on-prem ZenML Pro deployments
  docs/book/.gitbook/assets/on-prem-01.png
  docs/book/.gitbook/assets/on-prem-02.png
  docs/book/.gitbook/assets/on-prem-03.png
  docs/book/.gitbook/assets/on-prem-04.png
  docs/book/.gitbook/assets/on-prem-05.png
  docs/book/.gitbook/assets/on-prem-06.png
  docs/book/.gitbook/assets/on-prem-07.png
  docs/book/.gitbook/assets/on-prem-08.png
  docs/book/.gitbook/assets/on-prem-09.png
  docs/book/.gitbook/assets/on-prem-10.png
  docs/book/.gitbook/assets/on-prem-11.png
  docs/book/.gitbook/assets/on-prem-12.png
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/toc.md
Labels: documentation, internal

#3281 [helm] Independent setting of memory resources for migration pods
  src/zenml/zen_server/deploy/helm/templates/server-db-job.yaml
  src/zenml/zen_server/deploy/helm/values.yaml
Labels: enhancement, internal, run-slow-ci

#3302 Fix some docs
  docs/book/how-to/pipeline-development/build-pipelines/use-pipeline-step-parameters.md
  docs/book/how-to/pipeline-development/training-with-gpus/README.md
  docs/book/how-to/pipeline-development/training-with-gpus/accelerate-distributed-training.md
Labels: documentation, internal

#3265 Replace deprecated `datetime.utcnow()` with `datetime.now(timezone.utc)`
  docs/book/how-to/pipeline-development/develop-locally/keep-your-dashboard-server-clean.md
  src/zenml/cli/service_connectors.py
  src/zenml/cli/stack.py
  src/zenml/config/pipeline_configurations.py
  src/zenml/event_hub/base_event_hub.py
  src/zenml/integrations/airflow/orchestrators/airflow_orchestrator.py
  src/zenml/integrations/kubernetes/orchestrators/kube_utils.py
  src/zenml/integrations/whylogs/data_validators/whylogs_data_validator.py
  src/zenml/models/v2/core/api_key.py
  src/zenml/orchestrators/publish_utils.py
  src/zenml/orchestrators/step_launcher.py
  src/zenml/orchestrators/step_run_utils.py
  src/zenml/pipelines/run_utils.py
  src/zenml/service_connectors/service_connector.py
  src/zenml/stack/stack.py
  src/zenml/stack_deployments/stack_deployment.py
  src/zenml/utils/git_utils.py
  src/zenml/utils/string_utils.py
  src/zenml/zen_server/auth.py
  src/zenml/zen_server/routers/devices_endpoints.py
  src/zenml/zen_stores/migrations/versions/25155145c545_separate_actions_and_triggers.py
  src/zenml/zen_stores/migrations/versions/46506f72f0ed_add_server_settings.py
  src/zenml/zen_stores/migrations/versions/5994f9ad0489_introduce_role_permissions.py
  src/zenml/zen_stores/migrations/versions/7500f434b71c_remove_shared_columns.py
  src/zenml/zen_stores/migrations/versions/a91762e6be36_artifact_version_table.py
  src/zenml/zen_stores/schemas/action_schemas.py
  src/zenml/zen_stores/schemas/api_key_schemas.py
  src/zenml/zen_stores/schemas/artifact_schemas.py
  src/zenml/zen_stores/schemas/base_schemas.py
  src/zenml/zen_stores/schemas/code_repository_schemas.py
  src/zenml/zen_stores/schemas/component_schemas.py
  src/zenml/zen_stores/schemas/device_schemas.py
  src/zenml/zen_stores/schemas/event_source_schemas.py
  src/zenml/zen_stores/schemas/flavor_schemas.py
  src/zenml/zen_stores/schemas/model_schemas.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/pipeline_schemas.py
  src/zenml/zen_stores/schemas/run_template_schemas.py
  src/zenml/zen_stores/schemas/schedule_schema.py
  src/zenml/zen_stores/schemas/secret_schemas.py
  src/zenml/zen_stores/schemas/server_settings_schemas.py
  src/zenml/zen_stores/schemas/service_connector_schemas.py
  src/zenml/zen_stores/schemas/service_schemas.py
  src/zenml/zen_stores/schemas/stack_schemas.py
  src/zenml/zen_stores/schemas/step_run_schemas.py
  src/zenml/zen_stores/schemas/tag_schemas.py
  src/zenml/zen_stores/schemas/trigger_schemas.py
  src/zenml/zen_stores/schemas/user_schemas.py
  src/zenml/zen_stores/schemas/workspace_schemas.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: run-slow-ci

#3308 Adding the missing VertexAI experiment tracker docs
  docs/book/toc.md
Labels: documentation, internal

#3271 Create Sagemaker pipeline schedules if specified
  docs/book/component-guide/orchestrators/azureml.md
  docs/book/component-guide/orchestrators/sagemaker.md
  docs/book/component-guide/orchestrators/vertex.md
  docs/book/how-to/pipeline-development/build-pipelines/schedule-a-pipeline.md
  docs/mocked_libs.json
  pyproject.toml
  scripts/summarize_docs.py
  scripts/upload_to_huggingface.py
  src/zenml/enums.py
  src/zenml/integrations/aws/__init__.py
  src/zenml/integrations/aws/flavors/sagemaker_orchestrator_flavor.py
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
  src/zenml/integrations/huggingface/__init__.py
  src/zenml/models/v2/core/schedule.py
  src/zenml/stack/stack_component.py
  src/zenml/zen_server/routers/workspaces_endpoints.py
  src/zenml/zen_stores/schemas/pipeline_run_schemas.py
  src/zenml/zen_stores/schemas/schedule_schema.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/integration/integrations/aws/orchestrators/test_sagemaker_orchestrator.py
Labels: enhancement, internal, run-slow-ci

#3309 Backporting missing vertexai experiment tracker docs
  docs/book/toc.md
Labels: internal, backport

#3312 Remove trailing slashes from zenml login URLs
  src/zenml/cli/login.py
  src/zenml/cli/server.py
Labels: bug, internal, run-slow-ci

#3313 Fix Kubernetes service connector
  src/zenml/cli/annotator.py
  src/zenml/integrations/kubernetes/service_connectors/kubernetes_service_connector.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: bug, internal, run-slow-ci

#3301 Add notes on missing features for on-prem ZenML Pro deployments
  docs/book/getting-started/zenml-pro/self-hosted.md
Labels: documentation, internal

#3311 Fix wrong warning log when directly connecting to MySQL DB
  src/zenml/cli/login.py
Labels: bug, internal

#3316 Fix typo
  src/zenml/cli/utils.py
Labels: documentation, internal

#3318 Minor fix for Sagemaker
  docs/book/component-guide/orchestrators/sagemaker.md
  src/zenml/integrations/aws/orchestrators/sagemaker_orchestrator.py
Labels: documentation, internal

#3315 Schedule timezone fixes
  src/zenml/config/schedule.py
  src/zenml/models/v2/core/schedule.py
Labels: bug, internal

#3306 Misc code repository improvements
  docs/book/how-to/project-setup-and-management/setting-up-a-project-repository/connect-your-git-repository.md
  docs/book/user-guide/production-guide/connect-code-repository.md
  scripts/check_and_comment.py
  src/zenml/cli/code_repository.py
  src/zenml/client.py
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/integrations/github/code_repositories/github_code_repository.py
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
  src/zenml/pipelines/build_utils.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/utils/code_repository_utils.py
  src/zenml/utils/deprecation_utils.py
  src/zenml/utils/pipeline_docker_image_builder.py
  src/zenml/zen_stores/schemas/code_repository_schemas.py
  tests/unit/pipelines/test_build_utils.py
  tests/unit/utils/test_pipeline_docker_image_builder.py
Labels: enhancement, internal

#3323 Fix code download for custom flavor components
  src/zenml/entrypoints/base_entrypoint_configuration.py
  src/zenml/exceptions.py
  src/zenml/stack/flavor.py
  src/zenml/stack/stack_component.py
  src/zenml/utils/code_utils.py
Labels: bug, internal, run-slow-ci

#3326 Allow passing run configuration as dict when triggering pipelines
  src/zenml/client.py
Labels: enhancement, internal

#3325 Fix sorting by columns with potentially empty values
  src/zenml/models/v2/base/scoped.py
  src/zenml/models/v2/core/pipeline_run.py
  tests/integration/functional/models/test_sorting.py
Labels: bug, internal

#3304 Add vertex persistent resource to settings for step operator
  docs/book/component-guide/step-operators/vertex.md
  src/zenml/integrations/gcp/constants.py
  src/zenml/integrations/gcp/flavors/vertex_step_operator_flavor.py
  src/zenml/integrations/gcp/step_operators/vertex_step_operator.py
Labels: enhancement, internal

#3322 Fix use of config file in vLLM pipelines
  src/zenml/integrations/vllm/services/vllm_deployment.py
Labels: internal

#3329 Fixing the CI with the new `huggingface-hub` version
  docs/mocked_libs.json
  src/zenml/integrations/huggingface/services/huggingface_deployment.py
Labels: bug, internal, run-slow-ci

#3319 Handling string values as SecretStrs in store configurations
  src/zenml/cli/utils.py
  src/zenml/zen_stores/rest_zen_store.py
  src/zenml/zen_stores/secrets_stores/sql_secrets_store.py
  src/zenml/zen_stores/sql_zen_store.py
Labels: run-slow-ci

#3327 More code repository improvements
  docs/book/how-to/customize-docker-builds/how-to-reuse-builds.md
  docs/book/reference/environment-variables.md
  src/zenml/cli/code_repository.py
  src/zenml/client.py
  src/zenml/code_repositories/base_code_repository.py
  src/zenml/code_repositories/git/local_git_repository_context.py
  src/zenml/code_repositories/local_repository_context.py
  src/zenml/constants.py
  src/zenml/integrations/github/code_repositories/github_code_repository.py
  src/zenml/integrations/gitlab/code_repositories/gitlab_code_repository.py
  src/zenml/pipelines/build_utils.py
  src/zenml/pipelines/pipeline_definition.py
  src/zenml/utils/code_repository_utils.py
  src/zenml/utils/downloaded_repository_context.py
  src/zenml/utils/source_utils.py
  tests/integration/functional/zen_stores/test_zen_store.py
  tests/unit/pipelines/test_build_utils.py
  tests/unit/utils/test_code_repository_utils.py
  tests/unit/utils/test_source_utils.py
Labels: enhancement, internal

#3331 Fix materializer for new pytorch version
  src/zenml/integrations/pytorch/materializers/base_pytorch_materializer.py
Labels: enhancement, internal

#3328 Add some nicer docs
  .gitbook.yaml
  docs/book/getting-started/zenml-pro/README.md
  docs/book/getting-started/zenml-pro/core-concepts.md
  docs/book/getting-started/zenml-pro/self-hosted.md
  docs/book/getting-started/zenml-pro/tenants.md
  docs/book/how-to/data-artifact-management/complex-usecases/unmaterialized-artifacts.md
  docs/book/how-to/pipeline-development/build-pipelines/README.md
  docs/book/how-to/pipeline-development/build-pipelines/compose-pipelines.md
  docs/book/how-to/pipeline-development/build-pipelines/configuring-a-pipeline-at-runtime.md
  docs/book/how-to/pipeline-development/build-pipelines/fan-in-fan-out.md
  docs/book/how-to/pipeline-development/build-pipelines/hyper-parameter-tuning.md
  docs/book/how-to/trigger-pipelines/README.md
  docs/book/how-to/trigger-pipelines/use-templates-cli.md
  docs/book/how-to/trigger-pipelines/use-templates-dashboard.md
  docs/book/how-to/trigger-pipelines/use-templates-python.md
  docs/book/how-to/trigger-pipelines/use-templates-rest-api.md
  docs/book/toc.md
Labels: internal

#3310 Add run metadata and tag indices
  src/zenml/zen_stores/migrations/utils.py
  src/zenml/zen_stores/migrations/versions/4d5524b92a30_add_run_metadata_tag_index.py
  src/zenml/zen_stores/schemas/run_metadata_schemas.py
  src/zenml/zen_stores/schemas/schema_utils.py
  src/zenml/zen_stores/schemas/tag_schemas.py
Labels: enhancement, internal, run-slow-ci

#3333 Fix markdown link checker for external PRs
  .github/workflows/check-markdown-links.yml
  scripts/check_broken_links.py
  scripts/check_broken_links.sh
Labels: bug, internal

#3274 feat: implement implicit authentication for ACR and Storage Account
  docs/book/how-to/infrastructure-deployment/auth-management/azure-service-connector.md
  pyproject.toml
  src/zenml/integrations/azure/artifact_stores/azure_artifact_store.py
  src/zenml/integrations/azure/service_connectors/azure_service_connector.py
Labels: run-slow-ci
